### ISSUE TITLE
Subject headings in "Books media & more" journal record compared to e-journal record

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#1002]
Hi. A prof was just asking about access to this journal, Cognition and Culture, and I noticed that [this record](https://www.library.ualberta.ca/catalog/6831017) includes topical subject headings, whereas in [this one](https://www.library.ualberta.ca/catalog/110978984570521), the subject heading is not so meaninful. I know you're working on merging the journal records in Symphony with the ejournals list, so maybe this will be resolved by that work?
Thanks

**Comment by theLinkResolver** [comment]
@linds37 A good example of why we prefer the Symphony journal record, for sure.

**Comment by redlibrarian** [comment]
@linds37 Yes, the first record is from Symphony (good metadata) the second from SFX (slim metadata). The plan is to merge the records, allowing us to keep the Symphony metadata, but the SFX subscription and licensing information.

**Comment by redlibrarian** [comment]
I'm going to close this, as it refers to #900
