### ISSUE TITLE
NEOS list of libraries - link is broken

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#1005]
The NEOS website has changed - get a "page not found" error message when trying to find more info on a NEOS member library see https://www.library.ualberta.ca/catalog/3865428 as an example.

**Comment by redlibrarian** [comment]
This is due to recent changes made to the NEOS website. I have a question in to @kgood about it.

**Comment by alfodor** [comment]
Changes to locations have been corrected to point to new NEOS WordPress site. April
