### ISSUE TITLE
Add "text/email" to each call number line in holdings table.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1012]

**Comment by redlibrarian** [comment]
The link has been added, but the email and SMS text needs to be changed to reflect the actual item being sent. I've created a sms-email branch to finish that.

**Comment by redlibrarian** [comment]
OK, this is done. Check in next release.

**Comment by theLinkResolver** [comment]
@redlibrarian The email function seemed to work but I never got the message. Text did not work for me. Does think have something to do with it being in the test instance?

**Comment by redlibrarian** [comment]
@theLinkResolver Yes, the application sends, but you won't receive it because of the way the test server is set up. I call that "working" ;) As for the "text me" - I got a server error, is that what you got? I've reported that to our sysadmin to look into. That's the problem that I'm hoping to get resolved today.

**Comment by theLinkResolver** [comment]
@redlibrarian Yup, that's the error I get. I'll trust you that this is "working"! :) Great feature if it is.

**Comment by redlibrarian** [comment]
This is done and working fine.
