### ISSUE TITLE
changed active portfolio for SFX title - now no link available

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1031]
@redlibrarian See also #1003 as it contains your findings on what is and isn't a live lookup.

In response to a helpdesk ticket, I had to change the portfolio by which the linking occurs [for this title](https://www.library.ualberta.ca/catalog/110976010040226). It was previously using a MISCELLANEOUS_EJOURNALS target link and I have changed it to LOCAL_PASSTHROUGH_LCL.

Now, as you will see in the record, there is no link etc. available. I was hoping this kind of change would not be subject to the 2-day wait. @redlibrarian What's your understanding?

**Comment by redlibrarian** [comment]
@theLinkResolver That should be working. I can see "Available from Issue 1" in the box - is that from the new portfolio? If so, then the data is coming through, it just isn't displaying properly.

**Comment by theLinkResolver** [comment]
@redlibrarian No, it's from the old portfolio.

**Comment by redlibrarian** [comment]
Hm. OK, I'll see what I can find out.

**Comment by redlibrarian** [comment]
@theLinkResolver Oh, crap, I just figured it out. It only knows what target to look for by the target ID in the data extract (ie, the target ID is *not* looked up live). I think I can fix that.

**Comment by redlibrarian** [comment]
@theLinkResolver OK, I think I've fixed it, as best I can. One issue is that the live lookup API doesn't include the threshold information, so when a portfolio is added to a record, all the data will show up right away *except* the coverage. This will be part of the 2-day wait, as it's only available in the static extract. What I propose is something like the attached screenshot, where we put "Coverage temporarily unavailable" in the coverage box. This will automatically be replaced by the real coverage after 2 days. Does that sound acceptable? It's probably the best I can do.

![image](https://cloud.githubusercontent.com/assets/1093066/17444173/d7b1854e-5afb-11e6-8394-12de2e0d69de.png)

**Comment by theLinkResolver** [comment]
Glad you were able to fix this. And hopefully we will be looking at a 1-day wait in the future..?

As for the text, I would just tweak it to say "Coverage info temporarily unavailable" just to be 100% that it's the _details_ that are unavailable, not "coverage" in the sense of _access_. Any thoughts @ualbertalib/discovery-testing ?

**Comment by redlibrarian** [comment]
@theLinkResolver @ualbertalib/discovery-testing Sure, I can change the text to read "coverage information temporarily unavailable", unless there's another suggestion.

As for the delay, I'm going to be sitting down with our sysadmins to talk about our entire data ingest process, so hopefully we can get to the bottom of that.

**Comment by redlibrarian** [comment]
@theLinkResolver Is this working OK (I know the frequency of updates is an outstanding question).

**Comment by theLinkResolver** [comment]
Tested - working as expected.
