### ISSUE TITLE
sort by date is not functioning correctly

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1033]
Sample search results:
https://search-test.library.ualberta.ca/symphony?q=Altmetrics+for+information+professionals

When I apply sort by date, I end up with a list that's sorted by title. URL:

https://search-test.library.ualberta.ca/symphony?q=Altmetrics+for+information+professionals&sort=pub_date_sort+desc%2C+title_sort+asc

Also, the filter doesn't show up in "You searched for"

**Comment by redlibrarian** [comment]
See #1037

**Comment by seanluyk** [comment]
As in #1050 and #1037, this is now functioning correctly.
