### ISSUE TITLE
Make language names titlecase in databases language facet

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1035]
In checking #922 , I noticed that the names of languages appear in lowercase. I'm guessing that this is an underlying data issue, but I thought I would check just in case it wasn't.

**Comment by redlibrarian** [comment]
@seanluyk Hm. No, the language data is capitalized (and you can see it's capitalized in the record itself). Somewhere along the line it's getting converted to lowercase. I'll have to investigate.

**Comment by redlibrarian** [comment]
@astrilet Somewhere along the way the facet value is being changed from "English" and "French" to "english" and "french". We'd like them to be capitalized, as they are in the other collections.

**Comment by seanluyk** [comment]
Languages are now appearing in title case in the databases language facet, closing.
