### ISSUE TITLE
Add border to email link on Bookmarks page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1036]
Make border around Email link on bookmarks page consistent with other export options. Currently, the email link has no border:
![image](https://cloud.githubusercontent.com/assets/14880206/17606721/582708e8-5fde-11e6-9e90-49898383976e.png)

**Comment by redlibrarian** [comment]
I think @astrilet has this working.

**Comment by astrilet** [comment]
this has been fixed in commit attached to issue #980 commit c4fab20 
![screenshot from 2016-08-16 10 02 28](https://cloud.githubusercontent.com/assets/11414991/17708215/e13e10dc-6398-11e6-9858-02d21b435d25.png)

**Comment by seanluyk** [comment]
Border now appearing around email link, closing
