### ISSUE TITLE
Make institution and author facets available in advanced search for pre-limiting

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1040]
Just saw the fancy new institution level filter, which is a great addition! It got me thinking that perhaps the advanced search should contain all facets. Currently, everything is there except for institution and author.

**Comment by redlibrarian** [comment]
@seanluyk Thanks. And yes, we're having trouble figuring out *where* the advanced search facets are drawn from. Once we figure that out we'll keep them aligned.

**Comment by redlibrarian** [comment]
@seanluyk I had a brainwave and found where they were set. These will be in the next release.

**Comment by seanluyk** [comment]
That's great, I'll check in next release

**Comment by seanluyk** [comment]
Interesting, institution and author are now there, but geographic region and historic period are missing. Not sure if this was intentional?

**Comment by redlibrarian** [comment]
@seanluyk No, not intentional. I think I just got confused. I'll reinstate those.

**Comment by redlibrarian** [comment]
This requires a change to the solrconfig.xml file, which we've missed the window for for this term. It's too bad, but this will have to wait until the January release.

**Comment by seanluyk** [comment]
Institution facet is appearing as advanced search, and adding author probably isn't a good idea anyway without some usability testing to verify. Closing.
