### ISSUE TITLE
Collection: William C Wonders database

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1042]

**Comment by redlibrarian** [comment]
http://maps.library.ualberta.ca/

and the edit mode

you login with your personal library login

https://staff.library.ualberta.ca/toolstemplates/db/maps/edit/

**Comment by redlibrarian** [comment]
Done when:

- [ ] Map records are in Solr index
- [ ] New map views built (if appropriate)
- [ ] Staff view backend built into Discovery (or a standalone tool)

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
