### ISSUE TITLE
Staff Profile Edit Bug

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#1049]
It appears that with the last release we generate a 500 error when trying to save a change from a staff profile edit.

**Comment by redlibrarian** [comment]
Weird. The last release didn't touch anything to do with the CMS. The last time an issue like this crept in the problem was caused on the server by the ansible playbook. Worth investigating that? @kgood @henryzhang87

**Comment by redlibrarian** [comment]
@kgood Can I close this? This seems to be have resolved itself.
