### ISSUE TITLE
Sort by year in bookmarks page not working correctly

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1050]
Items in a bookmarks page list appear to not sort by year correctly, many titles are out of order.

To replicate: search for birds,  add the first ten items to bookmarks, go to bookmarks page, sort by year

**Comment by redlibrarian** [comment]
This is the same issue as #1033 and #1037. It's fixed in development, and will be fixed in the next release.

**Comment by seanluyk** [comment]
My bad, sorry for not checking!

**Comment by redlibrarian** [comment]
No worries!

**Comment by seanluyk** [comment]
Sort by date is working correctly in bookmarks and list views, closing issue
