### ISSUE TITLE
Bug with particular search terms

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1053]
This returns an error for some reason:
https://library.ualberta.ca/results?q=evans+ward+management

**Comment by theLinkResolver** [comment]
This is so weird. I tried all the other possible combinations and they work fine:

evans
ward
management
evans ward
evans management
ward management

also reordered the terms - same results.

evans ward management should return several hits, so it's not like it's just one record that's unretrievable for some reason.

However, changing evans to evan (i.e. making it 'singular' - I know it's a name) gives this error as well. Maybe a clue of some sort...?

**Comment by redlibrarian** [comment]
Done when:

- [ ] Bug fixed

**Comment by redlibrarian** [comment]
This no longer returns an error. It doesn't return hugely relevant results as it stands (because 'ward' means multiple things), but the underlying bug seems to have been resolved.

**Comment by seanluyk** [comment]
Not able to replicate this bug, perhaps due to the removal of the bento box design/EDS API. Closing.
