### ISSUE TITLE
Export to RefWorks from Articles and more results not working

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1056]
Here's how you replicate this issue:

-Try to export to RefWorks from an articles and more result, click save
-RefWorks login page does not come up

I tried this with EDS proper and did not encounter this issue

**Comment by linds37** [comment]
I've been noticing this problem as well. Tried on more than one computer and in both Chrome & IE. Article record that you get to through Blacklight will not respond when you try to export to refworks.

**Comment by theLinkResolver** [comment]
Erika just showed me this problem, too.
