### ISSUE TITLE
lowercase letters in "MLA" and "APA"

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1058]
@ualbertalib/discovery-testing 

Change to captalized "MLA"/"APA"

![apamla](https://cloud.githubusercontent.com/assets/14913579/17987800/5716115e-6adf-11e6-8e26-d2fc89e276b4.png)

**Comment by seanluyk** [comment]
Those should be uppercase if possible

**Comment by theLinkResolver** [comment]
@seanluyk For once, I think I beat you to a capitalization complaint.

**Comment by seanluyk** [comment]
@theLinkResolver ha! Yes, you beat me this time, but I'm on the lookout ;)
