### ISSUE TITLE
categories, hover box and placeholder text

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1064]
I'm noting some consistency issues with these..

"Books, media, ejournals & more"
- I see that "ejournals" has been added to the text of the prelimiter button, but not the placeholder text in the search box or at the other levels of search (grid box titles, "results for..").
- Having added "ejournals" here, it could suggest that this box is inclusive of what's in the "e-journals" search, which is not true. Maybe a better term would be "journals", to align with the term "books".
- For the hover box, it lists "print journals" and therefore should also list "ejournals", in the same way we included both "books" and "ebooks".

"e-Journals"
- Placeholder text reads "search journals" but should say "search ejournals"
- Also note the spelling/capitalization: once and for all, we should decide on our preferred spellings of ebooks and ejournals, e.g.
1. ejournals
2. eJournals
3. e-journals
4. E-journals
5. e-Journals
6. E-Journals

Let's end the madness! I personally like option 3 but I have a feeling that the hyphen will seem increasingly quaint with time. Like "e-mail".

**Comment by seanluyk** [comment]
Personally, I like option 5 the best, it seems to be the most grammatically correct but I could be wrong.

**Comment by fculpepper** [comment]
We've been directed to use a non-hyphenated standard in the LibGuides: eBooks NOT e-books. It'd be swell if we could keep this consistent across our platforms (so eJournals).

**Comment by sjshores** [comment]
That makes sense to me.  It also seems to be the way most people are going
in their writihg.  I would also encourage not using the uppercase second
letter, so just ebooks and ejournals, but am wondering if that contradicts
the LibGuides standard.  In any case, it would be good to achieve
consistency.

Sandra

**Comment by fculpepper** [comment]
The lowercase second letter does contradict the [LibGuide directive] (http://guides.library.ualberta.ca/creating-libguides/labels). Maybe difficult to change all those libguides at this stage.

**Comment by sjshores** [comment]
Fair enough.

Sandra

**Comment by seanluyk** [comment]
No longer relevant with removal of bento box design, closing.
