### ISSUE TITLE
Book series link

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#1068]
When I click on the link next to Series in [this record] (https://search.library.ualberta.ca/catalog/3486850) I expect to get a list of the titles in the series but instead [this is returned] (https://search.library.ualberta.ca/catalog?q=%22Alberta+in+the+20th+century.+;+v.+9%22).
It looks like it's searching "Alberta in the 20th century" as keywords which is not at all useful.

**Comment by theLinkResolver** [comment]
see also #1032 
Agreed that the desired behaviour would likely be to just search on series title. Or, perhaps, to do a title search (which includes series titles). It should search the series name as a phrase but not the designation (always found after the semicolon).

**Comment by redlibrarian** [comment]
@fculpepper @theLinkResolver Thanks both. I've added logic to do an advanced/title search on the series title, as a phrase, ignoring anything after the semi-colon. For Fairfax's example, this returns 34 results (same as the NEOS catalogue). This will be in the next release (hopefully next week) and we should check it pretty carefully then, as I don't want this to break anything existing. Thanks.

**Comment by redlibrarian** [comment]
Just FYI we *could* make the series title individually searchable (ie not as part of the title search), but this would require a schema change and reindex, which would mean we couldn't implement it before January. The current solution should only break if another title field has exactly the same title phrase, which is certainly likely among 6,000,000 records, but probably won't be a common occurence. We can reevaluate later in the term.
