### ISSUE TITLE
Transliterated title searching issue?

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1072]
Brought to my attention by Bernard in HSS. Bernard is transliterating Russian and Ukrainian titles and then searching for them in BL. 

He gave me the following search example: Ukrai'ns'ka radjans'ka muzyka

When this is searched, the following things happen:
1. [Simple search in everything](https://library.ualberta.ca/results?utf8=%3F&q=Ukrai%27ns%27ka+radjans%27ka+muzyka+): 952 results in Articles and More, but clicking on either the hit # or the view more button leads to a [no results page w/ placeholder links to library guides](https://library.ualberta.ca/articles?q=Ukrai%27ns%27ka%20radjans%27ka%20muzyka%20&includefacets=y&searchmode=all&view=brief&resultsperpage=20&pagenumber=1&highlight=y) (this should be changed btw to link to the main guides page)

The odd thing is that searching for these terms in EDS or the articles advanced search yields 0 results.

**Comment by redlibrarian** [comment]
Hmm. I'll have to do some testing. Ideally, we'd get away from those horrible LC transliterations and just search in (in this case) Cyrillic, which should work. AFAIK we now put the original language/character set in the Symphony records. @theLinkResolver does that sound right to you?

**Comment by seanluyk** [comment]
The issue here might not entirely be transliteration, I think, but the fact that results are displayed in bento box view but not retrievable

**Comment by redlibrarian** [comment]
Ah, sorry - I read the issue too quickly. I'll look into it.

**Comment by redlibrarian** [comment]
Clicking on the individual titles goes to the articles. Given that clicking on the hit #, view more button, and searching in EDS produces 0 results makes me think that EDS doesn't like the transliteration. When I look at the individual results they don't seem relevant, so I think the Blacklight-produced search string works (a little bit) to retrieve those titles, but in fact is not producing a valid EDS search string. I'll keep looking into it to see what the fix should be.

**Comment by redlibrarian** [comment]
Just a note: searching for **Українська** produces article results and allows a user to go through to the article results page.

**Comment by seanluyk** [comment]
Thanks @redlibrarian

**Comment by seanluyk** [comment]
Bernard just mentioned that this issue is still occurring - if he searches for the transliterated title in NEOS he gets results. I've asked him to email @redlibrarian a list of titles as examples

**Comment by theLinkResolver** [comment]
Sorry for my delay in looking at this. Searching in the original character set will only work for materials catalogued in the last few years. Most of our records only have the transliteration, and don't have the parallel original script. 

The other issue here is with the variation in how things are transliterated. In EDS and other databases, the transliteration for Cyrillic is done according to the International (i.e. European) Transliteration tables. In the Sirsi catalogue records, we follow ALA-LC transliteration. See details on the right side of the [Slavic Studies](http://guides.library.ualberta.ca/history/slavic-studies) LibGuide.

As for the example search of: Ukrai'ns'ka radjans'ka muzyka - Erika suggests removing the soft sign (') anytime this is present.

**Comment by seanluyk** [comment]
Thanks @theLinkResolver, I've forwarded your response to Bernard.

**Comment by seanluyk** [comment]
Closing as this issue is no longer relevant given the removal of the bento view (item was an article).
