### ISSUE TITLE
Make reserve circ rules dynamic

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1075]
There's an issue with the 2 hour loan note & hourly fines note. Not all reserves are two hour loans. For example, at Weir they're day-long loans, but the two hour loan note shows up, eg: https://search-test.library.ualberta.ca/catalog/6601213
Take a look at the ilink record for KF 245 C212 2014 (sorry, can't make a permalink for a reserve item) -- there, the circ rule is correct.

**Comment by redlibrarian** [comment]
This is going to require setting up a full lookup table for all the circ rules, which is another thing that we'll have to keep in sync with the Symphony team. Waiting for a list of the current circ rules and text from Peggy.

**Comment by redlibrarian** [comment]
@linds37 I've created a dynamic lookup file for all circ rules, but I'm only displaying the ones that apply to reserves. Changes to the circ rules tend to come from PSC, so we'll have to bear in mind that from now on a change to the circ rules will require a change to Blacklight.

**Comment by linds37** [comment]
Is that live in test?

**Comment by redlibrarian** [comment]
No, I'm waiting to get a consensus on 24h vs. 12h time for reserve due times, then it will have to be packaged and given to our sysadmin before it will be put into test.

**Comment by linds37** [comment]
k

**Comment by seanluyk** [comment]
This has long since been resolved. For this record, different reserve status appears in holdings table: https://library.ualberta.ca/catalog/6601213
