### ISSUE TITLE
Authentication for Staff and CMS

### ISSUE THREAD

**Issue by nmacgreg** [ualbertalib/discovery#1078]
RE: https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=36469;ArticleID=145962#145936

Please re-design and implement an appropriate system of credentials, to permit the actions of editing both documents in Comfortable Mexican Sofa, and Staff database entries.

**Comment by seanluyk** [comment]
Closing this issue as one of the things @nnunn is working on this year is untangling the CMS from Blacklight.
