### ISSUE TITLE
Subject headings search by keyword?

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#1080]
This issue was brought to me by one of the librarians, I don't think it's been covered elsewhere? Apologies if this is a repeat. 
When clicking on a subject heading from within a record, the results appear to be a keyword search. The expected behaviour was that the results would be only those records with that exact subject term.
The subject term "Barbie dolls > Social aspects" from [this record](https://www.library.ualberta.ca/catalog/7466163) gives 88 results in Books, media & more, the same number as doing [a search for the same terms](https://www.library.ualberta.ca/results?utf8=%3F&q=barbie+dolls+social+aspects) in the main search box. In this search, already [the second record](https://www.library.ualberta.ca/catalog/4004073) does not have the desired subject heading.
Maybe similar to [#1068](https://github.com/ualbertalib/discovery/issues/1068)?

**Comment by theLinkResolver** [comment]
Found it! Discussed in #708. I, for one, was satisfied that the relevance was taking care of things, even after suggesting that the desired result would be a phrase search of subjects only. But as @fculpepper has shown, that may not always be the case. 

But also, I'm not sure if I understand what is happening with these searches. When you click on the subject terms, the URL looks like: https://www.library.ualberta.ca/results?q=Barbie+dolls+++Social+aspects&view=brief**&search_field=subject**

@redlibrarian Does that last part mean something, in terms of what _kind_ of search is being executed (and how the relevance is ranked)?

**Comment by theLinkResolver** [comment]
Brought forward again today in a helpdesk ticket. Compare the results of searching for the subject "Imaginary Places - Maps" in three different ways:

[By clicking this subject heading in a record](https://library.ualberta.ca/results?q=Imaginary+places+++Maps&view=brief&search_field=subject) ([sample record](https://library.ualberta.ca/catalog/5652277))


[By using advanced search to search for these terms as a subject](https://library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=imaginary+places+maps&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search&utf8=%E2%9C%93&search_field=dummy_range&range[pub_date][begin]=&range[pub_date][end]=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced).

[By doing a keyword search for these terms](https://library.ualberta.ca/symphony?utf8=%3F&q=imaginary+places+maps) (same results as first example)

**Comment by seanluyk** [comment]
We've talked about this one quite a bit, and I think it gets to the issue of library staff expectations of what the expected results are from clicking on a subject heading vs. the expectations of students and faculty. There are advantages to each approach (keyword vs. exact). This is an excellent example of something that should be tested on are various user groups (i.e. not just undergraduate students).

**Comment by seanluyk** [comment]
This is planned to be fixed in the [next deployment](https://github.com/ualbertalib/discovery/releases/tag/3.0.85)/duplicates some other issues, so I'm closing for cleanup purposes
