### ISSUE TITLE
Problem with apostrophe searching

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1084]
**Bug report:**
"I tried searching kikuchi risjord's when trying to find the item with the following title:  Risjord's philosophy of nursing science: concerns and questions.   After the search is complete, it translate the search statement to kikuchi risjors.  If I search kikuchi risjords, it finds the item."

**Replication**
<img width="563" alt="screen shot 2018-05-17 at 10 18 51 am" src="https://user-images.githubusercontent.com/1093066/40190287-bcd18f2e-59bb-11e8-9ae4-5157b15cd29b.png">

<img width="423" alt="screen shot 2018-05-17 at 10 19 21 am" src="https://user-images.githubusercontent.com/1093066/40190302-cb669976-59bb-11e8-99ba-0b9f3675ea95.png">

Notice the search terms in the search box have been changed to **kikuchi risjors**. 

Searching without the apostrophe:

<img width="629" alt="screen shot 2018-05-17 at 10 20 20 am" src="https://user-images.githubusercontent.com/1093066/40190357-f8929be8-59bb-11e8-8926-b7c1c6a34585.png">

Note that we don't have anything in the local index, so this *particular* result set only comes from articles, but the search-term modification is a bug.

**Comment by redlibrarian** [comment]
Done when:

- [ ] Bug fixed
- [ ] Test written to test for correct result returned when apostrophe's used.

**Comment by weiweishi** [comment]
It's an EDS releated issue. Closing.
