### ISSUE TITLE
TOC not wrapping around Tools box

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1088]
First time I've noticed this. Confirmed in Chrome and Firefox:
https://www.library.ualberta.ca/catalog/5756085

![image](https://cloud.githubusercontent.com/assets/14880206/19831269/072bba74-9dc3-11e6-87bc-dffacf6de476.png)

**Comment by pgwillia** [comment]
Question during grooming about finding other potential items.  This query would identify any where the contents were at least 50 characters long:
http://solrcloud-test.library.ualberta.ca:8080/solr/discovery-test/select?fl=title_t,id,contents_tesim&indent=on&q=contents_tesim:/.{50}.*/&qt=standard&rows=4600&wt=json

**Comment by seanluyk** [comment]
@pgwillia interesting that the example in the issue doesn't come up in this query, I wonder if character length is just part of the issue?
