### ISSUE TITLE
Search terms disappear sometimes

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#1093]
Hi. This issue was reported to WAT, but wanted to make sure it is entered here. Comment from a colleague: When you want to adjust your search terms, sometimes your original search is there and other times it isn't -- it needs to be re-typed.  Not a big deal, but when the subject is long and you're trying to show a student how everything works, it would be nice if the original search was there so time wouldn't be wasted on retyping it.  (Can you tell I'm not a fabulous typer?  Ha!)  It's strange though because depending on what way I take into the results, it may list the original search or it may not.  If I have hit limiters or something to make it more specific, the search terms disappear.  I would like to see it remain the same no matter what limiter or what adjustments you make to your search.

**Comment by seanluyk** [comment]
Closing issue as I believe this no longer applies given the removal of the bento view.
