### ISSUE TITLE
display recall due date in items table if there is one?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1094]
[As per helpdesk ticket.](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=37595)

A user reported some confusion about the due date as displayed in the catalogue for something that had been recalled. The catalogue (both BL and classic) don't display the recall due date in the item listing - just the original due date.

While My Account and the email notification text are considered to be the tools that users should be consulting to manage their checkouts, the question is whether the catalogue should show the recall due date. The use case would be for a user who placed a hold on something to go back in the next day and see it reflected that the due date had been shortened.

With that said, the classic catalogue is not doing this at the moment, so it's not a case of classic doing one thing and BL doing another. To quote Peggy, "I'm not sure if the recall due date ever appeared in either the classic or Blacklight versions.  In any event, there's nothing that you or I can do in Symphony to make the recall date appear in the online catalogue."

Peggy also adds, "is it even a given that we want the recall due date to appear in the online catalogue?  How helpful is it to users doing a casual search to see a recall due date when they might not even know what that means?" Just a guess on my parent, but the answer to that question may need to come from PSC.

**Comment by seanluyk** [comment]
I think it's best for users to reply on the Place Hold function/automated notices and for us to not worry about messing with Symphony web services to have the most exact date. Closing.
