### ISSUE TITLE
after placing hold, only one of the items requested is listed

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1096]
When placing a hold on multiple volumes of a single title, only one of the volumes is listed as having been successfully requested. The others are not mentioned.

Example - I successfully placed holds on volumes 1984, 1985, and 1986/1987, but this is what I saw:
![holds](https://cloud.githubusercontent.com/assets/14913579/22430852/c6c49584-e6cc-11e6-949f-928b18f0cbe3.JPG)

**Comment by theLinkResolver** [comment]
In Classic Catalogue, when placing a hold on multiple volumes, we can see that multiple holds have been placed (although it doesn't actually specify which volumes on this screen, but seeing three lines at least tells me that the three volumes I clicked have been requested)

![opac](https://cloud.githubusercontent.com/assets/14913579/22431018/53386072-e6cd-11e6-8824-56a9b3cd63ec.png)

**Comment by redlibrarian** [comment]
I've assigned this to @jhennig , as it refers to his API My Account application, which is outside the discovery application.

@timwklassen This is an example of the blurred lines between different applications. We may want to rethink how/where we want to submit or triage issues.

**Comment by seanluyk** [comment]
Just placed a hold on 2 vols and both were listed, so the issue seems to have been resolved. This is also a My Account, rather than Blacklight issue, so probably doesn't belong here.
