### ISSUE TITLE
add CURR_AUTH to mapping table

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1097]
@redlibrarian I think you may have done this but I don't see it in production, yet.

For the purposes of testing, I have set the 2003 volume of [this title](https://www.library.ualberta.ca/catalog/2676563) to CURR_AUTH.

**Comment by theLinkResolver** [comment]
@redlibrarian I have no idea if any other new locations or item types have been added in the last number of months, so more followup might be needed.

**Comment by redlibrarian** [comment]
Thanks. I've made this change, and as with the new AHS location, this should get pushed to production this week. I've followed up and I don't think I'm missing any more right now.

**Comment by theLinkResolver** [comment]
Disregard the note above about a test item - it has since been changed to another location by Education staff, I believe. To avoid confusion, I will have to switch the location at the time I'm testing...

**Comment by theLinkResolver** [comment]
@redlibrarian Do you know when this will get pushed to production?

**Comment by redlibrarian** [comment]
Monday, I hope.

**Comment by theLinkResolver** [comment]
fixed
