### ISSUE TITLE
deal with recent NEOS library changes (e.g. AHS_KEC)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1098]
The item in [this record](https://www.library.ualberta.ca/catalog/3022272) that shows a blank library is for AHS_KEC (Kaye Edmonton Clinic). This change happened in the fall, I think.

There were also a couple of AHS branches that closed. Someone from the ILS team can help you get up to date, @redlibrarian. Not sure if there have been any other changes - I hear about this stuff second-hand as it is.

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver - I knew about the closures, but not about the new branch. I've added it to the configuration and it will get pushed with the next release (soon).

**Comment by theLinkResolver** [comment]
Fixed
