### ISSUE TITLE
Discovery: Complete test suite

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1103]
Once the work on issue #1144 is done, we can start thinking about how to tackle testing. We may want to start with a couple of very high-level "sanity check" tests, and then add more granular tests as we go. This might also mean removing a lot of the specs written for various unit and integration tests. The dev team has adopted minitest as their test framework, which is fine with me. We can add thoughts about how to approach / get on top of tests to this issue as we discuss. Setting up a couple of high-level tests *that pass* is essential for completing the GitHub workflows (#1147). Currently, tests fail, which means requiring status checks won't work.

**Comment by redlibrarian** [comment]
- [ ] Flesh out integration and acceptance tests.
- [ ] Unit tests for new gems

**Comment by redlibrarian** [comment]
If, as per #940 , we port our customizations over to the latest version of Blacklight, then we can write tests as we port the code. This is done when:
- [ ] Unit tests for Helpers
- [ ] Unit tests for Services
- [ ] Integration
- [ ] Acceptance

tests are completed.

**Comment by redlibrarian** [comment]
Verify the docker-compose
Session with Tricia on workflow
Investigate Gemnasium
Investigate Dependabot
Setup Github Workflow
Move Solr config back into Discovery repo
Set up UAT server
Decision on how to approach tests
Create working test suite

(Clean up this issue).

**Comment by pgwillia** [comment]
So tests are [green now](https://travis-ci.org/ualbertalib/discovery) but coverage is poor:'

Coverage report generated for RSpec to /home/travis/build/ualbertalib/discovery/coverage. 688 / 2180 LOC (31.56%) covered.

The [grab bag tests are mostly passing](http://cardiff.library.ualberta.ca/job/discovery-grabBag/lastBuild/console) (just one known issue causing failure -- @nmacgreg was going to look at it.)

I can look at adding a test like this one to the spec to try to improve coverage.
t/dataSanityRegression.t ... 
ok 1 - search-test.library.ualberta.ca: Search for shakespeare
ok 2 - Did we get content?
ok 3 - Check for masked error
ok 4 - Results contain a count of the number of books
ok 5 - Extraction of count successful
ok 6 - Count of books should exceed 14,000, actual: 19019

Did you have others in mind?

**Comment by pgwillia** [comment]
@redlibrarian `Coverage report generated for RSpec to /home/pjenkins/Code/discovery/coverage. 981 / 2231 LOC (43.97%) covered.` This is what simplecov reports.  Could you rank the 0% ones by priority?
![screenshot from 2018-07-26 15-40-52](https://user-images.githubusercontent.com/1220762/43290163-669bc56e-90ea-11e8-893d-3f6cefe42534.png)

**Comment by pgwillia** [comment]
Coverage is currently 68.52%.  I'm closing this as complete for now.  Could be improved!
