### ISSUE TITLE
Title search problem

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1111]
J Temple (2001) “Generalizations that aren't? Evidence on education and growth” European Economic Review.

Searching "generalizations that aren't" in "search the library" doesn't work. Neither does using the whole title. 

Well, actually, the bento box doesn't show the correct article but clicking on the "10 results" does display the correct article links ????

Searching the "evidence on education and growth" part of the title does give correct results.

Alternatively, searching for "european economic review" (in "search the library then looking in the eJournals box, or click ejournals under the "search the library" box, or "ejournals by title" under the "also explore") also works.

The title is definitely accessible just not searchable with the first part of it (without clicking on the result link at the top of the bento box). 

Not sure if this is a discovery or e-resources question.

**Comment by seanluyk** [comment]
No longer relevant with removal of bento.
