### ISSUE TITLE
[Discovery] Database license icons

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1113]
**User story:** As a user, I want to see the icons for the different license/funding details on each database.

**Description**: The databases are catalogued in the [LibGuide platform](
https://guides.library.ualberta.ca/az.php), and one of the fields is for license/funding details. Each of the possible values for this field has an associated icon. When we index the databases in Discovery using the LibGuide API, we see the value of the **icons** field which we map to **icons_tesim** in Solr. Based on the value of **icons_tesim** we display the appropriate icon in Blacklight. There are four license/funding detail values: U of A Licensed, HKN Licensed, Lois Hole Digital Library, and Open Access/Free. Currently only the U of A Licensed icon has been [implemented](https://github.com/ualbertalib/discovery/blob/34db630ecd87b8ff7dc08cd71055b49769e28821/app/views/catalog/_index_default.html.erb#L33). Responsibility for cataloguing the databases, maintaining the icons in LibGuides, and managing the license/funding details lies with the Collections Strategies Unit.

**Done when**:
- [x] License/funding details data is parsed out of the LibGuides API.
- [x] Appropriate icons are displayed for each of the four conditions.

**Comment by weiweishi** [comment]
A spike is needed to investigate if SpringShare API will return the icons field.

**Comment by seanluyk** [comment]
Needs more discussion after the investigation. For example, could CORAL data be used instead?

**Comment by seanluyk** [comment]
API documentation is behind a LibApps/guides login - anyone who wants access, please put in a helpdesk ticket. It looks like the following parameters using = expand could possibly give us the icon info:
 - icons
 - permitted_uses

**Comment by pgwillia** [comment]
Can get 
```
"icons_tesim":["\n    \n      6665\n      165\n      ualib-logo.png\n      licensed for  U of A\n      https://www.library.ualberta.ca/about-us/policies/restricted-resource-info\n      11710698\n      6665\n      \n    \n    \n      15484\n      165\n      cou-user.png\n      User Registration Required\n      https://www.library.ualberta.ca/about-us/policies/conditions-of-use/registration-required\n      11710698\n      15484\n      \n    \n    \n      15485\n      165\n      cou-sign-in.png\n      CCID Login Required\n      https://www.library.ualberta.ca/about-us/policies/conditions-of-use/restricted\n      11710698\n      15485\n      \n    \n  "]
````
from Solr. This will need to be parsed so that it can be interpreted. Started looking at that [here](https://gist.github.com/pgwillia/54371bf716c0301aaa81f203328d034e
).

This maps to the original content
```
pry(#<Databases>)> db['icons']
=> [{"id"=>"6665",
  "site_id"=>"165",
  "file"=>"ualib-logo.png",
  "description"=>"licensed for  U of A",
  "url"=>"https://www.library.ualberta.ca/about-us/policies/restricted-resource-info",
  "content_id"=>"11710046",
  "icon_id"=>"6665",
  "custom_url"=>""},
 {"id"=>"6666",
  "site_id"=>"165",
  "file"=>"save-sig-50c.png",
  "description"=>"conditions of use",
  "url"=>"https://www.library.ualberta.ca/about-us/policies/conditions-of-use",
  "content_id"=>"11710046",
  "icon_id"=>"6666",
  "custom_url"=>""}]
```
Then logos can be retrieved
`https://libapps-ca.s3.amazonaws.com/sites/#{site_id}/icons/#{id}/#{file}`

**Comment by seanluyk** [comment]
@pgwillia if it's possible to deduplicate the UAL shield for the database assets in the results view that would be preferable. Not sure how complicated that would be? It should still display on record pages

**Comment by seanluyk** [comment]
Closed with the latest release.
