### ISSUE TITLE
Authentication/Authorization for Staff Directory

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1116]
## Overview:

Use UofA's single sign on for the Staff Directory on Discovery project for authentication and authorize staff to edit their own staff directory information page. 

Implementation details:
- Have the "Edit" link
- User will be prompted with authentication from IST to login, and redirect to the edit page if they are authorized
- Change the URL structure with ccid for the slug (for uniqueness). 
- Currently the application keeps a user table with email addresses and we will need to add CCIDs in the user table, add a column in the db migration (there is a profile table and a users table, should be combined or should be joined via user_id foreign key column in profiles table). 
- Still have a master user for admin function (not hard to have a boolean column, `admin` on the users table to replace this shared admin functionality?)
- Coordinate with system admin team for the database migration. 
- Development can use OmniAuth-developer in local
- Testing with SAML authentication with IST (OmniAuth-saml / OmniAuth-Shibboleth). A staging server is available at IST. 
- Use existing Discovery staging for testing. Metadata needs to be shared with IST for testing.
- Working with Unix team to deal with configuration variables through the single config secrets.yml file. 

## Out of Scope:
- CMS (CMS will continue to use the basic authentication)
- Other Discovery functions such as Bookmarks. 
- Getting information from the SAML responses to update local user attributes.

**Comment by seanluyk** [comment]
I'm wondering if we should park this one, @weiweishi given that the plan is to untangle the CMS from Discovery, and this particular issue is not with Discovery?

**Comment by weiweishi** [comment]
I agree!


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by seanluyk** [comment]
@weiweishi sounds good, closing!
