### ISSUE TITLE
[Discovery] only 505 $a is being displayed for contents notes

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1121]
Contents notes (505 field) are not being displayed when they are encoded at the "enhanced content designation" level, which uses subfields t (title), r (statement of responsibility), and g (extent/misc).

Example:  Newgate Narratives
https://www.library.ualberta.ca/catalog/4220558
http://www.library.ualberta.ca/permalink/opac/4220558/WUAARCHIVE

**Comment by theLinkResolver** [comment]
https://www.library.ualberta.ca/catalog/7614357

**Comment by seanluyk** [comment]
Adding a funky example from a helpdesk ticket: https://library.ualberta.ca/catalog/2829082

**Comment by seanluyk** [comment]
@pgwillia @weiweishi @murny this is really screwed up so is a candidate to fix before the freeze if we can figure out the issue

**Comment by theLinkResolver** [comment]
The last record cited above was a bad record and I have now replaced it. However, there is still a problem as documented earlier in this issue.

**Comment by weiweishi** [comment]
Example: https://www.library.ualberta.ca/catalog/7614357
Looking at the librarian view for the Content notes, information is missing, it's probably a mapping issue

**Comment by pgwillia** [comment]
@theLinkResolver this is what it looks like now

https://github.com/ualbertalib/discovery/blob/d3526674e91ad7a751d616e8040c48bb04c5fed4/config/SolrMarc/symphony_index.properties#L152

There are two ways I can think to change it that would meet the requirements:

Are there any subfields that shouldn't be indexed? i.e. `contents_tesim = 505[a-z]`
Which specific subfields should be indexed? i.e. `contents_tesim = 505abcdefgrt`

Thoughts?

**Comment by seanluyk** [comment]
Kind of interesting that in [this example](https://search.library.ualberta.ca/catalog/7614357) $t comes before $g, at least in the librarian view. Perhaps that's an exception? If not, it does raise some issues on how confidently we could map more 505 fields w/o making a mess. It does seem like $t needs to be in there though

**Comment by theLinkResolver** [comment]
@pgwillia Sorry for the delay as I was away. I will separate the requirements into display and indexing.

We should display subfields a,g,r,t (wrt to @seanluyk's remark - these are repeatable and appear in any order, which should be preserved in display - see [examples](http://www.loc.gov/marc/bibliographic/bd505.html)). 

We should not display subfields u,6,8.

505 a,r,t should be indexed for keyword searching. Subfields g,u,6,8 should not be.

**Comment by pgwillia** [comment]
Replying to @theLinkResolver https://github.com/ualbertalib/discovery/issues/1121#issuecomment-459835902

Currently there is only one field used for both display and search.  With the recently merged changes it satisfies your display case.  But, the merged change includes subfield g in keyword searches.

My assumption with the merged change is that we would passively let the index catch up at the next full re-index.

In order to split the field for display and search case we would need to coordinate
- SolrMarc configuration change 
- Solr configuration change (for the request handler to use a different field name when searching)
- full re-index
- Discovery code deployment

We could phase this so that introducing the new fields for search/display to overlap with the existing `contents_tesim` use and then at some future point remove the deprecated fields from SolrMarc/Solr config/Discovery.

@seanluyk @nmacgreg

**Comment by theLinkResolver** [comment]
@pgwillia Sounds good. Display is more important here, and relevance is super low for contents notes so having 505 g indexed should be no harm. Things like CD track times and volume numbers are in 505 g, so, thinking more on it, it would have to be a pretty obscure search to have those coming up high in the search results!

**Comment by pgwillia** [comment]
Great.  Just to close the loop what we discussed was

-   I anticipate some changes to solrconfig and discovery application
-   cleanup of managed-schema to make it more readable
-   <https://github.com/ualbertalib/discovery/issues/1121> is one such issue
    -   where there is a need for different mappings for search and display we will
        -   introduce solr config change which includes definitions for the three fields i.e. contents_tesim, contents_display, contents_search (let Neil know about this and he'll deploy)
        -   introduce discovery changes to solrmarc & display which includes three fields (tag release)
        -   confirm that these things work together in staging without impacting production -> move to production
        -   repeat for batches of similar changes
        -   remove contents_tesim from discovery solrmarc & display (tag release)
        -   confirm that these things work together in staging without impacting production -> move to production
        -   re-index to remove content from content_tesim (in this case contents_tesim is a dynamic field so no config change to remove)
        -   repeat for batches of similar changes
    -   the goal being to make small incremental changes but balanced with the deadline of the code freeze
    -   my concern with the three fields is that content will be duplicated in the index bloating it in size. Neil assured me that Solr was over provisioned so should\* be able to handle this especially just in the case of one (or a small number) of fields.
    -   Neil expressed that we fairly recently did a solr config deploy so confidence in that part of the playbook is restored

**Comment by seanluyk** [comment]
Fixed in test, closing
