### ISSUE TITLE
seeing Alberta Health Services - Women's Health [in transition] in list view as library name for NLC_INT

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1127]
![in transition](https://user-images.githubusercontent.com/14913579/29976354-fdacfd34-8ef6-11e7-8aff-3ad16df60802.png)
 
The item's true location is Northern Lakes College.

**Comment by theLinkResolver** [comment]
@redlibrarian to confirm, it's not just the "in transition" that was a problem - the institution name is completely wrong here. The results view shows AHS Women's Health and the item table shows NLC.

**Comment by redlibrarian** [comment]
Great. We must be reusing library codes in Symphony.

**Comment by theLinkResolver** [comment]
@redlibrarian yes - likely a SirsiDynix practice, if I may pass the buck

**Comment by redlibrarian** [comment]
@theLinkResolver For sure. :) I'll get an updated list of codes from the Symphony team.

**Comment by seanluyk** [comment]
Fixed for now.

**Comment by theLinkResolver** [comment]
Nope, something is wrong here. I see **Alberta Innovates - Technology Futures - Calgary** in the list view where I should be seeing **Northern Lakes College - Internet**.

[example](https://www.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search&f_inclusive%5Blocation_tesim%5D%5B%5D=nlcint&utf8=%E2%9C%93&search_field=dummy_range&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced)

**Comment by seanluyk** [comment]
Good catch, @theLinkResolver - the locations are fixed in the record view and facet label, but not in the list view. @nnunn is investigating why and we're developing a better process for handling this

**Comment by nnunn** [comment]
Added to my list.
