### ISSUE TITLE
display UA shield when holdings include item in NEOS_FREE library

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1128]
([transferred from helpdesk](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=41412#))

Sample records:
https://www.library.ualberta.ca/symphony?q=7616648
https://www.library.ualberta.ca/symphony?q=Supreme%20Court%20Law%20Review (first result)

(Sort of related to #339?)

**Comment by redlibrarian** [comment]
I added "NEOS Free" to the list of locations recognized as "UAL locations" here.

**Comment by pgwillia** [comment]
Release 3.0.78 has this fix and is in staging today.
https://search-test.library.ualberta.ca/symphony?q=7616648
![screenshot from 2018-07-09 15-14-08](https://user-images.githubusercontent.com/1220762/42476317-cc57b920-838a-11e8-9922-e7a8c060892e.png)
https://search-test.library.ualberta.ca/symphony?q=7616648
