### ISSUE TITLE
varying appearance when viewing ejournal record

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1134]
Via search:

![tcm1](https://user-images.githubusercontent.com/14913579/31624784-0ce29330-b261-11e7-9d56-92a9097ee9cc.png)

Via link in the "Top 20 most searched for ejournals in 2016" list:

![tcm2](https://user-images.githubusercontent.com/14913579/31624798-1d82883a-b261-11e7-8943-8f9114e5cdea.png)

**Comment by seanluyk** [comment]
Not seeing this issue anymore, closing.
