### ISSUE TITLE
consider indexing general notes

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1142]
For those with helpdesk access, see [this helpdesk ticket](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=42004)

We display general notes (MARC 500 field) but they are not searchable. If this is considered at some point, relevance should probably be set fairly low to avoid turning up unwanted records.

**Comment by seanluyk** [comment]
Looks like all that needs to happen is for general_note_tesim to be added to SOLR config since this field has already been mapped for display. @pgwillia is there huge risk in doing this? Could we try it in staging in the next release? It should probably be ranked similarly to other notes fields such as local_note_tesim

**Comment by pgwillia** [comment]
I think the risk is low.  The change would be here https://github.com/ualbertalib/blacklight_solr_conf/blob/master/solr/blacklight-core/conf/solrconfig.xml#L184.

**Comment by seanluyk** [comment]
Excellent, thanks @pgwillia - this will improve the findability of a number of categories of items in BL

**Comment by seanluyk** [comment]
@pgwillia @weiweishi it would be nice to get this change approved so it could be announced alongside the Discovery-specific changes. Not sure how deployments for SOLR-conf work...do we also need to coordinate this with Neil?

**Comment by weiweishi** [comment]
I believe this will need to be coordinated with Neil to deploy into
production, and I don't know his process requires a release, or package the
current master branch. I will tag a new release and drop him the release
note, and maybe he will help us clarify what he needs to deploy changes in
this repo.



*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*
