### ISSUE TITLE
Change "item not found" logic and messaging.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1143]
First approximation solution: add logic so e-resource message doesn’t display if no item records; remove “ask us” sentence from bottom message, perhaps replace with “please try again in a few minutes”.
This issue should be resolved by this summer

**Comment by redlibrarian** [comment]
I can't find a record where this applies right now. When I do, I will take a screen shot of the message as it appears right now. When I do, I'll take a screenshot and paste it here so we can identify what needs to be changed.

**Comment by redlibrarian** [comment]
Done when:
- [ ] e-resource link does not display when there are no items
- [ ] missing items message tweaked

**Comment by redlibrarian** [comment]
Hmm. I can no longer replicate this bug. I'm going to move it out of the project, and we can revisit in phase 2 if necessary.

**Comment by theLinkResolver** [comment]
@redlibrarian [Here's something that was deleted last week](https://www.library.ualberta.ca/catalog/7070362).

**Comment by seanluyk** [comment]
Closing as the fix deletes mega-issue covers it all
