### ISSUE TITLE
Infrastructure and Workflows

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1144]
@pgwillia to
- [x] resurect Weiwei's docker branch
- [x] Move Solr config back into Discovery repo
- [x] add some bits to the Readme about how to use it
- [x] orient Sam and Natasha to using docker in development

@redlibrarian to
- [x] document discovery servers and their role
- [ ] Flesh out issues (bugs, user stories, etc)
- [x] security updates - Deal with Gemnasium warnings (Dependabot?)
- [x] Set up GitHub workflows
- [x] Request UAT server from ITS (or find out if current DI UAT will serve for Discovery)

Then we can talk about next steps
- [x] tests (start fresh with minitest?)
- [x] style (rubocop/hound)
- [x] travis-ci
- [x] docker UAT environment

**Comment by redlibrarian** [comment]
@weiweishi Is there anything else you need in here for now?

**Comment by pgwillia** [comment]
In order to setup Solr for Discovery in a Docker contianer, I'll be copying [blacklight_solr_conf](https://github.com/ualbertalib/blacklight_solr_conf) into discovery.  There are some notes in that's repo's readme that describe why Neil wants them separate. He should be in the loop about this change.

**Comment by pgwillia** [comment]
The security updates I was thinking about are the Gemnasium warnings.

**Comment by redlibrarian** [comment]
OK, I've fleshed out the Discovery server information as best I can. I have one question for Neil, which I will get the answer for and then update the file.
