### ISSUE TITLE
Setup GitHub worflows

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1147]
I want to set up the GitHub workflows as close as possible to the ones set up for the Jupiter project. The main piece here are the branch settings, setting up protection for the master branch:

- [x] Protect branch
- [x] Require pull request reviews before merging
- [x] Dismiss stale pull request approvals when new commits are pushed
- [x] Require status checks to pass before merging 
- [x] Require branches to be up to date before merging
- [x] Include administrators
- [x] Restrict who can push to this branch

Setting up the status checks will require a passing test suite, so this issue relies on #1103

**Comment by redlibrarian** [comment]
This is done, except for the status check requirement. Because we don't have a passing test suite, our status checks wouldn't pass. I will leave this unprotected until we have a passing test suite.

**Comment by pgwillia** [comment]
https://github.com/ualbertalib/discovery/pull/1156 and https://github.com/ualbertalib/discovery/pull/1157 would make for status checks for passing specs and style. The idea there was to forgive previous transgressions while allowing us to get feedback about changes we make. Some licence to make changes.

Requiring branches to be up-to-date before merging is probably a good one to have too.  What was the reason for exclusion?

**Comment by redlibrarian** [comment]
@pgwillia Requiring branches to be up-to-date is nested under the status check requirement, so it seemed to me we couldn't require up-to-date branches without requiring passing status checked. I agree that, after further discussion about what we'd like to do, setting up basic passing with Travis and Rubocop will allow us to enable these parts of the workflow. I'll do that now.
