### ISSUE TITLE
Search terms breaking search

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1171]
**Description** 
For some reason searching for **Gordon Winter** throws an error in Discovery, when searching for everything. 

![image](https://user-images.githubusercontent.com/2047614/41877514-beff5410-788e-11e8-8a4a-14b95cb670a2.png)

![image](https://user-images.githubusercontent.com/2047614/41877677-6dd20064-788f-11e8-8b8b-9d456d3c5531.png)

When searching only in **Books, media, & more** or **Articles & more**  it works properly. 
![image](https://user-images.githubusercontent.com/2047614/41877721-89badae4-788f-11e8-84dd-377283ccf8b7.png)

**Priority**
@redlibrarian is this a user report? how critical is this comparing to other development work? Will this issue go away once the article search is removed? 

**Expected behavior**
Search everything with the term "Gordon Winter" should return results.

**Comment by seanluyk** [comment]
As of v. 3.0.88, Gordon Winter is not breaking search terms - could be related to recent reindex, or not at all. Closing.
