### ISSUE TITLE
Named Collections as facet

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1177]
**As a user I want to**:
* Facet by a named collection

**As a collections librarian I want to**:
* See all the items in a given named collection

**As a donor I want to**:
* Find all the items I donated in a named collection

**Description**:
Some items are associated with particular named collections, often named after the person who donated the collection. One example is the "Schloss Collection". The name of the collection appears in the **Note** field which is taken from the MARC 590 field.

![screenshot from 2018-06-12 09-28-29](https://user-images.githubusercontent.com/1093066/41300498-1c358cba-6e23-11e8-8700-b113bc838bc4.png)
(https://library.ualberta.ca/catalog/2013590)

The tricky thing is that the 590 fields (General Note), like all MARC fields, contain free text. A 590 field *may* include the name of a collection, but that name will be embedded within a larger text string. A 590 field may also contain text that has nothing to do with a named collection. There is no structured delimiter for the collection name.

**Desire outcome**:
- [ ] Facet created using the collection names.

**Comment by theLinkResolver** [comment]
For reference - our [cataloguing procedure listing standardized named collection text](https://docs.google.com/spreadsheets/d/17H6bpl8-cJehnHV5YK5DmgUbwMfH2FRdfMWfCmBHjUU/).

**Comment by theLinkResolver** [comment]
@weiweishi correct, absolutely this is a living document going forward. I caution that there are likely some older statements that do not appear on this list, and also some of the things on this list are not "collections" per se (e.g. University of Alberta copy a gift of ...). 

We can probably help answer number 3, but let's hear what @redlibrarian has to say first.

**Comment by redlibrarian** [comment]
@weiweishi Yes, the 590 field is being indexed, but only the subfield a (https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/symphony_index.properties#L151) which I think/hope is the only subfield we need here. 

Given the length of the text and the number of possible values, I think it's best to have the field linked in the record rather than having a left-hand facet. In other instances (author, subject), we haven't been able to decide whether a search or a facet is preferable. My sense is that when the data is clean enough, a facet is better than a search, but @pgwillia might have a better understanding of that.

Question 3 is the most difficult. Because these names are embedded in a larger note field (e.g. https://library.ualberta.ca/catalog/747657) it's likely not going to be very straightforward to parse the text out of the note field as we are currently indexing it. I'm interested hear @theLinkResolver 's thoughts on that.

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
