### ISSUE TITLE
Discovery: Newspaper/Microfilm/Microfiche Request Form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1185]
As a regular user of the Discovery service, I want to be able to send a request within the Discovery system's record to access newspaper/microfilm/microfiche materials that are currently held at RCRF, so that I don't need to track the request form down on the library website, and don't need to type in the bibliographic information on the form.  

**Current situation/Context**
- There are microfilm/microfiche/newspaper items in the catalog, and discoverable in the Discovery service. They are mostly held at RCRF.  Often, there's only one bibliographic record for all the volumes/issues/years. 
<img width="1062" alt="screen shot 2018-06-28 at 2 45 27 pm" src="https://user-images.githubusercontent.com/2047614/42059822-eb96c6a2-7ae1-11e8-93ec-f3e1caf9145f.png">

- Currently, users don't have a way to request these items inside the Discovery system. They will need to go find the RCRF Request form and fill it in themselves:
https://web.library.ualberta.ca/catalogue/bard/, and filled in the required information so that the requested volume(s)/issue(s)/year(s) can be shipped to their desired pick-up location. 

- Some microfilm/microfiche objects can be requested through the regular "Place a Hold" button. They are usually monographs. They should continue to have the "Place a Hold" button. 

**Goal**
- To enable users to initiate the request within the record in the Discovery system. 
- To allow users to choose their desired pickup location for the materials. 
- To send the requests to RCRF/ILL team so that they can start processing the request. 

**Screenshot**
Request should be initiated from  
![image](https://user-images.githubusercontent.com/2047614/41871864-6bd90774-787d-11e8-8c26-04ec421b9edb.png)
To:
![screenshot from 2018-06-25 13-40-59](https://user-images.githubusercontent.com/2047614/41871939-9f8b96ae-787d-11e8-93e2-889110039a59.png)

Current RCRF request form is at:
https://web.library.ualberta.ca/catalogue/bard/

**Design Details**
- The request form will be reviewed - CJ will provide the language used on the form (wireframe will be created based on existing form, and the new language)
- The request form should be sent to depository@ualberta.ca, and ill@ualberta.ca
- Fields are deemed as required are:
  - Name and email address of the user who requested the object.
  - Title (auto-populated into the form)
  - URL to the record (auto-populated into the form)
  - One of these: Year/Volume/Date (if not applicable, user has to indicate it's not applicable)
  - pick up location
- We will need to figure out the logic to identify the records that needs to have the request form button. We will tolerate errors in deciding whether the users are presented with "Place a Hold" or "Request Me". Request form will be the fallback. 
- Business logic to identify the records will be based on the API response from Symphony. 
https://ws.library.ualberta.ca/symws3/rest/standard/lookupTitleInfo?clientID=Primo&marcEntryFilter=ALL&includeItemInfo=true&includeAvailabilityInfo=true&includeMarcHoldings&titleID=7564032

**ACTION ITEMS**
- CJ's team will send us some sample records to analyze what is the best logic to use to distinguish monographs and other kinds of microfilm/microfiche materials. 
- CJ will provide language for the new request form
- Dev team will create a wireframe based on the current request form, with the new language/labels. #1216

**Comment by seanluyk** [comment]
Done, closing.
