### ISSUE TITLE
Discovery: Deployment of release x.x.x

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1208]
After the following (at a minimum) have been merged
- [x] #1183 - reclaim RAILS_ENV 'test' by moving that environment to 'staging'
~~- [ ] #1195 - changes the way Solr ingest targets are configured~~

Both these items change configuration and will need coordination with @nmacgreg for corresponding configuration management (ansible) changes.

**Comment by pgwillia** [comment]
Would this be a breaking change? Should this be 3.1.0 or 4.0.0?

**Comment by weiweishi** [comment]
Personally I don't think these are "breaking" changes, as it has less impact to the production instance, but more for the backend/non-production configs. But I will let others to chime in as well @mbarnett @murny @cwant @piyapongch

**Comment by pgwillia** [comment]
Just a heads up that I'm cutting a new release 3.0.79. There are no changes to user facing features. This is in coordination with Neil's changes to configuration management to deploy to a 'staging' environment instead of a 'test' environment. This will then allow developers and continuous integration (CI) services to reclaim the 'test' environment for (potentially) destructive unit testing. #1183

**Comment by pgwillia** [comment]
The 3.0.79 release was successfully deployed in 'staging'. It is scheduled for deployment in production tomorrow (Wed Aug 15) morning.

**Comment by weiweishi** [comment]
@pgwillia I assume no service interruption will be involved with this deployment if all goes well? 

@seanluyk tagging you to let you know that a new release will be deployed to production tomorrow morning.

**Comment by seanluyk** [comment]
Thanks, @weiweishi

**Comment by pgwillia** [comment]
Replying to https://github.com/ualbertalib/discovery/issues/1208#issuecomment-413007963

There should be zero impact to the service if it goes well or if it needs to be reverted. Neil has already volunteered, "I'll take york out of the pool this morning & apply this version, so we can test a preview." This release only contains changes that impact the 'staging' environment and *no changes* to user facing features.

Note that this thread is in parallel to an email thread where @seanluyk is copied.
