### ISSUE TITLE
Discovery: [SPIKE] Identify business logic to identify micro items that needs the request form 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1217]
The business logic to identify the records will be based on the API response from Symphony.
https://ws.library.ualberta.ca/symws3/rest/standard/lookupTitleInfo?clientID=Primo&marcEntryFilter=ALL&includeItemInfo=true&includeAvailabilityInfo=true&includeMarcHoldings&titleID=920516

We will do the initial spike to understand what xml elements (or a combination of) to use to decide when to display the request form. 

### Sample Records
These are the type of micro items that will need the request form:

Serial titles:

https://library.ualberta.ca/catalog/7794495
https://library.ualberta.ca/catalog/465030

### Records 
- Display for items held at **University of Alberta Research and Collections Resource Facility**
- Item types will be "Microform"
- Item doesn't have any holding information, only the main bibliographic information.

**Comment by pgwillia** [comment]
![screenshot from 2018-11-27 15-28-37](https://user-images.githubusercontent.com/1220762/49115881-39c4a580-f259-11e8-810b-b86f7a9d0400.png)
I understand the first two criteria, but I'm not sure what "Item doesn't have any holding information, only the main bibliographic information." means.

**Comment by seanluyk** [comment]
@pgwillia hmm, I'm not quite sure I understand that third part either unless this is referring to the fact that for many microform titles, specific holdings aren't attached to the record in Blacklight. Take, for example, the [Edmonton Journal](https://library.ualberta.ca/catalog/1759039) For UofA holdings, we've not catalogued each holding. Is this what you were getting at @weiweishi

**Comment by weiweishi** [comment]
Thanks @seanluyk and gosh I can barely remember what I meant by that. *I think* it means that many serials in microforms only have the bibliographic records, and don't have detailed holding information in the catalogue.

**Comment by theLinkResolver** [comment]
I can assure there will always be one "item" for each record. @weiweishi it may also be that a record with extensive holdings like the [Globe & Mail](https://library.ualberta.ca/catalog/465030) can take so long to pull up that the timeout is reached and the items table is not rendered, and maybe that is a scenario that you were thinking of or had encountered when you were first putting the issue together.

**Comment by seanluyk** [comment]
Logic works as expected, even on a beast of a record such as this one: https://library.ualberta.ca/catalog/465030?feature_flag_request_forms=1
