### ISSUE TITLE
[Discovery] Add librarian view link to Tools menu

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1242]
Add Librarian View link to the Tools menu (see NEOS Blacklight for an [example](https://catalogue.neoslibraries.ca/catalog/8156891) of this functionality). This will help libraries staff better identify resources and will be useful for QA purposes while indexing rules are being revised with advice from Bib Services.  

Note: 
Librarian View is already available in Discovery service by pending `/librarian_view` to any given object. 
https://library.ualberta.ca/catalog/1759039/librarian_view
The requirement for this issue, is to add the link to the UI so it becomes available to library staff.
Prefer to be a pop-up window.

**Comment by weiweishi** [comment]
@seanluyk Confirm with you re: UI requirement for this ticket. I assume that the "Librarian View" should go here:
<img width="342" alt="screen shot 2018-09-04 at 7 00 50 am" src="https://user-images.githubusercontent.com/2047614/45032970-60838f00-b010-11e8-935c-bbffc10bc5aa.png">

Should it go after "Export to Endnote"?

The link should be called "Librarian View"? 

Thanks!
