### ISSUE TITLE
[Discovery] Create wireframe for BPSC No Loan Form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1246]
To create the wireframe in Balsamiq for the new request form based on the requirements. When the wireframe is completed, send it to Sean and Linda Quirk and Robert Desmarais for review.

**Current form**
https://docs.google.com/forms/d/126ZJ6r6L42AeoWVyOQRWdY9b0SYv7VxUljx6V1d56Po/viewform?edit_requested=true

**Required fields**

- Name/Email of the person who sends the request
- appointment time for the viewing

**Prepopulated fields**
 - the title of the object
 - call number of the object. 

**Additional fields**
- Free text field, optional, as "Additional notes" 

**Title**
Bruce Peel Special Collections Retrieval Request Form (Read on Site Items)

**Language to use as the description on top of the form**

All researchers (including students, faculty, visiting scholars, and members of the general public) must submit a Retrieval Request Form before 8am on the day of their planned visit (at the very latest) in order to be sure that library materials have been retrieved from storage and are available for their use. If you have any questions, please contact library staff at bpsc@ualberta.ca or call 780-492-5998 during regular business hours (Mon-Fri 12:00-4:30pm). 
Prior to your visit, please review our Reading Room Policies. https://bpsc.library.ualberta.ca/info/visit#policy

**Comment by murny** [comment]
Created a simple initial mockup of the requirements outlined above:
https://balsamiq.cloud/s3awdua/pmnl7qx/r8C53

Let me know if you got any feedback!

(Not quite sure on the title/name of the form itself? Used `RCRF/BPSC Retrieval Request Form (No Loan)` for now)

**Comment by seanluyk** [comment]
Thanks @murny I'll send this one along, too. Maybe just change the title to `RCRF/Bruce Peel Special Collections Retrieval Request Form (Read on Site Items)` for now and we'll get CJ and others to confirm.

**Comment by murny** [comment]
Title's now been changed :+1:

**Comment by weiweishi** [comment]
Thanks for the clarification @seanluyk. Updated the ticket for BSPC Read on site form only. 

Created a new ticket for the RCRF Read on site form #1251

**Comment by murny** [comment]
Updated BPSC Retrieval request from can be found here: https://balsamiq.cloud/s3awdua/pmnl7qx/rE1BA

**Comment by seanluyk** [comment]
@murny  - sent to BPSP for feedback

**Comment by murny** [comment]
Above requested changes have now been made: https://balsamiq.cloud/s3awdua/pmnl7qx/rE1BA

**Comment by seanluyk** [comment]
Thanks, @murny one more change. Beside first date of planned visit, please add the hours, e.g. First Date of Planned Visit (open Mon-Fri 12-4:30pm)

**Comment by murny** [comment]
Hours have been added to label as suggested :+1: 

https://balsamiq.cloud/s3awdua/pmnl7qx/rE1BA

**Comment by seanluyk** [comment]
Looks great, @murny. So I think the forms are more or less close to being finalized, would you agree?

**Comment by murny** [comment]
If CJ and other stakeholders are happy with them and they signed off on them then absolutely I would say they are finalised and we can close these tickets

**Comment by seanluyk** [comment]
Perfect, I'll send it to them once more for finalization

**Comment by seanluyk** [comment]
Linda and Robert are happy with this particular form, so this is now finalized.

**Comment by murny** [comment]
Sounds great @seanluyk. Closing out ticket! (will add a reference to this ticket from the implementation ticket #1259 )
