### ISSUE TITLE
[Discovery] Business logic to identify objects that need to have No Loan form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1247]
Based on the requirements, any object that is located at RCRF, and has a location/status "READONSITE" needs to have the RCRF no-loan form displayed #1251. Any object that is located at BPSC and has a location/status "READONSITE" needs to have the BPSC no loan form displayed #1184 

 

The information needs to be either parsed from the API response
(BPSC no-loan item: https://ws.library.ualberta.ca/symws3/rest/standard/lookupTitleInfo?clientID=Primo&marcEntryFilter=ALL&includeItemInfo=true&includeAvailabilityInfo=true&includeMarcHoldings&titleID=5642450
RCRF no-loan item: https://ws.library.ualberta.ca/symws3/rest/standard/lookupTitleInfo?clientID=Primo&marcEntryFilter=ALL&includeItemInfo=true&includeAvailabilityInfo=true&includeMarcHoldings&titleID=8081485)

Note that "current location" (not home location) is what needs to be used to identify these items, in addition to libraryID.

Or we could obtain that information from Solr, in the 926 tag, which is currently indexed but not displayed: https://library.ualberta.ca/catalog/8081485/librarian_view. Catch is the data in 926 is not live, and has a day's delay. 

Blocked by the implementation of the READONSITE status code in Symphony.

**Comment by seanluyk** [comment]
Here's an example of a Read on Site item at RCRF: https://ws.library.ualberta.ca/symws3/rest/standard/lookupTitleInfo?clientID=Primo&marcEntryFilter=ALL&includeItemInfo=true&includeAvailabilityInfo=true&includeMarcHoldings&titleID=8081485
Note that "current location" (not home location) is what needs to be used to identify these items, in addition to libraryID. 

If we decide to go the SOLR route for this kind of info, it can be obtained from the 926 tag: https://library.ualberta.ca/catalog/8081485/librarian_view
