### ISSUE TITLE
[Discovery] Create wireframe for RCRF No Loan Form 

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1251]
To create the wireframe in Balsamiq for the new request form based on the requirements. When the wireframe is completed, send it to Sean and CJ for review.

**Required fields**

- Name/Email of the person who sends the request
- appointment time for the viewing
- viewing location (options between the following two)
  - Bruce Peel Special Collection (Mon-Fri 12-4:30pm) 
  - Archives Reading Room (Tues-Thurs 9-4pm).

**Prepopulated fields**
- the title of the object
- call number of the object.

**Additional fields**
Free text field, optional, as "Additional notes"

**Title**
RCRF Retrieval Request Form (Read on Site Items)

**Language to use as the description on top of the form**

**Comment by weiweishi** [comment]
@seanluyk does this capture your understanding? We'd need language from CJ/Linda for RCRF no loan item form. Not sure if the language here #1246 still applies.

**Comment by murny** [comment]
Separate form for RCRF Retrieval Request Form can now be found here:
https://balsamiq.cloud/s3awdua/pmnl7qx/r8C53

(currently using same description as BPSC, but as weiwei says in above comment this is probably not relevant anymore and needs new language from stakeholder)

**Comment by seanluyk** [comment]
Thanks @murny I've asked CJ to review/provide description text

**Comment by seanluyk** [comment]
@murny here are CJ's requested changes:

Preamble text:

> No Loan items do not circulate, but can be viewed at the RCRF Reading Room on South Campus or the Bruce Peel Special Collections Reading Room on North Campus. Use this form to request viewing of the item at one of these locations. A staff member will contact you within two to three business days to arrange for your visit to view the item. 

 - The button/link in Discovery could say "Request to View"
 - Form title could then be: Request to View RCRF No Loan Items
 - Replace Call number field with Item URL field, with an example, as in the RCRF Microform/Newspapers form  
- Move Viewing Time below Viewing Location, as they will see the possible times when they select the Viewing Location

**Comment by theLinkResolver** [comment]
@seanluyk @sjshores Augustana not an option? Thought that was the plan. Just double checking as they may not be on CJ's radar

**Comment by sjshores** [comment]
Scott, I had confirmation from Denise that Augustana staff do not want to
be a normal reading site for these materials.

Sandra

**Comment by seanluyk** [comment]
@theLinkResolver I'm not sure if it is for this particular form, but I'll check

**Comment by theLinkResolver** [comment]
@sjshores sounds good. Note to self, update our "do not circulate" flags (for what they're worth - will check with CJ on that). These decisions always have tentacles!

**Comment by murny** [comment]
[Mockup](https://balsamiq.cloud/s3awdua/pmnl7qx/r8C53) now updated to above requested feedback from CJ/@seanluyk

**Comment by seanluyk** [comment]
@murny  - sent to CJ for feedback

**Comment by seanluyk** [comment]
Like #1216 just waiting for a thumbs up from CJ, then this is finalized

**Comment by seanluyk** [comment]
@murny: final feedback on this one from CJ:

For the locations, could you modify "Archives Reading Room" to "Archives Reading Room - RCRF"

Also, in the pre-amble it should read "Archives Reading Room - RCRF" instead of RCRF Reading Room, to be consistent.

**Comment by murny** [comment]
Done and Done, now reflected in [mockup](https://balsamiq.cloud/s3awdua/pmnl7qx/r8C53)

**Comment by weiweishi** [comment]
@seanluyk Closable?

**Comment by seanluyk** [comment]
@weiweishi wireframe approved by CJ, closing!
