### ISSUE TITLE
Reword text on Advanced Search page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1254]
Remove the following text (first two bullet points) on the [advanced search page](https://library.ualberta.ca/advanced):

- NB: This advanced search screen only searches local content.
- Please use the Articles Advanced Search to search for non-local content.

Suggest replacing the rest verbatim with text from [Stanford Searchworks Advanced Search](https://searchworks.stanford.edu/advanced), but we'll need to verify that all the operators are correct given that they are on a different Blacklight version

**Comment by weiweishi** [comment]
Natasha will verify the search tip texts are applicable in our instance.

**Comment by nnunn** [comment]
Ok I checked through Stanford's Advanced search tips and they DO NOT work on UAL Blacklight. Specifically, truncated terms and wildcard searches do not work. I have removed the first lines as requested and changed the language to be the same as Stanford on the points that do work the same. However, I have left the last two points as is.
