### ISSUE TITLE
Implement Micro/Newspaper Request form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1258]
Once the wireframe is finalized here, #1216, the form needs to be developed on the front end:

https://balsamiq.cloud/s3awdua/pmnl7qx/r8F6C

**Requirements**
Auto-populated fields:

- Title
- URL to the record 

The request form should be sent to depository@ualberta.ca, and ill@ualberta.ca

The request url would be  https://library.ualberta.ca/rcrf-specialrequest

**Comment by theLinkResolver** [comment]
@weiweishi @seanluyk I don't want to speak out of turn on this matter, but with respect to the name for the URL, it was once hoped that eventually the unbarcoded newspapers would be processed and the need to request them this way would disappear. (I presume we're talking about [these sorts of things](https://www.library.ualberta.ca/catalog/2687592))

**Comment by theLinkResolver** [comment]
...so that is to say that the newspaper aspect may diminish in importance over time, which may affect the naming convention :)

**Comment by seanluyk** [comment]
Good point, @theLinkResolver. In that case, for this form, how about we go with /rcrf-specialrequest or something as a catch-all?

**Comment by weiweishi** [comment]
@theLinkResolver @seanluyk thanks. I've updated the requirements for this form, to use:
 https://library.ualberta.ca/rcrf-specialrequest

**Comment by seanluyk** [comment]
As the form is in production under a feature flag, this work is done so the issue can be closed
