### ISSUE TITLE
[Discovery] Implement BPSC No Loan Form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1259]
Once the wireframe is finalized here, #1216, the form needs to be developed on the front end:

https://balsamiq.cloud/s3awdua/pmnl7qx/rE1BA

**Requirements**
Auto-populated fields:

- the title of the object
- call number of the object.

URL for this form is:
 https://library.ualberta.ca/bpsc-readonsite

The original request was that these forms need to be sent to Jeff Papineau jeff.papineau@ualberta.ca and Kevin Zak kzak@ualberta.ca (@seanluyk I'd like to push back on this requirement, as using personal email is not a good idea not only because the communications only go to individual emails, but this also means that any personnel change would need a deployment of the application. )

**Comment by seanluyk** [comment]
@weiweishi  - perhaps they have a delegated email account they could use instead? I'll check.  

For the URL on this and the RCRF read on site form, my preference would be to use the following convention:  /libraryacronym-location, e.g. /bpsc-readonsite

**Comment by weiweishi** [comment]
@seanluyk They do currently have a delegated email but I think that copies to everyone in BPSC, and they don't want that. If they'd prefer not to use the existing one, I wonder if we could suggest them to create a new one and set cc to these personal emails that they'd need?

**Comment by weiweishi** [comment]
Thanks @seanluyk I've updated the requirement for URL to be https://library.ualberta.ca/bpsc-readonsite

**Comment by murny** [comment]
Wireframe/Mockup is now finalized and can be found here: https://github.com/ualbertalib/discovery/issues/1246

**Comment by seanluyk** [comment]
@murny I've sent an email to BPSC staff. I'll let you know what they say. I like the idea of a newly created delegated account (they don't want to use their generic account).

**Comment by seanluyk** [comment]
Adding another requirement to this ticket that's come out of testing:

When a user submits a request form, BPSC staff would like a confirmation email indicating that the request was received to be submitted. Specific text to follow soon

**Comment by seanluyk** [comment]
In production, feature flag removed. Closing.
