### ISSUE TITLE
contents field truncated in record view

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1267]
This is not a new problem (i.e. not an unexpected result of recent changes), but I don't think anyone reported it before. Same behaviour in Firefox & Chrome.

![trunc](https://user-images.githubusercontent.com/14913579/45500552-274bcd00-b73c-11e8-9b6d-f07c15c98c82.JPG)

**Comment by seanluyk** [comment]
I think this is duplicated in #1088, can you verify, @theLinkResolver? If so, please close this issue

**Comment by seanluyk** [comment]
P.S. @theLinkResolver fixing this issue is scheduled for the current sprint

**Comment by theLinkResolver** [comment]
@seanluyk Got me! Same issue. Closing.
