### ISSUE TITLE
[Discovery] Update UofA Library Links in holdings table

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1273]
Links to most UA libraries in the holdings table are currently going to an old NEOS page, e.g. https://catalogue.library.ualberta.ca/sirsi/index.cfm?location=UASCITECH

![image](https://user-images.githubusercontent.com/14880206/55440007-90bdec80-5563-11e9-8729-4a642d47e0a0.png)

It would be better if UA libraries linked to their locations page here instead: https://www.library.ualberta.ca/locations

For non-UA NEOS Libraries we should link to their equivalent location page linked to from these pages:
https://www.neoslibraries.ca/member-libraries/

@weiweishi @ConnorSheremeta I'm thinking that might be a good easy win as another "first issue" eventhough you've already worked on a bunch! We can tackle improving other display elements in the future but this would be good to get in place soon

**Comment by theLinkResolver** [comment]
@seanluyk totally agree FWIW. There's also a usability issue with these links (especially for internet holdings), right? One idea I will throw out there is to make the link not a link, and instead adding a clickable 
![huh](https://user-images.githubusercontent.com/14913579/45700796-b1c07200-bb2a-11e8-81e0-cd27f6ddbc50.png) or something after the library name. Then it's a bit more transparent about what will happen when the link is clicked.

**Comment by seanluyk** [comment]
@theLinkResolver thanks for your comments, this is absolutely true re: usability. Step 1 is getting the right links there, step 2 will be redesigning the record view (coming soon) to something closer to NEOS Blacklight, e.g. https://catalogue.neoslibraries.ca/catalog/1236269

**Comment by weiweishi** [comment]
And it's currently defined here:
https://github.com/ualbertalib/discovery/blob/master/app/views/catalog/_holdings.html.erb#L53-L55

We will need to map the locations and their urls as the location codes are not used in the URLs, so we can't construct the URLs automatically. Probably we need to expand this file https://github.com/ualbertalib/discovery/blob/master/config/locations.yml
This is a less ideal way to manage the information as the urls might subject to changes often. Let's chat this at our grooming meeting.

**Comment by seanluyk** [comment]
@weiweishi it might be worth revisiting the idea of a separate database to define libraries, locations, and URLs. I just added #1592 and am reminded that this needs to be added to NEOS discovery as well. It would be nice to be able to add, update, and delete these independently of a deployment. Yes, let's chat at the grooming meeting about this!

**Comment by weiweishi** [comment]
Dev team will come together to discuss the DB structure to support this.

**Comment by pgwillia** [comment]
Questions:
- [ ] In NEOSDiscovery [it looks like](https://github.com/ualbertalib/NEOSDiscovery/blob/a71bc06ae8e544f351320acaaf1358a09aca4840/app/views/catalog/_symphony_holdings.html.erb#L10-L33) the webservice response is parsed from a human readable string into a human readable string.  Why can't we just use the webservices response?

**Comment by pgwillia** [comment]
- [ ] SPIKE - can you have the same migration in two applications
- [ ] make these ActiveRecord Objects which share a migration
- [ ] SPIKE - gemify?
- [ ] refactor logic around these objects out of the view
- [ ] seed data from the existing table(s) -- question are they the same in both project
- [ ] error handling - if an id is looked up that doesn't exist catch in rollbar and use 'Unknown' temporarily
