### ISSUE TITLE
Indexed item will not display

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1286]
**Describe the bug**
An item indexed in Discovery leads to a "we're sorry, something went wrong" page. The item is indexed in Discovery because it's possible to view its MARC record by appending /librarian_view. It is possible that this issue applies to multiple records, although this is the only report.  

**To Reproduce**
1. Go to https://library.ualberta.ca/catalog/8105323/
2. See error
2.  Go to https://library.ualberta.ca/catalog/8105323/librarian_view

**Expected behavior**
Items that appear in search results should lead to their record view.

**Comment by theLinkResolver** [comment]
I just fixed this. There was an encoding error in one of the 856 fields. Specifically:

|3Grande Prairie Regional College Access|uhttp://search.ebscohost.com/login.aspx?direct=true&scope=site&db=nlebk&AN=1350223|zfrom EBSCO

was missing the |u before the URL:

|3Grande Prairie Regional College Accesshttp://search.ebscohost.com/login.aspx?direct=true&scope=site&db=nlebk&AN=1350223|zfrom EBSCO

**Comment by seanluyk** [comment]
Thanks @theLinkResolver, closing the issue.
