### ISSUE TITLE
Publication year facet changes when adding a subject limiter

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1290]
**Describe the bug**
When clicking on a subject from a record view, the behaviour of the Publication year facet changes from its default. The expected date range slider is removed and is replaced with textual description of publication range and [View Distribution link](https://library.ualberta.ca/catalog/range_limit?q=%22Trees++United+States%22&range_end=2010&range_field=pub_date&range_start=1785&search_field=subject&view=brief) 

**To Reproduce**
1. Go to [this record](https://library.ualberta.ca/catalog/1236269)
2. Click on subject [trees>United States](https://library.ualberta.ca/catalog?q=%22Trees++United+States%22&search_field=subject&view=brief)
3. Scroll down to Publication Year facet
4. Expand facet

**Expected behavior**
The date range slider in the Publication Year facet should be consistently displayed, regardless of additional limiters being added

**Screenshots**
![screen shot 2018-09-26 at 16 25 30](https://user-images.githubusercontent.com/14880206/46112726-d1017400-c1a8-11e8-89f8-7ea917aeb415.png)

**Comment by seanluyk** [comment]
@pgwillia another buggy one to fix if you have time

**Comment by pgwillia** [comment]
Looks like the range facet is populated from an AJAX call.  It's not happening in the case when you come from the catalog page.
![screenshot from 2019-03-01 13-18-04](https://user-images.githubusercontent.com/1220762/53664104-d44fce80-3c24-11e9-9d18-dd3309dbb427.png)
![screenshot from 2019-03-01 13-17-22](https://user-images.githubusercontent.com/1220762/53664105-d44fce80-3c24-11e9-8223-aa51b279fb28.png)
I think that turbolinks may be responsible.  I'm pursuing that angle.

**Comment by seanluyk** [comment]
Fixed in #1520, closing
