### ISSUE TITLE
open search does not use https in the blacklight layout

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#1291]
**Describe the bug**
The open search link in the blacklight header is not relative and is using http instead of https. This breaks our tests.

**Comment by nnunn** [comment]
Does someone know what this actually does? I have no idea and it was not added by me. Could we perhaps just delete it?

    <%= opensearch_description_tag application_name, opensearch_catalog_url(:format => 'xml') %>

in

https://github.com/ualbertalib/discovery/blob/master/app/views/layouts/blacklight.html.erb

**Comment by nnunn** [comment]
@seanluyk @weiweishi ?

**Comment by pgwillia** [comment]
This is opensearch https://github.com/ualbertalib/discovery/issues/1243.

**Comment by nnunn** [comment]
Well ok great - could you switch it to either an absolute link or HTTPS?

**Comment by pgwillia** [comment]
This is where that url is set https://github.com/projectblacklight/blacklight/blame/master/app/views/catalog/opensearch.xml.builder#L9

[Note it's in the blacklight gem]

**Comment by pgwillia** [comment]
Jupiter enforces the protocol generated by `url_for` with a line in the config/environments

https://github.com/ualbertalib/jupiter/blob/add9c58c6b8c9642931a2e58e296c8ce3bd923c6/config/environments/staging.rb#L1

**Comment by nnunn** [comment]
I think I'll leave this in your hands - since I'm trying not to take on any new tickets.

**Comment by pgwillia** [comment]
`Rails.application.routes.default_url_options` doesn't seem to be respected. :(

**Comment by pgwillia** [comment]
Closed by https://github.com/ualbertalib/discovery/blob/master/app/controllers/application_controller.rb#L7-L12
