### ISSUE TITLE
[Discovery] Use database to manage library location codes/status codes

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1297]
Currently, library location codes and status codes are managed in multiple yaml files, and each time when they change (and they change often!), it requires a new release of the Discovery service. We need to find a better way to manage these library codes/status codes. 

Proposal: Create a table in the application database, create models for library status codes and location codes, and use activerecord to access these values? Any update will be a change to the DB, instead of deployment of code. 

 Questions:
- do changes to the databases need to be loaded immediately by the application? Or how often?
- who changes the database and how? Is an admin interface needed?
- is it possible to pull the information directly from Symphony, with no intermediate database? (we already have a connection to Symphony web services)

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendations

**Comment by pgwillia** [comment]
1273

**Comment by pgwillia** [comment]
Some thoughts (definitely not a stupid question) from @nmacgreg 

>Stupid question: can't you just get the library + status codes you need, directly from an API in Symphony? (guessing that the data gets loaded there, first).  Or make it part of the nightly "incremental ingest" process?  (Let me guess: not enough source fields)

>The shared information, between NEOSDiscovery & Discovery, is tricky.  Logically, these apps should share those tables, but they already have 1 database each.  Does that mean we should create a 3rd database, which they share?  I dimly recall that Rails supported the idea of talking to 2 separate databases... dunno if that messes up your existing code, having to specify which database, rather than the database?  Anyway, this is out of my domain, I'll shut up now.

**Comment by pgwillia** [comment]
@redlibrarian says
>The library and status codes *are* maintained in Symphony, but my understanding of the search API is that it's not a full API against all the data Symphony contains. Rather, it's a search API for items; when I was going through the API documentation to build the API calls Discovery is currently using, those were the only search functions I could find. However, I know there are other APIs for things like patron records, transactions, etc, so it's possible that that configuration information *is* exposed somewhere and I just never saw it. On the other hand, it's also possible that SirsiDynix never thought anyone would want to query the full list of codes and so haven't exposed them via an API.
> If they aren't available over the API, they may be exportable - I'd have to talk to the ILS team to find out.

**Comment by pgwillia** [comment]
- [ ] SPIKE - can you have the same migration in two applications
- [ ] SPIKE - gemify?
- [ ] Implementation of NEOS Discovery
- [ ] Refactor for SolrMarc
