### ISSUE TITLE
missing line breaks in My Account renewal message

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1299]
**Describe the bug**
After renewing items in My Account (CCID), the message showing what I renewed is missing some line breaks for readability.

**Screenshots**
![my account](https://user-images.githubusercontent.com/14913579/46227445-77ba5180-c31c-11e8-83ea-e7b0f01a5edd.jpg)

**Desktop (please complete the following information):**
 - Windows
 - Firefox
 - 60.2.1esr (64-bit)

**Comment by seanluyk** [comment]
Thanks for reporting @theLinkResolve! I think I'll move this to a helpdesk ticket and close the issue as the problem lies in my account, not Blacklight as far as I can tell
