### ISSUE TITLE
Log output with Deprication Warning

### ISSUE THREAD

**Issue by nmacgreg** [ualbertalib/discovery#1301]
**Bug description**
When a single search is executed from the browser, this error message repeats more than 50 times in /var/log/httpd/error_log: 
App 7113 stderr: DEPRECATION WARNING: Building search parameters by calling show_only on DatabasesController. This behavior will be deprecated in Blacklight 6.0. Instead, define show_only on a subclass of SearchBuilder and set search_builder_class in the configuration. (called from each at /var/www/sites/blacklight/vendor/ruby/2.1.0/gems/blacklight-5.15.0/lib/blacklight/search_builder.rb:141)

**To Reproduce**
While tailing the log, run any search, our favourite: https://forest.library.ualberta.ca/symphony?utf8=%3F&q=global+warming

**Expected behavior**
There should be no errors in the log when a search is run.

**Other Recommendations**
Write a test that runs a list of searches, and other common actions, and ensures there are no errors or warnings in the log (only expected log entries).  (I sorta can't believe you don't have this already, it's best practice.)

**Comment by pgwillia** [comment]
Duplicate #1958
