### ISSUE TITLE
WIP Add Matomo tracking

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/discovery#1312]
**Describe the solution you'd like**
We would like to add Matomo tracking code to the library website, so that we can gather usage data into the library's Matomo instance for comparison with Google Analytics data and features.

This issue is WIP until we determine how much link-level tracking we require from Matomo, similar to what [blacklight_google_analytics is doing](https://github.com/jronallo/blacklight_google_analytics/blob/master/app/assets/javascripts/blacklight_google_analytics.js.erb).

It must be possible to turn it off without requiring a fresh deployment. The GA implementation does this by putting the site code in the app config, and only publishing the javascript if the site code is present.

**Additional context**
Contact pbinkley if you need an account on our Matomo instance.

**Comment by seanluyk** [comment]
@pbinkley the only thing I would add that will likely delay this that I should have mentioned this morning is that @nnunn is currently focusing her time on untangling the CMS from Discovery, so I'm wondering if it's worth pursuing this before that work is complete?

**Comment by pbinkley** [comment]
I checked with @nnunn and confirmed that this is can be done entirely within the discovery app, as Google Analytics is, so it won't require any of her time. And if we make it as similar to GA as possible it shouldn't add anything much to the untangling.

**Comment by seanluyk** [comment]
@pbinkley that's great!

**Comment by seanluyk** [comment]
Closing as the CMS is soon to not be part of the Discovery application, so this isn't an issue for this repository.
