### ISSUE TITLE
[Discovery] Conditions of Use on SFX Records

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1315]
**Remove**
The Our Usage Rights information that appears in tables on SFX records ([example](https://www.library.ualberta.ca/catalog/110978984350777)) is not drawn from its authoritative source (which is the CORAL ERMS), so should be removed. 

**Replace**
This should be replaced with a Conditions of Use Link to its CORAL record (currently displaying in tiny font as [ill](https://erms.library.ualberta.ca/coral/terms/?issn=1091-8515).
[To-Do] have a screenshot/wireframe for "View Terms of Use"

**Additional Context**
 - The CORAL ERMS is currently behind LDAP authentication, so view access for users would need to be configured, and discussed with CSU

**Comment by seanluyk** [comment]
Requested feedback from CSU librarians on this change

**Comment by theLinkResolver** [comment]
@seanluyk You may know this already but I'll share with all readers that the current data comes via an iframe tag that is in the "authentication note" field each individual SFX target at the service level. I think Ernie H. and Bib agreed to put it there because we knew that we weren't using that field for anything else at the time (and still are not, to my knowledge).

**Comment by seanluyk** [comment]
@weiweishi  @pgwillia @murny. Attaching a quick and dirty mockup, but just to clarify to requirements (once ready on the CORAL side):
 - Remove integration of OUR information coming in via SFX API
- Populate the Our Usage Rights column with the CORAL Links (style improvements to my ugly mockup are most welcome!)
- Remove ill link at the bottom of the page, and BrowZine link while you're at it

![screen shot 2018-11-26 at 15 56 36](https://user-images.githubusercontent.com/14880206/49047460-bb9ecb00-f194-11e8-9221-ec441fe2e3a1.png)

**Comment by seanluyk** [comment]
So here's the plan:

Before the work on this ticket can be done:
-Jeremy is going to work on a public-facing version of CORAL so that users can access terms of use information without needing to log in

Requirements for this ticket on the UI side can be found above at: https://github.com/ualbertalib/discovery/issues/1315#issuecomment-441834548

**Comment by seanluyk** [comment]
Update - Jeremy has a test version working and CSU is doing UAT. Once they're happy Jeremy will move this to production and we can make the UI changes in discovery.

**Comment by redlibrarian** [comment]
This is done.
