### ISSUE TITLE
Record error

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#1322]
**Describe the bug**
When you go to https://library.ualberta.ca/catalog/8105878 you get a "We're sorry but something has gone wrong issue"

**To Reproduce**
1. Go to 'https://library.ualberta.ca/catalog/8105878'
2. See error

**Expected behavior**
You should see the record view for "Like mother, like daughter?: how career women influence their daughters' ambition"

**Comment by seanluyk** [comment]
Looks like a similar issue to #1286. The item is indexed but won't display (but its [librarian view does](https://library.ualberta.ca/catalog/8105878/librarian_view))

**Comment by theLinkResolver** [comment]
I have just fixed this by correcting an erroneous 856 field:

|3University of Alberta Access$uhttp://www.jstor.org/stable/10.2307/j.ctt22p7kg7$z(Unlimited Concurrent Users)|zfrom JSTOR

The $ should be a | as follows:

|3University of Alberta Access|uhttp://www.jstor.org/stable/10.2307/j.ctt22p7kg7$z(Unlimited Concurrent Users)|zfrom JSTOR

The takeaway from this and #1286 seems to be that a record that contains an 856 but without a |u will trigger this result.

**Comment by seanluyk** [comment]
@theLinkResolver looks to be a similar issue with the 856 field: https://library.ualberta.ca/catalog/8105878/librarian_view

**Comment by seanluyk** [comment]
Thanks @theLinkResolver-  I'll keep this one open since it'll be good for us to figure out a better way to handle these errors on the user side.

**Comment by seanluyk** [comment]
Adding another example from the helpdesk https://www.library.ualberta.ca/catalog/7671309/librarian_view

I suspect this is another example where the missing $u in the first 856 is breaking it

**Comment by theLinkResolver** [comment]
@seanluyk Ugh, both 856s are messed up in this record. One lacks a |u, one lacks a |3! The mono team will have to dredge up the proper URL for King's and fix this one - I will let them know.

**Comment by weiweishi** [comment]
It seems these are data issues and need to be fixed on the individual records? And the ones mentioned in this thread seem to have been fixed? @seanluyk are you okay with closing this ticket?

**Comment by seanluyk** [comment]
Closing this ticket as we'll work with Bib to fix the underlying issues causing these records not to display
