### ISSUE TITLE
Wording and structure of search buttons?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#134]
'Noted that they frequently search newspapers and that it was not evident where they should go to search them. They noted that it was not an option in the ‘you are searching’ buttons and stated that they would visit the Subject Guides section for a newspaper guide.
Regarding ‘you are searching’ buttons, wondered aloud: “How are journals, ejournals and articles different?”'

**Comment by nnunn** [comment]
We can't fix this within Blacklight until all the Digitization and Collections are also searched. For now I am closing this - if we get any similar comments we can look at it again. It might be good to expand on what "digital collections" are, but I will wait for more feedback.
