### ISSUE TITLE
[Discovery] Configure Mail for UAT

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1342]
**Is your feature request related to a problem? Please describe.**
Recently debugging email/sms is there a way to see how mail performs in a production like environment?

**Describe the solution you'd like**
Add [MailCatcher](https://mailcatcher.me/) as a gem or docker container.

**Describe alternatives you've considered**
* use gmail smtp
* install a linux mail application in the image

**Additional context**
On a record view page (For example https://www.library.ualberta.ca/catalog/2913584), on the left hand side there are "Email me this item", "Text me a link to this item", and "Send correction"
![image](https://user-images.githubusercontent.com/1220762/47243176-7e356980-d3ae-11e8-87b0-6f3cc3423f11.png)
![image](https://user-images.githubusercontent.com/1220762/47243225-94dbc080-d3ae-11e8-99ca-b1024039bb3f.png)
![image](https://user-images.githubusercontent.com/1220762/47243243-a58c3680-d3ae-11e8-9a27-867e148c8dab.png)

**Comment by weiweishi** [comment]
- Change the docker-compose to add the new docker image for the mailcatcher
- Change the environment environments/uat.rb
'''config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = { :address => "localhost", :port => 1025 }'''
- Readme documentation
