### ISSUE TITLE
Treatment of statement of responsibility

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1364]
**Is your feature request related to a problem? Please describe.**
Statement of responsibility (245 $c) is not displayed, but this information is important for users to see as it specifies different forms of authorship. For example, on [this record](https://library.ualberta.ca/catalog/817700) there is nothing indicating that Bechert is the editor. Compare with [this record from Stanford](https://searchworks.stanford.edu/view/1401892), which uses a completely different layout and displays this subfield in a Responsibility field    

**Describe the solution you'd like**
 - 245 $c is mapped to a Responsibility field, displayed, but not faceted
 - We continue to rely on other fields (e.g. 700) for faceting by author
 
**Describe alternatives you've considered**
 - Leave as is

**Additional context**
 - Just documenting this while it's fresh, as this would require a redesign of the record page
 - There are possibly very good reasons for not displaying this, such as concerns over duplicated information
 - Will need to confirm this direction with Bib Services as part of metadata requirements

**Comment by theLinkResolver** [comment]
I would also suggest making sure 245 $c is indexed for keyword searching. It would be interesting to see what relevance Stanford uses.

**Comment by seanluyk** [comment]
Example of $k being displayed when $a is present: https://search.library.ualberta.ca/catalog/8277121

**Comment by seanluyk** [comment]
Fixed in test, closing.
