### ISSUE TITLE
Include library and status in bento results? 

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#138]
'Upon clicking more, they asked how they could tell what library the item was located in.'

**Comment by redlibrarian** [comment]
Further feedback suggests that title only is confusing, especially with many books with the same title (search for "science fiction")

**Comment by redlibrarian** [comment]
Author and Call Number are available under More. I wonder either if they could be added to the basic (non-more) view, or if we could add subtitle and author instead. What do you think, @nnunn ?

**Comment by nnunn** [comment]
Ok I've added the subtitle - I think (hope) this will be enough. We'll know more when I have more records.

**Comment by redlibrarian** [comment]
Thanks Natasha, that's great. It'll be good to get more feedback before we
tweak again.

On Tue, Apr 28, 2015 at 3:06 PM, Natasha Nunn <notifications@github.com>
wrote:

> Ok I've added the subtitle - I think (hope) this will be enough. We'll
> know more when I have more records.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/138#issuecomment-97207143>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB
