### ISSUE TITLE
Add call number to the BPSC form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1404]
This was not included in the initial wireframe but was raised when they reviewed the form on UAT. They'd like to have the Call Number of the item to be auto-populated into the form. 

Call number can be added between title and item url field on the form.

**Comment by murny** [comment]
Call number is the thing thats highlighted here? Correct?

![image](https://user-images.githubusercontent.com/1930474/49254262-09f6d880-f3e6-11e8-9930-233aca69496a.png)

**Comment by weiweishi** [comment]
Yes. That is call number.  And CJ didn't request to have this added to RCRF forms. I can double check with him to make sure. For now only need to add to BPSC form.

**Comment by murny** [comment]
I made the assumption here in #1417 that this call number field on the form is a required field just like title and item url? Is this a fair assumption?

**Comment by weiweishi** [comment]
I think this is an assumption that needs confirmation. I know BPSC wants to potentially use this form for requests that might not be triggered by Discovery records, and we will need to verify with them that all the requests they deal with are materials with call numbers.

**Comment by murny** [comment]
@weiweishi Before we close this...Did we get confirmation about my assumption with regards to call number being a required field?
