### ISSUE TITLE
[Discovery][Spike] Investigation on database icons

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1412]
This is to investigate the work required for #1113, in particular, to see if these icons and the information needed on the UI is indexed in Solr. 
If yes, implement the required changes. 

If not, document how databases entries are ingested into Discovery. and list information we will need to gather from API guide and other places to proceed, based on our current ingest pipeline.

**Comment by pgwillia** [comment]
Looks like there is something there about icons.  Upon first obersvation, not sure how to parse the combination of integers, image filenames and text.
<pre><code>
{
  "responseHeader":{
    "zkConnected":true,
    "status":0,
    "QTime":34},
  "response":{"numFound":1,"start":0,"maxScore":14.119791,"docs":[
      {
        "id_tesim":["11710698",
          "6665",
          "15484",
          "15485"],
        "title_tesim":["GamingDirectory.com"],
        "title_t":["GamingDirectory.com"],
        "title_display":["GamingDirectory.com"],
        "databasedescription_tesim":["<strong>Also known as: |Gaming Directory| </strong> Lists casino properties worldwide with a complete property profile and executive contact data by department and position. Updated daily.<br />"],
        "url_tesim":["https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=4637",
          "https://www.library.ualberta.ca/about-us/policies/restricted-resource-info",
          "https://www.library.ualberta.ca/about-us/policies/conditions-of-use/registration-required",
          "https://www.library.ualberta.ca/about-us/policies/conditions-of-use/restricted"],
        "enableproxy_tesim":["0"],
        "subject_tesim":["BUSINESS",
          "Social Sciences",
          "Sociology"],
        "subject_t":["BUSINESS",
          "Social Sciences",
          "Sociology"],
        "subject_topic_facet":["BUSINESS",
          "Social Sciences",
          "Sociology"],
        "type_tesim":["Database"],
        "format":["Database"],
        "electronic_tesim":["Online"],
        "location_tesim":["University of Alberta Internet"],
        <b>"icons_tesim":["\n    \n      6665\n      165\n      ualib-logo.png\n      licensed for  U of A\n      https://www.library.ualberta.ca/about-us/policies/restricted-resource-info\n      11710698\n      6665\n      \n    \n    \n      15484\n      165\n      cou-user.png\n      User Registration Required\n      https://www.library.ualberta.ca/about-us/policies/conditions-of-use/registration-required\n      11710698\n      15484\n      \n    \n    \n      15485\n      165\n      cou-sign-in.png\n      CCID Login Required\n      https://www.library.ualberta.ca/about-us/policies/conditions-of-use/restricted\n      11710698\n      15485\n      \n    \n  "],</b>
        "languagenote_tesim":["English"],
        "id":"11710698",
        "_version_":1618929304126619648,
        "timestamp":"2018-12-04T13:48:17.425Z"}]
  }}
</code></pre>

**Comment by pgwillia** [comment]
This is what it looks like before it's indexed (this would be more helpful)
```
pry(#<Databases>)> db['icons']
=> [{"id"=>"6665",
  "site_id"=>"165",
  "file"=>"ualib-logo.png",
  "description"=>"licensed for  U of A",
  "url"=>"https://www.library.ualberta.ca/about-us/policies/restricted-resource-info",
  "content_id"=>"11710046",
  "icon_id"=>"6665",
  "custom_url"=>""},
 {"id"=>"6666",
  "site_id"=>"165",
  "file"=>"save-sig-50c.png",
  "description"=>"conditions of use",
  "url"=>"https://www.library.ualberta.ca/about-us/policies/conditions-of-use",
  "content_id"=>"11710046",
  "icon_id"=>"6666",
  "custom_url"=>""}]
```

**Comment by pgwillia** [comment]
This is what I had started to look at to use the icons_tesim: https://gist.github.com/pgwillia/54371bf716c0301aaa81f203328d034e

Basically we'll need to map the string separated by line breaks back to id, site_id, file, description, url, content_id, icon_id. 

Then, to retrieve the logos:
`https://libapps-ca.s3.amazonaws.com/sites/#{site_id}/icons/#{id}/#{file}`
