### ISSUE TITLE
[Discovery] Change Layout of Record page

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#1426]
**Is your feature request related to a problem? Please describe.**
The current single records page is confusing for users. 

**Describe the solution you'd like**
Rework the layout of the single records page to reflect the following mock-up:
![records](https://user-images.githubusercontent.com/495318/49885620-fb9cb980-fdf4-11e8-8fd0-b297ef04a6f3.jpg)

**Comment by pgwillia** [comment]
Is there any change to mobile/responsive experience? Not immediately. We'll come back to that.

What shall we do with middle and right columns that are exceptionally long? Will happen. Just stay in your lane.

**Comment by weiweishi** [comment]
Blocked by #1432 if we'd like to have this done properly with latest Bootstrap

**Comment by weiweishi** [comment]
- [ ]  making sure existing tests are working with the new record view page.
