### ISSUE TITLE
Databases that do not need EZProxy have proxy URL prepended/ones that need it do not

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1454]
**Describe the bug**
I recently noticed that there's a piece of code that's prepending the EZProxy URL (http://login.ezproxy.library.ualberta.ca/login?url=) to all database records, regardless of whether or not they need it. There's a related problem where databases that DO need the EXProxy URL prepended for off-campus access don't have it for some reason. What this means in practice is that a user accessing a database from Blacklight will be required to log in to EZProxy even if the resource isn't proxied and even if they're on campus, which is extremely annoying and vice versa, will not be prompted to login and will be directed to a vendor login page. I also noticed in the case of the NEOS Catalogue, that there's a pretty significant performance hit when accessing it in an EZProxy session. I noticed this because the NEOS catalogue had incorrectly been proxied in LibGuides (the SpringShare product where database assets are managed), so I turned this off, yet almost a month later, it's still being proxied. A search in the repository found the EZProxy URL, and I confirmed this with a number of examples. 

**To Reproduce**
1. Access the [NEOS Catalogue](https://library.ualberta.ca/catalog/11711067). "Click here for access"
2. Note that the EZProxy does not exist in the source (in LibApps). URL received on ingest should be something like http://ualweb.library.ualberta.ca//uhtbin/cgisirsi/x/0/0/57/49?user_id=WUAARCHIVE

**Expected behavior**
I see two possible ways of dealing with this:
1.  If possible, modify the database ingest script so it looks for the "Proxy Enabled" setting in LibGuides. If yes, prepend proxy. If no, don't! 
2. Modify the ingest script to pull in/use the LibGuides "Friendly URL" instead (e.g. http://guides.library.ualberta.ca/databases/neos), which redirects to the appropriate link (proxied or not proxied) 

**Additional context**
I need to touch base with CSU to confirm that this is no longer required and if there's a really good reason not to mess with anything. I think this is meant to be a failsafe, but I don't believe it's needed any longer

**Comment by seanluyk** [comment]
@weiweishi this is high priority for discussion at the next grooming meeting/next spring as the problem is bigger than I first realized. I've updated the title and comment to reflect the fact that the EZProxy prefix isn't coming through when it should, which means users can't access our databases from off campus via Blacklight. I think the first step will be a spike into the database ingest code

**Comment by pgwillia** [comment]
I might have got it wrong when I did https://github.com/ualbertalib/discovery/commit/41bc2e333863435397ceb9599914db969f6f9f44

This is it now:
https://github.com/ualbertalib/discovery/blob/master/app/helpers/catalog_helper.rb#L39-L46

**Comment by seanluyk** [comment]
@pgwillia may be the case. I'm working with CSU on an improvement that could remove the need for logic to be handled in Blacklight. If we think that's preferable to doing this in BL I can get that work prioritized, but in the meantime, we may need to roll some of these changes back

**Comment by pgwillia** [comment]
```
"enableproxy_tesim":[
        "1",1367,
        "0",178,
        null,39375]}
```
1 and 0 account for all the Database content.

Example of `enableproxy_tesim:1`
```
"title_display":["ABI Inform Complete"],
"id":"11710046",
```
Example of `enableproxy_tesim:0`
```
"title_display":["Knotia.ca"],
"id":"11710906",
```

I suspect that the logic got flopped in my change

**Comment by seanluyk** [comment]
Thanks @pgwillia the good news is that I'm the only person who actually noticed so far!

**Comment by seanluyk** [comment]
Will do this quick fix; then spike to investigate if friendly URL can be ingested instead

**Comment by seanluyk** [comment]
Fixed in latest release.
