### ISSUE TITLE
[Discovery] Finish cleaning up CMS project from Discovery

### ISSUE THREAD

**Issue by murny** [ualbertalib/discovery#1476]
Issue https://github.com/ualbertalib/discovery/pull/1465 did a pretty job removing most of the CMS, but there is still a few chunks of code in discovery relating to the CMS that can be safely removed as well.

- [x] We got multiple CMS view layouts no longer being used (home/french/cms/cms_french)
- [x] We got lots and lots of CSS that only has to do with the now removed CMS
- [x] we also got lots of javascript relating to profile/cms pages (stupidtable, hoverintent, what is in ualib-home that we actually need? etc)
- [x] We got CMS stuff within our `bin/setup`, rake tasks (cmssetup.rake), in our README.md etc. that needs removal
- [x] I assume the CMS project is now using a different database? Let's drop these models from our schema/migrations
- [x] cleanup rubocop rules that had exceptions for CMS
- [x] cleanup ansible playbook

**Comment by weiweishi** [comment]
@nmacgreg @nnunn Does CMS have its own database, or does it share the same DB with Discovery. There are DB related code we could remove from Discovery if CMS has its own.

**Comment by nnunn** [comment]
library-cms has its own database so go ahead and remove that code!

**Comment by murny** [comment]
#1493 pretty much completes this now. 

Created another ticket for a deeper cleanse of the CSS/JS here: https://github.com/ualbertalib/discovery/issues/1502

Also the checkbox for refactoring ansible will probably be a separate ticket (was on the priority list) and I'd assume this will be done here.
