### ISSUE TITLE
[Discovery] Decimals difficult to read

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1488]
**Describe the bug**
Reported to the helpdesk - decimals in call numbers are difficult to read. Here's an example (decimal after 793): 
![image](https://user-images.githubusercontent.com/14880206/52374751-49abf300-2a1b-11e9-8150-84753050af75.png). 

Record in question: https://search.library.ualberta.ca/catalog/2468719

**Expected behavior**
Font weight makes it possible to see decimals in call numbers.

**Comment by ConnorSheremeta** [comment]
Closed as this is fixed in #1678
