### ISSUE TITLE
[Discovery] Add Google Analytics for search.library.ualberta.ca

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1516]
**Is your feature request related to a problem? Please describe.**
Now that Discovery is separate from the Library website/cms search.library.ualberta.ca needs it's own Google Analytics property.  There are lots of analytics we'd like to peruse once this is configured.

**Describe the solution you'd like**
Should make the value here 
https://github.com/ualbertalib/discovery/blob/939731db09e2db879f01b92b8f9185307458e903/app/views/layouts/application.html.erb#L28
configurable like https://github.com/ualbertalib/jupiter/blob/7d1853fd8c8c33e0edcffff68be18cf0b7da34d9/app/views/application/_analytics.html.erb#L11
```
 <!-- Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.secrets.google_analytics_token %>"></script>
  <%# TODO: javascript_tag, nonce: true do %>
  <%= javascript_tag do %>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    document.addEventListener('turbolinks:load', function() {
      return gtag('config', '<%= Rails.application.secrets.google_analytics_token %>', {
        'page_path': window.location.pathname
      });
    });
  <% end %>
<!-- End Google Analytics -->
```
Then make this a secret configurable by envar like this https://github.com/ualbertalib/jupiter/blob/7d1853fd8c8c33e0edcffff68be18cf0b7da34d9/config/secrets.yml#L29
```
shared:
 google_analytics_token: <%= ENV['GOOGLE_ANALYTICS_TOKEN'] %>
```

https://github.com/ualbertalib/jupiter/blob/7d1853fd8c8c33e0edcffff68be18cf0b7da34d9/.env_deployment_sample#L11

**Describe alternatives you've considered**
Just update the property token without the refactor.

**Comment by weiweishi** [comment]
this is completed, will be deployed.

**Comment by pgwillia** [comment]
This was deployed but is not collecting data.

**Comment by pgwillia** [comment]
Strongly suspect that disabling turbolinks in https://github.com/ualbertalib/discovery/issues/1589 is responsible.
