### ISSUE TITLE
Remove subtitle infavour of having this all in the title field

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1517]
If we're comfortable with removing subtitle in favour for a more inclusive title field we can clean up the rest of the ingest code https://github.com/ualbertalib/discovery/blob/939731db09e2db879f01b92b8f9185307458e903/config/SolrMarc/symphony_index.properties#L33-L35

and solr config (subtitle_unstem_search, subtitle_t, subtitle_display, subtitle_vern_display) https://github.com/ualbertalib/blacklight_solr_conf/blob/bc89d514ca857214c57bc2cb023e0d6dfe4a79c6/solr/blacklight-core/conf/solrconfig.xml#L398

This is related to https://github.com/ualbertalib/discovery/issues/1309 and https://github.com/ualbertalib/discovery/issues/978.

**Comment by seanluyk** [comment]
@pgwillia I think this will be fine, the only reason it wouldn't be is if we ever would want to separate this info for display purposes
