### ISSUE TITLE
Create Responsibility field for record view, to appear below title

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1544]
**Is your feature request related to a problem? Please describe.**
To free up space/improve the display of 245$c, statement of responsibility, it would be beneficial to display this in a separate responsibility field outside of the title. Here's an example of this approach: https://searchworks.stanford.edu/view/11056542

**Describe the solution you'd like**
Display 245$c in a Responsibility field, below the title/subtitle

**Additional context**
 - Relates to #1521

**Comment by seanluyk** [comment]
Just checking 3.0.106 and not seeing this in test FYI @weiweishi @ConnorSheremeta

**Comment by weiweishi** [comment]
looking at the code, I think a reindex is needed for this to take effect.


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*

**Comment by seanluyk** [comment]
@weiweishi right, that makes sense
