### ISSUE TITLE
Bookmarks Broken

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1549]
**Describe the bug**
Navigating to saved bookmarks leads to a 404 error

**To Reproduce**
1. Do a search
2. Add some items to bookmarks
3. Go to bookmarks https://search.library.ualberta.ca/bookmarks

**Additional context**
Bookmarks page loads before items are added, so the error is related to adding items

**Comment by seanluyk** [comment]
@weiweishi this is the issue I mentioned this AM that has some helpdesk tickets

**Comment by weiweishi** [comment]
I think this issue is related to the part where it renders the refworks link:
https://rollbar.com/ualbertalib/discovery/items/97/
where the error is thrown
```
<%= link_to t('blacklight.tools.refworks'), refworks_export_url(url: bookmarks_export_url(:refworks_marc_txt, params_for_search)), class: 'btn btn-default', id: 'refworksLink', target: '_blank' %>
```

the error message is related to key length, and it's probably because of this:
https://github.com/rails/rails/pull/25192?

**Comment by seanluyk** [comment]
@weiweishi good sleuthing, hopefully, this can be fixed in this release? Wondering if it's related to the RefWorks export issue too?

**Comment by pgwillia** [comment]
More specifically this is encrypt_user_id https://github.com/projectblacklight/blacklight/blob/v5.15.0/lib/blacklight/token_based_user.rb#L37-L41
```
# Used for #export action with encrypted user_id, available
# as a helper method for views.
def encrypt_user_id(user_id)
  message_encryptor.encrypt_and_sign([user_id, Time.zone.now])
end

##
# This method provides Rails 3 compatibility to our message encryptor.
# When we drop support for Rails 3, we can just use the AS::KeyGenerator
# directly instead of this helper.
def export_secret_token salt
  OpenSSL::PKCS5.pbkdf2_hmac_sha1(Blacklight.secret_key, salt, 1000, 64)
end

def message_encryptor
  derived_secret = export_secret_token("encrypted user session key")
  ActiveSupport::MessageEncryptor.new(derived_secret)
end
```

**Comment by seanluyk** [comment]
Fixed in production, but there's a new issue I'll add to a separate ticket
