### ISSUE TITLE
Items with multiple types of electronic resources have buttons where the label/url don't align

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#1584]
**Describe the bug**
I was assigned a helpdesk ticket about https://search.library.ualberta.ca/catalog/8587995
The first link is coming from ws.library.ualberta.ca and the second two are coming from trying to match the 856 $3 labels ["University of Alberta Access", "Dataset documentation"] with the singular url from 856 4 2 $u ["https://catalog.ldc.upenn.edu/LDC2000S85"].

**To Reproduce**
1. Go to https://search.library.ualberta.ca/catalog/8587995
2. See three buttons
  * Click Here for University of Alberta Access (Request Form) -- this is okay
  * University of Alberta Access -- this links to the dataset documentation
  * Dataset documentation -- this links to the current page

**Expected behavior**
1. Go to https://search.library.ualberta.ca/catalog/8587995
2. See two buttons
  * Click Here for University of Alberta Access (Request Form) -- this is okay
  * Dataset documentation -- this links to the dataset documentation

**Screenshots**
![Screenshot from 2019-03-28 09-31-06](https://user-images.githubusercontent.com/1220762/55191607-3d652c00-5168-11e9-8b5a-801bf8657efe.png)
![Screenshot from 2019-03-28 09-30-35](https://user-images.githubusercontent.com/1220762/55191608-3d652c00-5168-11e9-8400-6a466df3c018.png)

**Additional context**
Can think of two ways to fix this
 ~~- in https://github.com/ualbertalib/discovery/blob/9408b84b11fd650f38d934f8b10b9ae428775945/config/SolrMarc/symphony_index.properties#L160 populate `summary_holdings_tesim` (maybe rename this to be more meaningful?) with just the labels equivalent to [getSupplUrl](https://github.com/solrmarc/solrmarc/wiki/Predefined-Custom-Methods#getSupplUrls)~~
~~- trim labels for `url_fulltext_display` from https://github.com/ualbertalib/discovery/blob/9408b84b11fd650f38d934f8b10b9ae428775945/app/helpers/catalog_helper.rb#L50 before `supplimentary_urls` is consumed~~
- [x] use SymphonyService to collect labels and urls for related resources

**Comment by weiweishi** [comment]
@seanluyk will check if the first link will be the primary URL.

**Comment by seanluyk** [comment]
@pgwillia Amanda just confirmed that the first 856 link that appears is **not** always the primary link, but it is for this data set. I think the more difficult fix is what needs to be done

**Comment by pgwillia** [comment]
@piyapongch recommended creating a field for primary and supplemental urls where the label and url are paired together and separated by a | like https://github.com/ualbertalib/discovery/blob/baf659bdbdef77c70513dabd4ca7e2b4ea9d6cc5/config/SolrMarc/kule_index.properties#L129

https://github.com/solrmarc/solrmarc/blob/936774b41f4a1fa2128b99a2b4ca6f79284e11e3/src/org/solrmarc/index/SolrIndexerShim.java#L400-L414

**Comment by pgwillia** [comment]
https://search.library.ualberta.ca/catalog/5422921 is another example
![Screenshot from 2019-04-30 09-50-39](https://user-images.githubusercontent.com/1220762/56975148-6e50cc00-6b2d-11e9-827d-177d660ded42.png)

**Comment by pgwillia** [comment]
Use a custom script `related_resource_links = script(related_resource_links.bsh) getRelatedResourceLabelAndUrl()`  expect
`["Contributor biographical information | http://catdir.loc.gov/catdir/enhancements/fy1002/2009046369-b.html", "Publisher description | http://catdir.loc.gov/catdir/enhancements/fy1002/2009046369-d.html", "Table of contents only | http://catdir.loc.gov/catdir/enhancements/fy1002/2009046369-t.html"] ` for https://search.library.ualberta.ca/catalog/5422921

```
# related_resource_links.bsh
public String getRelatedResourceLabelAndUrl() {
  Set<String> labels = new LinkedHashSet<String>();
  Set<String> urls= new LinkedHashSet<String>();
  # need to further investigate what $x is doing here -- probably selecting only the urls
  AbstractValueIndexer<?> labelsIndexer= getOrCreateIndexer("{8563}?((ind1 = 4 || (ind1 = 7 & $x startsWith \"http\")) && (ind2 = 2 || (ind2 = 1)))", "||");
   getFieldListCollector(record, labelsIndexer, labels);
  AbstractValueIndexer<?> urlsIndexer= getOrCreateIndexer("{856uz3}?((ind1 = 4 || (ind1 = 7 & $x startsWith \"http\")) && (ind2 = 2 || (ind2 = 1)))", "||");
   getFieldListCollector(record, urlsIndexer, urls);
   # iterate over both labels and urls to generate the result - "label | url" array that's expected
   return result;
}
```

**Comment by pgwillia** [comment]
Is there a way to do a live lookup for the related resource url as well?

**Comment by pgwillia** [comment]
The non_ua_items is exactly that list!

**Comment by seanluyk** [comment]
Adding another use case here: https://search.library.ualberta.ca/catalog/8536131

Currently, no 856 links are displaying for this record (must be one of the indicators?).

**Comment by theLinkResolver** [comment]
Thinking just now - it might also be because there is no $3. I wonder if display depends on the presence of a $3.

**Comment by seanluyk** [comment]
@theLinkResolver looks like it could be: https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/symphony_index.properties#L158

**Comment by theLinkResolver** [comment]
@seanluyk Ah - agreed! 

While I initially thought this record had acceptable 856s, I have examined the NEOS cataloguing standards and have reckoned that a record should always have a $3 under the present circumstances, so I've recoded the $z info as $3. So now let's see how this looks tomorrow to see if this record fits the issue above. (p.s. I thought URLs/856s were live but not anymore? I might have missed that change)

In the future, we will need to modify the mapping and display to handle $y often instead of $3, as per a recent change to cataloguing standards/practice. Should I open a ticket on that to get it on the radar?

**Comment by seanluyk** [comment]
@theLinkResolver glad it's working now, thanks! Does Blacklight mapping need to be modified or is this more of an internal note for bib?

**Comment by theLinkResolver** [comment]
@seanluyk We can withdraw this most recent example from this issue (the original/initial problem remains. Bib does need to communicate upcoming changes to mapping & display requirements for 856s, so I can open that up in a new issue.

**Comment by pgwillia** [comment]
Deployed on search-test
