### ISSUE TITLE
Bookmarks email completion behaviour

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1589]
**Describe the bug**
Submitting the email form from bookmarks leads to a 404 error page

**To Reproduce**
1. Add some items to bookmarks
2. Click on email
3. Complete and submit form

**Expected behavior**
User should be returned to bookmarks page and email sent message should appear

**Additional context**
The email actually does get sent

**Comment by weiweishi** [comment]
This is done and closing. Waiting for deployment to production.
