### ISSUE TITLE
Add new languages location

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1592]
There's a new location in Symphony that will need to be added to [statuses.yml](https://github.com/ualbertalib/discovery/blob/master/config/statuses.yml)  so holdings don't appear blank:

languages: "languages"

**Comment by ConnorSheremeta** [comment]
Added issue for NEOS discovery [here](https://github.com/ualbertalib/NEOSDiscovery/issues/264)

**Comment by weiweishi** [comment]
This is done. Closing
