### ISSUE TITLE
Create feature tests for the search result page

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1600]
Current the catalogue search feature tests are very basic. We'd like to test the following features on the search result page as well.

This is an epic issue. Each checkbox can be turned into a separate issue/PR

- [x] Search results can be faceted (ideally will test all facets, but could focus on more popular ones, like Access, Institution, Publication Year, and Language), making sure the "More" link in facets works
- [x] Search results can be sorted by Year, Author and Title
- [x] Can change the search results per page. 
- [x] Can clear search terms and go back to the search box
- [x] For UofA holdings, the search results present a Shield/logo
- [x] Display of Google book jackets
- [x] A Symphony record contains metadata: Author, format, publication year, copies owned by
- [x] A database record contains metadata: format, and language, and logos for the condition of use.

**Comment by ConnorSheremeta** [comment]
I'm unsure where 'language and logos for the condition of use' metadata are for a database record (from the last checkbox), I've changed the criteria on the issue to just look at the format metadata for now.
