### ISSUE TITLE
[Discovery][Spike] RefWorks Import for Single Item Fails

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#1638]
**Describe the bug**
RefWorks import of a single item fails. The item reported is: https://search.library.ualberta.ca/catalog/6664649. Interestingly, other items do seem to work (e.g. https://search.library.ualberta.ca/catalog/4840545). Import of this item also fails from NEOS Discovery.

**To Reproduce**
1. https://search.library.ualberta.ca/catalog/6664649
2. Click Export to RefWorks
3. Try to add item to RefWorks library
4. See error (Import failed
Oops, we encountered some technical issues. Please try again later.)

**Expected behavior**
Import consistently works

**Additional context**
See also #847 #972 #1484. I think there's something in the data for the records that fail that's causing it to break

**Comment by seanluyk** [comment]
Thanks so some sleuthing from Amanda in bib, we think there may be an issue with some scripts:

https://search.library.ualberta.ca/catalog/8432754 (german, umlaut, eszett) - imported
https://search.library.ualberta.ca/catalog/8432757 (dutch, accent acute) - imported
https://search.library.ualberta.ca/catalog/8432824 (880 fields, chinese characters) - error
https://search.library.ualberta.ca/catalog/8500924 (880 fields, ukranian, cyrillic script) - error
https://search.library.ualberta.ca/catalog/8500927 (czech, crescent, accent acute, bolle) - imported
https://library.ualberta.ca/catalog/6664649 (macron) - error
https://library.ualberta.ca/catalog/8234110 (macron) - error
https://search.library.ualberta.ca/catalog/7085826 (macron) - imported, macron over u in sutras of title not imported

I'm going to submit a ticket to ProQuest as well to see what needs to be done on our end to resolve RefWorks import issues.

**Comment by seanluyk** [comment]
@weiweishi @pgwillia @ConnorSheremeta  - RefWorks got back to me and asked: "So it looks like the filter being called does not recognize the tagging in the file received. Do you know what format is being sent and what filter is being called. These would be set in the catalog."

I'm not sure how to answer this, but maybe you could look into it? I'm happy to keep the conversation with RefWorks going.

**Comment by pgwillia** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. https://search.library.ualberta.ca/catalog/6664649
> 
>     2. Click Export to RefWorks

At this stage I get 
![Screenshot from 2019-05-17 13-55-36](https://user-images.githubusercontent.com/1220762/57957071-4e086780-78b8-11e9-9e50-165a84bc43d7.png) What should I do to get past this?  Do I need to create an account or something?  Which side should I be using?


> 
>     3. Try to add item to RefWorks library
> 
>     4. See error (Import failed
>        Oops, we encountered some technical issues. Please try again later.)

**Comment by seanluyk** [comment]
@pgwillia you should be able to sign up for an account by selecting the option on the right

**Comment by pgwillia** [comment]
The ones marked error are working for me in Firefox on Ubuntu.  Is this browser/os specific?
![Screenshot from 2019-05-23 15-34-13](https://user-images.githubusercontent.com/1220762/58288265-50633980-7d70-11e9-8f06-9d6c87e694f3.png)

**Comment by seanluyk** [comment]
@pgwillia they all work for me now, which makes me think something got fixed on the RefWorks side
