### ISSUE TITLE
[Discovery] U of a logo license image broken

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/discovery#1676]
**Describe the bug**
Image for 'licensed for u of a' of the u of a logo is broken. The src on the image is '//s3.amazonaws.com/libapps/sites/165/icons/6665/ualib-logo.png' which I believe is a poorly formed URL that should be 'https://libapps-ca.s3.amazonaws.com/sites/165/icons/6665/ualib-logo.png'

**To Reproduce**
1. Make a search
2. Click on library in left sidebar
3. Click on 'University of Alberta Internet' facet
4. Notice that every item has a broken image where the u of a logo should appear

**Screenshots**
![Screenshot from 2019-06-12 13-13-56](https://user-images.githubusercontent.com/14242562/59379721-92025700-8d14-11e9-880c-e827a1ee0521.png)

**Additional context**

It was discussed below that brand guidlines specify that the U of A shield must be accompanied by text. Natasha has provided a shield with text here:

https://user-images.githubusercontent.com/495318/59459963-3d75df00-8ddb-11e9-8a02-9f41e8ca8cd4.png

that could be stored in app/assets/images and used for both the U of A holdings icon and the database icon.

**Comment by ConnorSheremeta** [comment]
Note: database icons appear to be working:
![Screenshot from 2019-06-12 13-27-37](https://user-images.githubusercontent.com/14242562/59380274-f671e600-8d15-11e9-9ebc-2e28e0e39719.png)

**Comment by seanluyk** [comment]
@nnunn could you provide @ConnorSheremeta with a new link to this asset?

**Comment by nnunn** [comment]
@ConnorSheremeta I'm a bit confused as I do see a logo on these records:

![Screen Shot 2019-06-13 at 10 56 54 AM](https://user-images.githubusercontent.com/495318/59451999-064b0200-8dca-11e9-8679-63c91b30114d.png)

**Comment by nnunn** [comment]
Also -- a much larger issue for discussion. Our brand guidelines state that we should not use the university shield without the logo text. Should we possibly change these logos to reflect this rule? Maybe to something like this?

![ual-small-logo](https://user-images.githubusercontent.com/495318/59452241-85403a80-8dca-11e9-9a4e-24c7f85f3eb3.png)

**Comment by ConnorSheremeta** [comment]
Very strange @nnunn , I do not see logos on those same two records. I've also tried on another device and am getting the same results
![Screenshot from 2019-06-13 10-59-57](https://user-images.githubusercontent.com/14242562/59452429-eb2cc200-8dca-11e9-940f-08b24dbe3be5.png)

**Comment by nnunn** [comment]
hmmm firewall issue maybe?

**Comment by nnunn** [comment]
Sean also sees the logo, but he's on the same network. I'll take a look on a one of the public computers.

**Comment by nnunn** [comment]
Gah - it was just cached on my computer. It's broken after a hard refresh.

Where do you think is a sane place for that image to live? I'm thinking within the discovery application makes sense? If so could you use the small png that includes the text?
![59452241-85403a80-8dca-11e9-9a4e-24c7f85f3eb3](https://user-images.githubusercontent.com/495318/59453533-537ca300-8dcd-11e9-9ad5-b0df123ef2bc.png)

Let me know if this works...

**Comment by ConnorSheremeta** [comment]
Yes that would make sense, it could go into app/assets/images. Should a similar png also be used for the database icon? (pictured above) If so, it would have to be a more detailed one as the one provided looks blurry when matching the size of the other database icons.

**Comment by nnunn** [comment]
How's this size?
![ual-md-logo](https://user-images.githubusercontent.com/495318/59459963-3d75df00-8ddb-11e9-8a02-9f41e8ca8cd4.png)

**Comment by ConnorSheremeta** [comment]
That's perfect! I've updated the issue with the details we've discussed

**Comment by pgwillia** [comment]
TIL that the UAL branding is part of a toolkit provided by another group on camups https://www.ualberta.ca/toolkit/downloads/logos/administration-offices-and-services/libraries
