### ISSUE TITLE
Implement good URLs

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#169]
http://www.w3.org/Provider/Style/URI.html

**Comment by nnunn** [comment]
@redlibrarian so do we have a way forward with this? I feel like the cms URLs are good, but I'm not sure what else I need to do.

**Comment by redlibrarian** [comment]
I can look into implementing in blacklight. Does it make sense to do this? For example, rather than "https://search.library.ualberta.ca/catalog/6758088" to have something like "https://search.library.ualberta.ca/catalog/asian-american-athletes-in-sport-and-society"?

**Comment by redlibrarian** [comment]
This seems like it could be pretty tricky, as the slug URLs are typically generated in the model. We don't have an ActiveRecord model, so I'm not sure how this would work. Postponed until phase 2.

**Comment by redlibrarian** [comment]
We're happy with the current URLs, as they are opaque. We can look at this again if it proves to be an issue.
