### ISSUE TITLE
missing records June 10-14

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#1702]
**Describe the bug**
Potentially thousands of Symphony records created June 10-14 are not in discovery and have not appeared after the monthly full index.

**To Reproduce**
Record samples cited in #1694. Thought it best to create a separate issue for the immediate problem, as #1694 is geared to detection of future problems.

**Additional context**
Maybe the full index didn't happen?

**Comment by seanluyk** [comment]
@theLinkResolver the monthly re-index should have happened, and it looks like the samples cited in #1694 are all there now. If you have any more examples of missing records from that period please add them here

**Comment by theLinkResolver** [comment]
@seanluyk Amanda and I confident that we're good on this now.
