### ISSUE TITLE
[Discovery] Resolve brakeman warnings

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/discovery#1720]
**Describe the bug**
There are 3 redirect warnings for brakeman which should be resolved

**To Reproduce**
1. run ```brakeman```
2. see the three warnings.

**Additional context**
This could be resolved by wrapping the referer with ```URI.parse(...).path```

**Comment by pgwillia** [comment]
https://brakemanscanner.org/docs/warning_types/redirect/
