### ISSUE TITLE
Test email and SMS functionality.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#180]

**Comment by nmacgreg** [comment]
That's odd.  I was under the impression our kickstart process left all new servers with a working sendmail configuration...  So, I checked servlers falkirk, dover, and york -- they're all configured & working just fine. 

However, I found that server forest had been missed: /etc/mail/sendmail.cf was empty, and half-a-dozen emails were queued for delivery.  I resolved that with "m4 sendmail.mc > sendmail.cf && service sendmail restart", then I tested that I could send myself mail from the server -- it works fine, now!

Can you test it now, Sam (eg forest & falkirk, in the Test environment)?
[What? Does this application send email?  Why & under what conditions?  We ought to write a test which demonstrates this functionality is working!]

**Comment by redlibrarian** [comment]
OK, thanks. I don't know if sendmail is on austin - if it's not, that explains why I thought it would need to be added to test and prod. Anyway, if it's working, that's great. 

Blacklight has an "email me this record", where users can have something sent to them. There shouldn't be any non-user triggered emails. There's also a "text me this message" which might use email, in the same way. 

And yes, we'll have a test for each of these features.

Thanks again - I'll test the functionality sometime today.

**Comment by redlibrarian** [comment]
Can't test this until we get austin/dundee straightened out (in the absence of falkirk/forest). So I'll have to see later on today.

**Comment by redlibrarian** [comment]
I managed to test this on dover. The email is triggered successfully, but threw an error. I overrode app/models/record_mailer.rb to fix it. We'll have to test that again.

**Comment by redlibrarian** [comment]
Tested, and this works.
