### ISSUE TITLE
Search Error on specific search

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#1811]
**Describe the bug**
A search for "Inner Journey" returns a "We are sorry, something has gone wrong" error.

**To Reproduce**
1. Go to the library home page
2. Do a search for "Inner Journey"

**Expected behavior**
We should get the search results for Inner Journey instead of an error.

**Comment by pgwillia** [comment]
NoMethodError: undefined method `join' for nil:NilClass
  File "/var/www/sites/blacklight/app/views/catalog/_index_default.html.erb", line 22, in _app_views_catalog__index_default_html_erb___88590831960807737_69920126634720

https://github.com/ualbertalib/discovery/issues/1797

**Comment by pgwillia** [comment]
`<%= document['location_tesim'].join(', ') %>` is the source of the problem.  Two ways to address it
- use [safe navigation](https://rubyinrails.com/2017/11/17/safe-navigation-operator-ampersand-dot-in-ruby/) `document['location_tesim']&.join(', ')
- figure out why this object(s) don't have a location_tesim.

**Comment by pgwillia** [comment]
(this problem currently only appears in production)

**Comment by pgwillia** [comment]
Since October 9, 2019

**Comment by pgwillia** [comment]
There was a re-index not long before. https://code.library.ualberta.ca/gitweb/?p=Unix.git;a=blob_plain;f=Change/2019/Q3/CR00000837.html;hb=HEAD

**Comment by pgwillia** [comment]
Has impacted 1767 unique queries. 
As of now
Occurrences: 1,872
IPs affected: 605

**Comment by pgwillia** [comment]
It looks like these queries involve titles that are only held by concordin.
https://search.library.ualberta.ca/catalog/7484506
https://search.library.ualberta.ca/catalog/3594123
https://search.library.ualberta.ca/catalog/7484719
etc, etc.
