### ISSUE TITLE
Two searches throwing errors.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1837]
**Describe the bug**
Two particular searches are throwing errors.

**To Reproduce**
1. Search for *Learner-centred teaching' or 'Maryellen Weimer'
2. Both searches return errors rather than result lists.

**Expected behavior**
Lists of results.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Additional context**
The book shows up in a search using the catkey:
https://search.library.ualberta.ca/symphony?utf8=%3F&q=7433734

The author search works if you click on the authors name in a record:
https://search.library.ualberta.ca/catalog?author=Weimer%2C+Maryellen%2C+1947-&search_field=advanced

And the desired record shows up as #20 in the list. So the book is there, but both an author search and a title search throw errors.

**Comment by pgwillia** [comment]
Duplicate #1811
