### ISSUE TITLE
Minor corrections in library names in full record display

### ISSUE THREAD

**Issue by sjshores** [ualbertalib/discovery#184]
Sam, this is me being picky.  I've noticed that HT Coutts appears as Ht Coutts.  Can you please change the lower case t to upper case?  Also, would you mind changing the prepositions and similar words in the library names to lower case, so not University Of Alberta, but University of Alberta.  Many thanks.

**Comment by redlibrarian** [comment]
This is fixed now. Let me know if you notice anything else like this.

**Comment by sjshores** [comment]
Thanks!
