### ISSUE TITLE
Set up data synchronization between Symphony and Discovery DB

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1843]
Since release 3.0.113, we have moved the management of location codes, circulation rules, statuses, and item types into DB, instead of static yml file in Discovery. This will avoid a new release every time a change is introduced in Symphony, and will allow for more efficient/accurate data used in Discovery.

Now we need to work with ILS team to create a solution that will sync the data from Symphony to  the DB, possibly as a cron job:
- [x] Meeting among ILS/Dev/@redlibrarian to talk about possible ways to get the information out of Symphony
- [x] Whiteboarding a solution that will work efficiently, with less development/system administration effort involved. 
- [x] Develop/Implement the solution.

**Comment by pgwillia** [comment]
More information https://github.com/ualbertalib/discovery/issues/1760

**Comment by weiweishi** [comment]
Reports from ILS team is ready to go. We will need a sample file to create script, establish workflow with @nmacgreg. @pgwillia will follow up with ILS for the reports.

**Comment by pgwillia** [comment]
We've tested data synchronization between Symphony and Discovery DB.  Happy with results!
