### ISSUE TITLE
[Discovery] Danger should not be installed in production.

### ISSUE THREAD

**Issue by ConnorSheremeta** [ualbertalib/discovery#1885]
Changes made in Jupiter should be reflected here as well: https://github.com/ualbertalib/jupiter/pull/1421

From PR:
Update Gemfile to reflect this. Also added require false, as we don't need to load Danger.

Also changed spec to test in Dangerfile

**Comment by murny** [comment]
Fixed once this PR gets merged https://github.com/ualbertalib/discovery/pull/1886

**Comment by murny** [comment]
Now merged into Master. Closing this out
