### ISSUE TITLE
Word changes on BPSC request form

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/discovery#1889]
From BPSC:
1. We have made a long-term change to our hours, opening half an hour later, so the last line of the preamble should say that we are open at 12:30 rather than 12:00.
https://github.com/ualbertalib/discovery/blob/master/config/locales/en.yml#L45
This line needs to be updated. 

2. The third question seems to be leading to some confusion: "First date of planned visit (open Mon-Fri 12-4:30pm, but renos are expected to cause intermittent closures in 2019-20 so please confirm hours here)."  We have patrons panicking if they are not going to get here at the time they said, and the time simply doesn't matter to us, so it is very unnecessary.  We propose that the third question be rewritten as follows:

"Please indicate the first date of your planned visit. Public access hours are Monday-Friday 12:30-4:30pm. Facilities maintenance work is expected to cause intermittent closures this term, so please confirm public access hours [here](https://bpsc.library.ualberta.ca/)."
Change here:
https://github.com/ualbertalib/discovery/blob/master/config/locales/en.yml#L49

**Comment by pgwillia** [comment]
![image](https://user-images.githubusercontent.com/1220762/82704263-654c0480-9c32-11ea-9a14-d5aa1d68743f.png)
![image](https://user-images.githubusercontent.com/1220762/82704509-ef946880-9c32-11ea-98db-b9cdffa6310a.png)

Was completed a while back.  Unfortunately I think this is moot for a while.
