### ISSUE TITLE
Placeholder For Priority NEOSDiscovery Performance Issue 

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/discovery#1951]
Details have not been provided at this time, but creating this as a placeholder ticket so that we have something to discuss in our Sprint kickoff on Monday

**Comment by pgwillia** [comment]
I believe this is related to https://github.com/ualbertalib/NEOSDiscovery/issues/354

**Comment by pgwillia** [comment]
No further reports of the issue.  I'll close.
