### ISSUE TITLE
Remove Browzine link from record views.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#1963]
Due to the cancellation of Browzine as of April 30, we will need to remove the browzine link from record views:

<img width="465" alt="Screen Shot 2020-04-22 at 12 36 51 PM" src="https://user-images.githubusercontent.com/1093066/80020284-fabe7200-8495-11ea-84e5-37c6d9b4c681.png">

This link is found here: https://github.com/ualbertalib/discovery/blob/01f4b0d60b7f340add4d0336871ea3b85d40f211/app/views/catalog/_holdings.html.erb#L127

And it is also included in specs:

https://github.com/ualbertalib/discovery/blob/a3a914930cadcc1df7ff6f78716d2879459cde11/config/promoted_services/service_records.xml#L5

https://github.com/ualbertalib/discovery/blob/a3a914930cadcc1df7ff6f78716d2879459cde11/spec/fixtures/browzine_record.xml#L5

https://github.com/ualbertalib/discovery/blob/edd287abc8a7bf48c376f520406b341efe34091b/spec/unit/promoted_services_spec.rb#L6

The entire paragraph in the record view can be removed.

**Comment by pgwillia** [comment]
In production
