### ISSUE TITLE
</span> tag showing up in facet more modal 

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/discovery#2011]
![image](https://user-images.githubusercontent.com/1220762/83818485-b8877380-a684-11ea-8da5-558c5c301184.png)

This shouldn't show up.  It might be something in here: https://github.com/ualbertalib/discovery/blob/c2f2e431c39a1d8f9661b25d9f900bb1e4179eb5/app/views/catalog/_facet_pagination.html.erb#L1-L17

**Comment by pgwillia** [comment]
Same issue exists in NEOSDiscovery.

**Comment by orangewolf** [comment]
found this ticket while looking for a solution to this same problem on other blacklight projects. Bumping Blacklight to 6.23.0 will fix the issue. https://github.com/projectblacklight/blacklight/issues/2247 =-)

**Comment by pgwillia** [comment]
In the master branch
