### ISSUE TITLE
BPSC Retrieval Request Form Update

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/discovery#2037]
This came in via an email chain from Linda Quirk -> Weiwei -> Me. Linda writes:

"The form needs a minor update in the context of COVID-19 and Peel's upcoming facilities project.

My idea is to replace this section:
Please indicate the first date of your planned visit. Public access hours are Monday-Friday 12:30-4:30pm. Facilities maintenance work is expected to cause intermittent closures this term, so please confirm public access hours here. 

With this:
Please note that the reading room in Bruce Peel Special Collections will remain closed through the fall term (2020) due to COVID-19 and in order to accommodate a large facilities project.  Limited services are available. Updates and details can be found on the Peel website [here](https://bpsc.library.ualberta.ca).  "

**Comment by pgwillia** [comment]
> Yes, except that I forgot to indicate that this third section should begin with the question (sorry about that!), so it should read as follows: **Please indicate the first date of your planned visit.** Please note that the reading room in Bruce Peel Special Collections will remain closed through the fall term (2020) due to COVID-19 and in order to accommodate a large facilities project. Limited services are available. Updates and details can be found on the Peel website here.

**Comment by pgwillia** [comment]
In production
