### ISSUE TITLE
Add OCLC number (Marc 035a) to the search index.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#2050]
This is an issue that has arisen with NEOS Discovery, but the two systems use the same search index. Concordia library uses WorldCat Local, and OCLC does not index our 001 cataloguing key. This means, they can't link directly to an item for hold-placing purposes. They *can* use the OCLC number, which *is* indexed in WorldCat Local, but we currently don't index that field. If we index that field, we may be able to come up with a solution for them to build a working place hold link. 

**Describe the solution you'd like**
Add something like **oclc_number_tesim = 035a** to the [[Symphony index properties]](https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/symphony_index.properties). Also add the oclc_number_tesim to the Solr search config (can use the same weighting as call number, I think). Then, when the next full reindex happens, records will become searchable by OCLC number in both UAL and NEOS Discovery.

**Describe alternatives you've considered**
We thought about adding this functionality to the place hold system itself, but we're limited by the Symphony API response, which can't search by anything but the 001/catkey.

**Comment by pgwillia** [comment]
Is this only relevant to materials in the symphony ingest?  Not databases, kule or sfx?

**Comment by redlibrarian** [comment]
That's right, yes. Only Symphony material gets reported to OCLC and gets an OCLC number. It's possible that there could be overlap with some Kule material, but this is mostly a solution to a NEOSDiscovery problem with placing holds, so that shouldn't be a concern.
