### ISSUE TITLE
Update proxy prefix?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#2075]
This may only be a query for @pgwillia 

Is the proxy prefix included in the new database-driven config? It's not derived from another source like symphony, but it currently lives in ingest.yml

https://github.com/ualbertalib/discovery/blob/master/config/ingest.yml#L1

If we change that from http to https, I don't think this will cause a problem, but I don't want to do it here if it will be redundant when we actually deploy the new db-driven config to production.

Thanks,
Sam.

**Comment by pgwillia** [comment]
For this codebase (Discovery) it looks like the proxy is coming from the ingest.yml config https://github.com/ualbertalib/discovery/blob/dc1967f61b25aba36f899a13ec3fc324b466b8c7/config/application.rb#L31

But for NEOSDiscovery the proxy is from the db-driven config. https://github.com/ualbertalib/NEOSDiscovery/blob/666a04170545e6c13bc5c69398d5011f7fcf242a/app/helpers/holdings_helper.rb#L32

**Comment by redlibrarian** [comment]
Oh, right, because in NEOS Discovery, the proxy is context dependent. Thanks, I forgot about that. This isn't an urgent change to make, so I think I will park this for now and come back to it after we've gotten used to working with the DB-driven config. 

Thanks.
