### ISSUE TITLE
Proxy prefix not being prepended to some Electronic Access links.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#2076]
Description:

A few records have been reported which should have the proxy prefix prepended to the electronic access links but do not. Other records are properly displaying the proxied URL. The same behaviour should apply to all electronic records (unless location is "Free Access", prepend the proxy prefix).

**To Reproduce**
These three records show the problem (hover over "University of Alberta Access")
https://search.library.ualberta.ca/catalog/4114691
https://search.library.ualberta.ca/catalog/4114739
https://search.library.ualberta.ca/catalog/4113878 

**Expected behavior**
This record displays the right behaviour:
https://search.library.ualberta.ca/catalog/6865591

**Additional context**
Proxy logic is [here](https://github.com/ualbertalib/discovery/blob/7c99f433441536ff576910926b21b16214183040/app/helpers/catalog_helper.rb#L37). Record view logic is [here](https://github.com/ualbertalib/discovery/blob/303acded158f9cc9d751aec92edb307208eb32b6/app/views/catalog/show.html.erb). 

NB: I'm not sure this is a code problem, since we've used the same proxy logic from the beginning, but I can't see a problem in the data. It would perhaps be worth digging into the data side of things (e.g. the MARC records).

**Comment by theLinkResolver** [comment]
All 3 of the examples have a blank second indicator for the 856. That must have something to do with it. 

(It's a valid value in terms of what's permissible in that position, but I'm fairly certain it's a cataloguing error in these cases - the second indicator should be 0, I think. Please don't take that as gospel though.)

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver  - I had noticed that, but I wasn't sure if that could be causing the problem. We don't look at it when determining the proxy logic. I can ask the cataloguers to make the change and then see if that fixes it.

**Comment by redlibrarian** [comment]
Fairfax added the second indicator and that fixed the problem. No idea why!
