### ISSUE TITLE
Unsecure content on Articles results page

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#223]
On EDS Articles search results page bookjackets are http instead of https.

**Comment by redlibrarian** [comment]
The EDS API documentation only lists insecure URLs for sessions and searching (https for authentication). I've opened a ticket with them to see if there are secure endpoints we can use.

**Comment by redlibrarian** [comment]
They're currently looking into it: "EBSCO New Case #1783618 - HTTPS and Blacklight integration"
