### ISSUE TITLE
Position of e-book bento box?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#306]
Since we are e-preferred, should be place the ebook pane above the print pane?

**Comment by nnunn** [comment]
Will consult with Kenton on this.

**Comment by nnunn** [comment]
Kenton and I both agree that it is best to leave print books above ebooks because most of our content is still print. We can revisit this in the future. The question was raised of whether separating print and ebooks makes sense. Perhaps User Tests will give us more clarity on this.
