### ISSUE TITLE
Consistency of date labels/data.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#308]

**Comment by nnunn** [comment]
@redlibrarian not sure how to fix this or where the inconsistencies are.

**Comment by redlibrarian** [comment]
This was kind of a place holder to make sure we caught everything. One example is that the search page says "ejournals", but the bento page says "electronic journals". Should these be made consistent?

**Comment by redlibrarian** [comment]
This was to catch a discrepancy between the catalog controller and the articles controller. I've fixed it now.
