### ISSUE TITLE
Back/history anchors?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#315]
"Also, if I'm scrolling down a page, including the home page, and I move forward to a second page, then go back to the first, is there a way to go back to the exact spot on the first page (where I left off)?  Sorry, I don't have the proper terminology to use for this!"

I think this is actually browser behaviour, no?

**Comment by nnunn** [comment]
This is a browser behaviour. There is a way to force all browsers to do it, but it takes a lot of rather ugly javascript. I am closing this for now. If it is brought up again in user testing I will re-open it
