### ISSUE TITLE
Kill sessions after 2 hours and add message to warn users

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#319]

**Comment by pbinkley** [comment]
We're looking at the same thing in HydraNorth: https://github.com/ualbertalib/HydraNorth/issues/226 . If you've got an application-side solution, we'd love to borrow it.

**Comment by redlibrarian** [comment]
It shouldn't be too difficult to add the timeout in the Rails
configuration. Adding the flash message should also be pretty easy. The
question is going to be at what point in the user's workflow does it make
sense to present the message....

On Tue, Jun 9, 2015 at 10:54 AM, Peter Binkley <notifications@github.com>
wrote:

> We're looking at the same thing in HydraNorth: ualbertalib/HydraNorth#226
> <https://github.com/ualbertalib/HydraNorth/issues/226> . If you've got an
> application-side solution, we'd love to borrow it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/319#issuecomment-110430559>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by pbinkley** [comment]
OK - it would be good to solve this in the same way if we can, for the sake of consistency and ease of sysadminning.

**Comment by redlibrarian** [comment]
Sure thing. We'll keep you in the loop.

Though, now that I think of it, since you are actually using
authentication, doesn't this problem go away for you? We have this issue
because we don't want to offer/force people to authenticate...?

Maybe this needs more of a face-to-face discussion at some point.

On Tue, Jun 9, 2015 at 11:21 AM, Peter Binkley <notifications@github.com>
wrote:

> OK - it would be good to solve this in the same way if we can, for the
> sake of consistency and ease of sysadminning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/319#issuecomment-110438783>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by pgwillia** [comment]
User sessions are cleaned up by Devise.  Guest/public sessions are not.

**Comment by pbinkley** [comment]
It arose as a problem under load testing: zillions of sessions piled up in the sessions table, and zillions of mysql connections were left hanging. We learned that the mysql connection pool is not shared by multiple Passenger processes: each has its own pool . So the session cleanup is part of larger resource-management problem.

**Comment by redlibrarian** [comment]
Oh, I see. This is more about the session management piece than the actual
"bookmarks" piece. Neil just added something to manage sessions, but I
haven't looked at it in detail yet...

On Tue, Jun 9, 2015 at 11:28 AM, Peter Binkley <notifications@github.com>
wrote:

> It arose as a problem under load testing: zillions of sessions piled up in
> the sessions table, and zillions of mysql connections were left hanging. We
> learned that the mysql connection pool is not shared by multiple Passenger
> processes: each has its own pool . So the session cleanup is part of larger
> resource-management problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/319#issuecomment-110440504>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by redlibrarian** [comment]
See #736 for a possible resolution to this.
