### ISSUE TITLE
Tool tips to explain what each search option does

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#348]
E.g. "databases", "ejournals".

@nnunn - what do you think?

**Comment by nnunn** [comment]
@redlibrarian not sure exactly how this would look. Would this be in the Bento Box?

**Comment by redlibrarian** [comment]
No, in the main web-page. I ran this by a few other people, and they don't think it's worth it. Let's talk about it tomorrow, but I think we can just close this issue without changing anything.

**Comment by redlibrarian** [comment]
The more I think about it, the more I think this was a librarian request.
