### ISSUE TITLE
Add Proactive Chat widget to web/blacklight pages.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#381]

**Comment by nnunn** [comment]
@redlibrarian I need a bit more information about this one.

**Comment by redlibrarian** [comment]
Waiting for @kgood to provide widget code.

**Comment by redlibrarian** [comment]
Here's the widget code:

    
    <div class="needs-js">JavaScript is required...</div>

    
    <script type="text/javascript">
      (function() {
        var x = document.createElement("script"); x.type = "text/javascript"; x.async = true;
        x.src = (document.location.protocol === "https:" ? "https://" : "http://") +     "us.libraryh3lp.com/js/libraryh3lp.js?8994";
        var y = document.getElementsByTagName("script")[0]; y.parentNode.insertBefore(x, y);
      })();
    </script>

**Comment by redlibrarian** [comment]
We're going to delay implementing this until after the new website launch.

**Comment by redlibrarian** [comment]
@kgood I knew I had found the widget code. It's here if you need it.

**Comment by redlibrarian** [comment]
We can add the widget to a few select pages in the website anytime now, I think.

**Comment by gooyers** [comment]
Hi @redlibrarian. The possibility of proactive chat on bento box Blacklight pages came up during PSC yesterday. Is this still being considered?

I could see there being issues that would need resolving (ex. Once dismissed, will the proactive chat widget know to 'stay dismissed' even if a user is conducting multiple searches and returns to the bento box page multiple times). But the consensus at PSC was that it would be worth considering.

**Comment by redlibrarian** [comment]
@kgood @sjshores @timwklassen Should this go to WAT? I shouldn't make the call on this, as I really don't like the proactive chat feature. I'll do whatever the decision is, obviously, but I shouldn't be the one to decide how to proceed on this.

**Comment by sjshores** [comment]
Yes, it should go to WAT, but I'm wondering if it might be too late to
incorporate for go-live.

Sandra

**Comment by redlibrarian** [comment]
@sjshores it's an easy change to make, and we will have to make one more code release before launch (just little things).

**Comment by gooyers** [comment]
One final thing that came up with PSC was that if it were integrated, perhaps a longer time limit than 15 seconds could be used.

**Comment by redlibrarian** [comment]
The time limit would be decided either by PSC or by Kara, as chatref person... / @gooyers

**Comment by alfodor** [comment]
The 4 digit # assigned in the proactive chat widget is what will
determine how many seconds it takes to pop up. (ie,
...libraryh3lp.js?8994) Currentlywe are using 8994 in production for a
15 second pop up. If we think we might alter that time in the future
use one of these numbers (1740 (currently 1s) or 1739 (currently 60s)
which we can alter from the libraryh3lp side of things and not have to
push up.

April

On Thu, Dec 3, 2015 at 11:08 AM, redlibrarian <notifications@github.com>
wrote:

> The time limit would be decided either by PSC or by Kara, as chatref
> person... / @gooyers <https://github.com/gooyers>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/381#issuecomment-161734897>
> .
>



-- 
*_______________________________________________________________*
*April Fodor  |  *information technology services  |  university of alberta
libraries
780-492-4682  |  4-30 cameron library  | april.fodor@ualberta.ca

**Comment by kgood** [comment]
Closing Issue.
