### ISSUE TITLE
eds limit in bento box seems set at a maximum of five

### ISSUE THREAD

**Issue by nnunn** [ualbertalib/discovery#390]
even though I change the @local_eds_limit variable in the bento/index.html.erb the interface will not list more than five results. I can set it to 4 and it works so the variable is working, but I think there must be a limit set in eds itself?

**Comment by redlibrarian** [comment]
Turns out this is part of a wider issue where we can't control the number of facet values for articles. I'm looking into it...

**Comment by redlibrarian** [comment]
There was a problem in the controller. Fixed now.
