### ISSUE TITLE
Database Subject Lists on Subjct Section

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#391]
Where do these point?

**Comment by redlibrarian** [comment]
Hmm. Those point to the old database list interface. We don't have subjects
in the databases yet (b/c it's trickier than I thought). I'll have to
figure out how to get subjects in, then these links can point to blacklight
searches...

On Tue, Jul 21, 2015 at 2:57 PM, kgood <notifications@github.com> wrote:

> Where do these point?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/391>.
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by redlibrarian** [comment]
Jeremy has added the subject information to the database dump I'm using. I'll implement subjects tomorrow, and then these list searches can be built.

**Comment by redlibrarian** [comment]
Should this now point to LibGuides subject lists? @kgood

**Comment by kgood** [comment]
Closing old issue.  Temp solution found for where we point these links.
