### ISSUE TITLE
Fix Blacklight deprecation warnings.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#423]

**Comment by redlibrarian** [comment]
These are upstream.

**Comment by redlibrarian** [comment]
If, as per #940 we start with the latest version of Blacklight, then these deprecation warnings are moot, and the issue obsolete. Leaving this issue open until we can discuss it this afternoon.

**Comment by weiweishi** [comment]
Now we have forked Blacklight gem, can we identify the deprecation warnings and remove them?

**Comment by pgwillia** [comment]
Duplicate #1958
