### ISSUE TITLE
Add Stanford's format icons (or something like that).

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#427]

**Comment by redlibrarian** [comment]
An example of the icons can be found here. @nnunn Are there open-source/cc-licensed icons we might be able use for this?

**Comment by redlibrarian** [comment]
Looks like Stanford's icons are from the Font-Awesome font.

https://fortawesome.github.io/Font-Awesome/icons/

The full list of Stanford's icons is here: http://searchworks.stanford.edu/

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
