### ISSUE TITLE
Sound recording/non-musical recording facet value

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#428]
Is this video recording, or sound recording as well?

**Comment by seanluyk** [comment]
@redlibrarian , I think the streaming databases (e.g. Naxos) are to blame. They label as "sound file" in the 300 field. Not sure where non  musical recording is coming from. It's probably more important to spilt sound recordings from video recordings. The musical/non-musical distinction isn't worth it.

**Comment by theLinkResolver** [comment]
@redlibrarian @seanluyk Do you guys remember where you were seeing this? I can't find it.

**Comment by seanluyk** [comment]
Hmmm, I'm no longer seeing "non-musical recording" but do see the occasional record labeled as format = sound recording.

Here's a list of sample records labeled as sound recording: https://search.library.ualberta.ca/symphony?f%5Bformat%5D%5B%5D=Sound+Recording&q=beethoven

It looks like if an item contains a substantial amount of narration, it gets labelled as sound recording, for example, in this [Jeremy Irons thing that sounds awful](https://search.library.ualberta.ca/catalog/6951565)

**Comment by theLinkResolver** [comment]
I think the original facet values we were seeing were straight out of the MARC labels/definitions, which are, indeed, "Nonmusical sound recording" and "Musical sound recording". We now use "Sound Recording" and "Musical Recording". And @seanluyk is likely right - if most of the work is non-musical, it will get tagged as "Sound Recording". I will close this.
