### ISSUE TITLE
Test Zotero and Mendeley cite/import.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#429]

**Comment by seanluyk** [comment]
@redlibrarian as expected, this works with EDS records, but not pure Blacklight ones. Zotero just isn't picking up that there's metadata to be had. Apparenty Stanford has figured it out, and my Chrome Zotero connector recognizes record there.

**Comment by redlibrarian** [comment]
Hm. This should be working. See: https://github.com/projectblacklight/blacklight/issues/30

I'll have to investigate some more, maybe follow up with the blacklight list.

**Comment by redlibrarian** [comment]
Interesting, the Stanford catalogue is using COinS for Zotero (and probably other things, like Mendeley). I don't know if that should be enabled already in Blacklight, or if we'll have to add it. This may end up getting postponed until after the January launch.

**Comment by redlibrarian** [comment]
in Stanford's app/views/catalog/show.html.erb, they have:

    <% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
      <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(@document[@document.format_key]) %>"></span>
    <% end %>

I wonder if we need to install an openurl extension to the SolrDocument class for this to work?

**Comment by redlibrarian** [comment]
@seanluyk I got a request from a faculty member to add this in, which reminded me that I had forgotten to do it. The new code should be in test today or tomorrow - can you test it when it's in test? We can then push to prod pretty quickly. Thanks.

**Comment by seanluyk** [comment]
Sure, I'd be happy to @redlibrarian

**Comment by redlibrarian** [comment]
@seanluyk This is in search-test now. Thanks.

**Comment by seanluyk** [comment]
Sorry for the delay in looking at this. It appears that search-test can't be reached

**Comment by seanluyk** [comment]
It appears that this is mostly working for books and ebooks (with fields being split oddly in some places, but this is typical with Zotero), but not for other formats. For example, adding a journal to Zotero adds a journal article, and other formats are treated as web pages.

**Comment by redlibrarian** [comment]
@seanluyk OK, thanks. It looks like the openURL Blacklight generates isn't always correct. This will need some fine-tuning, probably in the summer.

**Comment by seanluyk** [comment]
This is working as well as can possibly be expected as far as I can tell - did some comparisons between importing citations in EDS and Blacklight and get very similar results. This works for books/ebooks but needs fine tuning for other formats as Sam explains

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
