### ISSUE TITLE
Article search from front page doesn't limit to Journal Articles.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#441]

**Comment by redlibrarian** [comment]
@nnunn - Can you add "&eds_action=addfacetfilter%28SourceType%3AAcademic+Journals%29" to the Articles search limiter on the home page, please? Thanks.

**Comment by redlibrarian** [comment]
I'll have to figure out how to add the facet filter to the ArticlesController...

**Comment by redlibrarian** [comment]
Similar to how we've labeled Symphony and Ebooks, should we call this "Articles and more (EDS)"?

**Comment by nnunn** [comment]
I think I need more info on this one.

**Comment by redlibrarian** [comment]
Oh, this one is *old* and can be closed. I'd forgotten about this.

On Tue, Nov 10, 2015 at 1:59 PM, Natasha Nunn <notifications@github.com>
wrote:

> I think I need more info on this one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/441#issuecomment-155564054>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB
