### ISSUE TITLE
display all 240 subfields (music, treaties, language eds., etc.)

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#457]
There needs to be a way to do this without cluttering up the display.

**Comment by seanluyk** [comment]
@redlibrarian it should be possible to not clutter up the display too much, I've seen this in other Blacklight implementations. The majority of uniform titles aren't too huge.

**Comment by seanluyk** [comment]
This is important, but can probably wait a bit - moved to the next milestone.

**Comment by theLinkResolver** [comment]
Revised the issue name a bit and am just adding a couple records as examples for future testing, as these have been brought to me by Bib colleagues:

https://search.library.ualberta.ca/catalog/4185920
https://search.library.ualberta.ca/catalog/2868996

@redlibrarian when we get to this one, we should also be looking at the handling of the 130 and synchronize the two. all in good time..

**Comment by redlibrarian** [comment]
OK, I've added all the 240 subfields (a-z) into a "Full/Alternate Title" field, which will appear right below the main title in the record display. This field won't appear in the brief record/result view, but I think that's OK. These alternate titles are also indexed for search. This will all appear in the next release.

**Comment by seanluyk** [comment]
That's great, @redlibrarian, I'll check in on this in the next release. Self-assigning and relabeling so I remember to check.

**Comment by seanluyk** [comment]
It looks like the 240 is displaying in full in the full/alternate title field, but not in the uniform title field, which has the hyperlinking. I think it would probably be just fine if only the full/alternate title field were displayed, and the uniform title field were supressed. It would be ideal if it could be displayed and hyperlinked, but I think that can wait. 

Here are some examples: 

1. [Uniform title duplicated in full/alternate title](https://search-test.library.ualberta.ca/catalog/1743283)

2. [$m and $n not displaying](https://search-test.library.ualberta.ca/catalog/1628432)

2. [$m, $n, $r not dislpaying](https://search-test.library.ualberta.ca/catalog/263859)

3. [$k and $o not displaying](https://search-test.library.ualberta.ca/catalog/6029598)

**Comment by redlibrarian** [comment]
@seanluyk I'll move this to summer projects.

**Comment by seanluyk** [comment]
Sounds good, and just to confirm - for now if the full alternate title could display instead of the uniform title, that would be great!

**Comment by redlibrarian** [comment]
Ok, I've done that - full/alternate will show, but uniform title will not, and we can revisit the details in the summer.

**Comment by seanluyk** [comment]
After reviewing some sample records I believe this is working as expected. Closing issue.
