### ISSUE TITLE
Get a real SSL cert

### ISSUE THREAD

**Issue by nmacgreg** [ualbertalib/discovery#475]
Henry's HAproxy for HydraNorth is using the "old" birmingham wildcard certificate.  This is expedient, but best practice is not to mix certs between services, and *not* between Dev/Test/Prod environments. 
Let's get a real cert for www.library.ualberta.ca, after we go into Production.

**Comment by redlibrarian** [comment]
@nmacgreg Is this done, or is it still pending?
