### ISSUE TITLE
Add original (e.g. CJK) title info to bento and brief results.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#480]
https://search.library.ualberta.ca/catalog/5919314

**Comment by theLinkResolver** [comment]
There will be some other considerations around data in the original vernacular script, too. For instance, some of what is currently mapped to the "Original" field duplicates other fields, and also includes some bits that aren't wanted in the record view, such as the "Description based on" note.

A different approach would be to just present the vernacular title here. Once that is mapped/isolated, I presume it will be available for display in bento/brief results, as requested in this issue. The 880 field is an interesting one. Summer project for sure.
