### ISSUE TITLE
Add subscription info info to e-journal brief results?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#481]

**Comment by redlibrarian** [comment]
I don't think there's room to do this. The subscription info (see table in the individual records) take up quite a bit of space. I will mark this as to be looked at post-launch.

**Comment by theLinkResolver** [comment]
@redlibrarian hadn't noted this issue previously, but I guess maybe you could grab the coverage statement from 856 $3 and present that in the brief results? Definitely low priority/enhancement stuff, but I wanted to log that idea...

**Comment by redlibrarian** [comment]
@theLinkResolver Are we talking about SFX ejournals, Symphony ejournals, or both? This may need to wait until we've figured out deduplication...

**Comment by theLinkResolver** [comment]
@redlibrarian I guess it would be both. This is a nice idea, from whoever had it, but we also want to be careful about presenting dates of subscription coverage in one box and dates of publication in another box. Labeling is key (isn't it always?).
