### ISSUE TITLE
SFX "books"

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#483]
e.g. "angewandte chemie"

I just looked in the SFX admin interface, and it looks as though some of those are classified as books, which means they're excluded from our e-journal export (for sfx2sirsi, blacklight, and EDS). If this _shouldn't_ be the case, then we'll have to talk to Erika... the book records appear in the current e-journals interface because it queries SFX directly (I assume). So either, those aren't e-journals and should be excluded from the e-journals interface, or they are e-journals (or monograph serials) and should be included in all systems...

**Comment by redlibrarian** [comment]
@theLinkResolver Are eBooks that are included in the SFX knowledge base also catalogued?

**Comment by theLinkResolver** [comment]
@redlibrarian In theory, yes. The e-book team's workflow includes watching for new SFX targets that represent packages/products we own, comparing the target title list with the list supplied through acquisitions, and activating all the titles in that target, if it matches what we have bought.  But they would have bulk-loaded those titles in the catalogue at the time of the acquisition.

Put another way, they catalogue first (bulk loads) and activate later, so the SFX activations would not be unique, in comparison to the catalogue.

Feel free to fill me in a bit more about the issue raised here with Angewandte Chemie, and with how/if you are using the SFX book data, as I'm not sure if I addressed the issue.

**Comment by redlibrarian** [comment]
Thanks Scott - I was just worried that Ebooks in the SFX KB might be
getting lost in the shuffle, but I don't think they are. The worry with
Angewandte Chemie was just that it was a book in SFX, which made me wonder
what we were going with SFX ebooks. But if they get catalogued at any point
in the line, then they will be making their way into Blacklight.

On Wed, Oct 7, 2015 at 12:49 PM, Scott Davies <notifications@github.com>
wrote:

> @redlibrarian <https://github.com/redlibrarian> In theory, yes. The
> e-book team's workflow includes watching for new SFX targets that represent
> packages/products we own, comparing the target title list with the list
> supplied through acquisitions, and activating all the titles in that
> target, if it matches what we have bought. But they would have bulk-loaded
> those titles in the catalogue at the time of the acquisition.
>
> Put another way, they catalogue first (bulk loads) and activate later, so
> the SFX activations would not be unique, in comparison to the catalogue.
>
> Feel free to fill me in a bit more about the issue raised here with
> Angewandte Chemie, and with how/if you are using the SFX book data, as I'm
> not sure if I addressed the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/483#issuecomment-146291565>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by seanluyk** [comment]
Closing issue - not indexing SFX books currently
