### ISSUE TITLE
Map catalogued databases as "format:Database".

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#486]

**Comment by redlibrarian** [comment]
@theLinkResolver Can you let me know what field (or combination of fields) I should look for in Symphony to tell whether something is a database or not? I don't think there's an actual format or GMD... thanks.

**Comment by theLinkResolver** [comment]
@redlibrarian There are two scenarios:

1. Catalogued as an integrating resource. Will have all of these attributes:
- Bib_Lvl (Leader position 07) = i
- Ser_Type (008 position 21) = d or w

2. Catalogued as a monograph (pre-2002):
- Unfortunately, there is no surefire attributes in the MARC record.  I don't think there are actually very many in this category.

If item record data is available, then for #2 -- and actually for all scenarios -- you could look for the presence of an item record with library=UAINTERNET and the Itemcat1=DATABASE or WEBSITE.  In theory, all of our catalogued databases should have an item with those attributes.
