### ISSUE TITLE
Add MARC 264 to pub_date indexing.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#494]

**Comment by redlibrarian** [comment]
Cf #547 #746 #855

**Comment by redlibrarian** [comment]
Ugh. OK, well, it's ugly, but it seems to work. @theLinkResolver when the next release is in test on Monday (hopefully) we'll have to look at this, but I think it should be working now.

**Comment by theLinkResolver** [comment]
@redlibrarian The fix doesn't seem to be in production..?

**Comment by theLinkResolver** [comment]
Fixed in test
