### ISSUE TITLE
Recreate ipcheck link

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#499]
www.library.ualberta.ca/ipcheck

This was asked for by Ernie Howe. Necessary/useful now that we have whatsmyip.com?

**Comment by redlibrarian** [comment]
@kgood Did I ask you about this? Is this still needed?

**Comment by kgood** [comment]
Ernie thought this was still useful.  It is available here: 
https://web.library.ualberta.ca/ipcheck/

So just need to communicate this after Jan 2.
