### ISSUE TITLE
Article search is broken

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#501]
Doesn't look like the search parameter is being passed to the controller.

**Comment by redlibrarian** [comment]
Fixed.

**Comment by seanluyk** [comment]
This has come back again. A search prelimited to articles is not providing any results

**Comment by redlibrarian** [comment]
There must be something happening with the EDS API. This works for me most of the time, though I see this problem intermittently.

**Comment by redlibrarian** [comment]
I haven't seen this in a while. @seanluyk have you noticed this lately?

**Comment by seanluyk** [comment]
I've not noticed it lately either.

**Comment by seanluyk** [comment]
I haven't noticed this in quite some time, so closing
