### ISSUE TITLE
Known item search failing

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#503]
Hello
I'm having some difficulty with finding the various editions of Anger and Honsberger on Real Property (aka Law of Real Property by Anger, Honsberger and sometimes La Forest).
If I search for "anger and honsberger on real property" (no quotes) I get only the '85 edition.
If I try "honsberger real property" I get almost 1000 results, but the books I'm looking for aren't near the top of the results (or anywhere? I didn't dig down).
If I try "La Forest real property" (Anger is dead, Mr Honsberger is a wonderful old gentleman but no longer writing this book: La Forest is the actual current author), I get nothing at all.
"Anger Honsberger" gets me the single old '85 edition.
I know that the current looseleaf was published in 2006, so I tried "honsberger real property 2006" and got 20 results, including the '85 ed. (?) but I still can't see the current edition!
Is the backend still being populated and missing some stuff, or am I missing something?
Thanks a lot for putting up with our many whinges, especially this close to rollout.
Meris

**Comment by theLinkResolver** [comment]
@merisjames I am poking through the issues for anything cataloguing-related where I can add my five cents.  I was intrigued by this one, as it touches on a few things of interest - notably, the cataloguing of loose-leaf (an integrating resource), and the change in authorship over time/editions, where the original authors' names are how the work is identified.  (I worked in Law for half my career, so it's near and dear!)

As of today, I am finding that the 2006 work is at or near the top of search results in all the search scenarios you described, which is great!

**Comment by redlibrarian** [comment]
@merisjames Is this still an issue? Thanks.

**Comment by merisjames** [comment]
No, everything seems work work well now.

**Comment by redlibrarian** [comment]
OK, thanks. It could have been a problem with our indexing. I'll close this issue, but feel free to reopen or open a new one if you notice the problem again.
