### ISSUE TITLE
Make all subject fields clickable (like 610).

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#504]
Hello
Not to pile on, but I found another issue.
Sanagan's encyclopedia of words and phrases, legal maxims, Canada shows with the subject headings on Neos:
Subject term: Law--Canada--Terminology. Subject term: Law--Canada--Terms and phrases. Subject term: Legal maxims--Canada.
On Blacklight, it seems to have conflated a few of these together, resulting in
Subjects
Law
Canada Terminology
I don't think either of these entries are particularly meaningful... And "Canada Terminology" doesn't actually give any results!
Thanks again
Meris

**Comment by seanluyk** [comment]
@merisjames I agree. @redlibrarian, maybe rather than splitting the subject heading vertically, they could still remain on one line (allowing implied hierarchy to remain), but each heading and subdivision could be hyperlinked separately to allow for individual string searches. Searching for an entire string is also desirable too, not sure how this could be accommodated.

**Comment by redlibrarian** [comment]
The issue here is that the individual subject terms don't link to searches, but facets. Hierarchy is lost in the indexing of the individual terms/facets and can't be recovered with the facet links. This is one of those areas where I would like to take a step back to try to figure out what is useful for people who are searching. Do people look at the LCSH strings? Does the hierarchy matter? What behaviour/functionality are we trying to build. I realize that the answer to the first two questions is "obviously yes" to librarians, but I worry that we may not provide any useful information/functionality by providing information in a way that librarians find "obviously" valuable. Anyway, this is a larger and more complex issue than just improving the display of subjects, so we'll need to talk about it some more.

**Comment by seanluyk** [comment]
I agree. A big problem is that sometimes subject headings have a hierarchy, sometimes not, and many times what's in a heading is not really a subject, but could be a format. 

One possible solution (and apologies for always bringing them up), is how [Cornell deals with LCSH] (https://newcatalog.library.cornell.edu/catalog/781653). 

You can cumulatively add subject heading nodes to your search as each is hyperlinked, and mousing over further to the right adds more terms. 

In this case, if I had found this bibliography of folk music in the Catskills Mouintains, I could easily see if there were more sources that weren't bibliographies, or go back even further. 

Whether or not this is something a user would do, I'm not sure. It would represent an enhancement in how iLink deals with subject headings, that's for sure, and could improve subject based discovery.

**Comment by redlibrarian** [comment]
The Cornell solution is interesting, but still has a few problems. However,
it does provide a really good example of how a *full* LCSH search is
problematic: clicking 'bibliography' on either line only returns the
current item. This is the same problem we have in iLink with the LCSH
strings. In addition to searching, faceting is another option. We should
probably discuss this in person as a group to try to get to the bottom of
it.

On Fri, Oct 2, 2015 at 9:46 AM, seanluyk <notifications@github.com> wrote:

> I agree. A big problem is that sometimes subject headings have a
> hierarchy, sometimes not, and many times what's in a heading is not really
> a subject, but could be a format.
>
> One possible solution (and apologies for always bringing them up), is how Cornell
> deals with LCSH <https://newcatalog.library.cornell.edu/catalog/781653>.
>
> You can cumulatively add subject heading nodes to your search as each is
> hyperlinked, and mousing over further to the right adds more terms.
>
> In this case, if I had found this bibliography of folk music in the
> Catskills Mouintains, I could easily see if there were more sources that
> weren't bibliographies, or go back even further.
>
> Whether or not this is something a user would do, I'm not sure. It would
> represent an enhancement in how iLink deals with subject headings, that's
> for sure, and could improve subject based discovery.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/504#issuecomment-145068172>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by seanluyk** [comment]
I agree, we should talk about this in person, it's a complicated issue. I think that the Cornell option is a good solution, but you're right, it misses other possibly related items (e.g. articles about folk music of the Catskills). However, it's possible in the Cornell interface to remove and modify facets after the fact. 

Ideally we could have the best of both worlds - search for the entire string or parts of it, and facet genre terms (encyclopedias, periodicals, etc.), and possibly also search subject terms as keywords.

Where does [FAST] (http://www.oclc.org/research/themes/data-science/fast.html) come into this?

**Comment by redlibrarian** [comment]
Given that there's no behind the scenes structure for facets, I don't think something like FAST is an option right now (it could be implemented, but would require a lot of development and metadata work). I think I see two things: what can we do right now to make the subject headings usable, and what would we like to see down the road (something like Cornell's maybe) which isn't achievable in the time frame we have, but could be implemented as part of Phase 2.

**Comment by seanluyk** [comment]
I think the main issue is that we don't want to be splitting form subdivisions from topic subdivisions, because they don't make sense out of context. 

For example, the heading: Folk Music--Bibliography, is only meaningful in that the form is linked to the topic. Nobody wants to search for bibliography as a subject (or periodicals, or encyclopedias), and breaking the link between the two does more harm than it helps. Likewise, history and criticism is a meaningless term when not connected to something else, as it's applied everywhere, but within context, it's useful.

Geographic and temporal subdivisions do make sense out of context, and it makes lots of sense to facet them wherever possible.

**Comment by redlibrarian** [comment]
Natasha has written some code to address this. We're going to test this on the new indexing/search rules, and it should be in place for the next release.

**Comment by fculpepper** [comment]
I think this is related? Not all of the subject headings are displaying in the awesome clickable subdivision string. 
For example [this record] (https://search.library.ualberta.ca/catalog/833869), first subject heading has clickable bits:
![image](https://cloud.githubusercontent.com/assets/14892870/10949116/703680ee-82ee-11e5-8759-13d7b246d07b.png)

But in [NEOS] (http://www.library.ualberta.ca/permalink/opac/833869/WUAARCHIVE), we can see there are 5 more headings that should be subdivided:

![image](https://cloud.githubusercontent.com/assets/14892870/10949151/a7677ce4-82ee-11e5-8950-7057dbf2ec5d.png)

Only the 610 did it properly.

**Comment by redlibrarian** [comment]
Thanks @fculpepper. I should be able to make the rest of the subjects appear in the clickable/string format as well.

**Comment by redlibrarian** [comment]
This is more or less fixed. There's one last tweak to make (in another ticket).
