### ISSUE TITLE
Data problem?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#507]
https://www.library.ualberta.ca/results?utf8=%E2%9C%93&q=Mohawk+interruptus+%3A+political+life+across+the+borders+of+settler+states https://www.library.ualberta.ca/results?q=9780822376781
Tell us more.: searching for: Mohawk interruptus : political life across the borders of settler states nets 2 article results -- where's the book/ebook list? using the isbn 9780822376781 nets - 2 titles where the ebook shows the colon as brackets

**Comment by redlibrarian** [comment]
This search works without quotes, but does not work as a phrase search. I wonder if this is the punctuation problem @gooyers noticed (i.e. a letter not separated by a space from its punctuation can't be found). I'll have to investigate further, but given that the item can be found, I'm going to lower the priority on this one.

**Comment by theLinkResolver** [comment]
This was the issue where search strings containing title-_space_-colon-_space_-subtitle were not returning results from Symphony, or bad results. Fixed in #712 - closing.
