### ISSUE TITLE
Link to main U of A site

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#508]
Request to put this back in the top left corner, which makes me wonder if the university's web people will have a problem with us removing it?

**Comment by redlibrarian** [comment]
@kgood Thoughts?

**Comment by kgood** [comment]
I don't think there will be an issue with anybody on campus but this did come up a lot in the launch week.  Need to think on this.

**Comment by nnunn** [comment]
done - on ui-new branch
