### ISSUE TITLE
Change "BARD" label to "Library offsite shelving"

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#510]
This, then, wouldn't have to be changed after move to RCRF. But what is policy on these names?

**Comment by redlibrarian** [comment]
@sjshores Do you have any thoughts on this?

**Comment by sjshores** [comment]
I think that we should leave it at BARD, which is a very well known name, even though we will have to make a change as we move to RCRF.

Thanks,

Sandra

**Comment by redlibrarian** [comment]
OK, thanks Sandra.
