### ISSUE TITLE
Microform

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#516]
Thanks Sam - the format mappings look good.  I concur that this element will not allow us to distinguish the format of the physical item.  I checked the MARC rules and in fact, they state "microforms, whether original or reproductions, are not identified by a distinctive type of record code".
  
So the question becomes, where are we going to show that to the user.  The 337 and 338 can help us here in instances where the record describes the micro format (example), but in the hundreds of instances where micro items appear on a print record (example), only the item metadata will tell us for sure.
 
Something that is being considered right now is to change all instances of BARD items with location of MICROFILM to ON_SHELF (at BARD's request, because they don't have a separate shelving location for microfilm).  But over here, we are a bit concerned that it will conceal the actual format of the item from users.
 
Currently, the item type tells us the format/media type (microform) and the location tells us specifically what kind (carrier) of micromaterial it is.  But if it becomes On Shelf, we lose that.  (That's not a Blacklight problem, per se, but I'm trying to help find a solution that works in the Blacklight environment.)
 
With that said, I noted that the Item Type is not displayed in Blacklight -- which would be Microform, whether film, fiche, or opaque, for these items.  Is that a "final" decision or still up for some debate? 
 
On a totally different note, here is something I spotted when I was poking around in Blacklight.  Some missing text when I pointed to certain menu items:

**Comment by theLinkResolver** [comment]
@redlibrarian This was my issue. Now that Item types are displayed in the items table, this issue can be closed. In terms of displaying microform as the format of the material that a record describes, we have the GMDs showing currently and if/when we do the enhancement work around material type granularity, we can replace the GMD with something cleaner from the fixed fields. Closing.
