### ISSUE TITLE
LCSH display

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#522]
I've noticed something in regards to the way Blacklight treats subject headings that could cause some issues. It was first noticed in french records, but it appears to be the same with english results as well.

Should subject headings in Blacklight be parsed/broken up? So that, for example, if an item is catalogued with the subject heading Canada -- History, both Canada and History should appear as subjects in the Blacklight record?

To provide a specific example, I found a book titled Feminist history in Canada: new essays on women, gender, work, and nation. The EDS record includes Women -- Canada -- History, Feminism -- Canada -- History, and several others. The Blacklight record includes only Women and Feminism (the first parts of the complete subject headings). Canada, History, and others are absent.

I just wanted to pass that along in case it wasn't a known issue. A large number of more specific subject headings would very often be found after two dashes (--), so to lose out on them would be to lose a lot of specificity/searchability. If parsing isn't possible, has including the full subject headings been considered?

Another thing, more on the usability side of things, Blacklight doesn't appear to be searching full titles properly. If I searched for Feminist history in Canada : new essays on women, gender, work, and nation I got zero results, but by searching for only Feminist History in Canada I was able to locate the book. This could be related to the previously identified issue with commas in searches, but removing all punctuation still didn't pull up the right book. 

Just wanted to pass that along. 

Cheers,
Brian

**Comment by linds37** [comment]
Including the entire subject heading would be ideal. Breaking it up removes specificity and is not helpful.

Searching for the entire book title works now.

**Comment by seanluyk** [comment]
@linds37 @redlibrarian - This is possibly an enhancement, but just putting it out there: I wonder if there is a way for entire subject headings to both be searched as 1 string, and as individual strings simultaneously, e.g. feminism--Canada--history AND feminism, history, Canada? I've always found it to be a drawback that when an entire string is searched andno more results are found because it's too specific

**Comment by redlibrarian** [comment]
Addressed in #504 I'm going to close this ticket.
