### ISSUE TITLE
Westlaw

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#527]
As we discussed today, I'd like to look into why we aren't able to add
catalog links to specific resources within Westlaw (and Quicklaw).

For example, a number of texts are available on Westlaw, and it would
make it much easier for users to find these texts if the catalog
linked directly to them.

Westlaw itself does permit this, so the issue must arise somewhere in
our systems.

**Comment by merisjames** [comment]
Historically, the way Westlaw was set up didn't play well with our proxy server, so deep linking didn't work. The "new" Westlaw works much better, and deep links seem to work swimmingly. QL also seems to work quite well. I was told that now, it's less "can't" and more "won't".

**Comment by theLinkResolver** [comment]
@redlibrarian has figured out how to make SFX links to Quicklaw and Westlaw journals work! Closing issue. @merisjames the serials team will be in touch re. cataloguing.
