### ISSUE TITLE
Author facet in list view

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#530]
When searching for a known item with lots written about it, it can be difficult to find the actual title. For example, searching for Catcher in the rye salinger, I had a tough time finding the actual book, as opposed to books about the book.

An author facet would help to alleviate this issue.

**Comment by redlibrarian** [comment]
Duplicated in #693

**Comment by redlibrarian** [comment]
Author facet is in place now. @seanluyk Can you verify?

**Comment by seanluyk** [comment]
Looks great, and I can verify that this is working. This will improve discovery quite a bit.
