### ISSUE TITLE
Find more by this author hyperlink and no more results 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#531]
1. Searched for known item in collection (Binding and Care of Printed Music)
2. Clicked on first result in books
3. Clicked on find more by this author, [Carli, Alice, 1961-] (https://search.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=Carli,+Alice,+1961-&subject=&utf8=%E2%9C%93&search_field=dummy_range&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&commit=Limit&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced)
4. Resulting page is "We are sorry, something has gone wrong"

I think this is beacuse this is the only item by this author. Need a new page that says the same thing as Ilink , "no more items by this author" or something like that

**Comment by seanluyk** [comment]
Hmmm...there appears to be something unexpected happening. Clicking on this author does not just bring back her works (1 book), it brings back two, and is finding the second one because this is an all field search.

Is there no way to force a fielded search in Blacklight?

**Comment by redlibrarian** [comment]
Yes, that's been added and will be in next week's release.

**Comment by seanluyk** [comment]
This appears to be working now. Closing.
