### ISSUE TITLE
Clipped fields in record views

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#532]
I've noticed that some of the longer field labels are clipped in a record view. For example on [this record] (https://search.library.ualberta.ca/catalog/2929530), **additional author** and **publisher/issue #** are clipped.

**Comment by seanluyk** [comment]
This is closed, but I don't see that it's been fixed. Should this have a check in next release label?

**Comment by astrilet** [comment]
I think this is problem with definition:
.dl-horizontal dt {
  width: 160px;
  margin-right: 5px;
}
working on it now

**Comment by redlibrarian** [comment]
This is fixed in development, and will be in the next release.

**Comment by theLinkResolver** [comment]
Looks good
