### ISSUE TITLE
Record Display - holdings info not showing library location

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#535]
This book https://search.library.ualberta.ca/catalog/6062615 does not say what library it is in. (It's at Red Deer College http://www.library.ualberta.ca/permalink/opac/6062615/WUAARCHIVE)

**Comment by redlibrarian** [comment]
I've implemented a fix for this, it will be available in the next release.

**Comment by linds37** [comment]
great. How do I tag items in GitHub?
Do you want us to be creating new tags?

Lindsay Johnston, Public Services Manager & Subject Librarian
Rutherford Humanities & Social Sciences Library
<http://guides.library.ualberta.ca/rutherford> and Weir Law Library
<http://guides.library.ualberta.ca/law>
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta
T6G 2J8
780.492.0598

lindsay.johnston@ualberta.ca

**Comment by redlibrarian** [comment]
Hi @linds37 , you can create tags from the issues list, and clicking on Labels. Feel free to create some if you think they would be useful - if it gets confusing we can always prune later. 

To add a label, just click on the word Labels in the issue (to the right of the issue text. That will give you a drop down of available labels.

**Comment by hannepearce** [comment]
Not sure if this is the same issue? See record [here](https://search.library.ualberta.ca/catalog/4855917) Had to go into iLink to see if it was at Coutts or somewhere else. iLink record [here](http://www.library.ualberta.ca/permalink/opac/4855917/WUAARCHIVE)

**Comment by redlibrarian** [comment]
Hi @linds37 and @hannepearce - these both look like they're working now. Can you confirm and let me know? Thanks.

**Comment by hannepearce** [comment]
Yes it appears to be working now. Thanks!

**Comment by linds37** [comment]
Yes, it works on my screen too. Thanks!
