### ISSUE TITLE
Wrong language listed in record

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#537]
The record for [Canadian mathematical bulletin] (http://search.library.ualberta.ca/catalog/954926939713) says it's in Spanish, it's in English. 
Here's the [iLink record] (http://www.library.ualberta.ca/permalink/opac/6867624/WUAARCHIVE).

**Comment by redlibrarian** [comment]
Strange. The MARC record is correct, and we aren't seeing this with other languages. I'll have to investigate...

**Comment by redlibrarian** [comment]
Oh, I just realized this is a record from SFX, not from Symphony/iLink. The problem must be there.

**Comment by redlibrarian** [comment]
I've asked Scott to take a look.

**Comment by theLinkResolver** [comment]
Ex Libris has made the correction in the SFX Knowledge Base and it will appear correctly when next week's KB update is released and applied (Wednesday).

**Comment by theLinkResolver** [comment]
@redlibrarian This has been fixed in the SFX KB but it's still showing as Spanish in Blacklight.

**Comment by redlibrarian** [comment]
Thanks - the data will need to be reindexed. It should be fixed in the next code release, if not sooner.

**Comment by redlibrarian** [comment]
Hm. Still not fixed...

@nmacgreg Are the nightly update/indexes being done?

**Comment by theLinkResolver** [comment]
Language is right, now. @redlibrarian everything ok with updates/indexing?

**Comment by redlibrarian** [comment]
I still have no confirmation about nightly indexing, but I'm going to close this ticket. There's an open issue about indexing ( #685 )
