### ISSUE TITLE
Reorder holdings

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#539]
Also, the holdings are crazy out of order, can they be ordered chronologically?

I'm not sure if this is possible. The order they're displayed is the order they come out of the Symphony Web Services. Also the "dates" are in fact strings, which would need some work/manipulation before they can be made sortable. I'll investigate.

**Comment by theLinkResolver** [comment]
The concerns in this issue have been addressed. [See this record for example](https://www.library.ualberta.ca/catalog/1705621). Each library's holdings are now together, and the items appear to be in order. There are still some oddities, like how (in this example) the HSS holdings are in descending order and then the other libraries are in ascending order, but I think that is a problem with Symphony web services, as I've seen similar issues in the classic catalogue for years. I am closing this.
