### ISSUE TITLE
Default OR or AND?

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#540]
804189 results for united nations report disarmament
648188 results for united nations disarmament

I would have expected the top search to yield fewer results than the bottom search.

**Comment by redlibrarian** [comment]
OR and AND aren't really concepts that map well to the way the indexing is done. A better question than comparing result sets is "are you finding what you're looking for?"

**Comment by redlibrarian** [comment]
We'll be discussing this question on Friday, but a tweak to the index should also be in place before then. I'm going to close this ticket.
