### ISSUE TITLE
Library locations still not displaying properly (holdings)

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#542]
Not sure where the last copy in [this record](https://search.library.ualberta.ca/catalog/6034499) is housed or when it is coming back. I'm assuming 'checked out" should read the date it is due.

**Comment by hannepearce** [comment]
Another instance of the library not appearing in the record. In [this record](https://search.library.ualberta.ca/catalog/4416644) it looks like the 2nd copy is at Coutts, the labelling tells me it's probably at Kings...

**Comment by redlibrarian** [comment]
We're still having problems with all the library labels appearing for some reason - I keep fixing it, but it keeps coming back.

As for the due date - I'm not sure I'll be able to display that. I'll have to look into it. I'm going to split this issue up into two.

**Comment by redlibrarian** [comment]
OK, so the holdings labeling issue should be fixed in the next release (see #581 ). As for the due-date, I've added it to the Symphony Web Services module, so this should also be visible in the next release.

**Comment by hannepearce** [comment]
This issue appears resolved.

**Comment by scastell** [comment]
I'm reopening this issue as I've found a few records that aren't displaying a location - ie 
https://search.library.ualberta.ca/catalog/7049023, and 
https://search.library.ualberta.ca/catalog/816296.

Missing location in both cases is Alberta Innovates - Technology Futures - C-FER Technologies

see 
, and
http://www.library.ualberta.ca/permalink/opac/7049023/WUAARCHIVE, and

**Comment by redlibrarian** [comment]
OK, I fixed the C-FER location. I hope this is the last problematic location...

**Comment by theLinkResolver** [comment]
@redlibrarian I happened to notice that this location is once again not displaying correctly in the filters list. It's showing up in the items okay.

**Comment by redlibrarian** [comment]
It's because of the stupid **-** in the name. I've put a fix in place, hopefully this will finally fix it in the next release.

**Comment by redlibrarian** [comment]
@theLinkResolver @scastell @hannepearce This should be fixed now.

**Comment by hannepearce** [comment]
Fixed! closing
