### ISSUE TITLE
No results for common topic facet

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#543]
Was looking at [this record] (https://search.library.ualberta.ca/catalog/4821424), and clicked on the [history and criticism facet] (https://search.library.ualberta.ca/catalog?f%5Bsubject_topic_facet%5D%5B%5D=History%20and%20criticism&q=&view=brief) and no results were returned. 

I expected to find many more results for this commony applied heading.

**Comment by merisjames** [comment]
I have found that the first subject heading, which is usually something really general, yields many results. The second subject heading almost always has zero results. I haven't seen many-any results with more than two subject headings, which is an additional issue.

**Comment by seanluyk** [comment]
I agree @merisjames , I think something is wonky with the splitting of the subject heading, where the first, more general one yields many results, and subsequent subdivisions don't yield any.

**Comment by redlibrarian** [comment]
This issue is linked to the discussion we need to have about LCSH strings. (Issue #522 ).

**Comment by redlibrarian** [comment]
OK, so the WAT recommendation is to use the LCSH strings, and @nnunn thinks she can reproduce the functionality we talked about (separate, but combinable, LCSH headings). I need to add the full LCSH string back into the record...

**Comment by redlibrarian** [comment]
Addressed in #504 .Closing this ticket.
