### ISSUE TITLE
"Unknown" format facet

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#544]
Under the **format facet**, I've wondered what "unknown" is referring to. For an example, see [this record] (https://search.library.ualberta.ca/catalog/829898). I see a mix of materials, including:
*curriculum media
*media
*magnetic media
*streaming video
*slides, transparencies, etc.
 If it isn't possible/desirable to label each of these things by format, maybe consider changing the "unknown" label to "other"?

**Comment by theLinkResolver** [comment]
@redlibrarian Here's something I can definitely help with - mapping some of the unmapped formats, such as "Kit" (Sean's example record).

**Comment by redlibrarian** [comment]
@theLinkResolver OK, thanks. I'll show you where the mapping is. If there's something we can do there, that would be great.

**Comment by redlibrarian** [comment]
@theLinkResolver Here is the current mapping. If you can add to this table, and share that with me, that would be awesome. Thanks.

# MAPPINGS

# format mapping
#    leader 06-07
map.format.aa = Book
map.format.ab = Journal
map.format.am = Book
map.format.as = Journal
map.format.ai = Continually Updated Resource
map.format.ta = Book
map.format.tm = Book
#    leader 06
map.format.c = Musical Score
map.format.d = Musical Score
map.format.e = Map or Globe
map.format.f = Map or Globe
map.format.i = Sound Recording
map.format.j = Musical Recording
map.format.k = Image
map.format.m = Computer File
#    007[0]  when it doesn't clash with above
map.format.h = Microform
map.format.q = Musical Score
map.format.v = Video
#    none of the above
map.format = Unknown

**Comment by seanluyk** [comment]
If the weird formats can't be mapped accurately, I wonder if unknown could
just be instead labelled other?

**Comment by redlibrarian** [comment]
Hi @seanluyk - yes. I'll make that change now, and then @theLinkResolver can look into the mapping when he's back from vacation.

**Comment by seanluyk** [comment]
@redlibrarian it doesn't look like this is functioning properly yet - we still have many unknowns, and video is particularly problematic.

**Comment by redlibrarian** [comment]
@theLinkResolver Any thoughts?

**Comment by redlibrarian** [comment]
OK, @theLinkResolver has given me some additional mappings which should help to address this. Long term we have a plan to increase the granularity of format mapping, but this will have to wait until next year.

**Comment by theLinkResolver** [comment]
Improved "Format" mapping has been implemented. Caveat: "book" covers a lot of things. Presumably this is preferable to "textual item" or something. If anything is identified where the format facet *really* doesn't make sense, it can be reported as a cataloguing question (via the helpdesk).

As @redlibrarian mentioned, we are hoping to increase the granularity in a future phase, but I think we're already ahead of iLink at this stage.
