### ISSUE TITLE
Phrase search (in "") returns no article results

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#548]
It appears that EDS results won't come up if a phrase is searched in double quotes.

**Comment by redlibrarian** [comment]
Searching the articles controller with double-quotes works (https://search.library.ualberta.ca/articles?q=%22shakespeare%22, https://search.library.ualberta.ca/articles?q=%22charles+dickens%22), but the results don't render in the bento box. Probably a problem with the bento controller.

**Comment by redlibrarian** [comment]
OK. Phrase search has been fixed. There's still a problem with single-quote searching, but it's not high-priority.

**Comment by seanluyk** [comment]
EDS results in "" are being returned in simple search, but not advanced search. Closing this issue, but opening a new one.
