### ISSUE TITLE
"Library has" statement above items table (MARC holdings statement)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#549]
Looking at this record. http://search.library.ualberta.ca/catalog/2633318
 
There is a statement above the items table, "Library has: 2010". I see that it is coming from the MARC holdings.  In this instance, it is from the AHS_CROSS holdings, so not what we want to see.  (Bigger question, perhaps: What is the plan for MARC holdings in Blacklight?)

**Comment by redlibrarian** [comment]
The summary holdings statement here should be taking all subscriptions into account - I guess the logic is wrong and needs to be revisited.

Personally, I dislike the summary of holdings statement. I don't think people read them and they give a summary of what the items table already says. At some point down the road we should discuss it and see whether it's still necessary. In the meantime I'll fix up the problematic logic.

**Comment by redlibrarian** [comment]
Further to our discussion about summary holdings statements, @theLinkResolver , I'm going to move this issue into the next milestone, as it needs to be thought through from the beginning.

**Comment by theLinkResolver** [comment]
The confusing "Library has" statement has long been removed from display, and the issue of summary holdings is covered nicely in #691. Closing this issue.
