### ISSUE TITLE
Advanced search error for "raisin"

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#550]
This started with trying to find the book "A raisin in the sun". Using the advanced search, I got the [something has gone wrong] (http://search.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=raisin+in+the+sun&title=&author=&subject=&utf8=%E2%9C%93&search_field=dummy_range&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&commit=Limit&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced) error message  when I searched raisin in the sun in both the advanced search and the title boxes. I got the same error when I searched just raisin. I don't get this error when I search other words in these fields.
Oh, and yes, there are a bunch of books with raisin in the title. Searching raisin or raisin in the sun from the basic/everything search brings a bunch of stuff.

**Comment by fculpepper** [comment]
Also, I get results when searching "old man" in either all fields or title but get the error message when I try "old man and the sea" and "old man sea" (without quotes).

**Comment by merisjames** [comment]
I *think* what's going on here is that the search is structured to be your query AND format selection
However, it defaults to not checking either print or online... Which then yields zero results
![and](https://cloud.githubusercontent.com/assets/14880530/10233291/dc230c8c-684a-11e5-90da-0f6c42f0cfea.jpg)

**Comment by fculpepper** [comment]
But then why does is it work with just "old man", no format selected?

**Comment by merisjames** [comment]
Good question :) When I checked off "print" I got 83,823 results.
I wonder if this is something to do with stop words... Although it's not consistent, as "old man sea" didn't work.

**Comment by fculpepper** [comment]
Ooooo, yeah, okay! Selecting one or both formats lets me search for "raisin
in the sun" in the title field so that's swell.

But I suppose I don't really understand why we'd have to select a format
first instead of using the limiter after searching. And too, it's not
consistent cause some searches return results without selecting a format.

**Comment by merisjames** [comment]
Yes, plus lots of people are going to miss that they *have* to select a
format (not intuitive) like we just did, and end up thinking there are no
results/getting fed up because they know there are results.

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca

**Comment by redlibrarian** [comment]
I'm not sure what's going on. You shouldn't have to select any of the fields below the search boxes. I'll look into it.

**Comment by seanluyk** [comment]
I think it's the stop word indexing problem again. For example, a search for *In Search of Lost Time* yields no results in the advanced search, but get lots in the simple search.

**Comment by redlibrarian** [comment]
Except that you do get results if you select "print", for example, which shouldn't be the case...

**Comment by redlibrarian** [comment]
Also just searching for "search lost time" (no quotes) gives the same error when a facet isn't selected...

**Comment by redlibrarian** [comment]
It looks like this wasn't actually related to any kind of search/facet problem, but was a problem with some logic on the results page that indicates whether something is an ebook. I fixed that logic, and all the searches specified in this ticket seem to work now. Please check when the next code release goes live.
