### ISSUE TITLE
Add contents_tesim to searchable fields in solrconfig.xml

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#551]
Doris noticed an interesting problem, which I think has been reported in another issue, but I'm not sure. 

Let's say a user wants to find information about Atwood's story, *Oryx and Crake*. 

A search in blacklight for "Oryx and Crake" only returns the novel in books and more and few results in ebooks and more. Same issue with single quotes, or no quotes, with different numbers of results.

However, a [recent and promising edited volume] (http://www.library.ualberta.ca/permalink/opac/6679183/WUAARCHIVE) contains a chapter on this story, but Blacklight is not picking it up.

**Comment by redlibrarian** [comment]
So, the marc record is part of the index now. This should be working...

**Comment by redlibrarian** [comment]
OK, I've added contents_tesim to the index. This will be visible with the next code release.

**Comment by seanluyk** [comment]
This does not appear to be working, but could be related to some of the other issues I submitted today, that suggest something broke in the latest release.

**Comment by redlibrarian** [comment]
Weird. Contents_tesim has been added, and it being retrieved, but this search still isn't working properly.

**Comment by redlibrarian** [comment]
OK, "Slanting I, imagining we" is now coming up (13th result) in a search for Oryx and Crake.
