### ISSUE TITLE
Labeling issue - "Clear all facets"

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#554]
In an Articles results view, there is a "clear all facets" link in the right hand corner. This is a good feature, but I think it could be labeled better. Most users probably don't know what a facet is. 

Also, this option is not available in all types of results views. It would be ideal if the same options were available in all views.

**Comment by redlibrarian** [comment]
The discrepancy is due to what's available through the EDS API vs. what's available to the Blacklight-indexed collections. I'll have to investigate this.

**Comment by seanluyk** [comment]
This shows as "Clear All Limits" now, which I think is much better labelling. Closing issue.
