### ISSUE TITLE
Repeated subject headings making subdivisions

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#557]
Geographic and other LCSH subdivisions seem to be masked in Blacklight when there are two nearly identical subject headings with different subdivisions.

-In the iLink record, there are the following subject headings:
*Dissertations, Academic--Great Britain--Indexes.
*Dissertations, Academic--Ireland--Indexes.

-Compare with [the Blacklight record](https://search-library-ualberta-ca.login.ezproxy.library.ualberta.ca/catalog/78263).
*Ireland--Indexes does not appear

I think it's great that the headings are faceted, but for a user wanting to refine their search to books about Irish dissertations, they would not be able to from this record

**Comment by redlibrarian** [comment]
This will be fixed with the new LCSH handling that @nnunn will work on.

**Comment by redlibrarian** [comment]
Addressed in #504 .Closing.
