### ISSUE TITLE
number of article hits - main search results page versus articles result page

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#558]
keyword search for kakapo

a)There is a discrepancy between the number of articles hits displayed on the main results page versus the articles results page

b) using the next and previous options to move through the articles doesn't work. The article numbers change but the articles do not.

a)
Search results -100 hits, 99 of which are articles. The view all articles page indicates that there are 235 hits, but there are really only 99.

![image](https://cloud.githubusercontent.com/assets/14927291/10251636/56aa8d28-68ef-11e5-9d79-51565e0de7d5.png)

![image](https://cloud.githubusercontent.com/assets/14927291/10251645/6fb85b74-68ef-11e5-843f-72191cc73733.png)

![image](https://cloud.githubusercontent.com/assets/14927291/10251818/c1d6f52c-68f0-11e5-8249-c688b78baa56.png)

b)  using the next and previous options to move through the articles doesn't work. The only thing that changes is the top number range. 

![image](https://cloud.githubusercontent.com/assets/14927291/10251839/e6457cda-68f0-11e5-8aa0-ff95f982afd2.png)

![image](https://cloud.githubusercontent.com/assets/14927291/10251876/23cc833c-68f1-11e5-8991-6ec4b1b74f1b.png)

**Comment by redlibrarian** [comment]
I have a sneaking suspicion that Ebsco has changed the EDS API on us, which is leading to this behaviour.

**Comment by redlibrarian** [comment]
This is a pretty big deal, and the EDS code is a mess when it comes to this. I can see how all the page/pagination information is being constructed, but I can't see how the code determines which records to assign to a page. This is not restricted to any given search and I'm a little worried that it's always been the case and we just never noticed it.... I'm going to get in touch with the EDS engineer who wrote the code to see what I can find out.

**Comment by redlibrarian** [comment]
Current bento box results are: 6 results in "Books, media, and more" and "1103" results in Articles/EDS. When I click through into the articles results, I only get 235 results.

**Comment by redlibrarian** [comment]
Just made a fix to the links from the bento page, and I now get the full 1103 results in articles.

**Comment by redlibrarian** [comment]
The problem of not moving through the results when you click next is still occurring. This only happens in the articles controller. I'm going to make a new issue for that bug. The original problem here (discrepancy in number of results) should be fixed in the next release.
