### ISSUE TITLE
Library facet errors: 15, ahsctr, burman, lakelndin

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#560]
Apologies if this has already been noted as an issue (I looked at recently opened issues and did not see it), but in the Library facet within a results page I keep seeing 3 additional libraries. For example, in [this results page](http://search.library.ualberta.ca/symphony?f%5Belectronic_tesim%5D%5B%5D=Print&q=education) there are three libraries with very long names. 

The name of the location changes slightly based on the bento box you are in (for example, they begin **/symphony?f%5Belectronic_tesim%5D%5B%5D=Print&f%5Blocation_tesim%5D%5B%5D=** in the Books box). But what is consistent, is that following **location_tesim%5D%5B%5D=**, the locations are listed as 15, ahsctr, and burman (Burman University I'd imagine).

An additional but related issue: when trying to click into these libraries from an [advanced results page](http://search.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=education&title=&author=&subject=&utf8=%E2%9C%93&search_field=dummy_range&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&commit=Limit&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced) the facet no longer works for these three locations and instead leads to a dead end (We are sorry, something has gone wrong).

**Comment by gooyers** [comment]
![2015-10-02_15-40-17](https://cloud.githubusercontent.com/assets/14891931/10258511/040fbb60-691c-11e5-80b9-2d63da63be7a.jpg)

**Comment by gooyers** [comment]
It appears there are 4 libraries without properly assigned names: Burman, 15, ahsctr (I would guess an AHS location), and lakelndin (perhaps the Lakeland Internet Library?).

They are visible in (this advanced search result)[https://search.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=&f_inclusive%5Blocation_tesim%5D%5B%5D=king&f_inclusive%5Blocation_tesim%5D%5B%5D=burman&f_inclusive%5Blocation_tesim%5D%5B%5D=15&f_inclusive%5Blocation_tesim%5D%5B%5D=ahsctr&f_inclusive%5Blocation_tesim%5D%5B%5D=lakelndin&utf8=%E2%9C%93&search_field=dummy_range&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search]. I included King's as trying to limit to the 4 nameless locations returned an error page. 

![2015-10-02_15-46-30](https://cloud.githubusercontent.com/assets/14891931/10258615/d8f488e2-691c-11e5-81fc-463b9c7b0e4c.jpg)

**Comment by redlibrarian** [comment]
Thanks @gooyers - I've seen this before. Burman should be fixed now, but I'll need to track down the others.

**Comment by redlibrarian** [comment]
These should be fixed in the next release.

**Comment by gooyers** [comment]
@redlibrarian The issue doesn't seem to be completely fixed. Burman now appears to be fixed, but the names for 15, ahsctr and lakelndin still list a long string of text instead of the name of the library. 

That being said, selecting these 3 locations from the advanced search (they are the three entries with only numbers) no longer leads to an error message. 

![2015-11-12_14-24-16](https://cloud.githubusercontent.com/assets/14891931/11131697/2cef3bee-8949-11e5-837b-627ff540062e.jpg)
![2015-11-12_14-24-51](https://cloud.githubusercontent.com/assets/14891931/11131702/3052843a-8949-11e5-8f89-ceb4bfad09a6.jpg)

**Comment by redlibrarian** [comment]
This still isn't working.

**Comment by redlibrarian** [comment]
OK - I've made a change to the location indexing. We'll have to see how this looks with a full dataset.

**Comment by gooyers** [comment]
This appears to be fixed. I can't locate any weirdly formatted library locations. I even checked in the advanced search, and there are no longer any blank locations there.
