### ISSUE TITLE
More link in facets - same window or popup, and is not 'more'

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#563]
This is a usability/design issue - the *more link* in a facet opens in the same window, and does not display more, but instead, the same results with the option to click next, or sort A-Z or numerical.

My experience with these lists is that they normally open up in a popup window, and show the next page of results, not the same list as before. 

Other useful options to consider include a scrolling window, or an A-Z horizontal index at the top (would look like a 90s website, but would save someone looking for something in the latter part of the alphabet clicking next continuously)

**Comment by redlibrarian** [comment]
Since this is a usability question and nothing is actually broken, I'd like to leave this to usability testing to see if this is actually a problem. Again, our rule of thumb has been to not change default Blacklight behaviour unless there is a demonstrated problem...
