### ISSUE TITLE
Back to home page instead of back to the page you were on

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#564]
When you navigate away from the main library page and then use the back button to return to the section you were at, you get returned to the main library.
For example if you go to [Research Support] (https://search.library.ualberta.ca/#research-pane) and then click on [Open Access] (https://search.library.ualberta.ca/research-support/open-access) and then   use the browser back button to go back to Research Support, you're returned to the [home page] (https://search.library.ualberta.ca/) instead. 
It's irritating and increases the number of clicks to move around the site.

**Comment by redlibrarian** [comment]
From what I understand, this is browser behaviour, not HTML/page behaviour. For example, the behaviour you describe occurs in Safari, but not in Chrome. I don't think there's anything we can do about that.

**Comment by redlibrarian** [comment]
@nnunn Can you confirm this, maybe with a link to a document that explains it?

**Comment by nnunn** [comment]
Yes, this is a browser specific action. However, it does appear that there could be a way to manipulate it using the HTML5 history API. I'm going to spend a little time looking into it.
