### ISSUE TITLE
EDS book chapter results (and others) not appearing in Blacklight

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#565]
I've noticed that if you search for a book chapter (or other items contained in larger items such as conference proceedings), no results appear. 

For example, a search for: *A short history of Beka* yields no results, yet this is [indexed in RILM] (http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=ram&AN=2010-21251&site=ehost-live&scope=site), which is indexed in EDS.

Not sure if this is an EDS problem, but it's a major discovery issue. I've also noticed that lots of EDS content that doesn't fall under this category is not appearing.

**Comment by redlibrarian** [comment]
We need to have a discussion about this. Currently, the EDS pane returns journal articles only. If we want to change this, then we'll need to figure out how to accurately describe the result pane, and the results themselves. This is something either the team or WAT will have to discuss.

**Comment by seanluyk** [comment]
This is a tricky one. I like that the Articles tab is accurate in that it only returns articles, but worry that lots of great content gets missed. However, with the databases showing up in search results, perhaps users find more of these materials in subject databases?

**Comment by redlibrarian** [comment]
We decided in the testing team and at WAT to include all content types in the EDS pane. I'm going to close this ticket, as it's duplicated in a bunch of other issues.
