### ISSUE TITLE
Policies - Archives Policies

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#572]
[Archives Policies link](http://archives.library.ualberta.ca/about/policies/) from [Our Policies page](https://search.library.ualberta.ca/about-us/policies/) points to old website.

**Comment by kgood** [comment]
The Archives site is being worked on right now and will see a complete refresh before the new year. It should be fixed before launch

**Comment by kgood** [comment]
Closing ticket - re: Archives Policy link.  As mentioned, we should have a new site by launch but even if not the current Archives web site is out of scope for this project and will likely remain with the old look and feel after Jan. 2.
