### ISSUE TITLE
Link to FOIP office on Web Site Privacy Policy Page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#574]
The link on the [Web Site Privacy Policy page](https://search.library.ualberta.ca/about-us/policies/privacy-policy/) to the [University of Alberta Information and Privacy Office](http://www.ualberta.ca/FOIPP/) points to an ugly re-direct. Might be worth updating it to their [new link](http://www.ipo.ualberta.ca/).

**Comment by kgood** [comment]
The link has been fixed.
