### ISSUE TITLE
Contextual information in "email me this item" and "text me this item" messages

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#575]
Just tested the email me this and text me this item features. The following message is returned for emails:

Title: War requiem
Author: Britten, Benjamin, 1913-1976
Format: Musical Score
Language: Latin
URL: http://search.library.ualberta.ca/catalog/294716
Message: This is the war reqiuem

I'm wondering if some more contextual information could be added to the message that users receive. Something indicating where it is being sent from, for example: "From the University of Alberta Library" or something as simple as that.

The text message just sends the link, which I assume is on purpose, but also just has empty brackets before the word Link:
() Link: http://search....

Perhaps the message could be something like: From the University of Alberta Library: http://search...

**Comment by redlibrarian** [comment]
OK, I've added some contextual information to both the subject and the body of the email, and improved the formatting a little. I've also added a "From University of Alberta Libraries" line to the text message. Please check in the next release and see if that's sufficient for now - we'll probably want to revisit this next term.

**Comment by seanluyk** [comment]
Looks better, closing this issue
