### ISSUE TITLE
Publication year facet - articles view

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#577]
The publication year facet is only allowing two options: Last 5 years and Last 10 years. Is this the intended configuration?

**Comment by redlibrarian** [comment]
This is the way EDS has their publication date facet configured (it's the default Blacklight format). I'm planning to change this to make it the same as our non-EDS pub date facet.

**Comment by seanluyk** [comment]
Looks like the Blacklight EDS view has gone back to only giving an option for the last 5 or last ten years. For some reason I thought it had been changed to the slider

**Comment by redlibrarian** [comment]
@seanluyk No, I haven't fixed this yet. It's always been the 5/10 year range thing. I hope to get to this next week.

**Comment by redlibrarian** [comment]
I'm going to link this issue with #929 , which I think will solve a lot of these EDS gem issues.
