### ISSUE TITLE
Wonky call numbers in books and more view

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#578]
Apoligies if this was already reported, but some odd call numbers are showing up in the call numbers facet:
![screenshot 2015-10-05 at 14 00 01](https://cloud.githubusercontent.com/assets/14880206/10291930/9d26d91a-6b69-11e5-8008-8b29ea1bedde.png)

**Comment by theLinkResolver** [comment]
I explored some of these and found that these unfortunate oddities are the result of many legitimate but also sometimes questionable things appearing in the LC call number field.  For instance, "f" looks like it is/was used by LC as a call number prefix for folio-sized sheet music.  In other words, the field data is correct (whether current or historical usage only), but it creates a challenge for machine-readability.

@redlibrarian I see that the "legitimate" call numbers are recognized and displayed as topics (e.g. "M - Music").  That gives some hope that the other stuff could be suppressed, perhaps?

Other thought is to prefer the 090 call number, if $b = AEU.  But then there are still going to be some call numbers to filter out (e.g. Internet Access, Shelved by title, Catalogued separately come to mind).

**Comment by redlibrarian** [comment]
I think that - absent a data cleanup project by Bib Services - the call numbers are about as good as they're going to get right now. @theLinkResolver , @seanluyk I'm going to close this issue, but @theLinkResolver and I know that we need to think about call numbers in the new year.
