### ISSUE TITLE
Screen does not change after placing hold

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#579]
I just placed a hold in Blacklight. After I placed the hold, the screen simply reverted to the "place hold" screen, so it was not clear whether it had worked or not. When I tried placing it again, it said "Error: that item is already on hold for the user. I checked Workflows, and the hold did work. Once a hold is placed, there should be some kind of confirmation message, and information that the user will receive and email message when the hold is ready. Classic catalogue says, "Hold Placed. You will be notified by email when your item is ready for pickup at University of Alberta Rutherford-Humanities & Social Science" and gives the name of the user and the title of book.

**Comment by jhennig** [comment]
Just tested this and there is a message but it's small. 
Maybe it was missed? Or perhaps another problem
I can highlight the message.

**Comment by fculpepper** [comment]
It needs to be bigger, at least more prominent than the Place Hold stuff.
Also, can we add a return to search button? Or make it so that after
placing a hold you can use the back button to return? It seems to get stuck
in My Account after placing a hold and you have to click Search & Home to
return but that wipes out your search. So if you want to request a bunch of
stuff from your results, you'll have to re-do your search after hold.

**Comment by linds37** [comment]
I see the small writing at the top now. As you suggest, Jeremy, I think it should be bigger, and also it should include the information "You will be notified by email when your item is ready for pickup at XX library".
It's confusing that the option to place a hold still appears on the screen and is more prominent than the confirmation. Can the Pick Up Library drop-down box and the "place hold" button disappear on the confirmation screen? 
I agree with Fairfax -- there should be an obvious way to return to the search screen.

**Comment by jhennig** [comment]
Thanks.  The hold is run from a different system so it's a little tricky.
We may need to just open a new window when the place hold button is clicked.  I'll see what I can work out.

Jeremy

**Comment by jhennig** [comment]
I have a version which should work on the test system. I'll have it deployed to production on Tuesday.

**Comment by jhennig** [comment]
New version is up. I think this should address your concerns.

**Comment by linds37** [comment]
thanks
