### ISSUE TITLE
Location/Status and Library not appearing in serials record

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#581]
I've noticed that on some serials records, location/status and library is not being displayed for some reason (looks like issue is MacEwan locations).
-[Example 1](http://search.library.ualberta.ca/catalog/395190)
-[Example 2](http://search.library.ualberta.ca/catalog/531662)

**Comment by redlibrarian** [comment]
Weird - I've worked through the first record reported here. Two offending items have locations of GR_MAC_INT and GR_MAC_CAC, both of which are in our location mapping file and should be being handled correctly. One of the failing status codes is ON_SHELF which, as we can see, is working for other items. I wonder if something could be happening which is preventing some of the XML from being parsed correctly...

**Comment by redlibrarian** [comment]
It looks as though the parsing of the XML response from Web Services is getting messed up somehow. I can see where the problem is, so it probably just needs some tweaking.

**Comment by redlibrarian** [comment]
This keeps getting weirder and weirder. I'm testing with item 1001644. The bib record should have 2 items: 1 UABARD and 1 UASCITECH. Web Services also shows two items, 1 BARD 1 SCITECH. The blank lines in the holdings table are where the holdings helper pulls back *both* itemID XML stanzas from Web Services. The holdings helper uses the value of the MARC 926 field to access the items, but when I look at the MARC record for the item in question, it shows three holdings: all three are at UASCITECH, all three have different ItemIDs, 2 of which are the same as what shows up in Web Services. Could this be a question of MARC records getting out of sync with Symphony? Is it possible that one of these items was removed, and the other moved to BARD after I got this record for my test set?

**Comment by redlibrarian** [comment]
The solution to this may be *not* to rely on the MARC record holdings information to construct the holdings table. However, there will still be an indexing problem, which is that we index locations according to the same (possibly out of data) 926 field. So even if the holdings table gets fixed, this record will continue to only be available in the UASCITECH facet, not the UABARD facet...

**Comment by sjshores** [comment]
Very interesting problem.  Sam, I think it might be worthwhile to talk in
person about this data problem.

Sandra

**Comment by redlibrarian** [comment]
Sounds good. It may be related to another weird data problem I've noticed:
(the "dark storage") problem.

On Tue, Oct 13, 2015 at 12:22 PM, sjshores <notifications@github.com> wrote:

> Very interesting problem. Sam, I think it might be worthwhile to talk in
> person about this data problem.
>
> Sandra
>
> On 13 October 2015 at 12:16, redlibrarian <notifications@github.com>
> wrote:
>
> > The solution to this may be *not* to rely on the MARC record holdings
> > information to construct the holdings table. However, there will still be
> > an indexing problem, which is that we index locations according to the
> same
> > (possibly out of data) 926 field. So even if the holdings table gets
> fixed,
> > this record will continue to only be available in the UASCITECH facet,
> not
> > the UABARD facet...
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ualbertalib/discovery/issues/581#issuecomment-147800602
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/581#issuecomment-147802489>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by redlibrarian** [comment]
I've just rewritten the holdings table code to only use the Web Services information. This, then, should always be "real-time" wrt the catalogue. I think this will solve the problem of missing information in the holdings tables (I'll do some more testing before I'm sure), but it raises a new problem: sometimes the library facet information will be out of date because this *has* to be based on static Symphony data. This is only really an issue when we go through a period with lots of movements of items (i.e. moving a lot of things to BARD), in which case the facet data will go stale between updates.

**Comment by redlibrarian** [comment]
I think this is fixed. We'll have to check it in the next code release.

**Comment by seanluyk** [comment]
Possibly related to this issue, I've noticed that the library location sometimes does not appear in mono records either, for example, [this record](http://search.library.ualberta.ca/catalog/5599777)

**Comment by redlibrarian** [comment]
It should be the same issue - therefore fixed with the next release - but keep your eye on it. If it's due to something else, we'll catch it.

**Comment by seanluyk** [comment]
This appears to be working
