### ISSUE TITLE
large number of search results when clicking on the find more by author option within a record

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#583]
Selecting the find more by this author option within a record results in a rather large number of hits, 
plus unable to view more than the first 25 results. ie

Simple search for american history: a survey
Select the 1974 edition from the books and more search results. 
Click on the name (Current, Richard Nelson) under find more by this author - 107,319 hits. 
Clicking the next option, ie attempting to view more than the first 25 hits, results in a We are sorry, something has gone wrong error message

![image](https://cloud.githubusercontent.com/assets/14927291/10312044/aef2fc6c-6c06-11e5-95a4-508be6c6a271.png)

![image](https://cloud.githubusercontent.com/assets/14927291/10312135/2adf7404-6c07-11e5-8cc1-ced93a31d99b.png)

![image](https://cloud.githubusercontent.com/assets/14927291/10312670/6afc015e-6c09-11e5-9525-59b16c053f5c.png)

![image](https://cloud.githubusercontent.com/assets/14927291/10319540/fbf1d590-6c2b-11e5-86ac-7ec6748b0027.png)

**Comment by gooyers** [comment]
I was going to submit the high number of 'find more' as an issue but I'll just comment here. I find the large number of results in the "Find more by this author" to be confusing for users. Simply because it does not do what the label would suggest. 

I see this as related to the comments in issue #533. If a search for Current, Richard Nelson returns 107,319 results, and a search for "Current, Richard Nelson" returns 42 relevant results, I believe the default search performed by the "Find more" link should include quotation marks. Rather than requiring users to perform a seperate search to achieve the desired initial functionality.

**Comment by redlibrarian** [comment]
OK, I've changed this to be a phrase search. Please check after the next code release and let me know if any of these problems persist.

**Comment by scastell** [comment]
The phrase searching doesn't seem to be working - end up with over 5 million results when I click on the author's name. Doesn't matter which author phrase I click on, same results.

![image](https://cloud.githubusercontent.com/assets/14927291/10672540/130c5046-78ae-11e5-8cd3-5c7927affe04.png)

**Comment by redlibrarian** [comment]
I wonder if changing the "mm" setting (next release) will fix this problem...

**Comment by scastell** [comment]
no change, still getting 5,691,190 search results.

**Comment by redlibrarian** [comment]
OK. I'm now seeing **471 results** for the Author link, which is still kind of high. The results look relevant, and should be even better in next week's release. @scastell Can you check in next week's release and let me know if this is still a problem?

**Comment by redlibrarian** [comment]
@scastell This should be working now. Please check and let me know if there's still a problem.

**Comment by scastell** [comment]
Much better. Difference in number of hits between blacklight (24) and classic catalogue (42) due to blacklight not including results from the added entry - personal name field (700)?  

ie 

Encyclopedia of the Confederacy. Current, Richard Nelson. - http://www.library.ualberta.ca/permalink/opac/1603088/WUAARCHIVE 

American history : a survey  7th ed. Current, Richard Nelson. - http://www.library.ualberta.ca/permalink/opac/2672741/WUAARCHIVE

not included in the results list


Problem with IE - get a webpage cannot be found error when I click on the get more by this author link - seems to happen no matter which author link I select.

**Comment by redlibrarian** [comment]
Thanks @scastell I'm going to close this issue, and open a new one for the IE bug.
