### ISSUE TITLE
Frequency of updates - Unable to locate new acquisitions

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#585]
I imagine this is just a question of how often new records are updated in Blacklight, but a colleague passed along the fact that they cannot find recently added titles in Blacklight. But in case it is an issue, I'll submit it here. 

To provide an example, BSJ just recieved a copy of the film titled *Samba*, directed by Éric Toledano.
I can see the result in [iLink](http://www.library.ualberta.ca/permalink/opac_fr/7113747/WUABSJ) and in [EDS](http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=cat03710a&AN=alb.7113747&lang=fr&site=eds-live&scope=site) but not in Blacklight.

**Comment by redlibrarian** [comment]
@nmacgreg Is the Solr index currently being updated nightly? Thanks.

**Comment by seanluyk** [comment]
Denis just reported the same issue as he could not locate [key#7113970](http://www.library.ualberta.ca/permalink/opac/7113970/WUAARCHIVE), which shows in Workflows as being created on October 1.

**Comment by gooyers** [comment]
This was not a "Check-in next release" issue. But I still am not able to locate the film *Samba* in Blacklight.

**Comment by redlibrarian** [comment]
I don't think there's been a reindex. I've asked Kenton and Neil to look into it.

**Comment by redlibrarian** [comment]
We have a problem with periodic indexing. I'm going to close this issue, as I'm investigating the issue in #685
