### ISSUE TITLE
Dead link on Delivery Services page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#590]
Link to [University Policy- from Registrar's office](http://www.registrarsoffice.ualberta.ca/404.html?item=%2fmy-personal-records%2fpersonal-information-changes%2f203-electronic-communication-policy&user=extranet%5cAnonymous&site=registrar) on the [Delivery Services Page](https://search.library.ualberta.ca/services/distance-students/delivery-services#books) is dead.

**Comment by alfodor** [comment]
changed link for university policy to http://www.registrarsoffice.ualberta.ca/About/U-of-A-Electronic-Communications-Policy.aspx
