### ISSUE TITLE
https links upsetting my browser

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#592]
This could be machine specific, but I thought I should report that I'm getting lots of "your connection is not private" messages when accessing https links from the [Research Assistance page](https://search.library.ualberta.ca/services/distance-students/research-assistance) in particular.

**Comment by seanluyk** [comment]
I noticed that the problem is mostly with the search.library.ualberta.ca links

**Comment by hannepearce** [comment]
this was happening to me as well but today seems to be resolved.

**Comment by redlibrarian** [comment]
@kgood @nmacgreg Thoughts?

**Comment by kgood** [comment]
Closing issue - re: issue with https.  I believe it has now been resolved and is working.
