### ISSUE TITLE
Double 'Subject' attributes in advanced search

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#594]
Apologies if this has already been noted. 

But there are currently two sections labelled 'Subject' in the attributes of advanced search. 

![2015-10-07_14-46-58](https://cloud.githubusercontent.com/assets/14891931/10350643/6c728680-6d02-11e5-995e-ca6e00460a90.jpg)

**Comment by gooyers** [comment]
There appear to be almost no duplicate subjects between the two attributes when expanded. 

However, I noticed that **Music** is duplicated. And features a different number of results in each (24,390 and 22 respectively).

**Comment by redlibrarian** [comment]
Hmm. It must be constructing the facet based on two different underlying data fields. I'll have to investigate.

**Comment by redlibrarian** [comment]
OK, this should be fixed in the next release.

**Comment by gooyers** [comment]
@redlibrarian Unfortunately there are still two Subject attributes when I click into advanced search.

**Comment by redlibrarian** [comment]
@gooyers It should be fixed now. Can you take a look?

**Comment by gooyers** [comment]
I see only one Subject attribute now. Thanks Sam.
