### ISSUE TITLE
Question: multiple editions

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#595]
How are the rankings of multiple editions determined?
Searching for "hogg constitutional law", the various (student) editions appear in order 1999, 2002, 2007, 2005, 2009, 2011, 2013.

**Comment by redlibrarian** [comment]
Ranking is always done on the basis of a relevance algorithm: it looks at which search terms appear in which data fields and constructs a score for each record (and breaks ties when necessary). The weighting of each field is specified in Blacklight's index configuration files.

**Comment by redlibrarian** [comment]
I should specify that this is true for multiple editions of the same title as it is for different titles. To Blacklight, multiple editions are not connected in any way - they are different titles that happen to share metadata (and thus have similar relevance scores).

**Comment by redlibrarian** [comment]
@merisjames Does this answer your question?

**Comment by merisjames** [comment]
Yes, it does.

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca
