### ISSUE TITLE
Advanced search attributes (sometimes) do not expand

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#597]
In the advanced search page, some of the additional attributes (Library, Call Number, Format, Publication Year etc) fail to expand upon being clicked. The Print vs. Online attribute always expands without issue automatically.

However, this behaviour appears to be weirdly inconsistent. A PSA at BSJ mentioned the problem to me but I was not able to replicate it on my computer in Chrome or Firefox. However, upon using Internet Explorer I was able to replicate the problem.

I tried this on multiple stations in BSJ and did not achieve any consistent results. Most of the time the attributes expanded no problem, but on several occasions they did not. The issue doesn't appear to be unique to any of the browsers. 

Refreshing the page multiple times usually appeared to resolve the issue so perhaps it's an issue that when the page does not load properly, the accordion menus fail to expand.

**Comment by redlibrarian** [comment]
Hmm. Interesting. Just to confirm, @gooyers , you *were* eventually able to reproduce the problem in Chrome and FF, not just Explorer (that's how I read it). 

@nnunn any thoughts? It does seem possible that a failure to load could prevent the relevant JavaScript from working.

**Comment by gooyers** [comment]
That's right @redlibrarian. On my station I only experienced the issue in IE, but my colleague experienced the issue in Chrome, and I tested it on our desk's station and experienced the issue in FF.

**Comment by gooyers** [comment]
@redlibrarian I think this may be the same loading issue so I'll comment here rather than opening a new issue. 

On rare occasions, the "More" button within bento boxes will fail to expand. 

It was more difficult to replicate than the previous issue, but by using IE as my browser and refreshing a few times I was able to replicate it. Dorothée experienced the same issue in Chrome.

![more](https://cloud.githubusercontent.com/assets/14891931/10400103/fd9bbda8-6e73-11e5-8e83-a38e8cfabfda.jpg)

**Comment by redlibrarian** [comment]
I'm a little concerned about these loading time issues. We noticed the last few days that, with Google being down, our pages were either not loading completely, or taking a long time. This is probably causing errors in the javascript. We rely on Google both for book jackets and (I think) fonts....

**Comment by nnunn** [comment]
Not really sure how to handle this one, since I can't replicate it.

**Comment by redlibrarian** [comment]
Let's just mark it as "investigating" and we'll keep an eye on it.

On Wed, Oct 14, 2015 at 9:40 AM, Natasha Nunn <notifications@github.com>
wrote:

> Not really sure how to handle this one, since I can't replicate it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/597#issuecomment-148089542>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by gooyers** [comment]
If an issue is difficult to replicate that at least speaks to it not being a severe issue. I'll happily check up on it periodically. 

I'm not sure if it's helpful, but I could take a screen cap video replicating the issue. It usually took a number of refreshes to replicate. GitHub doesn't support sharing mp4's though.

**Comment by redlibrarian** [comment]
I'm going to move this to the next milestone. It doesn't seem to be a high-priority issue, but we should track it down when we have time early next year.

**Comment by redlibrarian** [comment]
@gooyers Have you seen this lately? I haven't heard of this happening from anyone else...
