### ISSUE TITLE
"More info" in bento box display, books and more container

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#598]
When you click on *more info* for items in the books and more container of the bento box display, there is a call number field, but it's blank.

**Comment by redlibrarian** [comment]
Hmm. We used to have it, but I think I stopped indexing that when it was removed from the brief and full results for being inaccurate. I'll have to figure out what call number to use now...

**Comment by redlibrarian** [comment]
I've removed call number display from the bento pane, as there's no good candidate for what call number to use here. @theLinkResolver and I have noted that we need to think more deeply about call numbers in the new year.
