### ISSUE TITLE
Click fatigue - electronic items in bento box

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#601]
Let's say the perfect e-book or article result appears in one of the containers in the bento box display. Clicking on the title brings you to the detailed record (which is good), but you still have to either click to get full text access from the record, or click on getit!

Why not make clicking on the title bring you *directly* to the item (where possible), and have an option to view more/retrieve record, or something like that when necessary? This is more in line with the point and click expectation of users, and that the idea of top results is to save users time. Is the default behaviour wanting to see a more detailed record, or is this a more advanced user behaviour?  

Here's the logic that would need to go into this, and I have no idea how complicated this is to implement or if it's even possible!

1. If item is full text and UofA access, clicking on title goes straight to item, and there is a detailed record link below the brief results under more
2. If item is not UofA access, clicking on title bring you to the detailed record, which has the getit link, etc.

**Comment by gooyers** [comment]
The potential issue I see with this is that users also expect consistency.
In my opinion, clicking the title in a bento box (and in subsequent results pages) should always do the same thing.

I'd be interested to see what others think. But perhaps it might be possible to include a direct link under the 'More' button.

**Comment by seanluyk** [comment]
Re: consistency, I agree. I guess it's about balancing consistency with
user expectations of expediency to me. Did the user testing look at this at
all?


*Sean Luyk, B.Mus, MA, MLIS*Music Librarian
<http://guides.library.ualberta.ca/music>
Subject Librarian, Anthropology
<http://guides.library.ualberta.ca/anthropology>
Humanities & Social Sciences Library
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta  T6G 2J8
780-492-6779 | https://sites.google.com/a/ualberta.ca/sean-luyk/

**Comment by redlibrarian** [comment]
Adding a direct link under More is possible, but people have also mentioned wanting to include more information (like owning library, e-journal coverage) etc, under More. Space there is limited, so I'd want to be careful about what we decide to include there. 

The trickiest part about the logic that @seanluyk suggests is how much the system "knows" about a given record in the Bento controller (the code that handles the querying and construction of that bento pane). Currently, it has access to much less data than, e.g., the result view. This could be changed, but eventually it might come to building all of the result information into the bento box, which would probably indicate that we should rethink the architecture. 

One other thing I should mention is that @nnunn and I planned to give users the ability to toggle between the bento view and a full results view. This would exclude articles, but include all the other panes in a single result list, which some people had expressed an interest in before, but also requires thinking about. Like the LCSH issue, this is probably something that needs more detailed (and face-to-face) discussion.

**Comment by redlibrarian** [comment]
According to the discovery testing team and WAT, we're going to leave this as is for now, but may reopen the issue at a later date.
