### ISSUE TITLE
Item Types not displaying in bento box

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#604]
Not sure if this has been noted elsewhere, took a look and didn't see it. When searching the main search box and the results come up in the Bento Box view, some items are displaying "Unknown" next to them, as if blacklight isn't reading the item type.

![image](https://cloud.githubusercontent.com/assets/14892833/10375118/f05c6e32-6db3-11e5-8100-66d41d197752.png)

**Comment by redlibrarian** [comment]
There are some issues with the way our marc data is being mapped to format. @theLinkResolver will be looking into the mappings to resolve this.

**Comment by redlibrarian** [comment]
See issue #544

**Comment by redlibrarian** [comment]
We've added some new mappings to formats, and in the meantime I've suppressed the display of "Unknown" (the format is left blank if unknown) as more mappings are added, fewer items should display blanks here. I'm going to close this ticket, it should be better addressed in #544
