### ISSUE TITLE
Treatment of punctuation

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#605]
Dorothée noticed an issue this morning while trying to find [L'enfant cachée](https://search.library.ualberta.ca/catalog/6031800). More specifically, searching for ["enfant cachee"](https://search.library.ualberta.ca/results?utf8=%3F&q=%22enfant+cachee%22) returned no results, but a search for ["l'enfant cachee"](https://search.library.ualberta.ca/results?utf8=%3F&q=%22l%27enfant+cachee%22+) returned the relevant book as the only result. 

This behaviour could cause a number of problems, particularly from the perspective of users searching for french language results, but beyond that as well. That being said, I'm not 100% on what's actually going wrong.

From some additional searches that I've done, I'd speculate that it has to do with Blacklight treating punctuation not seperated by spaces as part of a word.  This is reinforced by the fact that in a search for **enfant cachee** (without quotation marks), the title being sought does not appear on the [first page of results](https://search.library.ualberta.ca/symphony?f%5Belectronic_tesim%5D%5B%5D=Print&q=enfant%20cachee) and doesn't appear prominently until you've added [several limiters](https://search.library.ualberta.ca/symphony?f%5Belectronic_tesim%5D%5B%5D=Print&f%5Blc_1letter_facet%5D%5B%5D=P+-+Language+%26+Literature&f%5Blocation_tesim%5D%5B%5D=uabsj&q=enfant+cachee) (at which point it is still the 16th result). Blacklight is treating **L'enfant** as a word distinct from **enfant** and is ignoring it in keyword searches as well.

To provide another example, the article example used during testing was [*Think Tanks, Funding, and the Politics of Policy Knowledge in Canada*](https://search.library.ualberta.ca/results?utf8=%3F&q=Think+Tanks%2C+Funding%2C+and+the+Politics+of+Policy+Knowledge+in+Canada). A search for that title works no problem, but a search for [Think Tanks,Funding,and the Politics of Policy Knowledge in Canada](https://search.library.ualberta.ca/results?q=Think+Tanks%2CFunding%2Cand+the+Politics+of+Policy+Knowledge+in+Canada) (no spaces between commas) returns no results.

**Comment by redlibrarian** [comment]
Hmm. That's a bit weird. I'll have to investigate the solr indexing rules to see what I can tweak there.

**Comment by redlibrarian** [comment]
L'enfant cachée is now working properly. The problem remains with "Think Tanks..." The only result I get back is from EDS. This is pretty low priority now that the initial search problem seems to be working, so I'm going to move it to the January milestone.

**Comment by gooyers** [comment]
@redlibrarian I think this issue is fine for the January milestone as it is relatively low priority. 

That being said, aspects of the initial issue I described are still not working properly. 

For example, a search for ["l'enfant cachée"](https://search.library.ualberta.ca/results?q=%22l%27enfant+cach%C3%A9e%22) returns the proper result.
But a search for ["enfant cachée"](https://search.library.ualberta.ca/results?q=%22enfant+cach%C3%A9e%22) returns no results under the Books box. 

The apostrophe in L' is still being less than ideally for french language searching. 

That being said, searches for [enfant cachee](https://search.library.ualberta.ca/results?q=enfant+cachee) and [l'enfant cachee](https://search.library.ualberta.ca/results?q=l%27enfant+cachee) now both return the desired title. Which is good, and fixed from the initial issue. 
 
However, the results page for [l'enfant cachee](https://search.library.ualberta.ca/results?q=l%27enfant+cachee) includes an astonishing number of results in the EDS box (19 million) compared to the search for enfant cachee. 

I'm not sure, but it seems as though Blacklight searches all of the EDS index for "L", or something similar. Upon clicking into the box, all seems to be well and only [174 articles](https://search.library.ualberta.ca/articles?q=l%27enfant%20cachee&includefacets=y&searchmode=all&view=brief&resultsperpage=20&pagenumber=1&highlight=y) are returned. But something odd/unintended is going on here.

**Comment by redlibrarian** [comment]
OK, thanks @gooyers I've compromised by moving it back to the September milestone, but setting the priority to medium. I'll see if I can get to it.

**Comment by redlibrarian** [comment]
@gooyers I just realixed that your search for **enfant cachée**, which won't work because it can only find it with the l' - it's a question of the precision of the search term, it's trying to find a version of 'enfant' **without** the l'. I would say that since all of **l'enfant cachée**, **enfant cachée**, **l'enfant cachee**, and **enfant cachee** all return the right book, even if the result sets aren't quite the same, this is probably as good as we're going to get it. I think we should probably bear in mind that we might need to explain to users (staff) that a phrase search is **very** precise, and that if you get no results, you should try without the quotation marks. Does this sound OK?

**Comment by gooyers** [comment]
@redlibrarian I agree that  **l'enfant cachée, enfant cachée, l'enfant cachee, and enfant cachee** all returning the right book (even with slightly different results) is more than alright. It speaks to the precision of phrase searching, and I agree that we should stress it in training. Re-attempting a search without quotation marks seems like a good practice as well. 

If Blacklight were able to ignore **L'** and **D'** etc as EDS is able to, I would consider that ideal. But I would put that under "enhancement" for investigation in January-April (if it is even possible with Blacklight). So that all sounds okay. 

The one remaining piece is that visual bug that I noted in the Articles box: 
*However, the results page for [l'enfant cachee](https://search.library.ualberta.ca/results?q=l%27enfant+cachee) includes an astonishing number of results in the EDS box (**19 million**) compared to the search for enfant cachee. 

I'm not sure, but it seems as though Blacklight displays a search of the EDS index for "L", or something similar. Upon clicking into the box, all seems to be well and only [174 articles](https://search.library.ualberta.ca/articles?q=l%27enfant%20cachee&includefacets=y&searchmode=all&view=brief&resultsperpage=20&pagenumber=1&highlight=y) are returned. But something odd/unintended is going on here*.

**Comment by seanluyk** [comment]
I believe that many library catalogues and databases ignore intial articles, and treat them as stop words. Not sure if this is wise, but here's a huge list of them:
http://www.loc.gov/marc/bibliographic/bdapndxf.html

**Comment by redlibrarian** [comment]
There's also a move to stop using stopwords at all - to leave off articles, etc, if they aren't required for a precise search. Anyway - let's leave that discussion until next term. I'm going to try to fix the EDS article count problem, then once the issue has been approved in the next release, let's move this issue to the January milestone for discussion. @seanluyk @gooyers

**Comment by redlibrarian** [comment]
OK, I've managed to hack together a fix. It's not pretty (simply strips **l'** and **d'** from the query, if they are present), but it will work for now. @gooyers Please check this in the next release.

**Comment by redlibrarian** [comment]
@gooyers OK, the EDS fix is in place now.

**Comment by gooyers** [comment]
@redlibrarian The EDS fix works, and the EDS box no longer displays a large number of results. 

But I'm not sure if the **l'** hack that strips it from the query is working though. As I noted in my previous comment the searches without quotation marks (l'enfant cachée, enfant cachée, l'enfant cachee, and enfant cachee) all return the correct book. But ["enfant cachee"](https://search.library.ualberta.ca/results?q=%22enfant+cachee%22_) still returns no results, while a search for ["l'enfant cachee"](https://search.library.ualberta.ca/results?q=%22l%27enfant+cachee%22) returned the relevant book as the only result. If the l' was being stripped, shouldn't this not occur?

As you said Sam, now that the EDS issue has been fixed I think this issue can be moved to the January milestone for further discussion

**Comment by redlibrarian** [comment]
The hack was only applied to the EDS box. I just added **l'**, **d'**, and **m'** to the Blacklight stopwords list and this seems to have fixed the no-result problem. That will be in production before we launch. Take a look at it then and see if that improves things. We can refined further in January if necessary.

**Comment by redlibrarian** [comment]
@gooyers Can you take a look at this when you have a chance and let me know how it looks to you?

**Comment by gooyers** [comment]
Still not sure that the Blacklight stopwords are working 100%. 

A search for "enfant cachee" doesn't return the item listed in the example above:
https://search-test.library.ualberta.ca/results?q=%22enfant+cachee%22
