### ISSUE TITLE
Lost Item Appearing in Bib-Record

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#606]
The following was just sent to me by one of our PSAs, he has highlighted the library locations not appearing with red arrows (which I know has already a known issue) but the green arrows show a title that is marked assumed lost in workflows. Past practice was not to show these items in the catalogue. I feel it should either not appear or at least have the label "Lost" to avoid confusion for the user.

![image 1](https://cloud.githubusercontent.com/assets/14892833/10375584/93dfaec8-6db6-11e5-9fba-7777fbb4b90a.png)

**Comment by redlibrarian** [comment]
The EASY_READ item belongs to Norquest, but Symphony is using NORQ_MAIN as a code, which I don't have in my location map. There's no indication in the Web Services record that the item is lost. 

As for the Coutts item, this one *does not* appear in the Web Services record, indicating that the item is lost/missing. This shouldn't be coming through to Blacklight, so in that sense it's similar to the other holding's problem we're having with dark storage items (issue #536 ). This will have to be investigated as part of that problem.

**Comment by redlibrarian** [comment]
OK, I think this is part of a bunch of related problems to do with holdings/items. #581 is an example. I have a fix in place - we'll need to check it on the next code release.

**Comment by redlibrarian** [comment]
@hannepearce You should have received an invitation to join the Discovery Testing team in GitHub. This will give you access as a collaborator on this repository (and it will mean I can assign the issue back to you). Can you see if you have it? Thanks.

**Comment by hannepearce** [comment]
@redlibrarian Yes I found it, sorry I missed that step a few weeks back. I accepted the invitation.

**Comment by redlibrarian** [comment]
@hannepearce No problem - thanks!

**Comment by hannepearce** [comment]
This issue appears resolved. All item locations are appearing as well as due dates.
