### ISSUE TITLE
Book cover images not displaying

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#607]
Some of the syndetics book cover images aren't displaying, for example, in: https://search.library.ualberta.ca/catalog/2017171

**Comment by redlibrarian** [comment]
We no longer use Syndetics for book covers, we use Google books instead. Having said that, I'm not seeing any book jackets. Sometimes Google can block the feed if they've been hit with too many requests, but I'll ask @nnunn to investigate this one.

**Comment by redlibrarian** [comment]
Book covers appear to be back. I wonder if this was related to the Google problem we were having on campus?

**Comment by seanluyk** [comment]
Looks like it. Too bad so many of the titles don't have images, but I guess this beats having to pay for the syndetics content.

**Comment by seanluyk** [comment]
For some reason, book covers are appearing in list view, but not necessarily in record views.

For example, in this [list of results](https://search.library.ualberta.ca/symphony?q=ziggy%20stardust%20and%20the%20spiders%20from%20mars) results 6 and 7 display book covers in list view, but not in their record views.
