### ISSUE TITLE
Suppress incomplete temp records

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#609]
Not an issue with Blacklight, but possibly something it could help to filter out. Is there any way for Blacklight to suppress incomplete records created by NEOS libraries for purposes internal to the holding library, such as [this one (http://search.library.ualberta.ca/catalog/7027362)? 

Since it's meant for UofA use, and we don't create records as brief as this this, I'm thinking that it might be possible to ignore records missing specific key MARC fields. In a large discovery system, they're unwanted noise.

**Comment by seanluyk** [comment]
Other examples
-http://search.library.ualberta.ca/catalog/5355452
-http://search.library.ualberta.ca/catalog/5355692
-http://search.library.ualberta.ca/catalog/4293107

**Comment by redlibrarian** [comment]
We would need to work with Jim on this - he's the programmer who extracts records from Symphony. Currently the Blacklight data is the same data we send to Ebsco for EDS (i.e. for all NEOS libraries that use EDS) - it doesn't have to remain that way, but it's a consideration.

I think it would be good to exclude them if we can figure out the best way to do that. I'll set this to the phase 2 milestone for investigation.
