### ISSUE TITLE
Make "articles advanced search" link stand out.

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#610]
Possible to make the 

For articles advanced search, click here 

statement bold or something so that it stands out on the page?

The heading for the non article advanced search results includes the phrase "in all library collections" ie 

 results for housing and japan in all library collections 

Reword the heading as articles aren't included in the results?

**Comment by redlibrarian** [comment]
I'm going to split these up into two issues so we can tackle them separately. They are both achievable.

**Comment by redlibrarian** [comment]
This issue is to make the "articles advanced search" link on the advanced search page stand out more.

**Comment by nnunn** [comment]
done - on ui-new branch
