### ISSUE TITLE
eBooks in 'Books and more' results

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#611]
eBooks are showing up in the Books and more search result box, format says "book" but the first 3 results are eBooks:
![image](https://cloud.githubusercontent.com/assets/14892870/10380951/6e4f8192-6dd4-11e5-8f50-324799b8b1c9.png)

And I'm betting this is not anything we have to do with but the record for that first eBook has the author in the ISSN field:
![image](https://cloud.githubusercontent.com/assets/14892870/10381025/e49222e2-6dd4-11e5-8443-88f1f30c2dea.png)

Also, my search term was "birds" but the top book and ebooks results aren't bird related, just authored by a Bird, so not that helpful. Though the article and journal results were relevant. I had similar issues with a search for "balding".

**Comment by gooyers** [comment]
I'll comment here as I think it's a related issue.

A search from the main bar limited to "articles" leads to a search page that includes books, ebooks, and various other formats.
![totalitarianism](https://cloud.githubusercontent.com/assets/14891931/10399966/41ada7f0-6e73-11e5-9275-fbd932371edc.jpg)
![totalitarianism2](https://cloud.githubusercontent.com/assets/14891931/10399970/45d2354e-6e73-11e5-88a6-35c2259f287e.jpg)

**Comment by redlibrarian** [comment]
<taking a step back> One of the initial headaches we had was deciding how to build/label the bento panes. Since a few people have brought up questions/concerns regarding how items are assigned to bento panes, as well as the labeling, and considering it's tricky to determine formats properly given the limits of (e.g.) MARC data. Maybe this is another thing that we should sit down face to face and hash out.

**Comment by theLinkResolver** [comment]
@redlibrarian I'm puzzled about why the author's name is coming up in a field labelled "ISSN".  I checked the record and it looks fine.  The author's name appears in two spots: the 100 field, and in $a of the 776.  Any ideas??

**Comment by redlibrarian** [comment]
@theLinkResolver Welp, it looks like the default mapping is for 776$a to be mapped to ISSN. Is that wrong? I think I use 776 for ISSN information in sfx2sirsi...

**Comment by theLinkResolver** [comment]
@redlibrarian At least there's an explanation! Okay, so the 776 is for another physical form of the item. In the case of this record, the field is describing the print version of this e-book, with the author's name in $a. (Your thought about the ISSN is not completely off-base -- 776 $x in a serial record is the ISSN of the title in that other format.)  

Like anything, there are pros and cons for having the 776 data be visible to the user, but in light of our current situation, I think you can pretty safely exclude any 776 data from being displayed in the Blacklight record, on the grounds that it is not displayed in the current OPAC. (and like anything, this decision can be reviewed later)

**Comment by redlibrarian** [comment]
@theLinkResolver OK, thanks - I'll remove the 776 from the ISSN mapping. The other ISSN mapping is the 022a - is that still fine?

And to get back to the original issue - the redesign of the bento panes has been discussed and approved by the testing team and we'll make that change shortly.

**Comment by theLinkResolver** [comment]
@redlibrarian That's right - the 022 $a is the (only) ISSN that we want to see displayed in the record.

**Comment by redlibrarian** [comment]
This is addressed in #684 . Closing.
