### ISSUE TITLE
Item at BSJ not appearing once BSJ limiter is selected.

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#614]
I find this issue to be a headscratcher.

Upon conducting an advanced search looking for items authored by **Alberta Education** with the subject term **Art dramatique**, the first result is [*Guide d'enseignement: art dramatique : secondaire premier cycle*](https://search.library.ualberta.ca/catalog/1760756) which is relevant and located at BSJ. 

![artdramatique](https://cloud.githubusercontent.com/assets/14891931/10402464/d1205112-6e82-11e5-8e83-c0115a9c0471.jpg)

![artdramatique2](https://cloud.githubusercontent.com/assets/14891931/10402472/d637a862-6e82-11e5-9f0f-035aa5aba497.jpg)

However, upon choosing BSJ in the Library/Location facet the Guide d'enseignement item no longer appears as the first result and no longer appears in the results list at all (or at least I could not find it). 

So essentially... limiting to BSJ appears to have removed an item from BSJ. I could not think of an easy way to see if this was occurring for other library locations. 

![artdramatique3](https://cloud.githubusercontent.com/assets/14891931/10402476/db2b2e34-6e82-11e5-8c3a-92eab377f633.jpg)

**Comment by redlibrarian** [comment]
Hmm. Interesting - weird. I'll have to look at the data we're getting from the index to try to figure this out.

**Comment by redlibrarian** [comment]
It looks as though the indexing rule only allows an item to be assigned to one location, and the first location that appears in the record is the BARD location, hence excluding this record from UABSJ. I'll look at fixing it.

**Comment by redlibrarian** [comment]
OK. I rewrote the indexing script, and this fixes the problem in development. This can be checked on the next code release.

**Comment by gooyers** [comment]
Thanks @redlibrarian. I can repeat the search in the coming days and check back in.

**Comment by redlibrarian** [comment]
Thanks Brian - I'll let you know when the new code is in place.

On Tue, Oct 13, 2015 at 11:24 AM, Brian <notifications@github.com> wrote:

> Thanks @redlibrarian <https://github.com/redlibrarian>. I can repeat the
> search in the coming days and check back in.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/614#issuecomment-147783993>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by gooyers** [comment]
Unfortunately I'm still experiencing the same issue. I tried the same search as before, and the "Guide d'enseignement" title appears as the first result in a search that is not limited to a particular library. 

And upon adding the BSJ location as a limiter, the "Guide d'enseignement" title is no longer the top result, nor is it among the 41 results.

**Comment by gooyers** [comment]
I could not repeat the same steps, as advanced search is not currently working (Issue #689), but this issue appears to be fixed. 

I conducted a simple search for **guide d'enseignement art dramatique**, entered the Books&more pane and was able to limit to BSJ without the item disappearing. I can open the issue again if I try the same path again once advanced search is up and the previous issue appears, but from what I can tell it's fixed so I'll close the issue.
