### ISSUE TITLE
database search

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#616]
I searched *Ulrichs* in the main search, selected databases as the place to search and it opened to one result but when I click on that result it takes me to this a German book about Napolean. record: https://search.library.ualberta.ca/catalog/318
I closed my browser and re-did the search the same way and it did the same thing.

**Comment by hannepearce** [comment]
I should note that on a second refresh it did go to the Ulrich's database page. Thinking it was just a weird Chrome glitch I tried firefox and it the problem came up again - it displayed the same book record.

**Comment by redlibrarian** [comment]
Weird. This is working for me now - and the URL is hard-coded into Ernie Howe's database of database records. I'd say this was just a glitch - @hannepearce can you let me know if this happens again. If we don't see/hear anything further, we can close this ticket next week.

**Comment by hannepearce** [comment]
Ok I just tested this out on the service desk and sometimes I get the database page sometimes I get that same bib record. I know this sounds crazy but if you click either on the words "International" or "Periodicals" and sometimes right in between them, that's when I get the funny record. I looked up the marc record for the item the [classic catalog](http://ualweb.library.ualberta.ca/uhtbin/cgisirsi/x/0/0/57/5?&searchdata1=318{001}&user_id=WUAARCHIVE) I keep getting and it has a cat key number 318 which appears to be the number assigned to this database in the URL - that is the only correlation I can find between the two items. Going to try this on another database just out of curiosity.

**Comment by redlibrarian** [comment]
Oh! I see what's going on. There's actually an ID collision - most of the Symphony catkeys are much longer than the database keys - this is a case where the catkey is small enough that it collides with the database key. I see what's going on. 

This will, I think, be changed with the move to using libguides as the database source - we'll mark the IDs with their source or format....

**Comment by redlibrarian** [comment]
This should be fixed when we fix Issue #498 .

**Comment by hannepearce** [comment]
yes other database tests thus far have not duplicated the problem. Glad I found the correlation, for a moment I thought this was just some random glitch following me around.

**Comment by seanluyk** [comment]
While checking #652 , I experiened ID collision, so I'm not convinced that this should be closed just yet.

**Comment by redlibrarian** [comment]
Interesting. The new (libguides ) database functionality should have
cleared up any collisions. If they're still occurring,  I wonder if the
reindeer has gone through.

**Comment by seanluyk** [comment]
I should add one caveat: I generally open large sets of links with Linkclump, so I'm not sure if it has something to do with this behaviour. When I click links individually it tends to not happen.
