### ISSUE TITLE
Bento box display and Version control

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#618]
Can future releases address the issue of version control? For example, look up this title: Policing Stalin's Socialism https://search.library.ualberta.ca/results?utf8=%3F&q=Policing+Stalin%27s+socialism
It comes up twice in the Books and More box and twice in the Ebooks box. You have to click on each one to eventually find out that we don't have this at the U of A in any format.

I mentioned this once before, Sam, but I've had feedback from colleagues on this just recently as well: are we wedded to the idea of separate bento boxes for books and ebooks. From a content perspective, it would make more sense for them to be combined. Then, in future, maybe version control would be possible as well -- ie: one click to see the locations reflected on all four records?

**Comment by redlibrarian** [comment]
The bento box design and labelling is something I want to discuss at the meeting on Monday. As for "version control" - which library locations own copies of a book is supposed to be visible on the results page (not the bento page). I don't know why that's not coming through, but I'll find out.

**Comment by redlibrarian** [comment]
I've verified that the owning locations should appear on the result view, we'll check on those in the next code release.

**Comment by linds37** [comment]
Thanks. It would be ideal if there was a way to pull all of the ver
