### ISSUE TITLE
Print or Online? facet labelling

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#621]
This is a picky one, and has to do with the fact that I'm coming at this from my perspective as a music librarian, so bear with me...

I wonder if the **Print or Online?** facet could instead be labelled **Access** (or something similar), and the options could be *Online* or *At the Library*. The reason I ask is that many of the items that come up are in fact not print per se:
-physical sound and video recordings 
-kits
-slides
-equipment
-even weirder stuff like globes

**Comment by redlibrarian** [comment]
We can discuss this on monday - it's related to the bento/labeling question we also need to discuss.

**Comment by redlibrarian** [comment]
This has been changed according to WAT's approval. It will be apparent in the next release.

**Comment by seanluyk** [comment]
Looks great!
