### ISSUE TITLE
Subject headings searches

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#624]
Related to #557, #543, #522, and #504, but with a twist.

When I clicked on the [Davis, Miles heading](http://search.library.ualberta.ca/catalog?f%5Bsubject_topic_facet%5D%5B%5D=Davis,%20Miles&q=&view=brief) from [this record] (http://search.library.ualberta.ca/catalog/5599777), I expected to be able to find journal articles on Miles Davis, but found that this was not an option (i.e. it appears that there are no articles with the terms Miles Davis).

I know why this is the case (it was searching the LCSH heading), but I see this as a major discovery issue.

Be comparison, when I clicked on Davis,Miles from the [parallel record in EDS](http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=cat03710a&AN=alb.5599777&site=eds-live&scope=site), it searched this term as keywords.

I see how either option has its advantages/disadvantages, but perhaps this is something we could talk about.

I wouldn't want a student to be stopped in their tracks mistakenly - they won't know why they aren't getting results.

**Comment by redlibrarian** [comment]
This is something we should discuss as part of the LCSH discussion on Monday. Given that we can never combine the two indexes (local and EDS), what can we do to make things easier/more intuitive. There are a few options, though none will be perfect.

**Comment by seanluyk** [comment]
@redlibrarian I see this is a really big issue. It's possible in EDS, so does it have to do with the functionality we're allowed to use via the EDS API?

**Comment by redlibrarian** [comment]
@seanluyk Which part? The we can't combine the indexes because they are stored in two different places (and one is the property of Ebsco). In terms of how the subject terms are searched, that's partly the API (how EDS results are returned to Blacklight) and partly the search logic is implemented on the EDS end. It is a big issue. Unfortunately, because we have no alternative but to license a knowledge base (= article metadata, full text, etc), this is a tricky problem. No-one's solved it, but there are different approaches we can take to making it easier to use. Maybe making the EDS/Blacklight distinction clearer is something we should consider - some places make their article/KB search completely separate from their discovery interface to avoid this problem...

**Comment by seanluyk** [comment]
@redlibrarian the ability to click on LC subject headings in EDS and it search these as descriptors across databases is really useful functionality, it's too bad that this can't be done in Blacklight. I don't see a huge advantage of paying for a knowledge base when you're limited in what you can do with it, but I see why EBSCO would want to hold onto some level of control over their property, even if I disagree with it.

**Comment by redlibrarian** [comment]
@seanluyk With KBs it's all or nothing: there are no open-source/access versions of a KB (well, there are a couple, but they are very new and not mature). So we either pay for a KB or we have no access to any article (etc) metadata or full text. And IP being what it is, the KB is a mess of licensing between us and Ebsco, and between Ebsco and the publishers. The advantage to the KB is exactly what you say: a unified index, which allows for searching to be mapped across data sources. Vendors like Ebsco, ProQuest/Ex Libris, would much rather we stop messing around with open-source software and just use their system. This could be a solution, except that they can't handle any but the most basic of our metadata (basically just MARC and Dublin Core data). Anyway - as you can tell I have a lot to say on this subject. :) One thing we can think about it whether it serves our users better to decouple the EDS knowledge base and search capacity from our local index/search...

**Comment by redlibrarian** [comment]
This should be *more-or-less* working in the next release. It's tricky to get right, so there will still be some tweaking to do.

**Comment by redlibrarian** [comment]
OK, this is basically working. The only thing that needs to be changed is that the link needs to go to the results controller instead of the catalog controller, in order to get article/EDS results.

**Comment by redlibrarian** [comment]
@seanluyk This one may not be perfect, but is an improvement. Can you let me know what you think? If it's working well enough we can close the issue and refine later on.

**Comment by seanluyk** [comment]
@redlibrarian , I like this solution, but since it's a change in behaviour (going to Bento display instead of a list of results), this may merit some more discussion with @ualbertalib/discovery-testing before closing the issue. It results in extra clicks, but does allow the user to search various indexes at once from a subject heading search, which I believe is added functionality. What does everyone think?

**Comment by redlibrarian** [comment]
@seanluyk @ualbertalib/discovery-testing Yes, I thought that made sense as it allows you to get, for example, EDS results, but I agree I shouldn't have made the decision unilaterally. What do others' think?

**Comment by gooyers** [comment]
I see going to a Bento display as a positive change, and I'd look forward to something similar being implemented for Advanced Search. 

People are unlikely to get relevant results from the Journals or Databases box (unless they click on a very general subject heading). But I think the ability to present results from the Blacklight and EDS index at the same time outweighs the small downsides.

**Comment by redlibrarian** [comment]
No-one else has chimed in. I'd like to leave it as is for now. If anyone raises an objection, it can be discussed/worked out next term.
