### ISSUE TITLE
Ebsco Article Search Inconsistency

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#626]
Searching this in EDS proper brings back a direct hit:

Descriptive analysis of seat ergonomics among Utica College population

Searching the same thing is Blacklight brings back no hits from the API in the bento box view.

Works fine if you are just using the article scope from the front page:

https://search.library.ualberta.ca/articles?utf8=%3F&q=Descriptive+analysis+of+seat+ergonomics+among+Utica+College+population

**Comment by redlibrarian** [comment]
This is related to the fact that we're excluding everything that's not a journal article from the bento results. It's one thing I want to discuss on Monday.

**Comment by redlibrarian** [comment]
This is working now.
