### ISSUE TITLE
Known database not appearing in database results

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#627]
I went to pull up the [érudit](https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=3424) database, but rather than going through the A-Z list I searched [érudit](https://search.library.ualberta.ca/databases?utf8=%3F&q=%C3%A9rudit) in the main search bar and limited to Databases. Unfortunately I got no results. Removing the accent did not change the search results.

For what it's worth, érudit is listed in both the Libguides list of databases and the [current list of databases](https://www.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=3424). 

Perhaps érudit isn't identified correctly as a database?

**Comment by redlibrarian** [comment]
That's weird. I know I've seen Erudit in the list before.

**Comment by redlibrarian** [comment]
Ugh. It's the stupid html-encoding problem (html is hardcoded in Ernie's database), so érudit is in fact appearing as "&eacute;rudit". I'll have to figure out how to fix it - though this should be resolved with the move to libguides database list.

**Comment by redlibrarian** [comment]
I'm trying an adhoc fix for now. This will be resolved in any case with the move to the libguides list.

**Comment by redlibrarian** [comment]
Hrm. This works now if you search with the accent aigu. It *should* come up without it, but it isn't. Not sure why not... This could be part of a larger diacritic search problem. @gooyers

**Comment by gooyers** [comment]
@redlibrarian I figured I'd try a search for another known database that includes a diacritic, Repère. 

Similarly, a search for repère returns the correct result under Databases, but a search for repere does not (see attached images).

Interestingly, the search for repere did return results with the accent grave. Which leads me to wonder, might it be that the Libguides populated results are treating diacritics differently? 

![2015-11-12_14-34-42](https://cloud.githubusercontent.com/assets/14891931/11132008/bbccab52-894a-11e5-9aba-07be8af894a3.jpg)
![2015-11-12_14-35-51](https://cloud.githubusercontent.com/assets/14891931/11132010/befc9346-894a-11e5-9d91-9caf8ec6748c.jpg)

**Comment by redlibrarian** [comment]
Interesting. I think that must be it, but I'm not sure why... I'll have to do some digging.

**Comment by redlibrarian** [comment]
So, I've confirmed that for some reason the libguides data is treating the accents differently. Searching for **Erudit* should bring back the same result as **Érudit** but it is not...

**Comment by redlibrarian** [comment]
OK, this will be fixed in the next release, @gooyers

**Comment by gooyers** [comment]
érudit and erudit, as well as repère and repere now all return the correct databases. Thanks Sam!
