### ISSUE TITLE
Result display issue 

### ISSUE THREAD

**Issue by dmc2** [ualbertalib/discovery#632]
When searching for: systematic reviews 2014 - everything (from the home page) and then "systematic reviews" 2014 - everything (from the home page) - there are 0 article results displayed for "systematic reviews" 2014. There are 8409 articles for systematic reviews 2014. I would have thought that there should be article results for the search with quotes "systematic reviews" 2014 - I will attach images. 
![systematic reviews 2014 home page no quotes](https://cloud.githubusercontent.com/assets/14880806/10522596/336b3440-7333-11e5-8bf5-668bfd7f9bcf.png)
![systematic reviews 2014 quotes](https://cloud.githubusercontent.com/assets/14880806/10522630/6c43086a-7333-11e5-9be7-dbd4a230b4e4.png)

**Comment by redlibrarian** [comment]
This is the same problem as issue #548 . It will be fixed in the next code release.

**Comment by redlibrarian** [comment]
Hmm. This still seems to be a problem...

**Comment by redlibrarian** [comment]
Hi @scastell - this should be working now. Can you verify?

**Comment by scastell** [comment]
A search for "systematic reviews" 2014 does result in a number of articles. The number of results, for both searches, (see screenshots below) is quite different from that in the original screenshots. 

![image](https://cloud.githubusercontent.com/assets/14927291/11308941/38365d6c-8f7e-11e5-9564-5be7b3e66a92.png)

![image](https://cloud.githubusercontent.com/assets/14927291/11308984/6c8ca904-8f7e-11e5-87ab-97f5121673a3.png)

**Comment by redlibrarian** [comment]
Thanks @scastell - are these the results you would expect to see?

**Comment by scastell** [comment]
little out of my area, so asked someone from health to look at the article results. Results are what they would expect to see, so unless someone else has a comment, the issue can be closed.

**Comment by redlibrarian** [comment]
OK, thanks. I'm going to close it for now. We can create a new issue if the problem comes up again.
