### ISSUE TITLE
Advanced Search: Any/All

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#633]
There is no difference in number of results in advanced search, between "any" and "all" with "okhee water" (no quotes) in "All Fields".

Also, what is the effective difference between using advanced search "any" in "All Fields" versus the basic search? There are 5k more results in the latter v the former.

**Comment by redlibrarian** [comment]
The advanced search is primarily for either specifying a field (e.g. title, author) or combining fields (e.g. title, author). As a result, there should be very little difference between using the All Fields advanced search and using the simple search (I'd have to check the index and code to see why there would be a difference of 5000 results between the two). 

Having said that, I think that "any" and "all" applies to the field boxes, not the terms within the fields. Within the fields, the nortmal relevance rules apply. So picking "any" and "all" but only searching within one field shouldn't make a difference. 

This is how I understand the indexing/searching working, so I could be wrong, but the idea supports the first issue you raise.

**Comment by merisjames** [comment]
There is still a 5k difference in number of results between advanced and basic search.

**Comment by redlibrarian** [comment]
I'm now getting the same results (43,281) for this search from both advanced search and simple search. @merisjames Can you take a look and see if you're getting the same?

**Comment by merisjames** [comment]
Basic: 48158 results for okhee water
Books and more 33179 results
eBooks and more 14507 results
Articles 6 results
Electronic Journals 463 results
Databases 3 results

Advanced: 43,281
Print 33,179
Online 14,973
At Library 45 

It looks like it isn't correctly adding up the advanced results for a total number of results?

**Comment by redlibrarian** [comment]
Hm. I think there isn't so much a search/retrieval problem here as an issue around what's getting put in what bento pane. Let's see if it's clearer when we redesign/relabel the panes.

**Comment by redlibrarian** [comment]
@merisjames Can you take a look and let me know if this is still an issue?

**Comment by merisjames** [comment]
Closer. 
461 v 464 (advanced) for "laminitis".
319 v 320 for "farrier".
Identical results for "tamarind"
1271 v 1290 for "costa rica"

**Comment by redlibrarian** [comment]
I think this is within tolerance for now. I'm going to move this to look at some more next term.
