### ISSUE TITLE
Manually deleted record appearing in Blacklight

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#635]
The following record was deleted manually from Symphony at least a week ago:

https://search.library.ualberta.ca/catalog/6783477

Apparently this was "manually deleted" because it was in an ebook package we no longer have.

**Comment by redlibrarian** [comment]
This is one of several issues that's making me think our updates aren't happening as frequently as we thought. @nmacgreg can you confirm updates are happening nightly? If so, then there's something else wrong...

**Comment by seanluyk** [comment]
@redlibrarian and @nmacgreg FYI - it's still appearing in Blacklight, but the link to the resource is gone.

**Comment by redlibrarian** [comment]
That means it's still in the index, but not finding a corresponding record in Symphony. This goes back to my suspicion that the index is not being updated. / @nmacgreg

**Comment by redlibrarian** [comment]
Closing this issue as I'm addressing it in #685
