### ISSUE TITLE
No results returned in advanced search

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#637]
Testing the advanced search, I searched in all fields with no pre-faceting for transhumance and no results were returned. Works fine in simple search.

This word appears in many titles and is a subject heading, so I'm wondering why it's not working?

**Comment by redlibrarian** [comment]
Ah, it's the same problem as in #550 . It's not a problem with the search term or anything, it's a bug in the result display logic. It's fixed, and so this should work fine in the next release.

**Comment by seanluyk** [comment]
This is not working correctly:
-Only results from books and more are appearing
-Only 26 results are returned, but a NEOS search returns 44

**Comment by redlibrarian** [comment]
There's a larger issue right now which is that advanced search is broken. See #719.

**Comment by redlibrarian** [comment]
@seanluyk Can you check this - advanced search for transhumance now returns 48 results.

**Comment by seanluyk** [comment]
This is fixed. Closing.
