### ISSUE TITLE
Indexing and retrieval by publisher

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#639]
Is publisher information indexed and retrievable? If it is, it doesn't look like it's working.

Here's what I did:

1. Searched for Henle in both simple and advanced searches, no limits
2. Selected books and more
2. Limited to music scores

Only 2 results were returned, but we've got hundreds of scores by this publisher. 

Could it have something to do with the fact that the publisher name in full is G. Henle Verlag, or some variation of this? If so, there's an issue with retrieval in that it's not searching within individual strings. 

In some disciplines (music included), being able to distinguish items by publisher is extremely important. It doesn't need to be facet-able, but keyword searches should still return results.

**Comment by redlibrarian** [comment]
Hi @seanluyk You're right, the publisher name wasn't set as searchable (due to the fact that publisher isn't an out-of-the-box Blacklight field; I added it to display, but forgot to add it to search). It's added to the index configuration, so you should be able to search by publisher in the next but one release (our sysadmin is currently pushing yesterday's release through).

**Comment by seanluyk** [comment]
Excellent, thanks @redlibrarian  I'll check it out two releases from now.

**Comment by theLinkResolver** [comment]
Just to double check due to some changes in MARC... @redlibrarian are both the 260 and 264 fields on equal footing in this regard (present and searchable)?

**Comment by redlibrarian** [comment]
@theLinkResolver No, it looks like only the 260 is being indexed. I'll add the 264. I assume it's subfield a, like the 260?

**Comment by redlibrarian** [comment]
(Correction, I'm also indexing the 260b for publisher name. Should that include 264b as well?

**Comment by theLinkResolver** [comment]
@redlibrarian To sum up -- 260 $b and 264 $b both describe publisher name: each record will have one or the other (not both), and all should be indexed.  260 $a and 264 $a have the place of publication.  While we're at it: if you are using 260 $c anywhere for date information, you should also use 264 $c the same way.

(Historical context: 260 is an older practice; 264 started to be used in its place for the last few years and has the ability to distinguish between publishing functions.)

**Comment by redlibrarian** [comment]
OK, thanks. I've added the 264$a and $b. The $c is a little trickier, as the date is handled by a custom Java program, but I'll see what I can do...

**Comment by seanluyk** [comment]
This does not appear to be working, but does show some improvement (45 results instead of 2 for search for *Henle*, although there should be many more results).

However, it's also spawned two new issues, #653 and #654 which makes me think that something broke in the latest release

**Comment by redlibrarian** [comment]
I'm now getting 583 scores for "Henle". @seanluyk does this look better? https://search.library.ualberta.ca/symphony?utf8=%3F&q=Henle

**Comment by seanluyk** [comment]
This is working really well, only 2 fewer results in Blacklight when I limit to musical score and compare results with iLink. Verified with some other publisher searches, so closing this issue
