### ISSUE TITLE
Picky issue - labeling and case

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#640]
1. Sorry, this is really picky, but I've noticed that location/status labels are lowercase instead of Title Case. For example:
-on shelf instead of On Shelf
-music score instead of Music Score
-book instead of Book, etc.

For some reason lowercase labelling comes off as sloppy to me, I'm not sure why.

2. Also, in the record view, we refer to material types as **item type** and in the results view, the **Format** facet. These two labels should probably match, the latter being preferable (or a better alternative).

3. Also, there's a mismatch between the item type labels and how these are labelled in the format facet. For example:

Record View Label | Results View Label
------------ | -------------
music score | Musical Score
music sound recording | Musical Recording
electronic resource | Sound Recording

**Comment by redlibrarian** [comment]
@nnunn I used lower case I think without consulting you. Can you take a look at this and decide what the best fit is, and what we'll need to do to make labeling consistent? Thanks.

**Comment by theLinkResolver** [comment]
I've moved the second part of this issue to #642 and will address it there (to some degree).

**Comment by seanluyk** [comment]
Not sure if this was resolved. Is it something I should check in the next release?

**Comment by nnunn** [comment]
This is fixed and should be up with the next release.

**Comment by seanluyk** [comment]
Re-opening so I can check this in the next release.

**Comment by seanluyk** [comment]
Looks great! OCD crisis averted, closing issue!
