### ISSUE TITLE
Map or Globe format

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#641]
Just encountered this while investigating #640. The occasional music score, recording, and book is incorrectly being labeled in the format facet as a *Map or Globe*. I see in the GMD that *cartographic material* is applied, which is an error in the catalogue records, and odd as the GMD does not match the material type in the item record:
![2015-10-16_16-01-25](https://cloud.githubusercontent.com/assets/14880206/10554273/3fcd00aa-741f-11e5-84bf-fbcda95937ee.jpg)
Here are some examples:
1. https://search.library.ualberta.ca/catalog/829666
2. https://search.library.ualberta.ca/catalog/2202999
3. https://search.library.ualberta.ca/catalog/1674669
4. https://search.library.ualberta.ca/catalog/45369

This looks to be an issue with the underlying data, but the facets expose these erros so it should probably be fixed.

**Comment by redlibrarian** [comment]
@theLinkResolver Can you take a look at this and let me know if this is fixable via mapping, or whether a project to correct the underlying data is required?

**Comment by theLinkResolver** [comment]
Great finds @seanluyk !  These records contain a coding error and the GMD got applied to them (based on the wrong coding) during a major automated cleanup project late last year.  I will arrange for the appropriate corrections.

**Comment by theLinkResolver** [comment]
The errors in these bib records are now in the queue to be fixed, and the changes will subsequently appear in the Blacklight results. As this is not a Blacklight problem, I am closing the issue.
