### ISSUE TITLE
Item type vs. format, and terminology used

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#642]
Separated from #640 ( submitted by @seanluyk )

Also, in the record view, we refer to material types as item type and in the results view, the Format facet. These two labels should probably match, the latter being preferable (or a better alternative).

Also, there's a mismatch between the item type labels and how these are labelled in the format facet. For example:

Record View Label 	Results View Label
music score 	Musical Score
music sound recording 	Musical Recording
electronic resource 	Sound Recording

**Comment by theLinkResolver** [comment]
@seanluyk I think this is a cataloguing question.

The results view shows us the "format" which is mapped from both the characteristics of the content and the bibliographic level (basically, monograph vs. serial).  This matches the "format" field as shown in the record view.  (I am working on getting more of these mapped out, and improving on the out-of-the-box terminology [issue #544 and elsewhere].)

"Item type" as it is displayed in the items table is an attribute of each individual item.  It has more to do with the medium or carrier of the content (e.g. microform, e-resource), although in practice the item type determines the loan period, which will trump the terms describing medium/carrier.  For example, the item type "No loan" is assigned to items residing in non-circulating locations (e.g. Reference, Special Collections) as well as items with circulation restrictions (e.g. certain gifted materials).  "Media" could be a disc that supplements a book (i.e. format field for the record=book).

All that is to say that the "item type" will not be a match of the "format".  That said, those little differences you described (music score vs. Musical Score) can be looked at in a later phase.

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver .

You're right that the item table doesn't use the MARC bib record data. It uses Symphony specific status/location strings. These currently default to what they are in the catalogue, but they can be changed. You can take a look at these two files for the current mapping - be warned though that the Symphony logic is inconistent:

https://github.com/ualbertalib/discovery/blob/master/config/statuses.yml
https://github.com/ualbertalib/discovery/blob/master/config/item_types.yml

If it would make sense to change these to make things clearer, more consistent, I think we can go ahead and do that. I can run it by Sandra first, to make sure. Let me know if you think that will help.

**Comment by seanluyk** [comment]
Thanks, @theLinkResolver and @redlibrarian. I think making them consistent would be a big improvement over iLink, and if it's not too much work to implement, I'd say it's worth it. 

However, you reminded me that things like no loan are there, which really are not item types, but refer to circ rules. I guess we're stuck with these unfortunately, but could make the ones that are item types match.

**Comment by redlibrarian** [comment]
Yeah, that's a limitation of Symphony, I'm afraid (mixing status, type, sometimes location, etc). But we'll do what we can to make it more consistent.

**Comment by redlibrarian** [comment]
I'm going to reassign this issue to the January-April milestone, as I don't think we have time to get to the bottom of this before the end of November.

**Comment by redlibrarian** [comment]
@theLinkResolver @seanluyk Not sure what we had decided to to here. Does this need to go back to the group for any discussion?

**Comment by theLinkResolver** [comment]
@redlibrarian @seanluyk I think the idea was that, any time there is an "item type" term that closely resembles a "format" term, we should try to get the two to match. I can look at this.

**Comment by theLinkResolver** [comment]
@redlibrarian The only two changes we can make [here](https://github.com/ualbertalib/discovery/blob/master/config/item_types.yml) are:

musicscore: music score ---- change to musical score
musicsound: music sound recording ---- change to musical recording

**Comment by redlibrarian** [comment]
Done. This will be in the next release.

**Comment by theLinkResolver** [comment]
Done; closing
