### ISSUE TITLE
My account links and renewals listing

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#643]
Hi. I just renewed some books by going from the big My Account link on the main page of the new website. That worked well.

The My Account tab at the top of the search results screens (bento box screen and detailed listings screens) and the Advanced Search screen simply takes you back to the main page of the website, not to the login page for My Account.

In the My Account screen, would it be possible for the default listing for checkouts to be in chronological order by due date? It's good that the feature is there to list them by due date, but it would be ideal for this to be the default.

**Comment by redlibrarian** [comment]
The first of these issues is for @nnunn (webpage fix). 

The second is for @jhennig .

**Comment by jhennig** [comment]
I have this fixed in myaccount on test.  Once the holds url is changes on the new website I can have this pushed to production.

**Comment by jhennig** [comment]
This is now in production.
