### ISSUE TITLE
856 lacking $3 results in tiny, empty button as link to e-resource

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#644]
See http://search.library.ualberta.ca/catalog/2373386

This is a data/cataloguing problem, where the 856 only has the URL in $u and is lacking a $3 with the library and coverage statement.  Unfortunately, I'm quite certain that there are lots of records like this.  (I've been fixing the serials as of late in relation to another project).

@sjshores This is yet another cleanup project.  A search for (http or https or ftp) not (access or cover or table or description) {856} gives us over 14,000 results.  Some of these are okay, as the 856 does contain a $3 with some sort of textual information (I tried to filter out some of the common ones, like "table of contents").  Jim could probably produce a list of records containing 856s that lack $3 contents, and those would be the ones to work on.

@redlibrarian Just to log an interim solution, I guess you could program Blacklight to display some generic text (e.g. "Link") when there is no data in 856 $3.

**Comment by sjshores** [comment]
Scott, Jim should be able to produce such a report, where there is no data
in the |3 subfield, but I also like Sam's suggestion of adding a word like
Link.

Sandra

**Comment by redlibrarian** [comment]
I've added default text that should work.

**Comment by theLinkResolver** [comment]
Looks good; closing
