### ISSUE TITLE
Call numbers not displayed

### ISSUE THREAD

**Issue by dmc2** [ualbertalib/discovery#645]
Searched for learning styles and looking through the eBooks and more results - when click on more button the call numbers aren't displaying
![callnumbers](https://cloud.githubusercontent.com/assets/14880806/10589976/92b931e6-766b-11e5-9597-20d68e686239.png)

**Comment by redlibrarian** [comment]
I'm actually going to remove the call number functionality from this result page. As per @theLinkResolver, in a large, multi-institution system like NEOS, it's almost impossible to determine which call number to display when you only want to display one. The clearest information is in the item table, so for now that's the place to get the call number from....
