### ISSUE TITLE
Chat widget

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#647]
The new chat widget popped up on my screen (it's swell!) but the "No Thanks" button didn't work, that is, didn't close the pop up when I clicked it. The x in the corner worked though.

**Comment by nnunn** [comment]
I'm not actually sure where this is.

**Comment by redlibrarian** [comment]
@kgood - I can't remember where we put it. I think it's just in the CMS
pages, no?

On Tue, Nov 10, 2015 at 1:30 PM, Natasha Nunn <notifications@github.com>
wrote:

> I'm not actually sure where this is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/647#issuecomment-155556595>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by kgood** [comment]
UI Issues with Chat box were resolved.
