### ISSUE TITLE
Opening new utilities, ie: RefWorks, Ask Us makes you lose your search screen

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#650]
When you export to RefWorks, the Refworks window opens in place of the search screen and you lose your search. Can it open in a new window? the Export to RefWorks function appeared to work well.  

It's the same when you click on Ask Us -- the window opens on top of the search page and you lose your search. This would not work for someone who was trying to receive help by chat, who needs to chat and see the search results at the same time

**Comment by redlibrarian** [comment]
@linds37 When I click on Export to RefWorks, it opens in a new window. This should be true for all browsers, but can you tell me which browser you're using?

As for the Ask Us window, yes, that can be made to open in a new window. @nnunn I think this needs to be done in the CMS?
