### ISSUE TITLE
Suggestion: Using EDS advanced search as default advanced search

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#651]
A colleague suggested this and I thought I would pass it along in case others want to comment on it. 

The argument was, since Articles aren't searchable via Blacklight advanced search (and makes necessary both an EDS advanced search for articles and Blacklight for everything else), why not just use EDS as the default advanced search? 

That being said, the EDS advanced search would not search 'everything' either. The database list, and down the line ERA or web pages, comes to mind.

**Comment by redlibrarian** [comment]
Yeah, I think the big downside would be that as we add more and more content to Blacklight that's not searchable in EDS, the advanced search would become less useful. 

I **actually** think that we'll find advanced search not being used very much, except by staff. If we make simple search work, then advanced search should be more or less a non-issue.

**Comment by redlibrarian** [comment]
@gooyers Given my response above, we can either close this issue and reopen it if the question comes up again, or we can move the question to the January - April milestone for more discussion. We won't make this change for the January release, it think. What do you think?

**Comment by gooyers** [comment]
I agree that ideally, an optimized simple search should limit the need for high usage of advanced search. And I agree that EDS is less than ideal as we add more content only searchable by Blacklight.

That being said, as it currently exists, Blacklight advanced search may be used fairly frequently for known item searches. In usability testing, users tend to click into advanced search when they're looking for something by title, or author names, as they don't see those as choices within the initial simple search box. 

I can close this issue though, as I just wanted to present the possibility for discussion. What we do with advanced search can be determined out of WAT/this subgroup discussion, or it could wait until the January-April milestone.
