### ISSUE TITLE
Links to Databases appear to be broken

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#652]
1. Searched for a database (Music Industry Data)

2. Clicked on link from databases container

**Result**: "we're sorry, something has gone wrong"

-Tried this with a few other databases and experience the same issue.

**Comment by seanluyk** [comment]
Noticed another twist to this issue...some of the items in a database query point to random records: https://search.library.ualberta.ca/databases?utf8=%3F&q=music

This is not happening consistently, but clicking on the odd item points to the wrong record.

**Comment by theLinkResolver** [comment]
@redlibrarian The second issue here sounds like the "ID collision" you described in #616 (to be fixed with #498).

**Comment by redlibrarian** [comment]
There was a bug in the database display code. This should be fixed in the next release.

**Comment by seanluyk** [comment]
The issue of "we're sorry, something has gone wrong" seems to have been fixed, but ID collision, related to #616 does not. Closing this issue.
