### ISSUE TITLE
SFX link display

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#655]
I don't recall seeing this last time, so something has changed:

*The University of Alberta access link in journal records are appearing in full, instead of as linked text

For example:
1. [This record](https://search.library.ualberta.ca/catalog/395190), and
2. [This record](https://search.library.ualberta.ca/catalog/531662)

**Comment by redlibrarian** [comment]
I can't remember if this was a design/accessibility decision. @nnunn can you remind me? Is there a reason to display the URL along with the label. If not, we can hide it.

**Comment by redlibrarian** [comment]
I noticed that, when a URL points to SFX (resolver.library...) the box gets extremely large and unpleasant. As a result, I've removed the URL text from the main UA Access box (below the title - see next release). We should reevaluate the secondary link boxes when this change is in place.

**Comment by redlibrarian** [comment]
@seanluyk @theLinkResolver Neither of the records identified at the top of the issue have any electronic access. I assume the print and e- versions of this item have been separated. In any case, the issue with links should be fixed now.

**Comment by seanluyk** [comment]
Looks like the records have been split, @redlibrarian . Noticed some other issues along the way, so I'll report them separately

**Comment by theLinkResolver** [comment]
@redlibrarian correct, re. the split of print and electronic serial records. there are now just a relative handful of NEOS library and free holdings attached to print records, which will take a few months to deal with.

**Comment by dmc2** [comment]
Looking for SPECK kit see https://search.library.ualberta.ca/catalog/6867610 and there is no access to the e-version, and after clicking on UofA access button and then choosing the Library catalogue there appears to be a SFX issue see the image. Hoping this can be fixed :) 
![spec error](https://cloud.githubusercontent.com/assets/14880806/11695489/b36a2d2c-9e6c-11e5-84d6-f2caea92fb99.jpg)

**Comment by redlibrarian** [comment]
I'm not getting the Software Error message - not sure why that's coming up. However, in the classic catalogue, clicking on the UA Access link also provides no access, so this needs to be reported to cataloguing corrections...

**Comment by dmc2** [comment]
I had to unblock the message and then I saw the message

Diane Clark, MLIS, MEd | Staff Development & Training Librarian,
Agriculture, Food & Nutritional Science Librarian | University of Alberta
Libraries | 4-40B Cameron Library | University of Alberta | Edmonton,
Alberta T6G 2J8 | p: 780.492.9364 | e: diane.clark@ualberta.ca

**Comment by redlibrarian** [comment]
@dmc2 Has it happened more than once? I'm not getting an error at all.

**Comment by theLinkResolver** [comment]
@redlibrarian @dmc2 Got the helpdesk ticket and removed the link from our record, as we don't subscribe to the online version. We do have a current subscription to the print version. (I have sent a note to Acquisitions querying this title, as the online version would probably be preferred... unless there is already some reason on file as to why the online version is inadequate.)

@redlibrarian I'm pleased to see that, as soon as I marked the item as a discard and removed the 856 and MARC holdings, our access disappeared. I didn't expect our link to go away, to be honest. Is that because you are pulling it from the MARC holdings instead of the 856?

**Comment by redlibrarian** [comment]
@theLinkResolver It's coming from the 856, but it's being looked up live against the Symphony API.

**Comment by theLinkResolver** [comment]
@redlibrarian That is terrific - I must admit I was concerned about deleted and broken links sitting around for 1-2 days after we correct them, but the live lookup solves that!
