### ISSUE TITLE
Back button and clicking on a record

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#656]
This is a new one, and I have no idea if it's machine specific or not, so perhaps some others could test.

From the results view:
1. Click on a record
2. Click your browser back button
3. Click on another record

Result: the occasional "we're sorry" page, but clicking the record again works.

**Comment by seanluyk** [comment]
If it helps, this is one of the URLs that did this :https://search.library.ualberta.ca/catalog/5106396/track?counter=2&search_id=173651

**Comment by gooyers** [comment]
I was able to replicate this issue as well Sean.

It appears that when clicking in from a results page, "/track?counter=2&search_id=173651" is sometimes being added to the URL which returns an error. Without that additional information, the URL's work fine: [https://search.library.ualberta.ca/catalog/5106396](https://search.library.ualberta.ca/catalog/5106396)

**Comment by kgood** [comment]
We had a misconfiguration with one of our servers.  We believe this should now be working.  can you please see if you can recreate it?  I was noticing it yesterday about every 3 or 4th click via the hit list but am not seeing it today since our fix.

**Comment by seanluyk** [comment]
Looks like this has been fixed, closing the issue.
