### ISSUE TITLE
Item notes (from PUBLIC field) not displayed in items table

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#657]
The PUBLIC field in item records is used to hold information on bound volumes that lack certain issues, as well as for items that are bound with other items. It is not presently displayed in Blacklight items tables.

Example from https://search.library.ualberta.ca/catalog/2529824:

In Workflows:
![lacks - sirsi](https://cloud.githubusercontent.com/assets/14913579/10676208/f9c35666-78c1-11e5-9ac0-8d7c59a207bd.jpg)

In iLink:
![lacks - opac](https://cloud.githubusercontent.com/assets/14913579/10676387/0123e6a4-78c3-11e5-80f0-c9e525a57cdf.jpg)

In Blacklight:
![lacks - bl](https://cloud.githubusercontent.com/assets/14913579/10676389/065e95ec-78c3-11e5-9e20-ce31680ba2fa.jpg)

(i.e. There is nothing to tell the user that the volumes are incomplete and may not include the specific issues they are looking for.)

Brief example of "bound with" scenario:

![bound with](https://cloud.githubusercontent.com/assets/14913579/10676277/59634888-78c2-11e5-94e1-a7770a5b4961.jpg)

(i.e. This item does not actually exist. It is a placeholder, to indicate that we have issues belonging to this title but that they are physically with another title - the upshot being that we want the user to place a hold on that other volume, which has a reciprocal note stating "includes v.20: no.9-10 of later title".)

**Comment by redlibrarian** [comment]
@theLinkResolver Can you tell me what field that ends up in in a MARC item or holdings record? I know I added public notes before, so I'm not sure why this one isn't appearing...

**Comment by theLinkResolver** [comment]
@redlibrarian I'm not sure what your item data looks like - maybe you can send me a snippet?  Or I can come look over your shoulder.

**Comment by redlibrarian** [comment]
The item snippet looks like this: 
    <ItemInfo>
    <itemID>0162016255919</itemID>
    <itemTypeID>PERIODICAL</itemTypeID>
    <currentLocationID>ON_SHELF</currentLocationID>
    <homeLocationID>ON_SHELF</homeLocationID>
    <chargeable>true</chargeable>
    <fixedTimeBooking>false</fixedTimeBooking>
    <publicNote># bound with earlier title</publicNote>
    </ItemInfo>

I think what's happening is that I wrote in logic to handle the public note if it made something unavailable. This isn't the right logic, I guess. I'll fix it.

**Comment by redlibrarian** [comment]
OK, I think this is fixed now, @theLinkResolver

**Comment by theLinkResolver** [comment]
This looks great! Closing
