### ISSUE TITLE
Placing hold not working

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#660]
I'm on my iPad trying to place a hold. It keeps saying "Cat key not specified", and won't place the hold. I tried on more than one book.

**Comment by fculpepper** [comment]
I'm getting the same error. But when I first try to place the hold I get this screen:
![image](https://cloud.githubusercontent.com/assets/14892870/10735335/161c31a8-7bcd-11e5-988a-6ca340892ebe.png)
Then I click the start new session link and it takes me to my account. I have to go from there to Search & Home to redo my search (this takes me to the current site, by the by). Once I've gotten back to the record and try to place the hold, I get the cat key error Lindsay describes.

**Comment by fculpepper** [comment]
Sorry, hit the close & comment button by mistake :/

**Comment by seanluyk** [comment]
I experienced the same issue as @fculpepper . This wasn't occuring before the latest release, so something's up!

**Comment by kgood** [comment]
I can confirm that this (holds) is broken.  We are investigating.

**Comment by redlibrarian** [comment]
@jhennig The link I'm using for people to place holds is e.g. https://myaccount.library.ualberta.ca/createholds.php?hldCatKey=531662

Does this look right? Or have I messed something up?

**Comment by jhennig** [comment]
Fixed with myaccount upgrade.

**Comment by linds37** [comment]
I just went through the holds process. It all worked. thanks!

Lindsay Johnston, Public Services Manager & Subject Librarian
Rutherford Humanities & Social Sciences Library
<http://guides.library.ualberta.ca/rutherford> and Weir Law Library
<http://guides.library.ualberta.ca/law>
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta
T6G 2J8
780.492.0598

lindsay.johnston@ualberta.ca
