### ISSUE TITLE
Sequence of links when prompted to login

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#661]
When I try to place a hold, but am not logged in, I get promoted to login, then get taken to My Account, and I lose the screen where I was trying to place the hold. If I try to use the back button, it just keeps asking me if I want to resubmit the form, and will not go back to the screen with the catalogue record on it. This is happening on my iPad.

**Comment by redlibrarian** [comment]
Same issue as #660 . We're investigating with @jhennig
