### ISSUE TITLE
Can't display record

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#662]
I am trying to view the record for Science foundation in China (catkey 5905222), but I just get "something has gone wrong".
 
https://search.library.ualberta.ca/catalog/5905222
 
I was just working on the record (Oct 26) -- my edits:
- added 090 field
- added 506 field
- added 856 field (for UAL access)
- added MARC holdings for UAL
- added item record for UAINTERNET

I had not viewed the record in BL previously. As a test, I removed my edits (just in case the item changes triggered something unexpected), but that made no difference.

**Comment by redlibrarian** [comment]
Fixed bug.

**Comment by redlibrarian** [comment]
@theLinkResolver This problem wasn't due to changes to you made the record, but was a bug in the display logic. It should be fixed in the next release. 

Just FYI, only item and 856 data is looked up live. Other changes aren't visible until a reindex.

**Comment by theLinkResolver** [comment]
Fixed
