### ISSUE TITLE
Availability of items in results view

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#663]
This is possibility duplicated in another issue, but I couldn't find it...

Is it possible to make the availability of items more clear in the results view?

How this is currently configured is that libraries that own the item appear in the **copies available** field in the order that they appear in Symphony, and it doesn't look like all libraries are listed.

I tried an experiement with a book I had checked out. From the screenshot below, it looks like the item is available, but it's actually checked out. 
![2015-10-27_15-04-50](https://cloud.githubusercontent.com/assets/14880206/10772624/aca49d00-7cbc-11e5-8f5a-2267557f660f.jpg)

I've seen some approaches to this in other Blacklight implementations , for example [UVA's Virgo](http://search.lib.virginia.edu/) which handles this a little differently, and may be worth looking it more closely.

**Comment by redlibrarian** [comment]
OK, some of this is a bit weird...

1) Originally, looking up the status of an item wasn't possible, but it is now, so the only question is how best to display it. My concern is that with different call numbers and potentially quite a few locations, that displaying availability here like Virgo does will involved recreating the whole status table, which would take up a lot of space (and potentially be really unusable). It looks like what Virgo does is displays availability when there's a single copy/location, but gives a link to an item table when there's more than one - I don't love that solution. We could, however, filter out checked out copies, or display unavailable locations in red, and available locations in green. Open to suggestions - maybe this should go back to the larger group... 

2) All libraries should be coming through. This looks like it's related to a different problem that I'm chasing down - I have to check with Neil on that...

**Comment by sjshores** [comment]
I'm wondering if we could instead change the phrase "Available at" to
something more accurate like "Held by" or "Owned by".

Sandra

**Comment by redlibrarian** [comment]
@sjshores We can do that easily, if we can agree on a label. Now that we have access to the live status, it might be good to indicate that too...

**Comment by redlibrarian** [comment]
OK, I figured out the problem with the missing locations. Those will be visible in the next release.

**Comment by seanluyk** [comment]
@redlibrarian I think this might be one worth bringing to the larger group for discussion. I think if we can incorporate status into a results view in a useful/clear way, it would be really valuable to users. 

If not, I like @sjshores' suggestion.

**Comment by redlibrarian** [comment]
I think this will need to be left until January to discuss. IMO, the results table on the record view is the only full/authoritative list of holdings.
