### ISSUE TITLE
Link to UofA Archives

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#665]
Can we add a link to [Archives] (http://www.library.ualberta.ca/aboutus/archives/) in either the Services section or the Library Locations & Hours section? Or maybe a link to [the location & hours page] (http://www.library.ualberta.ca/aboutus/archives/) in the Hours section and a link to their [webpage] (http://archives.library.ualberta.ca/) in Services?

**Comment by kgood** [comment]
Archives was added to hours application and is also found on special collections web site
