### ISSUE TITLE
Error Handling for SFX Outage

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#666]
The same type of "generic error" message is displayed for ejournal records when the SFX API is unavailable.  Is there a way to improve this to still display the record but indicate the access is temporarily unavailable.

**Comment by redlibrarian** [comment]
See issue #664

**Comment by pgwillia** [comment]
@redlibrarian can you give me an example of a record that calls the SFX API?

**Comment by redlibrarian** [comment]
Here's an example: https://search.library.ualberta.ca/catalog/1000000000393939 

The SFX service provides the content in the grey "subscription" box. 

In your dev environment, if you delete everything from your local solr instance, then rune **rake ingest[sfx_test-set]** you'll get some sample SFX records, and they'll be the only things in your index (if that helps at all).
