### ISSUE TITLE
Strategy for Robots.txt 

### ISSUE THREAD

**Issue by kgood** [ualbertalib/discovery#667]
Need to come up with strategy for what will be in our robots.txt file.  Do we allow indexing of everything?  Will this cause performance issues?   Hydranorth is working on this as well.

**Comment by kgood** [comment]
Stanford - https://searchworks.stanford.edu/robots.txt
Columbia - https://clio.columbia.edu/robots.txt
Cornell - https://search.library.cornell.edu/robots.txt
Virginia - https://search.lib.virginia.edu/robots.txt

So only Virginia has done significant modification.

**Comment by redlibrarian** [comment]
@kgood @pbinkley Still outstanding?
