### ISSUE TITLE
Location GOV_INFO displays as blank

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#669]
e.g. https://search.library.ualberta.ca/catalog/2887635

@redlibrarian I presume it just needs to be added here: https://github.com/ualbertalib/discovery/blob/master/config/statuses.yml

**Comment by merisjames** [comment]
That's a new location, so not surprised it's not showing up!

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca

**Comment by redlibrarian** [comment]
@theLinkResolver yes, you're right. I've added the new location to the statuses file. We'll have to have some way to keep on top of these after we launch (internal ITS procedure).

**Comment by theLinkResolver** [comment]
still blank.

**Comment by redlibrarian** [comment]
Gah. Stupid mistake. Should be fixed in next release.

**Comment by redlibrarian** [comment]
Fixed now.
