### ISSUE TITLE
Multiple copies (items) under one call number not displayed

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#672]
In the items table, when we have multiple copies of something under one call number, we are only seeing one copy.  example record: https://search.library.ualberta.ca/catalog/3064619

In Workflows, we see one copy at BARD and two copies at Health Sciences. Copy 1 is non-circulating (in their rare book room) and copy 2 is available in the stacks:
![wf 2 copies](https://cloud.githubusercontent.com/assets/14913579/10851226/7e182d64-7eef-11e5-9e6c-0fa1af869443.jpg)

In Blacklight, we only see one of the copies at Health Sciences - in this case, the non-circulating copy. The user does not see the other (circulating) copy at Health Sciences:
![bl 2 copies](https://cloud.githubusercontent.com/assets/14913579/10851252/ba39f96c-7eef-11e5-951c-0d6b39c9d9f3.jpg)

**Comment by redlibrarian** [comment]
Hm. This might have something to do with the XML parsing. I'll look into it.

**Comment by redlibrarian** [comment]
OK. I see what the problem is. Working on it now.

**Comment by redlibrarian** [comment]
@theLinkResolver @sjshores Do we need the "Number of Copies" information in the holdings table. It doesn't seem to add much.

**Comment by theLinkResolver** [comment]
@redlibrarian Mostly a function of inventory, but there are lots of instances where our local note (590) references a specific copy.

e.g. https://search.library.ualberta.ca/catalog/833532
https://search.library.ualberta.ca/catalog/844363

**Comment by redlibrarian** [comment]
Hm. Except that the "number of copies" data reports the **number** of copies, not which copy is which... @theLinkResolver

**Comment by redlibrarian** [comment]
So, for example in the https://search.library.ualberta.ca/catalog/833532 example, the 2 BARD copies will each have "2" under "Copy" when this issue is fixed. I thought the data showed the copy number too, which is why the label is "Copy", but now that I've fixed this problem in dev, I see that it does not. If there are 2 copies at a location, that field will read "2" for both copies... @theLinkResolver

**Comment by theLinkResolver** [comment]
@redlibrarian can you send me an example of the data? to make sure I get what you're talking about

**Comment by theLinkResolver** [comment]
@redlibrarian Oh, that is not helpful. The presence of two item lines should suffice in that regard.

**Comment by redlibrarian** [comment]
Here's the web services data for "Beyond the Bricks": https://ws.library.ualberta.ca/symws3/rest/standard/lookupTitleInfo?clientID=Primo&marcEntryFilter=ALL&includeItemInfo=true&includeMarcHoldings&titleID=3064619&includeAvailabilityInfo=true

You'll see that "numberOfCopies" is in the "CallInfo" ZML stanza, not the "ItemInfo" stanza. There's nothing to indicate which of the two UAHLTHSC items is "copy 1" or "copy 2". They each inherit the "numberOfCopies" information from the "CallInfo" data. @theLinkResolver

**Comment by redlibrarian** [comment]
@theLinkResolver I think seeing all three copies is useful, for transparency's sake. I think, though, that it makes the "Copy" field in the item table redundant, if not actually confusing... I think we should just remove it, since now we can see all copies... @sjshores

**Comment by theLinkResolver** [comment]
@redlibrarian That's right, seeing all three - with their own statuses and shelving locations - is the key. Too bad that the copy number is not available, to correspond to those local notes, but that is a fairly specialized use case and we hope the user would ask for assistance in tracking down a particular copy, if they needed to (they can't distinguish between copies when placing a hold, as it is).

In the item table, since you've shown that all the "copy" field does is total the number of copies for that location, I agree that it is redundant and potentially confusing, once your fix is in place.

**Comment by redlibrarian** [comment]
OK. I've removed the "Copy" field. Please check this in the next release and let me know what you think. @theLinkResolver

**Comment by redlibrarian** [comment]
@theLinkResolver Can you take a look - I think this is fixed now.

**Comment by theLinkResolver** [comment]
fixed
