### ISSUE TITLE
Include Call Number in Book Mark information

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#673]
Some people might like to bookmark books in the catalogue and then email a list to themselves so they can go and retrieve them off the shelf. I tested this today and it sent me links - ideally it would be nice if the info sent included call number so you don't have to click on each link to find out where to find it. More of a luxury request than a necessity.

**Comment by redlibrarian** [comment]
I'm starting to think including a "generic" call number is going to be a problem. @theLinkResolver and I have kicked it around, and there isn't a single call number that will generally work for something in the catalogue. I'll have to think about this one. I'm going to set it to the next milestone.

**Comment by redlibrarian** [comment]
I'm going to close this for now. If it becomes an issue reported by users we can look at it again.
