### ISSUE TITLE
Missing item showing up in search

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#678]
The record for this missing item, [Real analysis: modern techniques and their applications] (https://search.library.ualberta.ca/catalog/1746053), is displaying but without any items attached. It's not in EDS or NEOS and in WorkFlows it appears it was set to Missing in February (Last Activity Date):
![image](https://cloud.githubusercontent.com/assets/14892870/10859842/103902e0-7f27-11e5-8d78-ac27e64662f3.png)
Does this have to do with how frequently Blacklight is updated? If so, could it happen more frequently?

**Comment by redlibrarian** [comment]
Thanks @fculpepper - Blacklight is supposed to get updated nightly, but I think that this isn't happening. We're currently investigating with the sysadmins to find out why not, but missing/lost/otherwise suppressed records shouldn't appear.

**Comment by redlibrarian** [comment]
This is definitely due to the problem of the periodic reindexing not taking place. I'm going to close this ticket, as I'll be watching the problem in issue #685
