### ISSUE TITLE
Exclude Symphony content from EDS pane.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#681]

**Comment by theLinkResolver** [comment]
@redlibrarian done, right?

**Comment by redlibrarian** [comment]
Yes.

On Fri, Feb 26, 2016 at 1:22 PM, Scott Davies <notifications@github.com>
wrote:

> @redlibrarian <https://github.com/redlibrarian> done, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/681#issuecomment-189467431>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB
