### ISSUE TITLE
Exclude Symphony e-journal records from Journals pane.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#682]

**Comment by redlibrarian** [comment]
I've added labeling to make navigating these records easier until we can get this in place. See #774.

**Comment by theLinkResolver** [comment]
@redlibrarian @sjshores Here's a "what if"... and I sense that this would potentially be very complex to implement, so I'm thinking long-term, if at all... what if there was a way to patch together the bibliographic data from a Symphony e-journal record (with an SFX object ID in the 940) with the corresponding SFX holdings data and display it as a single record. So we could reap the benefits from our Symphony e-journal records, which generally have better and more flexible metadata, while also making use of the simulated Get It window that has been developed for the SFX e-journal records.

**Comment by redlibrarian** [comment]
@theLinkResolver @sjshores Since we have the Object ID in all equivalent records, this would be easy enough to do.

**Comment by sjshores** [comment]
Good idea then, but I would want the links to appear in a normal browser
window without having to scroll down to get them.

This would, I assume, also have the benefit of eliminating duplicate
Symphony and SFX records for the same journal.

Great idea.

Sandra

**Comment by redlibrarian** [comment]
Yes, we would likely position the e-holdings/sfx box above the print holdings (since e-preferred, etc). We could also look into collapsing the print holdings box to save space. 

I think that if we were just talking about **journals** from SFX, then we could get rid of the SFX ingestion process altogether. But we still need to figure out how to deal with non **journal** SFX material (which is currently not coming through into Blacklight).

**Comment by sjshores** [comment]
And, we have far more journals activated in SFX than catalogued in Symphony.

Sandra

**Comment by redlibrarian** [comment]
Oh right. That complicates things a little. Then we're back to deduplicating...

**Comment by redlibrarian** [comment]
We're looking at deduplication in issue #900
