### ISSUE TITLE
View all Books and more error

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#688]
When you click on the View all Books and more button from the result pane, you get this:
![image](https://cloud.githubusercontent.com/assets/14892870/10946002/2ce9f534-82dd-11e5-8fe8-33b59df8b2c7.png)

**Comment by redlibrarian** [comment]
@fculpepper Can you try clearing your browser cache and try again - it should work.

**Comment by fculpepper** [comment]
Sorry @redlibrarian, cache cleared, still happening.

**Comment by redlibrarian** [comment]
Weird. @ualbertalib/discovery-testing is anyone else having this problem?

**Comment by merisjames** [comment]
I just got the same result (no result) for the same search.

Tried a couple other searches as well, same no result.

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca

**Comment by scastell** [comment]
4:10 pm - just happened to me as well. Different search terms but same result.

**Comment by redlibrarian** [comment]
@ualbertalib/discovery-testing Does it happen both when you click on both the "X results" link at the top of the box, and the "View all Books..." link at the bottom? I can see a problem with the bottom link, but the top link continues to work fine for me... I'm having trouble tracking down where the problem might be.

**Comment by scastell** [comment]
In my case, just the bottom link. "x results" link works.

**Comment by redlibrarian** [comment]
@scastell Thanks.

**Comment by redlibrarian** [comment]
@fculpepper Is this fixed now? It should have been in a fix we put through yesterday.

**Comment by fculpepper** [comment]
Fixed!
