### ISSUE TITLE
Advanced author search irrelevant results

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#689]
Had to do some author searching this morning and ran into this. Not sure if this is related to the latest release but I have tested it at my workstation and on the desk. 

I did a search for Tove Jansson in basic search and got an error. So then I searched for Tove Jansson (Author name) in advanced search I got a bunch of strange results that do not seem relevant. 
![2015-11-04_9-58-34](https://cloud.githubusercontent.com/assets/14892833/10945596/671f58d6-82db-11e5-8c46-959bb6a319fd.jpg)

Rebooted browser and redid basic search. Worked this time and results were promising. 

![2015-11-04_10-00-57](https://cloud.githubusercontent.com/assets/14892833/10945655/b0e15cd0-82db-11e5-82f9-ad7dd86ec106.jpg)

View all books gave me an error message. I have to click on the 39 results link to view all titles.

There are 27 titles with this author in the NEOS catalogue. 

![2015-11-04_10-10-17](https://cloud.githubusercontent.com/assets/14892833/10945810/50c9dbd2-82dc-11e5-815f-46b29ab5adae.jpg)

So basic search is better, advanced search is broken (confirmed by searching Doctor Seuss to the same results) -- and bento box is glitchy (can start a separate issue for that if you like).

**Comment by fculpepper** [comment]
I'm getting the same 5,691,190 results as Hanne's first screen shot no matter which field I try to search in the Advanced search

**Comment by gooyers** [comment]
I received the same results. It seems the latest code release temporarily broke something in the advanced search

**Comment by redlibrarian** [comment]
See #719

**Comment by redlibrarian** [comment]
This should be working now. Please check.

**Comment by hannepearce** [comment]
Tested this with numerous authors and it appears to be working well. :)

**Comment by redlibrarian** [comment]
Great, thanks!
