### ISSUE TITLE
Different number of results, bento vs results page

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#690]
This is happening with all of the searches I've tried:
![image](https://cloud.githubusercontent.com/assets/14892870/10948897/4fda7d2e-82ed-11e5-8a9c-0482087a8d4d.png)

Click on "48 results" and now it's only 43:
![image](https://cloud.githubusercontent.com/assets/14892870/10948928/7706b7dc-82ed-11e5-863c-c66c86cfcd74.png)

**Comment by merisjames** [comment]
I think that perhaps whatever is going on here might also be manifesting in an issue I'm seeing... The "x results for searchstring" is consistently a larger number than the result of adding up all the individual bento box totals.

**Comment by redlibrarian** [comment]
OK, there were some discrepancies in how the total result set was being calculated. This should work now. In bento, **protoplasm** returns 47 Books, media, and more, and 6311 Articles, Ebooks and more, and the total result count is 6358, which I think is correct. Clicking through to each of the panes gives 47 and 6311 results, respectively. So this seems to be working.

**Comment by redlibrarian** [comment]
@fculpepper Can you confirm whether this is working to your satisfaction?

**Comment by fculpepper** [comment]
Yes, it's working. Huzzah!
