### ISSUE TITLE
Can the links be bigger, brighter, more apparent?

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#698]
Feedback from some staff is that the links in the records are difficult to differentiate from the other text. Specifically, the subject headings, it's hard to tell they're links when hovering because the font is small and the difference between the blue and green is not very apparent. Also, in journal records it's not obvious that the names of various databases are the links as the green is not different enough from the other black text. One comment was that users may not understand what they are suppose to click in order to access the journal.
The folks giving the feedback agreed that something like the Tools menu where the space around the link highlights would be better. Or if the link underlined or was just a more different colour when hovering.

**Comment by seanluyk** [comment]
I've heard this feedback as well
