### ISSUE TITLE
No results after clicking on results list from Bento box display

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#703]
1. Searched for 0043-8774
2. Clicked on Journal results (the numbered results; same result from "View All Electronic Journals")
3. Resulted in "no results found for your search"

Although the use case (searching for a journal by ISSN) is limited, I think the issue is part of a different problem, and is new.

**Comment by redlibrarian** [comment]
This was an oversight (ISSNs should have been indexed from the beginning). I've fixed it in the Solr config, so it should be working in next week's release.

**Comment by redlibrarian** [comment]
This fix doesn't seem to have made it into the current release.

**Comment by redlibrarian** [comment]
@seanluyk  Should be fixed now.

**Comment by seanluyk** [comment]
Fixed, closing issue
