### ISSUE TITLE
add "general note" portfolio text to e-journal display

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#704]
We use the "general note" field in SFX to advise users of outages and to provide access instructions, if needed. (It displays text on a separate line in the Get it window.) This text needs to be displayed in the e-journal records.

e.g.  Catalysis today [0920-5861]
![get in cat](https://cloud.githubusercontent.com/assets/14913579/11071778/ce034ecc-879f-11e5-8780-b654d6f06b16.jpg)
![get it bl](https://cloud.githubusercontent.com/assets/14913579/11071786/d6231c9a-879f-11e5-89c9-92c32ec4be55.jpg)

**Comment by redlibrarian** [comment]
@theLinkResolver Do you know if that's a MARC field? It's not appearing in our MARC records from SFX. If it's only needed for display (not search) then I should be able to pull it from the SFX API...

**Comment by redlibrarian** [comment]
It's available in the API, so I'll pull it from there. I'll have to get to it later this week. 

http://resolver.library.ualberta.ca/resolver?ctx_enc=info%3Aofi%2Fenc%3AUTF-8&ctx_ver=Z39.88-2004&rfr_id=info%3Asid%2Fualberta.ca%3Aopac&rft.genre=journal&rft.object_id=954925564669&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&url_ctx_fmt=info%%203Aofi%2Ffmt%3Akev%3Amtx%3Actx&url_ver=Z39.88-2004&sfx.response_type=simplexml

**Comment by theLinkResolver** [comment]
@redlibrarian It's portfolio-level data (vs. object/title), so probably not MARC. And yeah, it needs to be a live lookup for display.

**Comment by theLinkResolver** [comment]
What do the public service people think? Do you think this should be a critical/pre-December fix? I feel like my opinion is skewed by my everyday work.

These are the kinds notes that aren't displaying in Blacklight right now (we enter these in response to reported problems) --

![get it instructions](https://cloud.githubusercontent.com/assets/14913579/11309405/f609af0e-8f80-11e5-9c0a-e40cf3bc9d3a.jpg)


![get it problem](https://cloud.githubusercontent.com/assets/14913579/11309457/367c357a-8f81-11e5-9701-797d0d99925d.jpg)

**Comment by redlibrarian** [comment]
What do you think @ualbertalib/discovery-testing ?

This is actually likely an easy fix to make. I can always mark it as medium priority, move it to the September milestone and see if I can get to it....?

**Comment by seanluyk** [comment]
I think if it's an easy fix, it's well worth adding these notes.

**Comment by redlibrarian** [comment]
OK, thanks @seanluyk @theLinkResolver - I still have to look into it. I'll add this to the current milestone and see if I can get to it.

**Comment by redlibrarian** [comment]
OK, @theLinkResolver @seanluyk I've added the general note to the SFX records. Please check in the next release.

**Comment by theLinkResolver** [comment]
@redlibrarian I see the notes.  Can you do anything about the html tags?

e.g. https://search.library.ualberta.ca/catalog/954925402586

**Comment by redlibrarian** [comment]
@theLinkResolver I've fixed the html tags now. That won't be visible this week, but will be before we launch.

**Comment by redlibrarian** [comment]
Actually, this will be ready for this week's release, tomorrow or friday.

**Comment by redlibrarian** [comment]
@theLinkResolver This should be visible now in search-test.

**Comment by theLinkResolver** [comment]
@redlibrarian I am not seeing any SFX results in search-test...? I can wait until Thursday to clear this one.

**Comment by redlibrarian** [comment]
None at all? I see them... @theLinkResolver

**Comment by redlibrarian** [comment]
@theLinkResolver OK, they're there now - our fault.

**Comment by redlibrarian** [comment]
@theLinkResolver Check out https://search-test.library.ualberta.ca/catalog/954925402586

If this looks OK, can we close the issue?

**Comment by theLinkResolver** [comment]
looks clean - closing!
