### ISSUE TITLE
Subject faceting returns results that do not contain the selected subject heading

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#708]
Just stumbled across this one, and I'm not sure if I'm not understanding how this is supposed to work:

1. From [this record](https://search.library.ualberta.ca/catalog/6342850), I clicked on subject heading [Concertos (Clarinet)](https://search.library.ualberta.ca/catalog?utf8=%E2%9C%93&q=Concertos+(Clarinet)&view=brief&search_field=subject)
2. Applied format facet Musical Score
3. Sorted by year
   * [The resulting search](https://search.library.ualberta.ca/catalog?f%5Bformat%5D%5B%5D=Musical+Score&q=Concertos+%28Clarinet%29&search_field=subject&sort=pub_date_sort+desc%2C+title_sort+asc&view=brief)

* Many of the results do not contain this exact subject heading, but instead, a keyword (e.g. Clarinet) within it, or some combination of both (one keyword in one heading, one in another. For example:
   * [This record](https://search.library.ualberta.ca/catalog/5906761) is actually a percussion concerto that uses an sexet that has a part for a clarinetist, but does not have the subject heading **Concertos (Clarinet)** applied to it.

I don't recall experiencing this behaviour before.

**Comment by redlibrarian** [comment]
I think this is because the current functionality does a (keyword) search for the subject terms. We can probably make this a subject search (advanced), but I don't think we'll be able to make it a facet operation, given that we are now combining LCSH terms, while the facets keep them separate. I'll have to dig more deeply into it.

**Comment by theLinkResolver** [comment]
I think the ideal action would be a subject phrase search.

**Comment by seanluyk** [comment]
@redlibrarian @theLinkResolver  - I wonder if this is something worth discussing at our next group meeting? I see how a keyword search for subject terms has its advantages as well. For my music examples, the exact subject heading is the ideal action, but I wonder if this is widely applicable?

**Comment by redlibrarian** [comment]
@seanluyk @theLinkResolver I'm happy to bring this to the wider group for a decision.

**Comment by seanluyk** [comment]
Maybe at our next meeting, @redlibrarian? I'm of two minds on this issue: I like that the top results are likely items that contain the exact subject heading, and for many disciplines, a keyword approach for subjects returns additional relevant items; for disciplines where subject headings are applied to indicate what the item IS (e.g. a clarinet concerto), it becomes less helpful.

**Comment by redlibrarian** [comment]
Closing for now. We can reopen if a problem presents itself.

**Comment by theLinkResolver** [comment]
Where I previously stated that a subject **phrase **search would be ideal, I was quite impressed with the results of a subject keyword search as we saw at today's meeting. Relevance keeps the results we want at the top, while the keyword aspect broadens the search to bring other related materials into view.
