### ISSUE TITLE
Incorrect databases link

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#711]
Could be isolated to LISA, but I'll report any more I come across. Here's what I did:

1. Searched for LISA
2. Clicked on 1 databases result

This brought me to an [empty page with a chat box](http://library.ualberta.ca/databases/databaseinfo/index.cfm?ID=11710963)

The ID is way off for some reason. It should be [this page](https://www.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=3111).

**Comment by seanluyk** [comment]
Doesn't look to be isolated to LISA. Just tried it with [Google Scholar](http://library.ualberta.ca/databases/databaseinfo/index.cfm?ID=9646110) and it's the same issue

**Comment by merisjames** [comment]
Same for Quicklaw, Westlaw and Hein.
Incidentally, the Westlaw entry shows all the markup <br> etc.

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca

**Comment by redlibrarian** [comment]
Oh, I see what the problem is. OK, this will be fixed in the next release.

**Comment by seanluyk** [comment]
This is still leading to an ask us page, and this is also the case with other databases (e.g. RILM) - the cfm ids all seem to be too long

**Comment by redlibrarian** [comment]
This should be fixed now.

**Comment by seanluyk** [comment]
This is working now - tried a variety of searches for databases, and they get redirected to the right place. In the process though, I've found some other issues, which I'll report.
