### ISSUE TITLE
Subtitle search problem.

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#712]
Could be an isolated case, but I think is worth investigating if this has something to do with de-duping of results between the EDS and Books, Media, and More (BMM) containers.

1. Searched for User stories applied : for agile software development

Item does not appear in BMM container, but does in EDS container. We do have this ebook title [in NEOS](http://www.library.ualberta.ca/permalink/opac/5560387/WUAARCHIVE).

**Comment by theLinkResolver** [comment]
I was trying to replicate this and found that the position of the colon has an effect on whether this works or not. If you do the search without the space after applied, you will get results in the BMM container.

**Comment by seanluyk** [comment]
Thanks @theLinkResolver , this seems like a separate issue to me. I think it should return this book regardless of where the punctuation is. There's quite different behaviour depending on the presence/absence of spaces and the colon. Oddly, when I remove the spaces between the title and subtitle, I get many more relevent results in addition to the desired item.

**Comment by redlibrarian** [comment]
We've seen this problem before. I still need to figure out what's going on.

**Comment by redlibrarian** [comment]
Hm. I think this may have something to do with the fact that the title and subtitle are two separate fields, joined in the interface only with a colon. The colon, then, isn't part of the indexed title, so search behaviour is a little weird. 

For the record, searching for "User stories applied : for agile software development" returns 0 BMM results; "User stories applied:for agile software development" returns 44 results; "User stories applied" returns 632 results; and "User stories applied: for agile software development" returns 2 results. in principle, the three searches that include the subtitle *should* all return the same results... Not sure how I'm going to fix this yet.

**Comment by seanluyk** [comment]
I think this is partially working now - various uses of punctuation provide different numbers of results, but the item in question still comes up.

**Comment by redlibrarian** [comment]
@seanluyk Do you think this is working well enough that we can fix it next term?

**Comment by seanluyk** [comment]
@redlibrarian  - I think so. The difference in numbers is no big deal, and something we can deal with for now. Moving to the next milestone.

**Comment by redlibrarian** [comment]
This seems to be working now (though I haven't changed anything). I get 104 results for **User stories applied : for agile software development**,  **User stories applied: for agile software development**, and  **User stories applied for agile software development**

@seanluyk Can you test this and see if it's working to your satisfaction?

**Comment by seanluyk** [comment]
This appears to be working. I tried a few other iterations and the only one that gets very few results (2 in BMM is: User stories applied :for agile software development

Not sure if this is significant as the item is still findable.

**Comment by seanluyk** [comment]
This is working OK now, closing.
