### ISSUE TITLE
Display of 245 $n and $p (number and name of part/section of a work)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#718]
We need to make sure we get this right, as the number (245 $n) and name (245 $p) of a part/section of a work is integral to the title. In other words, the data needs to be displayed with the rest of the title proper (245 $a) in the record and in search results, and indexed as part of the title.

e.g.
![245](https://cloud.githubusercontent.com/assets/14913579/11129162/065d63ba-893b-11e5-9d38-4bf86793412f.jpg)
currently... https://search.library.ualberta.ca/catalog/431354
it's do-able.. https://searchworks.stanford.edu/view/362374

I searched for Making connections 3 Teacher's manual and this item was not in my results.
https://search.library.ualberta.ca/catalog/6576116
(and it's a good example of there being nothing in the record to tell me it's the teacher's manual)

(Issue #514 (closed) dealt with $n and issue #478 deals with $p; since the $p issue is unresolved, this new issue can supersede that one.)

**Comment by redlibrarian** [comment]
Hmm. OK, thanks. Dealing with that title field is tricky, but as you say, it's doable.

**Comment by redlibrarian** [comment]
See also #686

**Comment by theLinkResolver** [comment]
Been thinking and consulting with others about this and the way to think about may be that we should have all the title information from the 245 displayed, and in the order it appears. That would be subfields a, b, f, g, k, n, p and s.

Take a look at this example - I can't even load this record. (Does it have something to do with the fact there's no 245 $a? It comes up in a search but I can't get into it.)

http://www.library.ualberta.ca/permalink/opac/6046607/WUAARCHIVE
https://search.library.ualberta.ca/catalog/6046607

**Comment by theLinkResolver** [comment]
@redlibrarian I think if you can just get the 245 $p to display in the record as one of the first fields, like you did for the $n, that would be critical in the short term. (That's not where it should be in the long-term, but just getting it in the display is essential.)

e.g. https://search.library.ualberta.ca/catalog/2231491
This is the report for Kazakhstan (only), but the record does not tell you that.
iLink: http://www.library.ualberta.ca/permalink/opac/2231491/WUAARCHIVE

**Comment by redlibrarian** [comment]
OK, I've added 245p to the index and display. @theLinkResolver You'll have to let me know if they are labelled correctly in the next release. I'm going to move this issue to the Check in Next Release milestone. Once the 245p has been confirmed as working correctly, then we'll move this issue to the January milestone for the rest of the subfields.

**Comment by redlibrarian** [comment]
@theLinkResolver These are indexed and displaying, but they aren't displaying nicely. If this is OK for now, I'll address making them display properly in January.

**Comment by theLinkResolver** [comment]
@redlibrarian The fact they are displaying is key for now, so that's good. I'm not sure about the indexing, though. I tried the search for Making connections 3 Teacher's manual and still didn't get that item (see the first message in this issue thread).

**Comment by redlibrarian** [comment]
Ack. I forgot to add it to the search index. I'll do it now, and it will be in place in the next release (thursday or friday). @theLinkResolver

**Comment by theLinkResolver** [comment]
@redlibrarian First hit for this search now! Closing.
