### ISSUE TITLE
Advanced Search not working

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#719]

**Comment by redlibrarian** [comment]
Fixed. Will be working in next release.

**Comment by redlibrarian** [comment]
This is working now.

**Comment by sjshores** [comment]
Sam, I don't think it's working correctly.  Search for the title Mysteries of the Backwoods in all fields and it works.  Search for the title in the title field, and it returns no results.  The author and subject field searches in advanced search seem to be working.

Thanks,

Sandra

**Comment by redlibrarian** [comment]
Thanks @sjshores I just tested, and I think the stopword problem may have crept back into the advanced search (**mysteries backwoods** in title works). I should be able to fix it pretty easily...

**Comment by redlibrarian** [comment]
@sjshores I think this is fixed now - can you verify?

**Comment by sjshores** [comment]
I presume you mean in the next release?

**Comment by redlibrarian** [comment]
@sjshores Oh, actually no - it's not fixed yet. I got confused.

**Comment by redlibrarian** [comment]
OK **now** it should be working in the next release.

**Comment by redlibrarian** [comment]
@sjshores This should be working now.

**Comment by sjshores** [comment]
Yup.  All four searches in advanced search work for me now. Thanks!

**Comment by scastell** [comment]
Advanced search isn't working. All advanced searches lead to the following page
![image](https://cloud.githubusercontent.com/assets/14927291/12404406/90f4c56c-bdf8-11e5-83fe-cbdae7e4ebc1.png)

**Comment by redlibrarian** [comment]
Shoot. I know what the problem is. It will be fixed this week.

**Comment by redlibrarian** [comment]
Fixed.
