### ISSUE TITLE
Repeated 5XX fields

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#720]
I was wondering how it is determined which 5XX fields are displayed, and if repeated notes are supposed to be displayed?

For example, in [this record](https://search.library.ualberta.ca/catalog/6791277) a 500 note appears, but in fact, it has three 500 notes. It's not crucial in this case that all three appear, but I imagine that sometimes key info appears in subsequent notes.

**Comment by seanluyk** [comment]
Here's another twist just looking at [another record](https://search.library.ualberta.ca/catalog/7143047). 500 notes appear spliced together. Songs and Group Canadian are actually two separate 500 notes

**Comment by redlibrarian** [comment]
The note mappings are here: https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/symphony_index.properties#L144 

We're currently mapping the 500, 504, 505, 521, 586, and 590 fields. If a record has a multiples of any of these, they are merged. If additional note fields should be mapped, or if we need to display the individual notes for a given field separately, we can do that. My only concern is space / amount of text we're going to present to a user.

**Comment by theLinkResolver** [comment]
I'm glad we are talking about the note fields - many are prepared with care and give a roadmap to understanding/using the material (metadata as a love note to the future and all that). There is some good information there, but sometimes it adds up to an eyeful. Some might work better merged, others on separate lines. Some aren't in Blacklight that could be and maybe vice-versa. In the long-run, some cataloguer-centric ones can maybe even be filtered out (e.g. "Title from cover"). Maybe a smaller font would be appropriate for notes. I hope we can dig into this over time as we refine the system.

**Comment by redlibrarian** [comment]
Thanks @seanluyk @theLinkResolver . Early on I made a decision not to automatically include *every* not field we use, for the reasons you identified. Having said that, I'll add any note field that we think should be presented. We should do **that** right away. In terms of the display, perhaps in the new year we can work with @nnunn to figure out a clean way to present that text. Perhaps something like a snippet and "read more", which you see on the web quite often nowadays...

**Comment by theLinkResolver** [comment]
@redlibrarian I've reviewed all the note fields, and honestly, there are probably some cases to be made for adding more of these for display, but it needs more eyes and opinions than just mine. That said, as far as adding a few, I've made a shortlist for the immediate term:

515 (numbering peculiarities, where notes explain and clarify the item records)
540 (terms governing use and reproduction)
546 (language -- note, the current language faceting looks okay as is, based on the machine-readable fields 008 and 041, but the 546 should be preferred for display in the record, as it uses human-friendly language to describe works in multiple languages)

**Comment by seanluyk** [comment]
@redlibrarian @theLinkResolver  - I like the idea of a snippet and read more link for the future, and possibly it could display all notes currently displayed + all Scott has identified, separating out repeated fields. I think splicing repeated 5XX notes together is an issue, as they're often intellectually separate things. 

Although notes create display issues, I think the amount of metadata we have in our catalogue records is one of the really unique/valuable things we offer to the world, so if there were some way to still have them available, that but would great.

**Comment by redlibrarian** [comment]
OK, the 515, 540, and 546 have been added (check in next release for those).

**Comment by redlibrarian** [comment]
@seanluyk @theLinkResolver Can you take a look at these records and let me know how the seem right now? I don't think they're done yet, but some of the display has been improved, I think?

**Comment by seanluyk** [comment]
I think the display has improved by adding the -- between repeated notes, and the example records. I'm not seeing 546 in [this record'(https://search.library.ualberta.ca/catalog/6791277), but the other notes are there.

**Comment by theLinkResolver** [comment]
Wow, @seanluyk - good catch on the 546. Indeed, there are a few different subfields to display for the 546, and we are just displaying one of them right now. My bad.

@redlibrarian Can you add $3 and $b to the display... This is one of those fields where we want to see the contents in whatever order they are presented. I don't think this will break anything else (language as displayed in results list per #966) but maybe check this in dev to be sure?

**Comment by theLinkResolver** [comment]
@redlibrarian I think the label is wrong on this one. Still needs work.

**Comment by redlibrarian** [comment]
@theLinkResolver Oh yeah, you're right - this isn't read yet.

**Comment by theLinkResolver** [comment]
In this thread, we talk about dealing with long notes, so I am going to add an example of a different kind of long field - the record below has a large number of 020 fields (i.e. multiple ISBNs), and if any design work is done to collapse long fields into snippets with a "read more" link, you can see why the ISBN field would merit some consideration for that treatment!

https://www.library.ualberta.ca/catalog/44811

This is legit when you have a monographic set where each volume has an ISBN (i.e. there would be others like this).

**Comment by theLinkResolver** [comment]
And I'd say this relates to mobile-friendliness (#930). The above record must be "interesting" to look at on a phone. :)

**Comment by seanluyk** [comment]
The original issue in this ticket has been dealt with, closing.
