### ISSUE TITLE
Services for persons with disabilities page - broken link

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#722]
https://search.library.ualberta.ca/services/disability-services  - 

section titled <b>Loan Periods</b> - Please consult the <b><a href="http://guides.library.ualberta.ca/borrowing">loan period page</a></b>, for more information.

change link to the loan period page to https://search.library.ualberta.ca/services/library-cards-and-borrowing/undergraduate-students?

**Comment by alfodor** [comment]
I have updated the page. April
