### ISSUE TITLE
No results for item in collection

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#724]
1. Searched for [Alice carli binding and care of printed music](https://search.library.ualberta.ca/results?q=Alice+carli+binding+and+care+of+printed+music).

-0 results in BMM
-Just searching for binding and care of printed music bring it up no problem
-Searching for Alice Carli bring it up, but only after faceting by call number. It's way down at result#17

**Comment by redlibrarian** [comment]
Hm. There's something I'm not quite understanding here. **alice carli** brings up the correct result (admittedly buried), **binding and care of printed music**, **alice carli binding and care** and **alice carli printed music** all return the correct result, but the full title and author doesn't return anything. This must have something to do with the way Solr handles queries that I don't yet understand. I'll have to investigate.

**Comment by seanluyk** [comment]
Thanks, @redlibrarian  - this is weird because I'm pretty sure it worked before. I use it as a search example regularly as it's on my desk

**Comment by seanluyk** [comment]
As far as I can tell, this is working now. Will leave this issue open in case you'd like to investigate more.

**Comment by redlibrarian** [comment]
@seanluyk Interesting. I made a change to the indexing rules that was only pushed to production today. That must have fixed it. I'll close this issue. Thanks.
