### ISSUE TITLE
SFX record "format"

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#726]
@redlibrarian It looks like all of the SFX records have Format=Journal applied to them. I'm hoping that is something you control (it does not seem to be coming from the Object type SFX field - I checked some of the other object types). If you can change the format for all SFX records to display as Serial, this will mesh with the format faceting for the Symphony results. This is also more accurate since I see you have expanded the SFX set to include series, newspapers, etc., which is great.

![sfx journal](https://cloud.githubusercontent.com/assets/14913579/11227721/068b89ee-8d45-11e5-9c6e-5f86ffd0e096.jpg)

**Comment by redlibrarian** [comment]
I've updated the mapping for SFX to be the same as the mapping for Symphony. Seems to work fine.

**Comment by redlibrarian** [comment]
Looks like this fix didn't make it into the latest release. It will be in the next one.

**Comment by redlibrarian** [comment]
@theLinkResolver I'm not sure that this is fixed. "Journal" is still showing up, so it seems as if the journals may not have been reindexed with the new format...

**Comment by redlibrarian** [comment]
@theLinkResolver this should be fixed now.

**Comment by theLinkResolver** [comment]
fixed!
