### ISSUE TITLE
(Suggestion) "Chat with us" link should lead to "Ask Us" page.

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#728]
This suggestion came out of a PSC meeting on 11/18/2015, I thought I would record it here for consideration by the group:

The "Chat with us" link on the top-right of the bento box view opens the Ask Us Chat in a new tab. 

It was suggested that the button could lead to the Ask Us page (though still open in a new tab to allow users to keep their search results). The justification being that the Ask Us page provides more avenues for users to seek help, while still prominently featuring the Chat box.

**Comment by redlibrarian** [comment]
Thanks @gooyers . We already have a link to the ask-us page in the top banner. I think the idea was that we wanted to promote chat reference with the chat box lower down in the page. I can't remember how that decision came about, but if we're going to change it to go to the ask-us page, then I think that link becomes redundant, and one of the two should be removed.... thoughts?

**Comment by gooyers** [comment]
Personally, I think having both links is a bit redundant either way, but that that redundancy will likely be a positive in the first few weeks of full launch (if people feel lost, they have two very obvious place to click for help).

I'd suggest never removing the Ask Us link in the top banner as that is consistent throughout the entire website. If anything, I'd suggest removing the Chat with us" button and moving the helpful "Questions about your results or your research?" line to the banner, making it "Questions about your results or your research?: Ask Us" on all Blacklight search&results pages.

**Comment by redlibrarian** [comment]
OK, thanks @gooyers . Let's leave it as is for now, as providing more links in the immediate post-launch period is probably a good idea. We can revisit and simplify when people are used to the new system.

**Comment by redlibrarian** [comment]
Done. Check in next release.

**Comment by redlibrarian** [comment]
@gooyers This is in place now.
