### ISSUE TITLE
Error in item Location

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#730]
This may be an isolated case (I will try to find a similar example to see if this problem extends beyond one record), but I've come across a Blacklight record at BSJ that has an error in the item's location. 

The book is [Éducation physique](https://search.library.ualberta.ca/catalog/2558040), and Blacklight indicates that we have two copies in Special Collections. 

However, [EDS/Symphony](http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=cat00362a&AN=neos.2558040&lang=fr&site=eds-live&scope=site) reflects the reality that we have one copy in our Curriculum collection, and one in Special Collections (at least we are supposed to have a copy, but when I was checking the shelves I couldn't locate it). 

Regardless, I was able to find the copy in our Curriculum collection so at the very least Blacklight is considering a book that is catalogued as Curriculum to be in Special Collections.

**Comment by redlibrarian** [comment]
Thanks @gooyers I think this is related to #672 and should be fixed in the new release.

**Comment by gooyers** [comment]
Thanks @redlibrarian, I'll check in then.

**Comment by redlibrarian** [comment]
@gooyers This looks fixed to me - can you verify?

**Comment by gooyers** [comment]
It's fixed for me as well, thanks @redlibrarian
