### ISSUE TITLE
Database not coming up in results

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#731]
I'm not able to successfully locate the [Metopera on demand database](https://www.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=4651).

I've tried searches for MetOpera, Met opera, met opera on demand, etc.

**Comment by redlibrarian** [comment]
Interesting. It turns out that this database doesn't have any subjects assigned in LibGuides, which means it's not coming through in the libguides data. The database group is meeting next week - I'll confirm with them whether all databases should have a subject, or whether the data load needs to be modified.

**Comment by seanluyk** [comment]
That's odd - I was sure that this database had been associated with music, but we must have missed it. I've associated it now.

**Comment by redlibrarian** [comment]
OK, great, thanks @seanluyk . That will fix the problem for this record. I still want to discuss workflow with the DB group next week. I'll leave this ticket open until then.

**Comment by seanluyk** [comment]
@redlibrarian  - it looks like even if databases are tagged with particular subjects, they aren't coming up for some reason. For example:

1. Searched for anthropology in everything
-5 database results returned, yet there are [47 databases tagged as anthropoloy in the libguides a-z list](http://guides.library.ualberta.ca/az.php?s=56571)

**Comment by redlibrarian** [comment]
Strange. @seanluyk I'll investigate.

**Comment by redlibrarian** [comment]
@seanluyk Both these problems are fixed in development: MetOpera is coming back, and there are 47 databases in the Subject facet for Anthropology. Please check this in the next release.

**Comment by redlibrarian** [comment]
@seanluyk OK, this should be working now.

**Comment by seanluyk** [comment]
Fixed, closing
