### ISSUE TITLE
Database requires ezproxy authentication, and then redirects to dabatase description page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#732]
May not be Blacklight related, but reporting as this may apply to a large number of databases:

1. Searched in everything for Medici

Database result was returned, but I was required to authenticate, and then click on web access. I am often required to authenticate from on campus for some reason, but I don't usually also get directed to the database description page.

**Comment by redlibrarian** [comment]
@seanluyk Ah, this is a good example of something I need to discuss with the database group next week. Thanks.

**Comment by redlibrarian** [comment]
Currently, the database ingest only attaches a database to a single subject (it looks like the last one in the libguide record). This will need to be fixed. 

Selectors who are creating the initial database record can add a broad subject, so that no databases won't have a subject attached, and then should all come through.

**Comment by redlibrarian** [comment]
[ ] Proxy prefix removed
[ ] Alternate title field uses
[ ] Multiple subjects

**Comment by seanluyk** [comment]
@redlibrarian  - I'm not sure what you mean about attaching to a single subject - I believe this one is only attached to music.

**Comment by redlibrarian** [comment]
Sorry @seanluyk - I was using this ticket to capture other issues around the databases. Currently, a database will only be attached to a single subject, even if it has multiples - I was just making a note to myself to fix that.

**Comment by redlibrarian** [comment]
@seanluyk For the initial problem in this issue, the database group decided - for now - to point all database links to their respective database information pages (except free resources, which will link out directly). The proxy prefix will be removed, so you shouldn't have to authenticate until you actually click out to a database from off-campus. Please check this in the next release.

**Comment by redlibrarian** [comment]
@seanluyk This should be fixed now.

**Comment by seanluyk** [comment]
Fixed, closing
