### ISSUE TITLE
Privacy issue: view search history

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#736]
I was curious about how search history is cleared, and assumed that closing a browser would clear it (as opposed to closing a tab). 

It doesn't look like this is the case. After closing Chrome, reopening, redoing a search, and then clicking on view search history, the searches from my previous session were still appearing.

Not sure if this is a browser specific issue or not (i.e. browsers on AIOs will not behave the same). Will test that in HSS and get back to you.

**Comment by redlibrarian** [comment]
I think we had a question before about session timeouts (issue #319). The sysadmins and I will have to figure this out, but it will be good to warn people... I'll see if I can figure out a short term measure.

**Comment by seanluyk** [comment]
Good to know it's being investigated, thanks Sam.

**Comment by redlibrarian** [comment]
For me, testing in both Chrome and Firefox, the search history **is** cleared when the browser is restarted. @seanluyk Were you able to test the AIOs in HSS? Thanks.

**Comment by seanluyk** [comment]
It's not cleared on my machine or on the AIOs in HSS. Let me test again to confirm.

**Comment by seanluyk** [comment]
It clears in Firefox, but not in Chrome. Must have something to do with the version of Chrome installed on staff workstations and AIOs.

**Comment by redlibrarian** [comment]
OK, thanks @seanluyk - that gives us some more to go on.

**Comment by redlibrarian** [comment]
One of the problems it that this is very difficult to test. I can't replicate it, but @seanluyk and @kgood have. Any change I make can only be tested after it goes into production...

**Comment by redlibrarian** [comment]
I've added a 2 hour expiry to the session, which seems to be common practice given than session expiry on browser close seems to be unreliable. I don't know whether this will help the problem or not, but we should check again in the next release.

**Comment by redlibrarian** [comment]
@seanluyk @kgood Can you check to see if this made any difference? It may not have, but it's the thing to start with.

**Comment by seanluyk** [comment]
@redlibrarian search history is still showing after I restart Chrome.

**Comment by redlibrarian** [comment]
Thanks @seanluyk The consensus that @kgood and I have come up with is that this issue is somehow broweser related (though inconsistent, so hard to pin down). Not sure where we go from here... @kgood ?

**Comment by seanluyk** [comment]
Closing for cleanup purposes. No longer able to replicate.
