### ISSUE TITLE
More information in bento box display

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#737]
Reported by an HSS colleague:

1. Searched for [discipline of history and the history of thought](https://search.library.ualberta.ca/results?utf8=%3F&q=discipline+of+history+and+the+history+of+thought)

-The first 4 results in BMM are for the desired title, however, it's not possible to tell which one the user should click on, and the UofA copy may not be result#1, and isn't in this case

I realize that real estate is an issue, but would it be possible to have the *copies available at* field displayed in this view? That way a user could determine which record to click on, and University of Alberta Internet would give them a clue that that's the ebook they want.

**Comment by redlibrarian** [comment]
I think this should be possible, but will be a little trickier than making it appear in the results page. I think that, given that a user can click through to the results screen, this doesn't haven't be solved before launch, though it should be addressed next term.

**Comment by seanluyk** [comment]
Sounds good to me, thanks @redlibrarian

**Comment by theLinkResolver** [comment]
Ugh! I'm going to show this to the e-book cataloguers, as there are efforts underway to merge records like that. 

@redlibrarian There is a fixed field that you might be able to use to highlight the e-books/journals at the record level, rather than the item level, which I think would help you with this future enhancement. It relates to #687. It's the same element we will use to do away with the GMD, too! #534

**Comment by redlibrarian** [comment]
I've added the UAL shield to all Symphony records owned by (at least one) UA library. Does this solve this problem? @ualbertalib/discovery-testing

**Comment by seanluyk** [comment]
Looks like the shield is appearing for titles not owned by UAL, for example, in [this search](https://search-test.library.ualberta.ca/results?utf8=%3F&q=discipline+of+history+and+the+history+of+thought) result #5 shows the shield but the record shows MacEwan holdings only

**Comment by theLinkResolver** [comment]
@redlibrarian Is the table of contents 856 link causing a false positive?

**Comment by redlibrarian** [comment]
No, it should only be looking at the NEOS id codes. I'll check into it.

**Comment by redlibrarian** [comment]
OK, this should be fixed now (in the next release).

**Comment by seanluyk** [comment]
This is fixed - shield icon only appearing for UAL items, as far as I can tell
