### ISSUE TITLE
Adding Book Covers to the Books Media & More Search Results

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#738]
Our staff have asked if it might be possible for book covers to be added to the Books Media & More search results list, to help facilitate choosing a proper book. It seems superficial but we often "judge a book by it's cover" to determine if it might be appropriate. In our collection the cover image can be a large indicator of reading level, which isn't found in any part of an item record. Currently, In blacklight you have to click into each individual option to see more. Marking this as a question and as an enhancement.

![2015-11-20_14-44-22](https://cloud.githubusercontent.com/assets/14892833/11312834/f67f5d48-8f95-11e5-9f4c-e00566b19569.jpg)

vs

![2015-11-20_14-46-10](https://cloud.githubusercontent.com/assets/14892833/11312904/48bb0f3a-8f96-11e5-8ed5-bc84cbcdf4bb.jpg)

**Comment by redlibrarian** [comment]
@hannepearce I thought we had book-covers in the result list at one point, and I'm not sure what's happened. @nnunn can you remind me of our decisions around this? Thanks.

**Comment by nnunn** [comment]
We had them in the bento "more" section. I will put them up in this list for the next deployment.

**Comment by nnunn** [comment]
this is now done and will be up on the next release. We did have this before, but the variable seems to have changed from isbn_t to isbn_tesim

**Comment by redlibrarian** [comment]
Ah, that makes sense - sorry, my fault.
