### ISSUE TITLE
Searching for Journal - inconsistent results

### ISSUE THREAD

**Issue by hannepearce** [ualbertalib/discovery#739]
Was helping a student look up an article - known item search. I searched *BC studies* (Journal Title) in basic search and selected Journals to specify. I got no results.
![2015-11-20_16-07-59](https://cloud.githubusercontent.com/assets/14892833/11314348/066d1c20-8fa2-11e5-9b6b-455a210d8f12.jpg)

Repeated the same result in basic search without selecting Journals and it appears in the Journals bento box pane.

![2015-11-20_16-17-10](https://cloud.githubusercontent.com/assets/14892833/11314372/3e6ebd4a-8fa2-11e5-983a-7cd178e722ec.jpg)

**Comment by hannepearce** [comment]
This seems to be happening with any journal title I try.

**Comment by redlibrarian** [comment]
This is the same problem as #703. It will be fixed in the next release.

**Comment by hannepearce** [comment]
this seems to working now.
