### ISSUE TITLE
Library location links opening in new tab--would prefer new window

### ISSUE THREAD

**Issue by sjshores** [ualbertalib/discovery#742]
Hello,

I'm working through Ian MacLaren's message and have a suggestion based on his feedback.  Right now, the link from the library name in the call number, location, library, item type box opens a new tab and provides location information.  Ian didn't see that this was a new tab and therefore couldn't return to his search.  I think it would be more obvious to a user that the search tab still exists if the link opened up a new, small window instead of a new tab.

Is this possible?

Thanks,

Sandra

**Comment by redlibrarian** [comment]
@sjshores It's possible - unless that's browser behaviour - but I don't think it's a good idea. Opening in new tabs is more accepted behaviour - opening new windows tends to be associated with pop up ads. New windows can sometimes also open behind the current window, which someone wouldn't see. @nnunn What are your thoughts on this?

**Comment by redlibrarian** [comment]
@sjshores @nnunn My HTML is a bit rusty, but I seem to remember that whether target="_blank" opens a tab or a window is browser-dependent, not code-dependent...

**Comment by redlibrarian** [comment]
@sjshores Can we close this ticket?

**Comment by sjshores** [comment]
Yes, this functionality is fine.  Closed.
