### ISSUE TITLE
Publication year for Springer ebooks does not show up in Blacklight record

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#746]
Hi. I'm coming up with search examples for the training session. Try searching for stochasitc optimization, then go into the Books, media & more list and limit to University of Alberta Internet: hits 4, 5, and 6 do not give a year of publication. 

4. https://search.library.ualberta.ca/catalog/6641903

5. https://search.library.ualberta.ca/catalog/6930108

6. https://search.library.ualberta.ca/catalog/6791851

Not sure if there are any other ebook platforms that are having the same problem. Year of publication is an important factor when deciding what resources to pursue.

**Comment by redlibrarian** [comment]
@theLinkResolver These dates are coming from the 264c - this is an RDA change, right? Currently, Blacklight only looks at the 260c. I'll have to figure out how to change this if 264c is the new field.

**Comment by theLinkResolver** [comment]
@redlibrarian That's right - every record will either have a 260 or 264 (the new practice).  Wherever you are referencing the 260, you also need to reference the 264 (it looks like you are doing so for the publisher and place of publication already).

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver , pub date is tricker than publisher and place, because it's wrapped in a Java script that manipulates the data to get a clean date out of it. This might be a little tough...

**Comment by redlibrarian** [comment]
OK, I've rewritten the getdate script to use the 264c field in addition to the 260c field. I can't see any RDA records in my test set, so we'll have to verify that this is working in the next release.

**Comment by redlibrarian** [comment]
Looks like this still isn't fixed. Back to the drawing board.

**Comment by redlibrarian** [comment]
@theLinkResolver Do you have a sense of how many records this is affecting (roughly)? Fixing this will require a full reindex, which we'd like to avoid right now if possible. If this is currently a minority of records (I assume it affects all RDA records, so it could very well be the majority now), then I'd like to wait until January to fix this...

**Comment by theLinkResolver** [comment]
@redlibrarian We currently have 248,716 RDA records in the system, all of which should have a 264 rather than a 260.

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver - @sjshores Does that sound like a significant enough number to warrant changing the index at this time? These records won't display a publication year field.

**Comment by sjshores** [comment]
It's not a show stopper, but dates are important.  Let's talk about this
one at our Thursday meeting.

**Comment by redlibrarian** [comment]
Good news: I figured out how to easily test this. Bad news, I can't figure out how to fix it. This won't be ready for launch. I think it will have to be fixed next term.

**Comment by redlibrarian** [comment]
It looks as though the latest version of SolrMarc includes RDA support, so I think that's the roadmap to fix this problem. The latest version of blacklight-marc doesn't include the latest SolrMarc, but Henry's been looking into compiling and using it - we're planning to look at it more closely next term, so that's probably the way to go with this one.

**Comment by sjshores** [comment]
Great to hear.  Thanks,

Sandra

**Comment by theLinkResolver** [comment]
@redlibrarian The RDA support may help us here, but also the fixed field dates might be better to work with -- more machine-readable and always in the same character positions in every record. (I don't like referring to them all the time but it seems to be what Stanford uses to display dates.)

**Comment by redlibrarian** [comment]
@theLinkResolver OK. We should sit down and talk about the fixed field dates. Would this work for everything? In other words, should we be using them instead of the 260/264?

**Comment by theLinkResolver** [comment]
@redlibrarian Quite possibly. I asked Brian S. for a quick reaction to see if he has any concerns about using fixed field dates and as long as Blacklight can look at the "type of date/publication status" coding (also in a stable/consistent fixed field), he had no concerns.

**Comment by theLinkResolver** [comment]
Fixed in test.
