### ISSUE TITLE
subject heading elements displayed in reversed order

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#748]
I don't think this was always the case, but since last week I'm seeing subject headings displayed in reverse order (which, indeed, ruins the benefit of the tiered-clickability feature).

https://search.library.ualberta.ca/catalog/78263
- the correct order would be topical term (Dissertations, Academic), geographic subdivision, form (indexes).

https://search.library.ualberta.ca/catalog/6848964
- 1st one: should be jurisdiction, subordinate unit (the Commission), form
- 2nd one: should be topical term (Native peoples), geographic subdivision, general subdivision (claims), form

**Comment by redlibrarian** [comment]
@nnunn I think you and I are maybe **both** reversing the subject array.

**Comment by redlibrarian** [comment]
OK, should be fixed.

**Comment by redlibrarian** [comment]
@theLinkResolver Does this look OK to you?

**Comment by theLinkResolver** [comment]
fixed
