### ISSUE TITLE
Clicking into Journal bento box leads to error message

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#750]
This may be related to #703 and #739, but it is not related to ISSN, and it doesn't relate to inconsistent search results so I thought I would include it as it's own issue. 

Currently, if I try to click into the full results of a Journal box ([example here](https://search.library.ualberta.ca/ejournals?q=journal%20of%20applied%20polymer%20science)) I receive an error message. 

![2015-11-26_15-31-52](https://cloud.githubusercontent.com/assets/14891931/11431318/db45fa3e-9452-11e5-9794-48dc74bd80cc.jpg)
![2015-11-26_15-26-51](https://cloud.githubusercontent.com/assets/14891931/11431307/958db43c-9452-11e5-9469-c6d1dfad7286.jpg)

**Comment by redlibrarian** [comment]
Hi @gooyers - Yes, it's the same problem. It should be fixed in the next release.

**Comment by gooyers** [comment]
This is now working.
