### ISSUE TITLE
(Suggestion) Should "view results as a grid" link be visible outside of first results page?

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#751]
I'd failed to notice that the "view results as a grid" appears as an option within each bento box. 

It's nitpicking, but within specific bento boxes (ex. Databases) the "view results as a grid" option functions either as a back button (if users clicked into the bento box, as clicking the grid will just take them back a step), or it expands their search without them having asked to do so (if users limit to Databases from the simple search on the homepage, clicking to the grid makes them lose their previously chosen limiter).

I think it once again comes back to vocabulary/labeling. The "change view" option is not simply a toggle. Within individual bento boxes it would be more accurate to label the button as "return to grid results page" or something similar.

My suggestion would be to limit the "view results as a grid/list" button to the bento box page (and it's list view equivalent) and remove it everywhere else. I'd be curious what others thought as well.

**Comment by redlibrarian** [comment]
I agree that it's confusing to have it on individual result pages. I can add logic for that, if that's the feeling of the house. @nnunn @ualbertalib/discovery-testing

**Comment by seanluyk** [comment]
I think the only issue is with the search expanding without a user asking for that. This could be seen as an advantage, but I agree that consistent behaviour should be the goal.

**Comment by redlibrarian** [comment]
I haven't heard any reports of issues one way or another with this this term. I'd propose closing this and reopening if a problem arises from usability testing or user reports.

**Comment by theLinkResolver** [comment]
@ualbertalib/discovery-testing Maybe we could review this in our meeting on Monday, first? Having been at almost all the training sessions, I can say that grid/list behaviours did cause some concern on various occasions. Maybe we can run through the toggle scenarios and decide whether there is something to fix or refer to usability testing.

See also #862 re. toggling from the grid view.

**Comment by redlibrarian** [comment]
Sounds good - can you have Tim put it on the agenda? @theLinkResolver

On Thu, Mar 10, 2016 at 12:15 PM, Scott Davies <notifications@github.com>
wrote:

> @ualbertalib/discovery-testing
> <https://github.com/orgs/ualbertalib/teams/discovery-testing> Maybe we
> could review this in our meeting on Monday, first? Having been at almost
> all the training sessions, I can say that grid/list behaviours did cause
> some concern on various occasions. Maybe we can run through the toggle
> scenarios and decide whether there is something to fix or refer to
> usability testing.
>
> See also #862 <https://github.com/ualbertalib/discovery/issues/862> re.
> toggling from the grid view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/751#issuecomment-195006242>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by theLinkResolver** [comment]
@redlibrarian done!

**Comment by gooyers** [comment]
Closing issue as list/grid toggle has been removed.
