### ISSUE TITLE
Articles view - display issue

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#752]
I've noticed that in the articles view, the spacing of some text is weird, it's k ind of li ke thi s. This was most noticable in the content provider facet.

Also, text wraps when it probably shouldn't, and the number of results don't always line up.

Noticed this issue in Chrome.

**Comment by redlibrarian** [comment]
@seanluyk Do you mean the results view? ie http://search.library.ualberta.ca/articles?q=shakespeare

**Comment by seanluyk** [comment]
Yes, from a list of results in the articles search.
