### ISSUE TITLE
Google Scholar 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#753]
I'm wondering why Google Scholar is listed beside EDS and NEOS? I really like Google Scholar, but finding it literally requires someone to just Google it. Was this something someone asked for?

**Comment by sjshores** [comment]
Yes, there was strongly voiced feedback from a number of faculty members
that they want this, so we will launch with it.

Sandra

**Comment by seanluyk** [comment]
Interesting, thanks @sjshores. I'd be curious to see how many clicks this link gets, and if we end up answering questions about some of the content in Google Scholar (access issues, non scholarly content, etc.). Putting this right on our main page is somewhat of an endorsement.

**Comment by sjshores** [comment]
It's on our current front page, too.  Look just to the right of the EDS
search box!

Sandra

**Comment by seanluyk** [comment]
@sjshores , I know, I guess I'm wondering whether or not it's a good idea, but we can put this issue to rest since it's already been decided!

**Comment by redlibrarian** [comment]
@seanluyk Can we close this ticket?

**Comment by sjshores** [comment]
Yes, closed.
