### ISSUE TITLE
[Discovery] Remove call number attribute from advanced search

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#755]
Apologies if this has been noted previously, but in the advanced search the Call Number attribute still features call numbers beyond the established A-Z of LC. Additional call numbers in the list include: 
[, >, 9, n

The odd call numbers don't seem to be reflected in the item records (at least for those that I checked). 
For example, limiting to > as a call number lead me to this [results page](https://search.library.ualberta.ca/catalog?all_fields=&author=&commit=Search&f_inclusive%5Blc_1letter_facet%5D%5B%5D=%3E&op=AND&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&subject=&title=&utf8=%E2%9C%93). The first result is [Quand le stage en enseignement déraille](https://search.library.ualberta.ca/catalog/6189442) which has a call number of LB 2157 A3 Q36 2013. 

Additionally, I would suggest that the call numbers attribute be listed in alphabetical order, rather than in order of # of results, as seems to be the case now. I've marked this as 'enhancement' and for the January/April milestone. 

![2015-11-30_9-34-47](https://cloud.githubusercontent.com/assets/14891931/11477526/a1ec4266-9745-11e5-9983-838fb8d82237.jpg)

**Comment by gooyers** [comment]
Now that I think of it, @redlibrarian, should the subgroup stop adding issues now that the code freeze date has passed? Or is issue reporting still welcome?

**Comment by redlibrarian** [comment]
Hi @gooyers Issue reporting is still welcome. As usual, don't assign any new issues to a milestone. Leave them unassigned so that I can find and triage them. Anything not absolutely urgent will likely be assigned to the January milestone. @ualbertalib/discovery-testing

**Comment by gooyers** [comment]
Ah, my mistake. Thanks Sam!

**Comment by redlibrarian** [comment]
I don't know if this is a data problem or an indexing problem. @theLinkResolver Are there likely to be records with call numbers beginning with lowercase letters, even if only accidentally?

**Comment by theLinkResolver** [comment]
@redlibrarian The lowercase f will legitimately appear there, but it is not the part of the call number we want to look at (it's a prefix that LC used for music folios). Most of the other stuff is questionable, but we might have to live with it being there. The data comes from the 050 (LC call number field) and we (and our NEOS partners) tend to take it as it comes, in the interest of economy. Could the "unexpected" call numbers be suppressed from this facet?

**Comment by theLinkResolver** [comment]
@redlibrarian I realize that doesn't quite answer your question. Those lowercase letters and numbers are in the records (it's not an indexing problem).

**Comment by redlibrarian** [comment]
Hm. OK, thanks. There might be a way to strip the lowercase letters, but it won't be straightforward. I'll move this to something to look at for the summer.

**Comment by nnunn** [comment]
This is done.
