### ISSUE TITLE
Retain search terms in bento display.

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#756]
Hi. When you search the contents of a single bento box, the search terms stay in the search box. However, when you search across bento boxes, the search terms don't appear in the search box. Is it possible to create a "search within these results" feature and/or make the search terms stay in the search box, no matter where the search originated?

**Comment by redlibrarian** [comment]
Yes, this is doable.

**Comment by theLinkResolver** [comment]
@linds37 Do you agree that I duplicated this same issue in #828? If so, I will close that one in favour of this one.

**Comment by redlibrarian** [comment]
I agree that this is duplicated in #828. I'm going to close that ticket.

**Comment by redlibrarian** [comment]
I've fixed this. It will be in the next release.

**Comment by redlibrarian** [comment]
Hm. It's only retaining the first word in a phrase, ie "global warming" => "global". I need to tweak that.

**Comment by redlibrarian** [comment]
Strange. This is working right now on my workstation, but not in search-test. I'll check it again when the next release is pushed to test.

**Comment by redlibrarian** [comment]
Ok, this is working now in test. It should be good to go.

**Comment by seanluyk** [comment]
Working nicely, search terms are retained in all views and search within is functioning as expected
