### ISSUE TITLE
Book series not showing in Blacklight

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#757]
This may be related to another issue, I'm not sure.
A student was looking for this article [Gender Identity and the Modern Condition in The Sun Also Rises] (http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=lfh&AN=57519564&site=eds-live&scope=site), which we have access to through Literary Reference Center. But, when you search for the article in Blacklight, it doesn't come up.
EDS has this record listed as a book, Critical Insights: The Sun Also Rises, (it's an annual I believe), maybe that's why? Problem is, it's not in NEOS (although MacEwan's is) so the only way to find it is by searching EDS or Literary Reference Center.

**Comment by redlibrarian** [comment]
Hm. I have no idea why this is happening.

**Comment by sjshores** [comment]
I suspect the issue may be tied to the fact that this is a book chapter
rather than a journal article.  MacEwan has added individual records to
Symphony for the book series, and we haven't, but I don't get why the
article isn't appearing in the EDS bento pane.

Sandra

**Comment by redlibrarian** [comment]
It turns out that the API version of EDS is not kept in sync with the desktop version, so Literary Reference Centre wasn't enabled in the API/Blacklight. I've enabled it now, and I've made a note to reconcile the two sets of enabled databases.

**Comment by redlibrarian** [comment]
This is working now.
