### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#758]
Controllers
(Test each method)
- [x] bento
- [ ] catalog
- [ ] errors
- [ ] forms
- [ ] profiles
- [ ] advanced_search

Features
homepage ("/"):
(Only testing the "home" box for now)
- [ ] search box (presence)
- [ ] filters (destination links)
- [ ] top and bottom nav links
- [ ] also explore
- [ ] hours
- [ ] room booking
- [ ] account
- [ ] twitter feed (presence)

bento ("/results")
- [ ] boxes
- [ ] results + metadata
- [ ] search box + buttons
- [ ] links to result pages

results "/catalog"
- [ ] breadcrumbs
- [ ] facets
- [ ] results
- [ ] record metadata
- [ ] sort
- [ ] pagination and page nav
- [ ] grid/list link
- [ ] bookmark
- [ ] result count
- [ ] covers
- [ ] saved search link\
- [ ] symphony
- [ ] sfx
- [ ] databases

eds ("/articles")
- [ ] result count
- [ ] facets
- [ ] metadata
- [ ] title links
- [ ] covers
- [ ] pagination and page nav

record ("/catalog/<id>")
(test symphony (print and e), sfx, database)
- [ ] metadata
- [ ] subjects
- [ ] more by this author
- [ ] links
- [ ] holdings
- [ ] tools
- [ ] bookmark/go to bookmarks
- [ ] back to search/start over
- [ ] place hold

other pages
- [ ] email form
- [ ] SMS form
- [ ] bookmarks
- [ ] saved searches

Helpers/Services
- [ ] application_helper
- [ ] articles_helper
- [ ] errors_helper
- [ ] forms_helper
- [ ] holdings_helper
- [ ] profiles_helper
- [ ] status_helper
- [ ] marc_module
- [ ] sfx_service
- [ ] symphony_service

Unit
- [ ] lib/ingest/batch_ingest
- [ ] lib/ingest/database_om
- [ ] lib/ingest/databases.rb
- [ ] lib/ingest/ingester.rb
- [ ] lib/ingest/vocabulary.rb
- [ ] lib/tasks/cmssetup
- [ ] lib/tasks/delete
- [ ] lib/tasks/fetch
- [ ] lib/tasks/ingest_configuration
- [ ] lib/tasks/ingest
- [ ] lib/tasks/marc
- [ ] lib/tasks/session
- [ ] lib/tasks/spec
- [ ] config/ingest.yml
- [ ] config/logger.yml
- [ ] config/locations.yml
- [ ] config/statuses.yml
- [ ] config/item_types.yml

Performance

**Comment by pgwillia** [comment]
+1
