### ISSUE TITLE
Author facet issue

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#759]
The author facet in list view doesn't appear to be presenting as intended. 

I conducted a search for Butterfly and entered into the Books, media and more box, and upon expanding the Author facet I noticed that the facet includes a lot of dates, single letters, and single numbers instead of the usual full author names. I conducted a few other searches and the issue isn't limited to the 'butterfly' search. 

I remember that this facet was working properly a few days ago, so this seems to be a new issue. 

![2015-12-01_13-00-26](https://cloud.githubusercontent.com/assets/14891931/11512492/8d722486-982b-11e5-9fa3-1e567e99e89e.jpg)

**Comment by redlibrarian** [comment]
Gah. A change to fix a different problem caused this. This will be fixed in the next release.

**Comment by redlibrarian** [comment]
Crap. This has broken the author search functionality. It will need a reindex...

**Comment by gooyers** [comment]
This is now working in the test instance, as is clicking into "Find more by this author" within an item record.
