### ISSUE TITLE
Journals container, view all results labeling

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#760]
From the bento box view, the view all results button should read view all journals, not view all electronic journals, as both print and electronic journal results appear in this container.

**Comment by redlibrarian** [comment]
Hm. This is already fixed in the code. I'll have to talk to the sysadmins.

**Comment by redlibrarian** [comment]
@seanluyk This is fixed in test now...

**Comment by seanluyk** [comment]
This is fixed, but I noticed a few (some picky) things along the way:

1. There's now an ebooks and more pre-limit, but no bento box container for it

2. Articles and more is labeled as articles on the main search, but Articles, ebooks and more in the bento view

3. Pre-limits from the main page are all lowercase, but this is not consistent with the rest of the site, which uses TitleCase, and not consistent with how the bento box containers and view all buttons are labelled

**Comment by redlibrarian** [comment]
1. The ebooks prelimit is set to be removed in the next release (issue #773).
2. I'll fix that.
3. To me that's a design thing, and I defer to @nnunn on design....

**Comment by redlibrarian** [comment]
1. This is set to be fixed in the final release ( #773).
2. I've added the article prelimit label to #773.
3. This is a design thing, and I defer to @nnunn about those. I've asked her to weigh in in #773.

**Comment by redlibrarian** [comment]
OK, 1 and 2 will be fixed in the final release. 3 is still up for discussion I guess.

**Comment by seanluyk** [comment]
@redlibrarian #1 is fixed; #2 - still appears as Articles, ebooks and more in the bento view; #3 - case on main page are now matching case on bento box view

**Comment by redlibrarian** [comment]
@seanluyk Again, I'm seeing "Articles & more" in search-test. Maybe try the prod version when it's up later this morning (I'll let you know).

**Comment by seanluyk** [comment]
Fixed, but cases don't match so I'll open a new issue. My OCD dictates that if the cases don't match, the sun won't rise tomorrow!
