### ISSUE TITLE
Fix OUR license width in ejournal display.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#762]
Example record: https://search.library.ualberta.ca/catalog/954925545272

**Comment by theLinkResolver** [comment]
@redlibrarian These still don't look right when the browser window is small. (example from Firefox)

![our width](https://cloud.githubusercontent.com/assets/14913579/13576913/2891d5ac-e44d-11e5-9b78-d671860cd7c7.jpg)

**Comment by redlibrarian** [comment]
OK. Not sure what I'll be able to do with this now that our design person is away.

**Comment by theLinkResolver** [comment]
Fixed in test.
