### ISSUE TITLE
Exporting to Refworks makes search results disappear

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#763]
Hi. During the testing today, I tried exporting to Refworks. The Refworks screen opens on top of the search results screen. It needs to open in a new window. thanks,

**Comment by redlibrarian** [comment]
@linds37 What browser are you using? On Chrome, it opens in a new tab...

**Comment by linds37** [comment]
Hi, Sam. I was using Chrome. I'll try again...

**Comment by linds37** [comment]
Hi. It seems to have reverted to opening in the same page - I just verified
again.

Lindsay Johnston, Public Services Manager & Subject Librarian
Rutherford Humanities & Social Sciences Library
<http://guides.library.ualberta.ca/rutherford> and Weir Law Library
<http://guides.library.ualberta.ca/law>
1-01 Rutherford Library South
University of Alberta
Edmonton, Alberta
T6G 2J8
780.492.0598

lindsay.johnston@ualberta.ca

**Comment by redlibrarian** [comment]
Hmm. I'm not seeing this behaviour. @ualbertalib/discovery-testing Can anyone else confirm this is happening to them?

**Comment by redlibrarian** [comment]
@linds37 I tried it on a Windows workstation, thinking the OS might be the problem, and it still opens in a new tab. Maybe try clearing your browser history and trying again?

**Comment by redlibrarian** [comment]
@linds37 Is this problem still happening for you?

**Comment by linds37** [comment]
Yes. I think i figured out why we're seeing different things. The new window opens when you export to RefWorks from a single record. However, RefWorks opens on top of the search screen when you export from a list of bookmarks.

**Comment by redlibrarian** [comment]
Ah, Ok. Now I understand. I'll fix this for the next release but one.

**Comment by redlibrarian** [comment]
OK, this is fixed in dev. Will be in the next release but one.

**Comment by redlibrarian** [comment]
@linds37 This is working now. Can you verify?

**Comment by linds37** [comment]
Yes, this is working fine

**Comment by linds37** [comment]
closing issue..
