### ISSUE TITLE
Author facet - displaying first name only

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#765]
From the results view, lists of authors are displaying with first names only.

**Comment by seanluyk** [comment]
As an added twist, other elements are also being displayed as authors, such as birth and death dates.

**Comment by redlibrarian** [comment]
@seanluyk Yes, this broke in the last release (through fixing something else). It will be fixed tomorrow or Friday. Same issue as #759

**Comment by seanluyk** [comment]
Working as expected now. Closing issue.
