### ISSUE TITLE
electronic access (856) links are no longer showing coverage, etc. ($3)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#767]
https://search.library.ualberta.ca/catalog/6848964
The 856 $3 text for these links differentiates the version and describes coverage, i.e.
Free Access: English version 2008-2009
Free Access: French version 2008-2009

https://search.library.ualberta.ca/catalog/6819703
University of Alberta Access: 1926-

**Comment by redlibrarian** [comment]
Sorry, @theLinkResolver , they got lost when I redesigned the link logic. The will be back, not in this week's release, but sometime before we launch.

**Comment by theLinkResolver** [comment]
@ualbertalib/discovery-testing note this temporary issue, trainers

**Comment by redlibrarian** [comment]
Actually, this will be fixed in this week's release, today or tomorrow.

**Comment by theLinkResolver** [comment]
@redlibrarian I see the fix. There is a space that is displaying before the coverage, though.

**Comment by redlibrarian** [comment]
@theLinkResolver Oh yeah. Fixed. It'll be in the final release.

**Comment by theLinkResolver** [comment]
extra space is gone. closing
