### ISSUE TITLE
It occurs to me that I don't know how we're handling deletions

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#770]
It should be pretty straightforward - we use the "d" in the leader, I think, for the Ebsco extract, so this should work:

    status_text = 000[5], ( map.record_status ), DeleteRecordIfFieldEmpty 
    map.record_status .d = null 
    map.record_status .displayRawIfMissing = 1 
    **Note that his will insert a dummy value in all records in Solr, that do 
    not have a "d" in character 5 of the leader. **

**Comment by sjshores** [comment]
You could confirm with Jim and Elaine.

Thanks,

Sandra

**Comment by redlibrarian** [comment]
@sjshores Yes, I'll do that. I'm pretty sure this is what we did to resolve the EDS problem we had last year.

**Comment by redlibrarian** [comment]
OK, I've added the deletion logic to the symphony ingest rules. I can't really test it - we'll have to keep an eye on it. For non-symphony records (SFX, Databases), this is made trickier because either we don't use marc (Databases) or we don't use the 001 as ID (SFX). I'd recommend just running a rake delete on the whole collection before ingesting these, since they don't take very long.
