### ISSUE TITLE
Subject View in Articles v Books

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#775]
In books, viewing "Subject" has a "more" option that allows you to see *all* related subjects, even if only one or two resources match for your search.
In articles, the view is limited to the top subjects by hits, with no option to see more. This makes it difficult to narrow a search by subject when your terms are common for many subjects, but rare for the subject you're looking for. 
Is it possible to add the "more" option for article subjects?

**Comment by redlibrarian** [comment]
@merisjames The subject facet in books, etc, will show you all facets present in the result set (not sure exactly what you mean by "all related subjects"). The articles facet is handled by EDS, so not easy to change. Next term, we can see what options are available for the EDS/articles subject facet. Having said that, the EDS/articles facet should *also* present any subjects available in the result set. If you think that there are subjects being excluded from the facet, can you give me an example search and an idea of what you would expect to see in the facet? Thanks.

**Comment by merisjames** [comment]
The EDS subject facet cuts off, and doesn't have the "more" popup that is available for the subject facet in books. 
The example I'm using is "bird nesting". Articles cuts off at subjects with 295 hits... I want the subjects with just 2-4 hits (which are legal subjects, rather than ornithology-related).
![2015-12-03_14-26-16](https://cloud.githubusercontent.com/assets/14880530/11574622/f5b966c2-99c9-11e5-95d1-5b0dd6986962.jpg)
v
![2015-12-03_14-26-44](https://cloud.githubusercontent.com/assets/14880530/11574625/fb057486-99c9-11e5-8bba-fb42874e11c0.jpg)

**Comment by redlibrarian** [comment]
Again, I'm thinking of passing users to the EDS result screen rather than the BL one.

**Comment by theLinkResolver** [comment]
@redlibrarian That could resolve #865 too.

**Comment by redlibrarian** [comment]
@theLinkResolver Yes, I think it actually solves a lot of problems/confusion around what people are looking at.
