### ISSUE TITLE
Articles, ebooks, and more - no results

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#776]
Apologies if this has been reported elsewhere, but I haven't experienced it in a while:

1. Pre-limiting to Articles, ebooks, and more, and searching for anything (I tried a variety of search terms) results in no search results, and the following text repeated:

No search results.

Need help? Don't hesitate to contact your local reference librarian today, or try on of these useful guides:

Library Research Guide #1
Library Research Guide #2
Library Research Guide #3

**Comment by redlibrarian** [comment]
@seanluyk I had the problem you describe twice, but now it seems to be working again. I have the feeling this is a problem on Ebsco's end. Tricia is working on making the failure when this happens more graceful.

@kgood @sjshores We might need to revisit the whole EDS question if their API is flaky. This is about the third time in as many weeks that we've noticed a problem.

**Comment by seanluyk** [comment]
Thanks for looking into this, @redlibrarian . I just tried again right now and am experiencing the same issue as you describe - no results found the first few times, and then it works OK (in Chrome). Oddly, even if I take the URL and try in another browser (Firefox), I get no results. Is this somehow session related?

**Comment by redlibrarian** [comment]
@seanluyk I'm worried that it's a problem on the EDS end, i.e. that our application is working, but their API doesn't always respond. We had some trouble with their API a few weeks ago, and I'm a bit worried about relying on their service to always be available. I'll either add this latest info to the ticket I opened with them before, or I'll create a new ticket.

**Comment by redlibrarian** [comment]
I've sent an email to David Podboy and Anna Ramsay at Ebsco to find out if there are any issues with the API, and more generally, to get a sense of Ebsco's commitment to the API. If we feel the API is not reliable enough, we may need to look into replacing the EDS API with someone else's.

**Comment by redlibrarian** [comment]
OK, we got a reassuring email from David that there was a problem with the API returning 0 results, and they have fixed it at their end. We should still monitor the situation, but I'm hoping we've seen the last of this problem.
