### ISSUE TITLE
Change empty search text for EDS results.

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#780]
When you leave the search box blank, click Articles and then click Search, you get this screen.

https://search.library.ualberta.ca/articles?utf8=%3F&q=

This is probably not the desired outcome, and I don't think this text is meant to be seen by the user.

**Comment by seanluyk** [comment]
And if you click on [No Results](https://search.library.ualberta.ca/articles?q=evil+atomizer) you get a little easter egg

**Comment by redlibrarian** [comment]
@theLinkResolver The page itself is the desired outcome - we need a place for people to land if they use an empty search, but yeah, the text itself needs to be changed. I'll change that to something simple for now, and this can be worked on next term. Check for a change in the next release, and when that's approved, we can more this issue to the January milestone.

**Comment by redlibrarian** [comment]
Check in next release after today's.

**Comment by redlibrarian** [comment]
This is done in test, @theLinkResolver

**Comment by theLinkResolver** [comment]
looks good
