### ISSUE TITLE
links in EDS to Databases, EJournals

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#781]
Are these links/buttons on the radar for when we switch to the new site? They will need to point to different urls.

![eds buttons](https://cloud.githubusercontent.com/assets/14913579/11596264/4ad84df6-9a71-11e5-9127-1ba819d85708.jpg)

**Comment by redlibrarian** [comment]
@theLinkResolver Only the **Journals** link will need to change, since I changed the journals path in Blacklight. This is easy enough to do, I'll just have to remember to do it when we launch. @kgood this will be part of the launch work.

**Comment by kgood** [comment]
EDS ejournals and database links resolve to correct blacklight based URL.
