### ISSUE TITLE
problem with title display (record with no 245a)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#784]
Likely to be examined with related work on the display of 245 elements (#718)

https://search.library.ualberta.ca/catalog/676396

**Comment by theLinkResolver** [comment]
Nice to have a couple examples, so here's another
https://search.library.ualberta.ca/catalog/910246

**Comment by redlibrarian** [comment]
@theLinkResolver Waaaaaaat. :( 

This could either be easy to fix, or a real pain. Do you know roughly how many records we're talking about?

**Comment by theLinkResolver** [comment]
@redlibrarian I feel the pain... I found a bunch more like this - probably in the area of 100 give or take.

There's also this one, with a bit of a different 245, that I can't even get to load.
https://search.library.ualberta.ca/catalog/6046607
http://www.library.ualberta.ca/permalink/opac/6046607/WUAARCHIVE

Those are a bit trickier to find. For all of the above, there is no formal bibliographic title, and the convention is to use $k, which is the form. So these titles have names like Letters, Records, etc.

**Comment by redlibrarian** [comment]
@theLinkResolver Yes, I see the $k in the Symphony records. I should be able to add that to the MARC mapping, but it will be tricky, as Blacklight seems to **only** expect the $a. If we're only talking about 100 records, let's look into this next term. For 6046607, I'll see what the underlying cause of the error is and if I can fix it.

**Comment by theLinkResolver** [comment]
@redlibrarian Sounds good. On the bright side, re. 6046607, you will see that the title does display in search results, which is certainly better than seeing the catkey.

**Comment by redlibrarian** [comment]
See commit e38aba2. I've made it so that if there's no 245a, then "Untitled document" is displayed instead. This is the best I can do for now - we'll fix it properly in January.

**Comment by seanluyk** [comment]
Thought I would share this one I stumbled upon that's missing $k and displaying the catkey as the title: https://search.library.ualberta.ca/catalog/1297946

**Comment by redlibrarian** [comment]
Ugh. @theLinkResolver can we get a number of records with no $a AND no $k? At this point, I think we'll have to leave it until next term. What's the accepted ILS/AACR2 for no $k?

**Comment by theLinkResolver** [comment]
Ok, I hadn't checked it out yet, but that record *does* have a $k. Should be okay.

**Comment by redlibrarian** [comment]
@theLinkResolver @seanluyk Ah, phew - OK. Records with **no** 245$a will fall back to the **245$k** in the final release next week.

**Comment by seanluyk** [comment]
My bad, I mean't to say it doesn't have an $a, but this is yet another twise - the title is a combination of $k and $f - this might be the case for all archival fonds records in the catalogue.

**Comment by theLinkResolver** [comment]
@seanluyk lots of examples to test is a good thing! I'm finding it quite handy to have a couple in the issue threads.

**Comment by theLinkResolver** [comment]
(I see that these are all now displaying as "Untitled document" as promised, and the unretrievable record is now retrievable.)

**Comment by redlibrarian** [comment]
@theLinkResolver @seanluyk Is this working to your satisfaction now?

**Comment by theLinkResolver** [comment]
@redlibrarian Yes and no. We can retrieve the records, and they display something other than the cateky as the title, but I think there is more work to do around the 245. We could close this and open up that more complicated discussion in another issue...?

**Comment by redlibrarian** [comment]
@theLinkResolver Let's do that. I'm going to close this issue. Feel free to open a new one with your concerns - it will likely go in the summer projects milestone.
