### ISSUE TITLE
rename articles search button/middle bento as Articles & more

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#785]
per email-based decision. The reason (documented for posterity): EDS content includes Ebsco ebook collection, but all are already catalogued (or in the queue to be), and therefore in the Books, media & more pane. Also, the team does not want to inadvertently misdirect users here if they are looking for ebooks, when all ebooks (from all sources) appear in Books, media & more.

**Comment by theLinkResolver** [comment]
I see the pre-filtering button has been renamed, but the text that appears in the search box, when you click that button, still says "articles, ebooks & more". Sorry, not sure if this is better addressed with #773

**Comment by redlibrarian** [comment]
I've asked @nnunn to take a look.

**Comment by nnunn** [comment]
done - it now says  "articles, chapters, reviews, and more".
