### ISSUE TITLE
Change Description label to "Other Details"

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#788]

**Comment by sjshores** [comment]
Other Details, please.

Thanks!

Sandra

**Comment by redlibrarian** [comment]
Sorry @sjshores - I've changed the name of this issue to reflect that.

**Comment by redlibrarian** [comment]
@sjshores Done - check in next release (after today's).

**Comment by redlibrarian** [comment]
@sjshores @theLinkResolver Do either of you have an example record for this issue (this was the 'splitting the 300 field' issue). It should be resolved in search-test, but I can't find a record with a Description field using trial and error. :) Thanks.

**Comment by theLinkResolver** [comment]
@redlibrarian No problem! https://search-test.library.ualberta.ca/catalog/4614650

**Comment by redlibrarian** [comment]
@theLinkResolver Awesome, thanks. That record now has **Other Details: 1 map**. Does that seem adequate for now?

**Comment by theLinkResolver** [comment]
@redlibrarian Should be good!
