### ISSUE TITLE
Labeling of ebooks in bento box display

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#789]
Reported by Doris:

1. Searched for Shakespeare and the role of women

The first two results both display as book, but the first is an ebook, the second is a print book.

Is it possible to distinguish ebooks from print books in this display, by either adding the ebook note that appears in the results view, or relabeling the format to ebook.

I'm also wondering if instead of **note: this is an ebook**, if the presence of an 856 could trigger the labeling as ebook?

**Comment by redlibrarian** [comment]
@seanluyk The presence of the 856 is already what triggers the eBook note. I should be able to implement this in the bento results. However, as this is based on multi-field logic (i.e. there isn't a single field that will tell us whether something is an eBook), it may not be perfect.

**Comment by redlibrarian** [comment]
@seanluyk I should add that in the release that should come out today, **Online** has already been added to the bento view for all electronic items. Let's see if that's sufficient for now before working on this.
