### ISSUE TITLE
Results inconsistency

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#790]
Currently, when you display results from articles, ebooks, and more you see **Results for ___ in Articles** at the top of the page. This should be relabeled to **Results for ___in Articles, Ebooks, & More**

**Results for ___ ** should also appear for results from the other containers.

**Comment by seanluyk** [comment]
Also Results should be capitalized in all views.

**Comment by redlibrarian** [comment]
@seanluyk I think the **in <collection>** was removed from all result pages. @nnunn was that on purpose? This change will be visible in the release that's set to come out today. If this isn't what we should have (i.e. if we should go back to displaying the collection name), let me know.

**Comment by theLinkResolver** [comment]
and to chime in (whatever the outcome), we're now calling that grouping "Articles & more"!

**Comment by seanluyk** [comment]
@theLinkResolver  - oops, yes that's right. Labeling of results for ___in ___ should be consistent between the bento and results views.

**Comment by seanluyk** [comment]
I can confirm that results for __in __  is now gone, but I think this is an issue. It would be best if users could see which results sets they were looking at. What does @ualbertalib/discovery-testing think?

**Comment by scastell** [comment]
Agree that the header should indicate which results set the user is looking at. ie Results for ___ in Articles & more.

**Comment by redlibrarian** [comment]
OK, I've set these all back to the way they were, and using the labels of the bento boxes (Books, eBooks, & more, Articles & more, Journals, and Databases)....

**Comment by seanluyk** [comment]
Has this made it to the test instance yet? Currently not seeing it there.

**Comment by redlibrarian** [comment]
No, sorry, next release.

**Comment by seanluyk** [comment]
I'm seeing "results for_____" but not "in____".

**Comment by redlibrarian** [comment]
Hmm. I'm seeing the "in..." in search-test. It will be up in production this morning, maybe check again then. / @seanluyk

**Comment by seanluyk** [comment]
I've verified that this is working correctly in all bento boxes except articles and more (which isn't currently working)

**Comment by redlibrarian** [comment]
@seanluyk The articles and more results should be working now...

**Comment by seanluyk** [comment]
This is now working with all bento boxes. Closing issue.

**Comment by seanluyk** [comment]
Reopening, as I noticed that this is not appearing from a find more by this author search. For example:
https://www.library.ualberta.ca/catalog?f%5Bauthor_display%5D%5B%5D=Cordasco,+Francesco,+1920-2001

This just shows "Results for in all library collections" and is missing the searched term. The same is not true from an advanced search.

**Comment by redlibrarian** [comment]
Hm. Now that I see this, I wonder how this should be phrased."Results for <name> in all library collections"? - does that seem OK?

**Comment by seanluyk** [comment]
I think it should return the search term, if possible, from all search screens

**Comment by redlibrarian** [comment]
Sorry, the markdown screwed up my comment. Is, for example, "Results for Cordasco, Franceso, 1920-2001 in all collections" sufficient?

**Comment by seanluyk** [comment]
Ah, I see now. I think that should be sufficient.

**Comment by seanluyk** [comment]
This appears to be working in production and test, except for find more by this author searches - those still just show results for in all library collections

**Comment by redlibrarian** [comment]
That should be in the next release, too. Thanks.

On Thu, Apr 7, 2016 at 2:59 PM, seanluyk <notifications@github.com> wrote:

> This appears to be working in production and test, except for find more by
> this author searches - those still just show results for in all library
> collections
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/790#issuecomment-207084775>
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by seanluyk** [comment]
Trying to test the small part of this issue that wasn't working (in find more by this author searches), but can't seem to find this anywhere on a record. Now that author names are hyperlinked, is this no longer there? This is OK to close otherwise.

**Comment by redlibrarian** [comment]
Yes, since we figured out how to hyperlink the author names, we removed the "find more by" search link.
