### ISSUE TITLE
Placement of url in database entry

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#791]
Hi. Not sure if this has already been addressed - the placement of the url in this database entry is problematic https://search.library.ualberta.ca/catalog/11711117
Can it be moved to the top, or linked in the title?

**Comment by redlibrarian** [comment]
@linds37 It's can't be linked in the title. I'll see if I can move it up in the page, but this may need to wait until next term.

**Comment by redlibrarian** [comment]
@linds37 This is done. It will be visible in the next release after today's.

**Comment by redlibrarian** [comment]
@linds37 The URL has been moved, and this change is currently visible in test: https://search-test.library.ualberta.ca/catalog/11711117 / @sjshores

**Comment by redlibrarian** [comment]
@linds37 This is now in production. Can you verify?

**Comment by linds37** [comment]
Yes, looks great!
