### ISSUE TITLE
Reconcile active/inactive databases between eds and api2 instances.

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#792]
I believe this came up when we first implemented EDS, but perhaps it's even more relevant now.

I'm wondering if we should suppress the Harvard Library Dataset from the articles & more results? Would this have to be turned off completely from EDS?

It may cause users some confusion when they see books duplicated between different bento containers (or aren't expecting to see books in this results list). There is some potential value in seeing these here too though, so I'm not sure if this is wise.

**Comment by redlibrarian** [comment]
Gah. The instance of EDS we use for the API has it's own list of active/inactive databases. I'll have to go through them and make them all correspond. @seanluyk Harvard Library data will be removed from Articles and more for go-live.

**Comment by seanluyk** [comment]
Thanks @redlibrarian , and *of course* the EDS API would do that!

**Comment by redlibrarian** [comment]
OK, this has been done. The harvard dataset was the only inconsistency. It's now been disabled. @seanluyk This change should be available in about half an hour, if there's a test search you have.

**Comment by seanluyk** [comment]
Still seeing this in the test instance - Harvard Library Bibliographic Dataset comes up as a content provider for a search for chemistry

**Comment by redlibrarian** [comment]
Weird. I double-checked that it's been disabled... let's wait another day or so and try again. This isn't dependent on a code release, so I can keep investigating if disabling it doesn't work soon. @seanluyk

**Comment by seanluyk** [comment]
Sounds good, I'll have another look and let you know what I find @redlibrarian

**Comment by redlibrarian** [comment]
@seanluyk I'm not seeing Harvard Bibliographic Dataset anymore. It might just have taken a while for the change to take effect.

**Comment by seanluyk** [comment]
Not seeing the Harvard Bibliographic Dataset as a content provider. Closing issue
