### ISSUE TITLE
rename format facet Serial to Journal (Symphony and SFX records)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#793]
As per email discussion. There is a general preference for the word Journal in public display. Group acknowledges that everything serial (yearbooks, annotated acts, annual reports, etc.) will be labelled as Journal. Future efforts will be made to relocate annuals, biennials, conference proceedings, and mono series to Books, media & more container.

**Comment by redlibrarian** [comment]
OK, I've changed it back. It will be in the next release.

**Comment by redlibrarian** [comment]
@theLinkResolver This is done in test.

**Comment by theLinkResolver** [comment]
done
