### ISSUE TITLE
"format" for EDS results (source type vs. document/publication type)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#794]
This is an issue raised during one of the training sessions.

In the grid view for the Articles results, there is a term in parentheses after the title. The same term is listed as "format" in the results lists. Here is a sample search: 
http://bit.ly/1XTVyTS

I don't see these terms in the EDS record, but what the term means, when it is Academic Journal for example, is that the item is an article FROM an academic journal, rather than being an academic journal itself.

People would like to see the term from the Document Type field, such as "Article", in the grid and list views. 

However, it looks like not every EDS record has that field. Perhaps, then, it's a case of preferring the Document Type term, and using the Publication Type term if the former is not present (e.g. a thesis).

**Comment by seanluyk** [comment]
I'm wondering if this only applies to articles - I'm seeing other item types accurately represented (e.g. reviews, theses, etc.).

**Comment by redlibrarian** [comment]
This is baked into the EDS API results. I can probably fix it, but not before we launch.

**Comment by theLinkResolver** [comment]
One of the trainees made an interesting point that we see these same terms in the results lists within EDS and, in that context, we don't think anything of it. But the terms do seem out of place in the article container. Definitely an enhancement, not a showstopper.

**Comment by redlibrarian** [comment]
Again, I'm thinking of passing users to the EDS results screen, rather than BL.

**Comment by theLinkResolver** [comment]
@redlibrarian That will help clarity for a pre-limited articles search but not for the parenthetical terms we see in the grid view, unfortunately.

**Comment by theLinkResolver** [comment]
just want to cross-reference issue #705 here
