### ISSUE TITLE
database descriptions not indexed for searching?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#795]
This is an issue from a training session.

It does not appear that the database descriptions are being searched, but this is an expected behaviour.

Example for testing:
https://search.library.ualberta.ca/catalog/11710398

If a person searched for Baker's Dictionary of Music, it would be desirable for the above database to show up.
Search results:
https://search.library.ualberta.ca/results?utf8=%3F&q=Baker%27s+Dictionary+of+Music

**Comment by seanluyk** [comment]
Yes, it would be great if the database descriptions were indexed! In some cases, the name of the database doesn't accurately reflect what it contains, or useful information is buried there.

**Comment by redlibrarian** [comment]
@theLinkResolver @seanluyk This should already have been in place. It will be fixed in the final release.

**Comment by theLinkResolver** [comment]
works now for the example above - great!
