### ISSUE TITLE
better name for "format" facet?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#797]
@ualbertalib/discovery-testing I've tried not to let this one get to me, but it came up in training - and I'm not counting my unnecessary interruption of @gooyers today :(

As we all know now, the filter term "format" is used to describe the *type of content/material* described by a given record, rather than the version/form/manifestation of the item (online, braille, microfilm, etc.).

"Format" was probably a well-intentioned, out-of-the-box Blacklight term. I think we're now in a position to do better. For one, it's reeks a bit of library jargon. Secondly - and related - it might not even mean anything to some users (as @gooyers found in usability testing). And strike three, the root of the word being "form" aligns it with the other concept (how is the content conveyed).

Timelines aside, let's use this issue to find a better term. Like everything else, whatever we choose won't please everyone, but we should do our due diligence, since it has come up.

Here's the full list of terms comprising this facet, for reference purposes:

Collection
Part of Collection
Continually Updated Resource
Book
Journal
Musical Score
Music Manuscript 
Cartographic Material
Manuscript Cartographic Material
Video or Projection
Sound Recording
Musical Recording
Graphic
Computer File
Kit
Mixed Material
Object
Manuscript
Other

**Comment by theLinkResolver** [comment]
and some suggestions... (you'll see a pattern)

Type of material
Material type
Type of content
Content type
Type of resource
Resource type

**Comment by redlibrarian** [comment]
Perhaps we need to define what characterizes jargon. Looking at the list above, all of those (with the possible exception of type of material/material type) sound jargony to me. AFAICT, only library people and computer people talk about "resources" in this way.

**Comment by theLinkResolver** [comment]
re. jargon - hey, I could have offered up "type of expression"! Or even worse - "realization of work". But yeah, not actually much of a fan of "resource". Really hoping there are some better ideas out there among us!

Another approach might be to have these facets auto-expanded, so no one has to guess what the label means.

**Comment by seanluyk** [comment]
I'm OK with format, but I see what Scott's getting at. IMO, resource probably more accurately describes the various terms that go in the format facet, and is better aligned with current terminology used in bibliographic description.

As for jargon, I'm not entirely against using it if it's the correct term that our profession/discipline uses. Users at a university are already accustomed to learning the jargon of their disciplines, so it's not unreasonible for us to expect them to learn some of the jargon from our discipline as well, if it's more accurate. Format is already jargon, but maybe just older jargon?

**Comment by redlibrarian** [comment]
I haven't heard any user reports that this is a problem. I'd propose closing it and seeing if anything arises from usability testing or user reports.

**Comment by theLinkResolver** [comment]
I'm content knowing the concerns have been logged and discussed here, should the issue need to be revisited.
