### ISSUE TITLE
searchability of earlier and later titles

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#803]
earlier_title_tesim and later_title_tesim (sourced from 780 and 785) should be included in searched fields. I would *guess* that the appropriate weighting would be somewhere around where the title_addl is. These should also be included in the title search.

Relevance ranking is so good that I did not notice this sooner - variations in title are usually not very dramatic, and related titles are usually somewhere in the results. But often titles change completely.

Example for testing:
https://search.library.ualberta.ca/results?utf8=%3F&q=your+autism+magazine

The above search should return this title in the results:
https://search.library.ualberta.ca/catalog/397387

**Comment by redlibrarian** [comment]
I've add this to the appropriate indexed. Check in next release.
