### ISSUE TITLE
ensure correct placeholder text in search box

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#804]
@redlibrarian Just to make 100% sure on these. I think you more or less told me not to worry yesterday, but I think we both like it in writing. :)

![ebooks](https://cloud.githubusercontent.com/assets/14913579/11730277/34be4f22-9f51-11e5-994c-9098c5260b8d.jpg)

![journals](https://cloud.githubusercontent.com/assets/14913579/11730279/3d8b4fe2-9f51-11e5-8cc6-7ee6f83f462c.jpg)

**Comment by redlibrarian** [comment]
Yes, these are both correct right now on my workstation...

**Comment by theLinkResolver** [comment]
These look good now but I see this is assigned to @redlibrarian so I will leave for you.
