### ISSUE TITLE
ensure correct labels for Articles & more container

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#805]
@redlibrarian Hopefully okay in final release as per our conversation yesterday.

![ebooks in grid](https://cloud.githubusercontent.com/assets/14913579/11730376/f2d9f600-9f51-11e5-9e9f-c78d2276e55f.jpg)

![ebooks grid 2](https://cloud.githubusercontent.com/assets/14913579/11730380/f7516484-9f51-11e5-872f-46970ce5355f.jpg)

(okay to laugh at my red Xs)

**Comment by redlibrarian** [comment]
Yes, both of these are correct on my workstation right now.

**Comment by theLinkResolver** [comment]
looks good
