### ISSUE TITLE
OUR (Our Usage Rights) truncated

### ISSUE THREAD

**Issue by sjshores** [ualbertalib/discovery#806]
Hope I'm not duplicating an existing issue, but the OUR (Our Usage Rights) information is often truncated, especially if the notes or coverage information takes up too much space. e.g. CMAJ.
![2015-12-10_16-02-38](https://cloud.githubusercontent.com/assets/8203132/11731986/0c54267c-9f5d-11e5-9ad2-fe1382e1a877.jpg)

**Comment by sjshores** [comment]
Note, this is in SFX journal records in the journals box.

**Comment by redlibrarian** [comment]
@sjshores I've fixed this for now by hardcoding width percentages. This isn't a great permanent solution, but my CSS is rusty. @nnunn will have to look into this in the new year. It should fix the problem for now.

**Comment by redlibrarian** [comment]
@sjshores Looks like this is working in test now. https://search-test.library.ualberta.ca/catalog/954925545272  Should be up in production this morning.

**Comment by redlibrarian** [comment]
Fixed in production. Closing.
