### ISSUE TITLE
Switching between list and grid on the advanced search results page--problem

### ISSUE THREAD

**Issue by sjshores** [ualbertalib/discovery#807]
I just did my happiness search on the latest code release as an all fields term on the advanced search page.  The results came back as a list and looked good--the right number of records was returned. When I clicked to switch to the grid view, my search was lost.  I was taken to the grid view, but the results were the entire index (minus EDS article content), not my search results.

**Comment by redlibrarian** [comment]
Oh, this seems to happen only when you do an advanced search, as advanced search doesn't use the simple "q" parameter... we'll have to figure out how to pass all of the params between the controllers...

**Comment by redlibrarian** [comment]
Ugh. I can pass all the relevant parameters back to the controller, but the bento controller doesn't understand them (because it wasn't designed as an advanced search result view....). Hmm. I'm going to have to rethink this...

**Comment by redlibrarian** [comment]
As per the last DTTT meeting, we're going to remove the grid/list toggle, as the potential for it to be confusing outweights the usefulness.
