### ISSUE TITLE
Labeling on French version of search

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#808]
It looks like the new labeling of pre-limits did not carry over to the French version for the following labels:

-livres et journaux imprimés
-livres numériques
-journaux électroniques

**Comment by redlibrarian** [comment]
I found and fixed one instance of journaux électroniques, but I think that was just a place holder. @kgood @nnunn Are these set in the CMS? Can we change them there?

**Comment by redlibrarian** [comment]
OK, this was changed in the CMS and is live now. @seanluyk and @gooyers do you want to take a look and confirm?

**Comment by seanluyk** [comment]
Looks good to me!

**Comment by gooyers** [comment]
Thanks for catching this @seanluyk!

One thing I'd add is that **livres et plus** could be **livres, médias et plus**. Thanks again

**Comment by gooyers** [comment]
Dorothée can translate the hover labeling of the pre-limits early next week (Books and more, Articles and more, and Journals all have hover text).

**Comment by redlibrarian** [comment]
Thanks @gooyers ... I'll make that change this afternoon. Then, since this change take immediate effect, can I close this issue?

**Comment by redlibrarian** [comment]
Ah, OK, I'll leave this issue open until then, then. / @seanluyk @gooyers

**Comment by redlibrarian** [comment]
OK, that change has been made.

**Comment by redlibrarian** [comment]
@gooyers If you or Dorothée can give me the hover text, I'll fix them right away.

**Comment by redlibrarian** [comment]
Pinging @gooyers
