### ISSUE TITLE
Bento box and search from French version

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#809]
A search from the French version of the website returns an English grid and list view. 

Are there plans to make the search fully bilingual? I recall seeing it in French before.

**Comment by redlibrarian** [comment]
@sjshores @kgood Gerald asked this question too in the training session. Can one of you address this one?

**Comment by sjshores** [comment]
We can discuss this with Trish this afternoon, but my recollection was that
the search portion of the website was not going to be in French.  Sam, does
BL come with an easy option for French?

**Comment by redlibrarian** [comment]
@sjshores @kgood @seanluyk My impression was that we would be translating the top level web-pages and leaving the rest untranslated, and that that had been worked out with Tatiana.

On the technical side, we would have to go through the same process that @weiweishi went through with DMP - translation/local files for French would have to be created. We would also have to make sure that the custom text that we've added is also covered. Ideally we could get a locale file from another institution to start from, but given that most of the Blacklight implementations are American, I doubt they'll have French locale files worked up.

**Comment by seanluyk** [comment]
@redlibrarian for now, if it were easy enough to label the pre-limits and grid view in French that would be enough. I know of a German blacklight implementation, which doesn't help us unfortunately :)

**Comment by redlibrarian** [comment]
@seanluyk I'll make the changes to the home page and bento view today, and then we can address any other French language stuff later on. Looping @gooyers in just to keep him informed.

**Comment by gooyers** [comment]
Thanks @redlibrarian. As far as I've been made aware, the plan is currently to translate (and keep up to date) the new homepage, and a few select services-oriented web pages (for example, the Ask Us page). 

There are no established plans to translate the interface of the search tool. I discussed this with Dorothée in passing the other day, and we'll be keeping our ears open for feedback from our faculty and international students on the English-only interface.

**Comment by redlibrarian** [comment]
I'm going to close this issue for now. Please reopen if anything changes.
