### ISSUE TITLE
Records missing geographic term (651)

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#810]
Pointed out by an HSS colleague. Not sure if this is an isolated case:

The geographic term from [this record](http://www.library.ualberta.ca/permalink/opac/3441490/WUAARCHIVE) did not make it to [its Blacklight record](https://search.library.ualberta.ca/catalog/3441490). 

This is also the case for the record for the [electronic version](http://www.library.ualberta.ca/permalink/opac/3946060/WUAARCHIVE), the term is missing from the [Blacklight record](https://search.library.ualberta.ca/catalog/3946060).

I think what's happening is that the 651 is being stripped away and added to the geographic region facet (which is good), but it probably should still also be displayed on the record itself, as it also acts like a regular subject heading.

**Comment by redlibrarian** [comment]
@seanluyk I can display it raw in the record in the final release, but I won't have time to give it the hyperlinked treatment we give the 650s before we launch. Is this acceptable for now? We'll display it in the record, but we won't make it clickable until the April release?

**Comment by redlibrarian** [comment]
OK, this is set to be displayed in the final release, but only as a raw display. When that's been confirmed let's move this issue to the v.2.0.0 milestone so we can make geographic subject work the same as the other subject terms.

**Comment by seanluyk** [comment]
Excellent, thanks @redlibrarian

**Comment by seanluyk** [comment]
I'm seeing the geographic subject, but not the rest of the heading. Not a showstopper of course, but I think we should keep this open until geographic subject headings work the same as topical subject headings (displayed in full, and hyperlinked with ability to add/remove headings from the hierarchy)

**Comment by redlibrarian** [comment]
@seanluyk Sounds good. I'll move this to the January milestone.

**Comment by seanluyk** [comment]
It looks like this is partially working now, but in this example only Saskatchewan shows up under geographic subject, and encyclopedia is not there. Here's another example (where the subdivision is also removed (651 $v missing):

https://search.library.ualberta.ca/catalog/1448822

**Comment by redlibrarian** [comment]
Hi Sean,

It's not in production yet. If you try the same record in search-test, you
might be able to see the correct Geographic subject string (I'm not sure if
that version of the application is in test yet, but should be shortly).



On Thu, Apr 7, 2016 at 2:46 PM, seanluyk <notifications@github.com> wrote:

> It looks like this is partially working now, but in this example only
> Saskatchewan shows up under geographic subject, and encyclopedia is not
> there. Here's another example (where the subdivision is also removed (651
> $v missing):
>
> https://search.library.ualberta.ca/catalog/1448822
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/810#issuecomment-207081258>
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by seanluyk** [comment]
Doesn't appear to be in test yet - but I'll check back again

**Comment by redlibrarian** [comment]
Thanks. I can let you know when the latest release is in test.

On Thu, Apr 7, 2016 at 2:49 PM, seanluyk <notifications@github.com> wrote:

> Doesn't appear to be in test yet - but I'll check back again
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/810#issuecomment-207082147>
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by redlibrarian** [comment]
I don't know why it's not in test yet. I've asked our sysadmin.

**Comment by seanluyk** [comment]
Geographic subject is appearing now, closing
