### ISSUE TITLE
Lakeland internet library is misnamed

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#811]
https://search.library.ualberta.ca/symphony?f[location_tesim][]=lakelndin&q=

The library is displayed as Lakeland College Lloydminster for LAKELND_IN. The correct name is:

Lakeland College Internet

(LAKELND_LL is correct as is - showing as Lloydminster)

**Comment by redlibrarian** [comment]
OK, fixed. It will be visible in the next release.

**Comment by redlibrarian** [comment]
@theLinkResolver This should be working now in test.

**Comment by theLinkResolver** [comment]
fixed
