### ISSUE TITLE
AGL library filter is misnamed

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#812]
AGL_CAP is displayed as Alberta Government Library Internet, but should be just Alberta Government Library.

https://search.library.ualberta.ca/symphony?f[location_tesim][]=aglcap&q=

**Comment by redlibrarian** [comment]
Hm. Now that I look at it, I think my list of AG libraries hasn't been updated. @theLinkResolver can you tell me how to get a list of NEOS libraries and codes in workflows? The list I currently have is

aginternet: "Alberta Government Library Internet"
aglcap: "Alberta Government Library Capital Boulevard"
aglgwl: "Alberta Government Library Great West Life"
aglssp: "Alberta Government Library" -- this one is incorrect I think.
agltpn: "Alberta Government Library Telus Plaza"
aglcom: "Alberta Government Library Commerce Place"
agllb: "Alberta Government Library Labour Building"
aglmnc: "Alberta Government Library Monenco Building Calgary"
aglncc: "Alberta Government Library Neil Crawford Centre"

But do all these branches/locations still exist? @sjshores

**Comment by theLinkResolver** [comment]
@redlibrarian There must be a better way than this, but you can open a wizard like Item Search and Display and then chug through the drop-down list. Peggy Morgan would be my go-to if I wanted to find a better way.

And indeed, only two AGL locations now exist: AGL_CAP and AGINTERNET. Since there is only one branch, we don't seem to call AGL_CAP Capital Boulevard anymore - just Alberta Government Library.

**Comment by redlibrarian** [comment]
@theLinkResolver OK, great. I'll push that change through right away...

@sjshores When Blacklight is in production, we'll have to make sure we have some kind of workflow around keeping these lists updated. It's clunky, but maybe there's a way to streamline it.

**Comment by theLinkResolver** [comment]
fixed
