### ISSUE TITLE
(Question) How searchable is William C. Wonders Map Collection?

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#817]
I saw the William Wonders #29 referred to as an included data source (though that's from quite some time ago), and we also make reference to the map collection as being included in the new search tool within the training script. 

I don't have much experience using the William Wonders collection (http://maps.library.ualberta.ca/index.cfm), but I can't seem to locate items in the database within Blacklight. 

For example, when I search **England and Wales C-5** by call number in the map collection I return 11 results. 
![2015-12-11_16-06-27](https://cloud.githubusercontent.com/assets/14891931/11757762/56a0b3e8-a021-11e5-931d-168f5b30e0fb.jpg)

Upon clicking into a record, I tried searching within Blacklight using Title or Call Number but I received no results. 

![2015-12-11_16-06-55](https://cloud.githubusercontent.com/assets/14891931/11757775/72499f56-a021-11e5-883e-23f71b98d918.jpg)
![2015-12-11_16-07-30](https://cloud.githubusercontent.com/assets/14891931/11757781/774c1f2e-a021-11e5-87a8-06338ee34072.jpg)

This is very possibly me not understanding how the William C. Wonders collection is included in Blacklight. But I thought I would ask the question here, in case something unintended was going on.

**Comment by redlibrarian** [comment]
Hi @gooyers No - the Wonders database isn't included yet. It's earmarked for what's now Phase 3.

**Comment by gooyers** [comment]
Ah okay. It was my misunderstanding, it's mentioned in the training speaker notes as a collection that is not searchable at all. That *will* change, but isn't the case yet, so there's nothing misleading about the speaker notes. Thanks @redlibrarian!
