### ISSUE TITLE
Database description - image issue in Chrome

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#820]
This is a very minor one, only happening in Chrome:

-There is a small missing image icon displaying in database description pages in Chrome. For example, see [RIPM](https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=3401) and [RILM](https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=1469)

![image](https://cloud.githubusercontent.com/assets/14880206/11816706/d579bff8-a30e-11e5-82d0-307e0b823390.png)

**Comment by redlibrarian** [comment]
@seanluyk Ah, this isn't a problem with the discovery system, but with the database pages. @kgood can you take a look?

**Comment by seanluyk** [comment]
Oops, my bad

**Comment by redlibrarian** [comment]
@seanluyk Nope, no worries. It's hard to tell where the boundaries are, and this will get to Kenton in any case. :)

**Comment by kgood** [comment]
Closing old issue.  Images now work in Chrome
