### ISSUE TITLE
No results in symphony, databases, or journal boxes (+ French website not up to date)

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#821]
A smaller issue first, the french website should be updated to reflect the changes made on Friday.

![2015-12-15_11-00-55](https://cloud.githubusercontent.com/assets/14891931/11819062/2f77bb5c-a31b-11e5-9dd7-8a257e4dc66c.jpg)

The main issue, is that I've tried a few searches ([example](https://search.library.ualberta.ca/results?utf8=%3F&q=histoire)) this morning and received the same result: no results being returned in any box except the EDS box. At first I thought this issue was limited to the french website (I swear I had one search on the English version return a normal result set). But it's an issue on both versions of the site for me.

![2015-12-15_11-02-51](https://cloud.githubusercontent.com/assets/14891931/11819133/81b963de-a31b-11e5-9ffb-407b1356fcff.jpg)

**Comment by redlibrarian** [comment]
@gooyers That was a temporary outage while we update to the new index. The french website should be updated with the new code shortly. We can take a look then.

**Comment by redlibrarian** [comment]
@gooyers Can you take a look - everything should be back and working now. Let me know if you still see any problems.

**Comment by gooyers** [comment]
Yup! All is well, I'll close the issue. 
If the french website is set to be updated next update, that's great to hear too.
