### ISSUE TITLE
summary holdings statement is back

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#822]
@redlibrarian Noted that the "Library has" statement is back with the latest release. e.g. https://search.library.ualberta.ca/catalog/359529

It needs to go away again..

**Comment by seanluyk** [comment]
Does it need to stay for items where placeholder records are created (e.g. micro)? Thinking of issue #691

**Comment by redlibrarian** [comment]
I can't remember if I ever got around to removing it or what, but I've suppressed it in the latest code. If we have a chance to do one more code release the summary holdings statement will be suppressed for launch, if not, it will have to wait until January. I'm not sure about @seanluyk 's question. / @theLinkResolver

**Comment by theLinkResolver** [comment]
@seanluyk You're right - this is important, as it's the only place that microform holdings are described, but there's currently no logic in place to correctly identify, display and label the microform holdings. :(

**Comment by redlibrarian** [comment]
@seanluyk @theLinkResolver Let's put this on the list of things to talk about next term.

**Comment by scastell** [comment]
Something else to consider re summary holdings statements

Summary holdings statements appear to be the only way to identify holdings for periodical titles for which we have current print subscriptions but item records are not created for the individual issues at time of receipt. Reasons include print copies retained until microfilm/fiche is received, current x years  only retained (not sure how many of these are left) and others ie Der Spiegel.

Der Spiegel
UAHSS 
Location:	NORTH_1-- AP 30 S75
Library has:	38.Jahrg.(1984)-47.Jahrg.(1993); 1993- Incomplete: 1998,2005-2013 Current issues in Rutherford North Flr 1; others On Shelf

Last Der Spiegel issue  with an item record is AP 30 S75 2013: Nr.23-28; Most recent issue received is JAHRG.2015 NR.49 NOV 28, 2015
<a href="http://www.library.ualberta.ca/permalink/opac/389778/WUAARCHIVE">Entry in classic catalogue</a> 
Entry in <a href="http://www.library.ualberta.ca/permalink/opac/389778/WUAARCHIVE">New search tool</a>

**Comment by theLinkResolver** [comment]
Summary holdings are suppressed again. I've cross-referenced @scastell's remarks in #691 for future reference, so I can close this issue.
