### ISSUE TITLE
blank search of journals returns an error

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#823]
https://search.library.ualberta.ca/ejournals?utf8=%3F&q=

You can see by the resulting url what the problem might be!

**Comment by redlibrarian** [comment]
Fixed and live now. I'm going to close this.

**Comment by theLinkResolver** [comment]
@redlibrarian  This is broken again.

**Comment by theLinkResolver** [comment]
(all pre-filtered journal searches return an error)

**Comment by redlibrarian** [comment]
@theLinkResolver I fixed it again. I think the reason this problem keeps coming back is miscommunication on our end...

**Comment by redlibrarian** [comment]
@theLinkResolver Can you confirm it's working and close ticket if it is? Thanks.

**Comment by theLinkResolver** [comment]
Fixed.
