### ISSUE TITLE
items table missing

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#824]
https://search.library.ualberta.ca/catalog/1705621

I haven't been able to find another record with this problem yet.

**Comment by redlibrarian** [comment]
Looks like the timeout we set is too short for items with numerous holdings. I've raised the timeout and it works in dev, so this should work in the next release.

**Comment by theLinkResolver** [comment]
@redlibrarian Can you check these in dev, too? These are some of the longest records I can think of at the moment:

https://search.library.ualberta.ca/catalog/815666
https://search.library.ualberta.ca/catalog/554236

**Comment by redlibrarian** [comment]
OK, thanks for those. The first one loaded fine in dev, but the second one (Paper-) did not, so I've raised the timeout until it loads. This won't be in production today, but will be when we go live in January.

**Comment by theLinkResolver** [comment]
@redlibrarian Seeing these results in production, now. I will leave this open for the sake of testing the final example in January.

**Comment by redlibrarian** [comment]
@theLinkResolver I'd like to either close this or move it to the v.3.0.0 milestone - I think all but the last example now loads the holdings table.

**Comment by redlibrarian** [comment]
... moving it to January's milestone to check.

**Comment by theLinkResolver** [comment]
@redlibrarian The items table is there now, but it seems to be incomplete. There are 1,996 entries, but I believe there should be 3,452.

On further inspection, the items list is incomplete in the classic catalogue, too. So there's that...

**Comment by redlibrarian** [comment]
OK. These tables are in place in production now. It's slow, but they appear...
