### ISSUE TITLE
UofA Access links

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#825]
Not a major issue, just wondering why UofA Access links state UofA access twice (second time in brackets. Probably OK to remove the bracketed portion:

![image](https://cloud.githubusercontent.com/assets/14880206/11847520/2b7bfdfe-a3db-11e5-82e0-b96bafc90c5d.png)

**Comment by redlibrarian** [comment]
@seanluyk The bracketed portion **usually** contains the coverage (e.g. "1926-"), so the "University of Alberta Access" isn't repeated. This must be a data issue. I'll have to track it down. / @theLinkResolver

**Comment by seanluyk** [comment]
The records in question are from Alexander Street Press streaming databases if that helps.

**Comment by redlibrarian** [comment]
Looks like we have three (at least) kinds of labeling in our 856 links: "University of Alberta Access", "University of Alberta Access (<usage information>)" and "University of Alberta Access: <date information>". I'll see what I can do to clean this data up. / @theLinkResolver

**Comment by redlibrarian** [comment]
OK, I think I have this straightened out. In the next release we should check:
https://search.library.ualberta.ca/catalog/5947179
https://search.library.ualberta.ca/catalog/5025237
https://search.library.ualberta.ca/catalog/6702041

To make sure all versions of the label are displaying properly.

**Comment by theLinkResolver** [comment]
@redlibrarian That's right - single items/monographs are just captioned by "University of Alberta Access" while serials follow that with a colon and the coverage statement.
Before the UA button was moved up, the entire $3 was displayed as the button text. Would that solve it, to revert to that?

**Comment by redlibrarian** [comment]
I think it's solved now. Take a look when the next (and last!) release is up (hopefully Friday).

**Comment by theLinkResolver** [comment]
Ah yes, the $z is also quite important - usage limits and tips for finding content. Usually but not always enclosed in parentheses. 
some more examples to check on: 
https://search.library.ualberta.ca/catalog/6585660
https://search.library.ualberta.ca/catalog/6877258
https://search.library.ualberta.ca/catalog/7102811

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver The display for these translates into (e.g.) **Click Here for University of Alberta Access (2002- Click on the German flag to access this title)** and **Click Here for University of Alberta Access (Click "Index and Contents" tab to find this title within "Cases" folders)** which might not be **ideal** but I think is fine for now.

**Comment by theLinkResolver** [comment]
@redlibrarian Just needs to be clean and that seems to be the case now - great!

**Comment by theLinkResolver** [comment]
Looks good for all examples.
