### ISSUE TITLE
display call number & location in list view if filtering to a single library

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#830]
Suggestion from training session.

We previously examined the possibility of including the call number in results views, but determined that there was no way to display the call number that the user would want to see, as there are variations between branches and library systems. issue #645 

But what if there was a way to have the call number and location appear when results have been filtered to a single library?

**Comment by theLinkResolver** [comment]
Thinking about this more.. I should acknowledge that the concept works nicely for most monographs but there are complications for multi-volume sets and serials (due to potentially long lists of items; there could be a need to limit the number of items that would be displayed).

**Comment by redlibrarian** [comment]
Hm. This logic would actually be quite tricky to implement. I think for this one, I'd like to see how it plays out after a term (see if we hear any complaints about it). Are you OK with closing this issue for now and reopening it if it comes to be an issue?

**Comment by theLinkResolver** [comment]
@redlibrarian I'm agree with that approach.
