### ISSUE TITLE
named collection as a facet/filter

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#832]
Based on some discussion at training session.

The idea is to add named collections as a filter. Right now, these are represented by strings of local note text, e.g. University of Alberta copy in the Sarjeant History of Science Collection. The current way of searching for a collection is to identify and search for that phrase in the catalogue, which of course you can do in Blacklight already. The 'new' idea is to bring those collections forward as filters.

**Comment by sjshores** [comment]
Interesting idea, especially since we've had a number of questions from
keen users about searching for these collections.

Sandra

**Comment by redlibrarian** [comment]
We'd need to do a little processing of the 590 field, but I think this is a good idea.

**Comment by redlibrarian** [comment]
Done when:

- [ ] MARC 590 field is parsed to extract a collection name
- [ ] Facet built on that Solr field

**Comment by redlibrarian** [comment]
I've rewritten this issue as #1177 to include the information needed for the dev team. Closing this issue.
