### ISSUE TITLE
filtering/identifying locations within libraries

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#834]
Suggestion from training session.

There was an enquiry about filtering for collections/locations within a certain branch, such as HSS Music, Sci/tech Polar, Education Curriculum.

**Comment by theLinkResolver** [comment]
Or I guess, filtering for these alongside the existing library locations.

**Comment by seanluyk** [comment]
I like this idea, but wonder how useful it would be considering the many shelving locations that reflect circ rules instead of actual locations (e.g. no loan).

Perhaps there are some locations that we would want to turn this feature on for, but not others.

**Comment by theLinkResolver** [comment]
Been thinking more about this one and want to log some thoughts. I would disregard my earlier comment about trying to mix them in with the Library filters -- having a separate filter for them makes more sense. However.... by my count, there are around 55 valid UAL shelving locations (!), with many more possibilities throughout NEOS. 

It would be interesting to see if mapping all the UAL ones would prove too unwieldy. In theory, for any given search, there would be no hits for a good number of locations (e.g. Oversize flat, Data Ref, Trad Medicine, Polar Pamphlets, Music Mini, and so on). The benefits of being able to filter to Reserve, Curriculum, Microfilm, the various Music locations, etc. would likely be appreciated by users and staff. It is a mostly static list, as far as maintenance goes.

(note: circ rules like No Loan are mixed with item types, rather than shelving locations, so we don't need to worry about that, if we go down this road)

**Comment by seanluyk** [comment]
Being able to filter by specific music locations (especially music mini vs. music vs. music os) would be really helpful. I'd worry about putting too much work into adding this functionality given that I've already "killed" 3 shelving locations in music since starting here, so it's possibly others will disappear (e.g. music mini, music reference) in the near future.

**Comment by redlibrarian** [comment]
Duplicat of #832 (and probably at least one other issue). I'm going to close this one for now.

**Comment by theLinkResolver** [comment]
This issue is not a duplicate of #832. That issue is about filtering based on the 590 note. 

This one is about filtering item locations (from the item record, e.g. On Shelf, Curriculum, Polar, Music, Reserves). Indeed, that is the same as issue #419.
