### ISSUE TITLE
database not in results

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#835]
Looking for this one:
https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=4251

https://search.library.ualberta.ca/databases?utf8=%3F&q=Monthly+Catalog+of+US+Government+Publications

**Comment by theLinkResolver** [comment]
oops, see edit

**Comment by redlibrarian** [comment]
This database has no assigned subjects. The acquisitions team will be adding default subjects to newly licensed databases, but someone will need to go through the existing ones to assign subject. @kgood Is this something April & Sam C were going to do?

**Comment by redlibrarian** [comment]
@theLinkResolver As per Ernie's email just now, CDC has decided to purge the free databases from libguides. I believe the free databases have not been assigned a subject, as we knew they were going to be purged. So this record will disappear with the purge. Worth checking in January after that has been done.

**Comment by theLinkResolver** [comment]
@redlibrarian This one (Monthly Catalog of US Government Publications) is licensed, as opposed to the other one (Catalog of U.S. Government Publications), so it should remain in the list. agreed @merisjames ? Just needs a subject assigned?

**Comment by redlibrarian** [comment]
@theLinkResolver @merisjames Any librarian can add a subject assignment in LibGuides, and this will cause the database to be indexed in Blacklight. If a database has no subject after the free resources have been removed from LibGuides, someone in ITS will add a general subject so the database gets indexed.

**Comment by merisjames** [comment]
I'm pretty sure there was a "Government Information" subject, but there isn't any more... Although there is a "Information Gouvernementale" subject.

**Comment by redlibrarian** [comment]
@merisjames @theLinkResolver A few months ago a group met (collections and a public service manager (Angie), along with ITS) and decided that database *content* would primarily reside with public services to manage. I don't know how that's going to play out in practice - @linds37 this might be a question for PSC.

**Comment by redlibrarian** [comment]
The whole database questions is going to be looked at holistically. Is this particular issue resolved (i.e. can the issue be closed)? @merisjames

**Comment by merisjames** [comment]
I think that from the blacklight perspective, we're waiting on higher level
decisions , so yes, this can be marked as resolved.

**Comment by redlibrarian** [comment]
Thanks.
