### ISSUE TITLE
display edition in grid and/or list views?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#839]
I think this was alluded to in a training session last week, in relation to the discussion of this title: https://search.library.ualberta.ca/results?q=canadian+fundamentals+nursing

Edition could be a desirable piece of info to display in the grid and/or list view (if it can be done without making things cluttered - there is a tipping point..). Users might know the edition but not the publication year. And edition is a high-level way of identifying a work.

If @ualbertalib/discovery-testing agreed to this, my *opinion* on the best location for the grid view would be between the title/subtitle and year... Not sure about bold/italic/etc. 

For the list view, I'm not so sure what would be best. Maybe alongside the title if possible, or in place of language?

**Comment by hannepearce** [comment]
I think Edition needs to be pretty prominent. Could it not be put beside the title?

**Comment by redlibrarian** [comment]
Edition statement has been added to the title display in full record view, list view, and bento panes.

**Comment by theLinkResolver** [comment]
This very important info is now displaying.

@redlibrarian There is a space between the end of the title and the comma in grid and record views (not list view though). Can you get that out?

**Comment by redlibrarian** [comment]
Done. Check in next release.

**Comment by theLinkResolver** [comment]
Looks really good.
