### ISSUE TITLE
Email me this item doesn't work on mobile

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#840]
Gives error "you must enter a valid email address" even when valid address entered.

**Comment by merisjames** [comment]
It worked for me. Does your phone autocomplete your email with a space at the end? Mine does, and I have to delete it to be valid.

**Comment by redlibrarian** [comment]
@merisjames That's awesome, thanks! I hadn't noticed my phone was doing that, and that is indeed the problem. I didn't know where I was going to start troubleshooting the problem, but I think you've figured it out. That's great!

**Comment by redlibrarian** [comment]
Fixed.
