### ISSUE TITLE
Wording on Explore our New Search page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#842]
I really like the explanatory text on the [Explore our New Search page](https://search.library.ualberta.ca/search), and I have a few recommendations for rewording:

1. select your preferred view <del>into</del> **from** your initial search results
-I still find this wording a bit clunky

2.  <del>review</del> improved relevancy ranking of search results
-I think this is just fine without the word review

3.  <del>copy</del> <del>static</del> <del>URLs</del> <del>for</del> <del>every</del> search result**s** <del>into your workflow results</del>**can be run again using the URL in your browser bar 
-This is a tricky one to word, but static is probably not necessary, and workflow is a bit of a jargony word. I think this is an improvement, but is probably still a little too clunky

**Comment by merisjames** [comment]
"Copy the URL from your browser bar to make a link to resources and searches"?

**Comment by seanluyk** [comment]
I like that @merisjames

**Comment by alfodor** [comment]
These changes gave been made.

**Comment by psue** [comment]
oh ya larry mentioned the maps that gale scanned - nothing's ever come from
it. but there's no point in following up and demanding teh files from them
because we have nowhere to put them!
drives me crazy that there is nothing done and sewn up!

**Comment by seanluyk** [comment]
Thanks, @alfodor. Closing issue.
