### ISSUE TITLE
Make place of publication precede publisher in published field

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#843]
We have 260 $a and $b reversed in Blacklight. To be consistent with the major citation styles, place of publication should precede publisher, and this will make cutting + pasting that much easier :)

**Comment by theLinkResolver** [comment]
@redlibrarian token reminder that any changes applied to data from 260 would need to be applied to data from the 264. :)

**Comment by redlibrarian** [comment]
@seanluyk Done. Format is now e.g. "London: Routledge".
@theLinkResolver This doesn't deal directly with either the 260 or the 264. We still need to implement the 264, but this logic is independent of that.

**Comment by seanluyk** [comment]
Looking good, closing
