### ISSUE TITLE
Improve display of contents notes

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#844]
One area that I've felt has not been improved in Blacklight compared to iLink is how contents notes are displayed. The running list separated by -- continues to be challenging to read. 

Compare [one of our records](https://search.library.ualberta.ca/catalog/3730617) with [one from Stanford](https://searchworks.stanford.edu/view/5756807) as a possible model. I like how each item is easy to read, and that contents are higher up in the display.

**Comment by theLinkResolver** [comment]
@seanluyk good find - I like the way they did that.

I will also add the comment (borrowed from someone else, I think) that partial display of "long" note fields, with a "more" button to reveal all the text, could be a consideration as the appearance of Blacklight records evolves.

**Comment by redlibrarian** [comment]
OK, this should be doable. We'll just need to split our contents string on the double dash and present as a list...

**Comment by redlibrarian** [comment]
OK. I've made some improvements to this. It will still need some tweaking, but it's a step in the right direction. 

![image](https://cloud.githubusercontent.com/assets/1093066/14476297/1d3ab988-00c4-11e6-97c2-12e5aec98e09.png)

**Comment by seanluyk** [comment]
@redlibrarian  - this looks much much better, and I think opens up the possibility for longer contents notes than we're typically used to, especially if there were some way to collapse the contents.

**Comment by redlibrarian** [comment]
Yeah, I think something like that will have to be a summer project. But I think this is better. Take a look at some other records with large contents notes in the next release.

**Comment by theLinkResolver** [comment]
agreed - much better.

**Comment by seanluyk** [comment]
I've reviewed a number of records with large contents notes, and this is looking very good, much more usable.
