### ISSUE TITLE
Location bug?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#846]
Searched for lb2367.4 g74 in both the Classic catalogue (http://www.library.ualberta.ca/permalink/opac/6069333/WUAARCHIVE) and Blacklight (https://search.library.ualberta.ca/catalog/5265994):
Blacklight only shows for one copy MacEwan but not the Coutts 
Classic shows for both MacEwan and Coutts copies

**Comment by theLinkResolver** [comment]
@redlibrarian That particular call number search should return two records. The one that isn't being returned in Blacklight is 6069333. Are all the 090s being indexed or just the first one? (In this record, the matching 090 [MacEwan's - with no space after LB] is the second one.)

**Comment by redlibrarian** [comment]
@theLinkResolver Ah. I was misunderstanding the problem. I'll have to investigate further.

**Comment by redlibrarian** [comment]
Only the first 090 was being indexed. I'll change that.

**Comment by redlibrarian** [comment]
I did some basic testing and this seems to be working now. Please test in the next release.

**Comment by theLinkResolver** [comment]
Tested and closing
