### ISSUE TITLE
RefWorks export still a problem?

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#847]
There might be a problem in that titles do not seem to be going through.

Try exporting this record:

https://search.library.ualberta.ca/catalog/1417780

**Comment by merisjames** [comment]
Seems to be an issue with non-Roman characters? I tried a few other titles with other characters, and none worked, while strictly Roman character titles seem fine.

**Comment by redlibrarian** [comment]
Yes, it's a problem with the way RefWorks handles UTF-8 and https. 

https://github.com/projectblacklight/blacklight/issues/245

I'm inclined to wait until RefWorks 3 comes out to see if that fixes the problem, rather than try to hack Blacklight to fix it ourselves.
