### ISSUE TITLE
symphony, sfx e-journal records, deduplicating and prompting for ccid / pw

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#849]
related issue: Exclude Symphony e-journal records from Journals pane. #682

The below is as a result of an question from a patron who was trying to access an online journal (Harvard Business Review) from a computer on the university network. The patron is a NRC employee working out of the National Institute for Nanotechnology,  he does not have a ccid / pw. He has historically been able to access e-journals from his on-campus office without inputting a ccid and pw.

The patron uses the Journals tab to search for online journals. This morning he searched for the journal title, selected the record which indicates that the UA has internet access (the symphony record) and was prompted for a ccid and pw.  We finally realized that he could access the journal through the sfx record or the db that includes the journal but I was left with a couple of questions.

Which e-journal record will remain once the deduplicating has been completed, the sfx, the symphony record, or ? 
If the SFX entry, how will patrons know that other libraries also have online access to a particular journal? Other institutions may have more extensive e-holdings for a particular title, the patron may be using our catalogue but may actually be from another institution, ... .
If the Symphony record, will patrons who work on campus but do not have a ccid and pw now be prevented from accessing e-journals?

see https://www.library.ualberta.ca/journals?utf8=%3F&q=harvard+business+review

**Comment by redlibrarian** [comment]
We'll need to discuss this further to see whether or not we're deduplicating or merging records. @theLinkResolver @sjshores should we set up a meeting to have a preliminary chat about what this might entail?

**Comment by sjshores** [comment]
Yes, let's get going on that conversation and mapping out what would be
ideal.  Do you mind checking calendars and sending an invitation?

Thanks!

**Comment by redlibrarian** [comment]
We're currently in the process of deduping records. #900
