### ISSUE TITLE
Kanopy does not appear in search results for databases

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#850]
Just noticed this helping a patron:

1. Search for Kanopy in databases

No results are returned.

**Comment by redlibrarian** [comment]
Hm. Kanopy comes through when I index the databases on my workstation, but it's not coming through in production. There might be a problem with the updates...

**Comment by redlibrarian** [comment]
So updates are working (though deletes are not - that's something I have to fix), so I'm not sure why this isn't coming through....

**Comment by redlibrarian** [comment]
@seanluyk We've done a reindex and Kanopy is appearing now in test. This should be in production tomorrow or Thursday.

**Comment by redlibrarian** [comment]
@seanluyk This is now present in the live index.

**Comment by seanluyk** [comment]
Fixed, closing issue
