### ISSUE TITLE
word wrap problem for filters list in Firefox

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#856]
![line breaks](https://cloud.githubusercontent.com/assets/14913579/12271847/7ae7e570-b91a-11e5-8880-84004add01f6.jpg)

Browser window is at full width.

Chrome handles word wrap better, for the most part.

![chrome](https://cloud.githubusercontent.com/assets/14913579/12271961/feaf02bc-b91a-11e5-9482-094f8fb0d648.jpg)

**Comment by redlibrarian** [comment]
@nnunn Do you have any thoughts about this? Is this a Bootstrap thing?

**Comment by theLinkResolver** [comment]
Much improved
