### ISSUE TITLE
filters - different display behaviour between basic & advanced

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#858]
In a basic search filtered to Lakeland Vermilion, note the way the active filter is displayed:
![ll basic](https://cloud.githubusercontent.com/assets/14913579/12272336/38943806-b91d-11e5-8826-896ffb2117a6.jpg)

Here's the same active filter as displayed in an advanced search (at the top of the library filters list):
![ll adv](https://cloud.githubusercontent.com/assets/14913579/12272339/3e028e50-b91d-11e5-8940-0aeea6dc7205.jpg)

Please also note that in the above, the mapped library name is not displaying, but rather, the library code from the item record.

**Comment by redlibrarian** [comment]
This is fixed, probably due to changing the data we use for locations now.
