### ISSUE TITLE
two entries for Burman in library filters list / CUC problem

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#859]
https://www.library.ualberta.ca/symphony?f[location_tesim][]=cuc&q=

The above results are for the location code CUC, which was for Canadian University College. The name changed last summer and the location no longer exists in Sirsi, but the location is still somehow attached to these records.

**Comment by merisjames** [comment]
Even stranger, from that list, the following items only show UofA locations, yet came up under that (outdated) location code. Could this be an indicator that something's going awry with location codes more generally?
https://www.library.ualberta.ca/catalog/1006496
https://www.library.ualberta.ca/catalog/100298
https://www.library.ualberta.ca/catalog/1000340
https://www.library.ualberta.ca/catalog/1000152

**Comment by redlibrarian** [comment]
This might be clearer if we stop using the codes and start using just the library names... See #857 .

**Comment by redlibrarian** [comment]
It took a while for this to all get straightened out. @theLinkResolver can you let me know if this is still going on? These records look ok to me right now, but I could do with another pair of eyes.

**Comment by theLinkResolver** [comment]
@redlibrarian I think we're good now. but I found something else... sigh (new issue)

**Comment by redlibrarian** [comment]
@theLinkResolver OK, bring it on. :)
