### ISSUE TITLE
Something has gone wrong error

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#860]
This item, [Canadian professional engineering and geoscience: practice and ethics] (http://www.library.ualberta.ca/permalink/opac/6356560/WUAARCHIVE) is not displaying in the new discovery [https://www.library.ualberta.ca/catalog/6356560] (https://www.library.ualberta.ca/catalog/6356560)

**Comment by redlibrarian** [comment]
The error was in the due date parsing as this record has due dates of "NEVER". This should be fixed in the next release.

**Comment by redlibrarian** [comment]
This is now working in test.

**Comment by theLinkResolver** [comment]
Confirmed
