### ISSUE TITLE
Speed loading records with large numbers of items in results view

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#861]
This is related to the old problem we had where records with many holdings were slow to load in record view. This (hopefully) just requires some code optimization, but if that doesn't help we might need to look at how we're looking up locations.

**Comment by redlibrarian** [comment]
A good example of this is a journal search for "Nature", where many of the results have large numbers of holdings.

**Comment by theLinkResolver** [comment]
Related to slowness, it must be acknowledged that it comes up a lot in the training sessions. If we are stuck with a bit of slowness come launch time, is there something that could be done, design-wise, that makes waiting easier to stomach? A progress bar (counting up the number of hits)? A greyed-out screen with the word "Loading"?

**Comment by redlibrarian** [comment]
I'm marking this as a bug as it is impacting users in the live journal search.

**Comment by redlibrarian** [comment]
I've added a fix for this. I'm going to close the record for now - we can reopen if speed becomes an issue again.
