### ISSUE TITLE
advanced search vs. basic search

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#862]
Concerns around the differences between the basic and advanced search were raised a few times during training sessions. I will try to capture what I've been hearing (concerns/suggestions) to get the discussion going.
- As we know, from the grid view, clicking 'view results as a list' removes all the articles & more results. (Should we take this option away from the grid view?)
- Can we find a better way to describe the advanced search, and differentiate it from the _articles_ advanced search?
- The advanced search page 'search tips' use the terminology "local content" which no one seems to like.

**Comment by theLinkResolver** [comment]
Suggestion

Replace this: "NB: This advanced search screen only searches local content.
Please use the Articles Advanced Search to search for non-local content."

With this: "You are searching **books**, **media**, **journal titles** and **database titles**."

**Comment by redlibrarian** [comment]
As per DTTT I'm going to remove the toggle altogether. Remove text from search page "Features".

**Comment by redlibrarian** [comment]
We had a discussion at the last DTTT meeting about the best way to handle advanced search (probably contextually), but we need to have some more discussion.

**Comment by seanluyk** [comment]
Taking out the pieces of this issue that still apply (wording of the advanced search page) and creating a new issue. Closing this one as the other points no longer apply with the removal of bento design.
