### ISSUE TITLE
word stemming, spelling variations, spelling errors, autocomplete

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#863]
I am going to combine these questions into one issue, as they are somewhat related. These are questions arising from training sessions.

- People would like to know a bit more about how the word stemming works. I think @redlibrarian said there is a thesaurus module that is used. Can we see what's in it? Is there any variation between how it's applied to the local results vs. EDS? Does it look at real words only (vs. truncated words, e.g. I presume it's not looking at 'behavio' and trying to complete it with an 'r' or 'ur')?

- Related to the above, it doesn't look like spelling variations are taken to account, but there is some interest in this (e.g. could labour include results for labor?).

- Is there any (future) provision for handling spelling errors? or an autocomplete function?

**Comment by redlibrarian** [comment]
This is a complicated, deep topic. I'll write something up that addresses these issues...

**Comment by redlibrarian** [comment]
@ualbertalib/discovery-testing I've written a document addressing these issues and sent it out to the group. @theLinkResolver when you say "people would like to know" are you referring to the Testing and Training group, or library staff? If library staff, one thing to think about is whether it would be worth releasing the Language Analysis document to them. Or would something like a brown-bag covering the previously written explanation of the search engine & language analysis be worthwhile...?

**Comment by theLinkResolver** [comment]
@redlibrarian Certainly some non-DTTT people have asked about it at the sessions. Most are just happy to see pluralization accounted for, and some have dug deeper and done some experimenting with other words and scenarios, with mixed results. In the training context, presenters didn't have detailed explanations (understandably so).

I like both ideas of releasing a package of documentation and a brown-bag (maybe simultaneously in spring/summer?), topic being something like "what's under the hood?".
