### ISSUE TITLE
add institution-level library filter

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#867]
This was a popular one from the training sessions. People would like to have the option of doing their library limiting at the institution level (in addition to the branch level). @redlibrarian Is there anything that comes through in the item-level data that identifies the institution?
 
![neos institutions](https://cloud.githubusercontent.com/assets/14913579/12308296/c164df66-ba01-11e5-94d9-403e70576a29.jpg)

**Comment by redlibrarian** [comment]
@theLinkResolver AFAIK there is no institution level information in either bib or item records. It would be possible to create a custom facet that would handle this, but this will need a bit of programming.

**Comment by theLinkResolver** [comment]
@redlibrarian Yeah, I couldn't imagine what would possibly be there for you to work with in the item data. Theoretically, the location codes coming from the 090 (call number) in the bib record are at the institution-level, but in practice, those would be awful to work with. Item records are much more precise and manageable, and you are already having to keep track of locations for the library branch filter (090 codes would be *another* list to maintain).

**Comment by redlibrarian** [comment]
@theLinkResolver We'll have to look into it. We aren't indexing item level information. What about the current **Library** filter locations? If those accurately describe the owning library, we can have solr dynamically create a facet based on those values. For example "University of Alberta Rutherford" and "University of Alberta Cameron" would both map to the same "University of Alberta" facet value.

**Comment by sjshores** [comment]
How about mapping the numeric library values from the MARC 596 tag to
institutional facets?

**Comment by theLinkResolver** [comment]
@redlibrarian that makes sense. That's the way the names are constructed, as they should be, so you could use that.

This was a very popular suggestion indeed.

**Comment by redlibrarian** [comment]
@theLinkResolver @sjshores Any preference for the current mappings vs. the 596 field? I just looked at http://www.library.ualberta.ca/permalink/opac/559133/WUAARCHIVE and the 596 contains "21 43 52", but there are four items listed (Concordia, King's, Lakeland, and UA).

**Comment by sjshores** [comment]
So, Scott noted that the missing 596 value was for the King's copy.  He and
I just read the help information, and confirmed that the system creates the
596 numbers, and does so in the overnight adutext process that adds,
updates and deletes bibliographic data and indexing based on the day's
work.  I have no idea how you stumbled upon this particular record, Sam,
but this King's item was created today, and so I would expect the system to
add the number value for King's to the 596 tonight.

Sandra

**Comment by redlibrarian** [comment]
@sjshores Oh, ha! That explains why it was first in my standard "shakespeare" search. So it sounds like the 596 and the current mappings would both work for the labeling. @theLinkResolver does it matter which one we use?

**Comment by theLinkResolver** [comment]
@redlibrarian I don't believe it would... The 596 values are numeric, so probably a bit easier to work with than text. There's just the overnight update issue, but I think that's also the case with the current mappings -- 

e.g. If you take
https://www.library.ualberta.ca/symphony?q=William%20Shakespeare,%20a%20textual%20companion
and limit to King's, the first (desired) title disappears. But I presume it will work tomorrow or the day after..?

**Comment by redlibrarian** [comment]
I've been working with the 596 values a lot today, so I think this one will be doable. I'll tackle it tomorrow morning.

**Comment by redlibrarian** [comment]
This is done!

![image](https://cloud.githubusercontent.com/assets/1093066/14502984/2ecde0a6-016b-11e6-9115-ea5f390eb136.png)

**Comment by redlibrarian** [comment]
Oops. Just need to tweak that Augustana value.

**Comment by theLinkResolver** [comment]
@redlibrarian Wow! This is great - a feature that was asked for in a number of sessions.

**Comment by seanluyk** [comment]
The institution facet is displaying, but the institution names are clipped, and don't appear on one line:
![image](https://cloud.githubusercontent.com/assets/14880206/14722702/0f708730-07ca-11e6-8e68-12ba45d2bc49.png)

Also, I'm wondering about placement of this facet. It might make more sense to place it above or below the library facet. What does everyone think @ualbertalib/discovery-testing?

In the future, it would be ideal if this weren't a separate facet, and if it were possible to nest libraries under parent institutions instead:

-University of Alberta (50,000)
--University of Alberta Archives (1000)
--University of Alberta Book & Record Depository (11, 000)
etc.

**Comment by theLinkResolver** [comment]
Once it's working, I think above the Library facet would be the most desirable spot.

Also noticed that the 'button' (rectangle around the word Institution) is greenish and the text is also green (different from the other facets).

And noted that this facet isn't available via Advanced Search.

**Comment by seanluyk** [comment]
Nice work, Scott "eagle eye" Davies! @theLinkResolver

**Comment by redlibrarian** [comment]
I don't know why the values are using the codes rather than the text - it's working fine on my workstation. Let's check on that one in the next release. 

I've moved the institution filter to be above "Library".

I'm not seeing the issue with the "button" display. That sounds like an HTML tag problem, so I might have found and fixed that already. 

In terms of nested facets, that's a question of solr indexing rules. I don't know if solr is capable of doing it (I assume it is, since Endeca's index can do it), but will require investigation.

**Comment by redlibrarian** [comment]
Sigh. As for the "advanced search" filter, I've just discovered a problem with that as a whole. I'll have to make a new issue for that.

**Comment by fculpepper** [comment]
Institution facet is still displaying "clipped" as in Sean's comment above. Came to this issue because a couple coworkers were asking for this in the advanced search. Got that it's being worked on, will pass that along. In the meantime, is it possible to put all the UofA libraries at the top (in the Advanced search)?

**Comment by seanluyk** [comment]
Just checked again and this is still displaying as clipped/running on multiple lines for most, but not all of the institutions

**Comment by redlibrarian** [comment]
Yep. I'm looking into it right now.

**Comment by redlibrarian** [comment]
I think this is a problem with the Solr schema not being up to date...

**Comment by redlibrarian** [comment]
Gah. I can't see what the problem is, but this has been pushed to prod, which doesn't look good. Hopefully I'll have a fix for it by tomorrow.

**Comment by redlibrarian** [comment]
@ualbertalib/discovery-testing I can't figure out why this is working in dev but not in test and production. I'm going to remove the limit from tomorrow's release, but I'll put it back in as soon as it's fixed.

**Comment by redlibrarian** [comment]
I'm wondering if this needs a reindex; since we're going to be doing a full index on the next release, I've reenabled this. We'll have to check in the next test release.

**Comment by theLinkResolver** [comment]
Successfully implemented in test. As noted above, the filter is not available in Advanced search, but that is covered in #974. Closing this issue
