### ISSUE TITLE
index 919 field data

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#878]
Enhancement suggestion from Brian Stearns. Efforts are ongoing to merge e-book records from multiple vendors. In the provider-neutral "keeper" record, the 919 field is used to hold the 001/catkeys of the records that have been merged into it.

Could the contents of the 919 be indexed so records can be found that way? No need to display, just index. There can be multiple numbers in the 919 - each is in its own $a.

(A future idea would also be to make it so an existing permalink to one of the superseded catkeys would somehow point to the "keeper" record, but there are still some issues to be worked out on the cataloguing end before that can be brought forward.)

**Comment by redlibrarian** [comment]
I think the "future idea" is intriguing and worth pursuing, but it sounds to be as if the initial indexing of 919 fields is aimed more at staff than at students, faculty, etc. I'm going to put this in the Phase 2 milestone. We can revisit it then.

**Comment by redlibrarian** [comment]
I just realized that I have a concern about this. Currently, you can search by catkey, and it will bring up the correct record. False drops will occur if the catkey is part of a larger indexed number (maybe an ISBN or something), but this is unlikely. If we add the 919 field to the index, then multiple records will start being returned for a catkey search. The records will be related, but it might still be confusing. Also, is there a public service need for this, or is this more of a staff-facing function? Let's discuss it in the summer.

**Comment by seanluyk** [comment]
Given the concerns raised in Sam's comment about false drops, I'm closing this issue as this would create issues for users.
