### ISSUE TITLE
index awards_note_tesim (data from MARC field 586)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#879]
BPSC is glad that we are displaying the awards note, and noted that it would be helpful if it was indexed, as some users will search for works that have won specific awards.

**Comment by theLinkResolver** [comment]
@redlibrarian I wonder what kind of relevance score one would assign to this field. If someone knew the exact name of the award and put it in quotes, that's great, but I wonder how just entering a few of the terms in a general search would play out. And conversely, you don't want these records bubbling up too high in unrelated searches that happen to include the word "award"... just thinking aloud. I guess we'll see - it's nice that we can tweak over time.

**Comment by redlibrarian** [comment]
@theLinkResolver Is there anything to be done here? I think we're displaying this field - are we just keeping the issue open to tweak relevancy if necessary?

**Comment by theLinkResolver** [comment]
@redlibrarian We're displaying, but not currently indexing.

https://search-test.library.ualberta.ca/results?utf8=%3F&q=%22Golden+Sheaf+Award%22

**Comment by redlibrarian** [comment]
Yeah, sorry - I deleted my note because I can't read. :$ I'm adding it to the index now.

**Comment by theLinkResolver** [comment]
Search now returns desired results; closing
