### ISSUE TITLE
display data from 351 field (Organization and Arrangement of Materials)

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#880]
This is a field that is used in collection-level records. It does not need to be indexed. 

sample records for testing:
https://www.library.ualberta.ca/catalog/6282297
https://www.library.ualberta.ca/catalog/3801928

**Comment by redlibrarian** [comment]
So, the first record you provided includes this in Symphony:
"Organization/arrang.:	Organized into four series: Personal (with subseries: Photographs; Correspondence; Identity and licence documents; Books and periodicals; Miscellaneous); Professional (with subseries: Photographs, Western Canada Airways; Photographs, other; Miscellaneous); Military (with subseries: Photographs; Miscellaneous); Photograph negatives."

Is that generally how it should display, @theLinkResolver

**Comment by theLinkResolver** [comment]
@redlibrarian I'm going to need to check with Brian S. on this one (currently away).

**Comment by theLinkResolver** [comment]
@redlibrarian Sorry for the delay (Brian was **not** gone this whole time!). He says that the entire text of the field can be displayed as one paragraph, so yes, that display should be fine.

**Comment by redlibrarian** [comment]
I've added this now. I don't have any test records with a 351 field, so we'll have to check this one out in test.

**Comment by theLinkResolver** [comment]
https://search-test.library.ualberta.ca/catalog/6282297
https://search-test.library.ualberta.ca/catalog/5030504

**Comment by theLinkResolver** [comment]
Looks good; closing.
