### ISSUE TITLE
no "library" for SFX and database records

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#881]
e.g. See list of library filters for these results: https://library.ualberta.ca/journals?q=CNN+en+Espa%C3%B1ol+-+en+Efectivo+%28Spanish+Language%29+

So if I filter to U of A Internet as a library, I lose all the SFX (e-journal) records.
https://library.ualberta.ca/journals?f[location_tesim][]=uainternet&q=germanic+review
(And the same is true for the databases.) Understandably so, but maybe not the 'expected' behaviour?

**Comment by redlibrarian** [comment]
I can add the UA Internet location to both SFX and Database records, which makes sense to me, but how does the cataloguing world feel about that? :) / @sjshores @theLinkResolver

**Comment by sjshores** [comment]
I am in favour of doing this.

Sandra

**Comment by theLinkResolver** [comment]
@redlibrarian I'm glad it's something you can do! And I guess, as things roll along, this will always need to be a consideration (e.g. for ERA results).

**Comment by redlibrarian** [comment]
OK, I've just implemented this. It will be in the next release.

**Comment by redlibrarian** [comment]
Working now.
