### ISSUE TITLE
SFX links in Blacklight records are not in preferred order

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#884]
The "Nature" link floats to the top in our standard Get It window:
http://bit.ly/1PhNDvE
(ignore Ebsco Sci Ref Centre, which needs to be added to the aggregator list - that's another can of worms for @redlibrarian and the serials team)

The preferred sort does not occur for the Blacklight display:
https://www.library.ualberta.ca/catalog/954925427238

**Comment by redlibrarian** [comment]
I don't know that there's anything we can do about this in Blacklight. The concept of "aggregator" is within SFX, and is not included in the MARC records... I'll have to investigate, but we may want to discuss this further.

**Comment by theLinkResolver** [comment]
@redlibrarian @sjshores Might play into our discussion this afternoon...

**Comment by redlibrarian** [comment]
Right. I still need to think about this one.

**Comment by theLinkResolver** [comment]
@redlibrarian I sent you this in an email but I should have posted it here:

The global consensus is that Ex Libris/SFX makes it hard to export the data that describes whether or not a target is coded as an aggregator, at least in terms of the readily available export options. But alas, I finally found something in the SFX-Discuss-L archives that might help:

_to sort out all aggregator targets (or more precisely: all targets which Ex Libris considers as aggregators) I would recommend to login to mysql as an instance user and do the following:

select TARGET_NAME from sfxglb41.KB_TARGETS where AGGREGATOR=1 order by TARGET_NAME;_

**Comment by seanluyk** [comment]
Closing this issue as it isn't possible to maintain the ordering used in SFX once records are brought in to BL - default sort order prevails. The question of how we use SFX data will be addressed in discovery strategy group.
