### ISSUE TITLE
Find more by this author link not providing results

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#886]
Clicking on [Cordasco, Francesco, 1920-2001](https://www.library.ualberta.ca/catalog?f%5Bauthor_display%5D%5B%5D=Cordasco,+Francesco,+1920-2001) from [this record](https://www.library.ualberta.ca/catalog/466240) leads to the following screen:
![image](https://cloud.githubusercontent.com/assets/14880206/12466112/421c3004-bf8f-11e5-9154-c3c7557a8131.png)
NEOS shows 52 items for this author.

**Comment by redlibrarian** [comment]
Fixed, though I'm only getting 32 results in BL... / @seanluyk

**Comment by seanluyk** [comment]
Interesting...I wonder why the discrepancy? When I do an advanced search for this author, I get 55 results, much closer to the NEOS#: https://www.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=Cordasco%2C+Francesco%2C+1920-2001&subject=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search&utf8=%E2%9C%93&search_field=dummy_range&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced

**Comment by redlibrarian** [comment]
Hm. Interesting - I'll dig into it.

**Comment by redlibrarian** [comment]
Done when:

- [ ] Problem properly identified
- [ ] Author data cleaned up
- [ ] Decision made whether to search or facet
- [ ] Automated test(s) written

**Comment by weiweishi** [comment]
duplication of #938
