### ISSUE TITLE
Internet access link on print record

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#887]
Likely an isolated case, but I thought I would report it in case it isn't:

The [record for the 2005 ed. of the Oxford History of Western Music](https://www.library.ualberta.ca/catalog/2857188) contains print holdings, and a MacEwan Internet access link. The odd thing is that on the [NEOS record](http://www.library.ualberta.ca/permalink/opac/2857188/WUAARCHIVE) MacEwan Internet only shows as a holding location, and the link does not appear.

Is this an issue with the record, @theLinkResolver, or is Blacklight displaying a masked field by mistake, @redlibrarian?

**Comment by theLinkResolver** [comment]
@seanluyk I do see the MacEwan link in the NEOS catalogue -- I'm wondering if you switched to MARC display in NEOS, which has the undesirable effect of hiding the links from display when you are looking at the Item information tab.

**Comment by seanluyk** [comment]
Oops, it looks like I did, @theLinkResolver . The issue that this causes in Blacklight is that a user can select University of Alberta, HSS as the library, and the result will still be labelled as: this is an ebook.

**Comment by redlibrarian** [comment]
This should be one of the issues that will be resolved when we've separated print and electronic. Currently the separate characteristics "University of Alberta, HSS as the library, and the result will still be labelled as: this is an ebook" are all true for this record. When the separation of print and electronic is complete, the print record won't be tagged as an ebook.

**Comment by sjshores** [comment]
Monograph records should always have been separated between print and
electronic, whereas we used to use a single record for all formats for
serials, and are separating those, of course.

This looks to me like a case where MacEwan added an 856 full-text link to
an existing record that describes print, which they shouldn't have done.

Sandra

**Comment by theLinkResolver** [comment]
I am also curious about this one, as we seem to have access to the web edition of Oxford History of Western Music. I'm checking with Bibhelp about it, and pending the results, I will talk to the e-book team about separating print and electronic.

**Comment by theLinkResolver** [comment]
Regarding the practice of splitting print and electronic format monograph records, this came up in conversation with Michael recently and his sense was that there are actually lots of combined print+electronic mono records out there. I did a search for the word "access" in the 856, limiting to ON_SHELF, and got over 18,000 titles. And from looking at dates, the practice of combining seems to be alive and well.
 
All this is to say that perhaps the issue around how we filter At Library vs. Online isn't a problem that's going to go away as quickly as thought (though, on the serial side, I am very confident in saying that our work will be done before the end of April).
 
![mixed format](https://cloud.githubusercontent.com/assets/14913579/12961814/927c6048-cfff-11e5-9f8e-f69bc7c89701.jpg)

**Comment by theLinkResolver** [comment]
@seanluyk Regarding the Oxford History of Western Music, there is now a separate e-book record for the MacEwan item. We seemed to have access, but we haven't purchased/subscribed to it. With thanks to Michael (e-book team) and Shellon (acquisitions).

**Comment by seanluyk** [comment]
Thanks @theLinkResolver and Michael and Shellon! Odd that we've got access without purchasing, I'll look into this in the new FY.

**Comment by redlibrarian** [comment]
This record is fixed.
