### ISSUE TITLE
Cleanup Call Number Filter

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#892]
As there are no I or W call numbers in LCC, I was wondering why these were coming up (without labels, understandably):
![image](https://cloud.githubusercontent.com/assets/14880206/12630474/e1c81e40-c509-11e5-94ff-6d09c9eee377.png)

I think "I" is coming up because the call number shows as Internet Access, and "W" shows up (1 gov doc title), but I'm not sure why.

**Comment by theLinkResolver** [comment]
@seanluyk There is probably either an error or an 'unexpected' call numbering practice that has led to the appearance of those letters in the field from which the call number is sourced.

Longer answer, with a question for @ualbertalib/discovery-testing:
Call numbers, for use as a facet/filter, are sourced from the 050 (Library of Congress call number) MARC field. I think the presumption in Blacklight's design is that the idea of filtering by call number is another way of filtering by subject. The 050 field is different from the 090 field, which contains the actual call numbers as used by NEOS libraries - the same ones you will see in the item listing.

One could guess that the 050 field is present in a majority of records (including e-books, where we don't usually think in terms of LC call numbers, and we don't assign one locally). There is only one 050 in any given record, and it is supposed to always be in the standard LC call number format, so it is (theoretically) better-suited for use as a filter. There shouldn't be all the outliers that you might find in the 090 field (e.g. "Internet Access", "GOV DOC", "Shelved by title", etc.). And you don't have the problem of choosing which version of the call number is the right one (there can be many different call numbers across campus and across NEOS for the same title).

The truth is that there are some surprises in the 050, whether it's incorrect data or past-practices such as the lowercase "f" which appears to have been used by LC in it's records for music folios. In other words, a completely "legitimate" use of something that we don't expect to see in that field.

How does @ualbertalib/discovery-testing perceive the idea of filtering by call number? Do we think of it as a way of narrowing by subject? Or do we/users perceive it as a way to virtually "browse the shelf" (knowing that the material could be anywhere, including online)? Is it actually useful? Or a flashy feature that has limited application? Do the subject filters do it better?

All that said, @redlibrarian, if you could find a way to have everything other than the 'expected' LC classes get filtered as "other", that might make everyone feel better about what they are seeing.

**Comment by seanluyk** [comment]
Thanks, @theLinkResolver . To answer your question, I do kind of think of it as a supplementary way to filter by subject, and as a way to browse the shelf, and both are really useful features. The subject facet is of course quite a bit more narrow, but it saves users time when they can filter by larger disciplinary areas. Not sure if this is just a librarian perspective though - it would be interesting to test this out on students and faculty.

**Comment by linds37** [comment]
I think librarians, collectively, missed an opportunity to create unified
"shelf lists" by not assigning call number to ebooks. I'm not sure that we
should include this filter, since it would leave so many things out. Our
best gathering point is subject heading.

**Comment by seanluyk** [comment]
Closing issue - will rewrite as bug
