### ISSUE TITLE
display message when list of items is incomplete

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#893]
I wonder if we can display something when the items table is known to be incomplete, like this one: https://search.library.ualberta.ca/catalog/554236

From the above example, I found that iLink will display 1,996 items and Blacklight will display 1,995 (there are over 3,400 items in this record). So, if the number of items in the items table is 1,995, display a message (ideally above the table) that the list of items is incomplete, and to "ask us" for assistance. (Probably easier said than done, and not a dealbreaker to resolve in the short term -- others, please chime in if you disagree!)

**Comment by seanluyk** [comment]
Wow, this is a scary record! Another possibility for large records like these that would be great to add as a future enhancement, would be to have an expanding list when the number of items passes a particular threshold (e.g. 100), and there could be a link to view more.

**Comment by redlibrarian** [comment]
I'd actually like to take a step back and ask if it's useful to a user to display that many items? It seems like a discovery nightmare, and I'm not sure at that point what useful information we're conveying. Are there kinds of users who might need/want to know all 3400+ items? If so, perhaps we should figure out if there's a way to satisfy their needs without flooding the other users with that much information. Anyway, I'll put it down as something to work on over the summer, but I think we might want to discuss this one further.

**Comment by redlibrarian** [comment]
I just realized that the reason Blacklight will only display 1,995 items is that it's using Symphony web-services, so the limit is pretty much the same in the Symphony UI and WS.

**Comment by sjshores** [comment]
Here's a case where the summary holdings, if we ensure that they are
accurate, would be of use rather than the individual volume displays.

Sandra
