### ISSUE TITLE
Article indexed in 2 sources in EDS is not appearing in article search results

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#896]
Noticed this while preparing class materials...
- Article in question is ["Golias and Goliardic Poetry" by Walsh](http://resolver.library.ualberta.ca/resolver?genre=article&isbn=&issn=00258385&title=Medium%20%C3%86vum&volume=52&issue=1&date=19830101&atitle=%27Golias%27%20and%20Goliardic%20Poetry&aulast=Walsh,%20P.%20G.&spage=1&sid=EBSCO:MLA%20International%20Bibliography&pid=)
- Results are returned in EDS for this item (indexed in MLA Int. Bib. and FRANCIS)
- A [search in Blacklight](https://www.library.ualberta.ca/results?q=Golias+and+Goliardic+Poetry+walsh) does not return this item, no matter which terms are added/removed

**Comment by redlibrarian** [comment]
I think this may be a bug in the EDS integration gem. I'm planning to look at Indiana's gem to see if it would be better than the old Ebsco one.

**Comment by redlibrarian** [comment]
This is the same problem as #757 - should be fixed soon.

**Comment by redlibrarian** [comment]
This is working now.
