### ISSUE TITLE
Index locations instead of doing a live lookup to improve result screen speed.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#899]

**Comment by redlibrarian** [comment]
This is working by indexing the 596 field and using that to drive the location lookup (instead of the Web Services call we're currently using). All I need is a mapping of the 596 data from Elaine, then I can push this through. Should be able to finish it Monday (early next week anyway).

**Comment by seanluyk** [comment]
Perhaps related to this, but I just noticed that locations are not appearing in the copies available at field in results display.

-[Sample search](https://search.library.ualberta.ca/symphony?f%5Bformat%5D%5B%5D=Musical+Recording&q=Dem+Milners+Trern)
![image](https://cloud.githubusercontent.com/assets/14880206/13505156/1b28669e-e135-11e5-93ff-3284051ec735.png)

**Comment by redlibrarian** [comment]
Ah, crap. I meant to send an email to the team explaining this. I'll send it right away.

**Comment by seanluyk** [comment]
No worries, just wanted to make sure that nothing was broken

**Comment by redlibrarian** [comment]
So, this will be fixed after the next full reindex (should be next Monday, I think).

**Comment by redlibrarian** [comment]
This is working now.
