### ISSUE TITLE
no access to various journals via SFX record (target internal ID problem)

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#902]
https://www.library.ualberta.ca/catalog/2821634

**Comment by theLinkResolver** [comment]
This record is the problem: https://www.library.ualberta.ca/catalog/111014393768020

**Comment by theLinkResolver** [comment]
Here's another one that's broken.

https://www.library.ualberta.ca/catalog/954925246073

Common thread? Both have only one active portfolio for OVID_LIPPINCOTT_WILLIAMS_AND_WILKINS_TOTAL_ACCESS_COLLECTION_2016.

**Comment by redlibrarian** [comment]
Right thanks. I can't see why the target would be an issue, but maybe.

**Comment by theLinkResolver** [comment]
@redlibrarian Are the OUR codes in order on your end? It's a relatively new target.

**Comment by redlibrarian** [comment]
Possibly not (I'm going to get an updated file from Ernie next week) but that shouldn't cause this problem. What we see when the OUR link is broken is just an empty cell in the holdings table.

**Comment by redlibrarian** [comment]
Same problem with 954925535073

I've figured out what the problem is. For some reason, the internal ID of some targets in SFX have changed. I use these target IDs to do the live subscription/coverage/note lookup. For example, the the target ID for Ovid Lippincott used to be 3680000000000079 but is now 3820000000000109, meaning the display crashes when it tries to access subscription information. This shouldn't happen as long as we are running nightly updates, but for some reason the nightly updates have stopped running, so the data is stale. I will work to fix the underlying problem, and I can also put in a display workaround so that this fails gracefully when an ID has changed. It would be good to know why Ex Libris is doing this, and how frequently it happens. / @theLinkResolver

**Comment by theLinkResolver** [comment]
@redlibrarian This is probably another instance of this same problem:

https://www.library.ualberta.ca/catalog/111098465955000
Reported in Helpdesk ticket: [here](https://helpdesk.library.ualberta.ca/otrs/index.pl?Action=AgentTicketZoom;TicketID=32789)

I'm going to close that ticket and cross-reference this thread.

@redlibrarian Will see what I can find out re. internet target IDs as well.

**Comment by theLinkResolver** [comment]
Seems to be working now - updates must be running again. @redlibrarian I figured out what's going on with regard to these SFX target IDs. I will drop by later to fill you in. As you say, the nightly updates will resolve this.

**Comment by theLinkResolver** [comment]
Discussed with @redlibrarian - this will not be a problem going forward.
