### ISSUE TITLE
Index and display 518: Date/Time and Place of an Event Note

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#905]
Not sure how widely this is used outside of sound recordings and videos (any idea @theLinkResolver?), but it would be beneficial to index and display MARC 518 notes if possible. 

It's important for dates and places to be indexed and labelled appropriately, and info in the 518 often differs from what's included in publication information and includes information not found elsewhere (e.g. a recording studio).  

Tagging it "for discussion" as it's easy for me to keep finding fields to index, but I imagine we could keep going for quite some time.

**Comment by redlibrarian** [comment]
I have no records in the test set with this field, so we'll have to confirm this works in test.

**Comment by theLinkResolver** [comment]
https://search-test.library.ualberta.ca/catalog/6370273

**Comment by theLinkResolver** [comment]
Looks fine; closing
