### ISSUE TITLE
Google Scholar in database list

### ISSUE THREAD

**Issue by fculpepper** [ualbertalib/discovery#908]
Adding Google Scholar to the list of databases has been suggested/requested. I'm told it used to be there and coworkers have been looking for it there.

**Comment by fculpepper** [comment]
Yes, this is in addition to the link on the main page.

**Comment by redlibrarian** [comment]
Thanks @fculpepper - I don't see any reason why it wouldn't be there. Databases are managed within LibGuides now, so I assume it would be either someone in public services or WAT who would add  it. @sjshores @timwklassen - any reason why we can't just add Google Scholar to the libguides list?

**Comment by sjshores** [comment]
I see no reason not to add it.  Anyone who can create assets in Libguides
can go ahead and do that.

Sandra

**Comment by fculpepper** [comment]
Is there someone on the discovery team that can create assets in the database manager or should I open a helpdesk ticket? We were told not to fiddle with database assets: http://guides.library.ualberta.ca/creating-libguides/home.

**Comment by redlibrarian** [comment]
@fculpepper I'll do it, though we haven't yet worked out who has responsibility for databases more generally. / @sjshores

**Comment by redlibrarian** [comment]
OK, I've added Google Scholar. It should be in libguides now and will be in the Blacklight database interface tomorrow. @fculpepper @ualbertalib/discovery-testing
