### ISSUE TITLE
Clicking on subjects from database records leads to something has gone wrong page

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#910]
Just encountered this when clicking on the library and information science subject from this record:

https://www.library.ualberta.ca/catalog/11710953

**Comment by redlibrarian** [comment]
Hm. This seems to not affacet all database records. It looks like it either affects records with multi-word subjects, or subjects with "&" in them.

**Comment by redlibrarian** [comment]
Problem was with the ampersand. I've fixed this - it will be in the next release.

**Comment by seanluyk** [comment]
Interesting, thanks!

**Comment by redlibrarian** [comment]
This is working in test now.

**Comment by seanluyk** [comment]
This is working, but I'm now wondering why clicking on a subject attached to a database brings users to the grid view? The expected behaviour would be to see more databases with that subject applied in a list view, I think

**Comment by seanluyk** [comment]
As the initial bug has been fixed, this can be closed. I'll create a new issue about the usability question
