### ISSUE TITLE
remove eBook Collection results from EDS pane?

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#911]
This often comes up in training, and I thought it was covered in an existing issue, but I don't see it. Ebsco eBook Collection results in the EDS pane are/should be dups of items in Books Media & More. Could they be suppressed?

I think the idea of keeping them was to provide access to book chapters, but I tried searching for a book chapter title and it doesn't return that ebook in the results.

Search for Shakespeare:
https://www.library.ualberta.ca/results?utf8=%3F&q=shakespeare
--- Shakespeare : Upstart Crow to Sweet Swan has a chapter called "three early readers"

I broaden my search to shakespeare three early readers:
https://www.library.ualberta.ca/results?q=shakespeare+three+early+readers
--- My book isn't there.

Can chapter titles be searched? If not, then maybe we can drop the Ebsco eBook Collection results in the EDS pane.

**Comment by redlibrarian** [comment]
I don't think that's true, or at least not anything that I remember being
discussed among the wider group. We initially limited the EDS pane to just
journal articles, but that wasn't adequate, so we opened it up again, while
removing the Symphony results. Is this only a question about the Ebsco
ebook collection, or about ebooks in general?

I don't know how ebook chapters are made searchable (if at all).



On Fri, Feb 26, 2016 at 1:38 PM, Scott Davies <notifications@github.com>
wrote:

> This often comes up in training, and I thought it was covered in an
> existing issue, but I don't see it. Ebsco eBook Collection results in the
> EDS pane are/should be dups of items in Books Media & More. Could they be
> suppressed?
>
> I think the idea of keeping them was to provide access to book chapters,
> but I tried searching for a book chapter title and it doesn't return that
> ebook in the results.
>
> Search for Shakespeare:
> https://www.library.ualberta.ca/results?utf8=%3F&q=shakespeare
> --- Shakespeare : Upstart Crow to Sweet Swan has a chapter called "three
> early readers"
>
> I broaden my search to shakespeare three early readers:
> https://www.library.ualberta.ca/results?q=shakespeare+three+early+readers
> --- My book isn't there.
>
> Can chapter titles be searched? If not, then maybe we can drop the Ebsco
> eBook Collection results in the EDS pane.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/911>.
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by theLinkResolver** [comment]
@redlibrarian I think this might have been an erroneous assumption by myself and others, then... it's even reflected in the hover box text where we decided to say "articles, chapters, reviews and more". We should remove the word "chapters" if the chapter titles are not searchable. 

I assume it is the Ebsco eBook Collection that gives us all the eBook results, but I guess we don't know that for sure. What we do know for sure is that all Ebsco eBooks are catalogued, so we could pretty safely remove them from the EDS pane.

**Comment by redlibrarian** [comment]
Book chapters are included, but they may not be what you were expecting. http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=lfh&AN=22870095&site=eds-live&scope=site

I think there are other ebook collections than Ebsco ebooks in EDS, but I'd have to check.

**Comment by theLinkResolver** [comment]
@redlibrarian OK, that makes more sense (re. chapters)! 

Re. other ebook collections, let me know what they are if you find any, and I will check on the cataloguing status.

**Comment by theLinkResolver** [comment]
Since we are planning to de-dup journals and databases within Blacklight, I am wondering if this issue should remain open...?

**Comment by redlibrarian** [comment]
I guess we should discuss it tomorrow - if there's anything in the eBook collection that isn't catalogued we should keep it. Given that this was only reported by staff, I think, I was going to close it until we hear back from usability testing.

**Comment by redlibrarian** [comment]
According to @theLinkResolver and Erika, there shouldn't be any Ebsco eBooks that aren't catalogued, so we should be safe to turn it off.
