### ISSUE TITLE
EDS fields searched and relevance ranking

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#912]
Related to #911, and it's a question from today's session: which EDS fields are searched by Blacklight, how is relevance ranked? I assume it's all controlled by EDS...

**Comment by redlibrarian** [comment]
Yes, the EDS results are driven by an API call to Ebsco, so fields and
relevance is the same as in the regular version of EDS (and controlled by
Ebsco).

On Fri, Feb 26, 2016 at 2:32 PM, Scott Davies <notifications@github.com>
wrote:

> Related to #911 <https://github.com/ualbertalib/discovery/issues/911>,
> and it's a question from today's session: which EDS fields are searched by
> Blacklight, how is relevance ranked? I assume it's all controlled by EDS...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/912>.
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by theLinkResolver** [comment]
@redlibrarian I'm going to relay this thread/your answer to the person who asked and I will either close the issue or add questions if there are any further ones.
