### ISSUE TITLE
Holds

### ISSUE THREAD

**Issue by merisjames** [ualbertalib/discovery#913]
Not sure this is a Blacklight issue at all, but... 
I placed a hold on the 24th as part of the training session, then immediately cancelled it. I did receive a hold cancellation notice.
I just now got a "your hold is in" email.

**Comment by redlibrarian** [comment]
No, the hold systems is separate from the Blacklight system. @jhennig can you look into this?

**Comment by redlibrarian** [comment]
I've passed this along to Jeremy.
