### ISSUE TITLE
Philosopher's Index in EDS & in Blacklight

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#917]
Hi, Sam. I'm just preparing for a Philosophy class. It looks like results from Philosopher's Index show up when I search directly in EDS, but they don't show up in the Articles pane when I search in Blacklight.

In Blacklight, I searched for: mind philosophy dualism Searle

In EDS, I searched for: mind and philosophy and dualism and Searle

EDS pulls 12 results from Philosopher's Index, but Blacklight doesn't pull any. 
For example, EDS finds these article citations: 

Reflections on John Searle's Philosophy of Consciousness

'Searle on Brains As Computers' in 'Newsletter on Philosophy and Computers' 

Searle and Buddhism on the Mind and the Non-Self

When you look those titles up in Blacklight, they don't come up at all.

We don't have access to the journals that these articles are in within our collection, but I didn't think that should matter.
It's not really the individual articles that I'm concerned about, but the fact that no results from Philosopher's Index come up in the Blacklight search. Do you know why?

Thanks,
Lindsay

**Comment by redlibrarian** [comment]
Thanks @linds37 . We have to maintain the list of active databases between the desktop version of EDS and the API version manually, and there are sometimes inconsistencies. Philosopher's Index was turned off, but I've enabled it now. It should be present within Blacklight within the hour.

**Comment by linds37** [comment]
Great - thanks!
Brian and I had feedback in our session that we should publicly list what databases are included in EDS & Blacklight. We've heard this before. I know it would be an ongoing project to maintain, but it would create transparency and increased understanding of our discovery tools. If you would need help from public services staff to do this, please tell us and hopefully we can work something out.

**Comment by redlibrarian** [comment]
There's a google doc that includes both enabled and "in EDS but turned off"
databases - for staff. Is it the feeling of staff members that faculty and
students would like to see this list?

On Tue, Mar 8, 2016 at 10:31 AM, linds37 <notifications@github.com> wrote:

> Great - thanks!
> Brian and I had feedback in our session that we should publicly list what
> databases are included in EDS & Blacklight. We've heard this before. I know
> it would be an ongoing project to maintain, but it would create
> transparency and increased understanding of our discovery tools. If you
> would need help from public services staff to do this, please tell us and
> hopefully we can work something out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/917#issuecomment-193880580>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by linds37** [comment]
Yes. Is it always up-to-date?

**Comment by redlibrarian** [comment]
I think so; it changes very rarely. I should go through it again to make
sure.

On Tue, Mar 8, 2016 at 10:52 AM, linds37 <notifications@github.com> wrote:

> Yes. Is it always up-to-date?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/917#issuecomment-193889508>
> .
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB
