### ISSUE TITLE
Add 550 notes to record.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#918]
@theLinkResolver This was a request from BPSC. Can you tell me what we use the 550 for, as opposed to the other note fields? Thanks.

**Comment by theLinkResolver** [comment]
@redlibrarian This field is also on my wishlist. It describes issuing bodies (e.g. associations, institutes, government departments, etc.) for serials, including notes on whether a title is an official organ of a society, what the relationship is to the publication, and changes over time. It consists solely of text in $a (i.e. no special formatting needs) and can be labelled as "Issuing body note".

**Comment by redlibrarian** [comment]
OK, thanks, @theLinkResolver It turns out the record in question was meant to have a 590 note (but the note was added to the 550). Brian has fixed that record, so this one is no longer urgent, but is something we'll add when we get a chance.

**Comment by redlibrarian** [comment]
This has been added and is displaying properly.

**Comment by theLinkResolver** [comment]
550 looks good; closing
