### ISSUE TITLE
prompted for CCID for free resource

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#921]
I know this is an issue in iLink and am wondering if the new search will address it. When linking (off-campus), I still need to go through EZproxy for free resources such as this:

https://www.library.ualberta.ca/catalog/6324606

**Comment by redlibrarian** [comment]
I'm pretty sure we want to leverage the cusomizability of Blacklight to prevent this. I can make sure all resources tagged as "Free Access" don't get proxied. This may not cover all resources which don't require a proxy, but it's a start. / @kgood do you have any thoughts about this?

**Comment by redlibrarian** [comment]
@theLinkResolver I think I have the logic in place. In the record listed above, the proxy prefix is not used. However, I'm having difficulty finding a non-Free, but non-SFX record to test with (since SFX doesn't get proxied either). @theLinkResolver can you think of a record like that?

**Comment by theLinkResolver** [comment]
@redlibrarian https://www.library.ualberta.ca/catalog/6825189

**Comment by redlibrarian** [comment]
@theLinkResolver Thanks, that's perfect.

**Comment by redlibrarian** [comment]
OK, this should work now. It will be ready in the next release.

**Comment by theLinkResolver** [comment]
Tested a few different scenarios and this is working great! Big score!
