### ISSUE TITLE
Add UA icon or "UAL" text to UA-owned books, etc, in bento view.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#923]

**Comment by redlibrarian** [comment]
So, in LibGuides and in the database info pages, we include a small icon of the UA shield for databases that are specifically licensed to us (as opposed to free resources). In the original Blacklight database interface we had them too, as the old DB of DBs included license information. That's gone from the current Blacklight DB interface (based on libguides), because there's no license field to look at. This raises the question of how LibGuides knows which databases should get the shield (unless they all do, since we removed free databases). If this is the case, then I can add the shield to all databases, all SFX ejournals, and any Symphony records that have one or more UAL holdings. I should be able to implement this pretty easily, but the question remains about the LibGuides databases.

**Comment by redlibrarian** [comment]
OK, this is done for the bento box. I assume the same thing is desired in the result views. It needs some tweaking, but that should be done as part of #836

**Comment by redlibrarian** [comment]
I've added the icon to the result lists as well.

**Comment by theLinkResolver** [comment]
@redlibrarian There are still some free resources in the (LibGuides) database list. An example would be the Alberta Law Collection.

**Comment by redlibrarian** [comment]
Hm. OK. Then there must be a way to specify UA-licensed in LibGuides, but I can't see the field anywhere. I'll check with April next week. Be advised that the UA shield will appear on *all* databases in the next release. Tweaking the databases will be in the release after that, I hope.

**Comment by redlibrarian** [comment]
This is working in test, with the above mentioned proviso. Also, the Symphony e-journal piece needs to be tweaked.

**Comment by redlibrarian** [comment]
Checking with April now...

**Comment by seanluyk** [comment]
This works really wellin test, the only suggestion I have is regarding the placement of the icon in both views. 

In the grid view, is there any way to make sure it doesn't land on its own line? 

In the list view, is there any way to move it up so it's to the left of the brief record, and not on its own line?

**Comment by redlibrarian** [comment]
Thanks @seanluyk - I still have to tackle all the aesthetic elements (e.g. #836 ), so I'll put your suggestions through as part of that issue. I've added the logic to the databases to reflect whether they're licensed or not - that will be in the next release.

**Comment by seanluyk** [comment]
I think this is good now - shield icon is not appearing on its own line, and from what I can tell, it's only appearing for UofA items
