### ISSUE TITLE
Go to Bookmarks not working

### ISSUE THREAD

**Issue by lindaslater** [ualbertalib/discovery#924]
In Firefox, nothing happens when I click on Go to Bookmarks.  In Chrome, I get an error message saying "We are sorry something has gone wrong".

**Comment by redlibrarian** [comment]
Check in next release. @lindaslater @seanluyk

**Comment by redlibrarian** [comment]
This is working in test.

**Comment by theLinkResolver** [comment]
@redlibrarian I'm not able to do this in Firefox in search-test.

**Comment by redlibrarian** [comment]
Hm. It works fine in Chrome, but I'm still getting nothing in Firefox. Investigating...

**Comment by redlibrarian** [comment]
Ugh. It's a Chrome/Firefox thing: http://stackoverflow.com/questions/20673043/html-a-href-link-with-button-not-work-in-firefox-but-work-google-chrome-why-is-i

**Comment by redlibrarian** [comment]
OK, weird. Well, it works now in both Chrome and FF, though the text is black instead of green (this is due to the code change required to fix the problem). It's a minor thing though and can be tweaked later on.

**Comment by theLinkResolver** [comment]
Working for me now in Firefox.
