### ISSUE TITLE
Subject headings not showing up in record

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#926]
Hi. In some records, the subject headings don't show up. For example https://www.library.ualberta.ca/catalog/626044

I purposely searched for words that appear in the subject headings for this book, and it comes up 3rd on the list. So, I think the field is being searched, but it's not being displayed?

Here's the search that I did: England social conditions 19th century industrial revolution

**Comment by theLinkResolver** [comment]
@redlibrarian Same as #810?

**Comment by seanluyk** [comment]
Looks like this is the same one, @theLinkResolver - for some reason I thought these were back?

**Comment by redlibrarian** [comment]
OK, the Geo Subject was appearing in the record, but as the facet, and not clickable (as per #810 that was going to be left until later. However, I've added the geo subject to the normal, clickable subject interface now. I've removed the static Geo Subject string as it was confusing when presented alongside the normal subject interface. This fix will require a full reindex to see, so it might not be in the next release, but will be present before the May launch.

**Comment by theLinkResolver** [comment]
@redlibrarian I think this is good now?

**Comment by redlibrarian** [comment]
I think so, though this example record isn't the best indication...

**Comment by redlibrarian** [comment]
This is working.
