### ISSUE TITLE
Item has no access link

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#927]
Found this issue while reviewing some BL links I had sent a student, and noticed that it had no access link:

https://search.library.ualberta.ca/catalog/7245545

It looks like this catkey does not appear in iLink or Workflows (catkey for this title in iLink is 7142592), so I'm wondering if it was a temporary catkey for a new record prior to reindexing?

What is the process for adding these kinds of records to BL? I'm thinking that until the "true" catkey has been assigned, that the record should not be added to BL, but I could be getting this issue from.

Any insights @theLinkResolver or @redlibrarian?

**Comment by theLinkResolver** [comment]
@seanluyk It looks like this is a case where multiple vendors' e-book records have been merged into a single record - the record you are pointing to was one of the ones that was deleted in favour of another.

I am going to see if I can get some more insight into the e-book de-duplication process plays out -- specifically, if there are any consistent ways that the "keeper" record is determined (i.e. what is the criteria for determining which record is kept). Then if you have to choose a record to permalink to, you will be able to do so confidently, knowing it won't get deleted.

There are some considerations around this in #878.

**Comment by seanluyk** [comment]
Thanks, @theLinkResolver, I guess I was surprised it was still there, but I tend to find issues at ideal times. It would be interesting to see when that record would be purged from BL. I sent the link out to a student on February 23rd if that's of any help

**Comment by redlibrarian** [comment]
This is an issue with the delete logic, which I need to fix. Issue #932

**Comment by redlibrarian** [comment]
I've added logic which will add a note "No copies found. This item may be lost or missing" to records like these. I think there's an underlying data problem here that we'll need to talk about in the summer. For this  particular issue, please check in the next release, and if the temporary solution is satisfactory, we can close this one.

**Comment by redlibrarian** [comment]
This is working in test.

**Comment by redlibrarian** [comment]
@theLinkResolver Can you take a look at this on search-test and let me know what you think? https://search-test.library.ualberta.ca/catalog/7245545

**Comment by theLinkResolver** [comment]
@redlibrarian The note looks good. A reasonable temporary solution that gives some info to the user.

**Comment by seanluyk** [comment]
@redlibrarian this is a good temporary solution, but it would be great if something like "Please contact the library for assistance locating this title" could be added to the note.

**Comment by redlibrarian** [comment]
OK, sure, I'll take care of it. Thanks.

On Thu, Apr 7, 2016 at 3:05 PM, seanluyk <notifications@github.com> wrote:

> @redlibrarian <https://github.com/redlibrarian> this is a good temporary
> solution, but it would be great if something like "Please contact the
> library for assistance locating this title" could be added to the note.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/discovery/issues/927#issuecomment-207087995>
>



-- 
Fender F-35
Ibanez M522SBS
Cordoba 45FP
Lafferty LB

**Comment by theLinkResolver** [comment]
@seanluyk In this thread, I had promised to get some more info about how the e-book team decides which record to keep when they are de-duplicating. There is no hard-and-fast rule, but generally, Michael says: "We will keep an OCLC record over a record that came from another source. Or we keep whichever record is clearly better." I guess the best bet, if you are sharing a link on a libguide and you have found two records, is to ask for them to be merged (helpdesk ticket to Cataloguing). I realize that is not the same as the situation above, but probably the most helpful advice I can personally give on the matter. :)

**Comment by seanluyk** [comment]
I'm not able to see this example in search-test (page not found - https://search-test.library.ualberta.ca/catalog/7245545. Once the note can be verified with an example, this issue can be closed

**Comment by seanluyk** [comment]
Thanks, @theLinkResolver this is good to know!

**Comment by theLinkResolver** [comment]
@seanluyk Here's an example (all items marked as discard):
https://search-test.library.ualberta.ca/catalog/2114122

**Comment by seanluyk** [comment]
I think the note will do the trick until we can prevent these records from making their way to BL, closing
