### ISSUE TITLE
Initial search screen, articles & more search not working

### ISSUE THREAD

**Issue by scastell** [ualbertalib/discovery#928]
The Articles & more limiter (initial search screen) is not working. The following error message displays regardless of the search term. 

No search results.

Need help? Don't hesitate to contact your local reference librarian today, or try on of these useful guides:

    Library Research Guide #1
    Library Research Guide #2
    Library Research Guide #3

![image](https://cloud.githubusercontent.com/assets/14927291/13925168/f4b4fa88-ef4c-11e5-853b-03e7c106e2a7.png)

**Comment by redlibrarian** [comment]
Can you try it again @scastell ? I just did some searches and they worked fine. It might have been a temporary problem with the EDS API.

**Comment by scastell** [comment]
Tried again, same result. Used 2 different staff stations, tried Firefox and Chrome.

**Comment by redlibrarian** [comment]
@ualbertalib/discovery-testing Can anyone else replicate this problem? Thanks.

**Comment by merisjames** [comment]
I got no results.

Meris James, MLIS
Public Service Librarian
J.A. Weir Memorial Law Library
meris@ualberta.ca

**Comment by seanluyk** [comment]
Worked for me, although I've experienced this problem in the past. Is it possible that browser cache has anything to do with the issue?

**Comment by scastell** [comment]
I have deleted the browser histories. Restarted the stations. ... same results ie none.

**Comment by linds37** [comment]
worked fine for me just now (Monday, March 21 at 11:46 am). 
Btw, I made a typo, but it still found results. I searched for Chicagoe (don't ask me what the "e" is for) and it found things in all 4 panes.

**Comment by linds37** [comment]
@scastell what are you searching for?

**Comment by theLinkResolver** [comment]
@redlibrarian I also have this problem.

**Comment by scastell** [comment]
Aha, I see a possible explanation. 

I attempted to duplicate the search but forgot to click the articles & more box so searched everything, results as expected. I then went back to the original search box redid the search limiting it to articles & more. Voila - search results. 

I then cleared the browser cache and tried again. This time I clicked on the articles and more box. No search results. Seems that one needs to have searched everything in order to trigger the results using the articles & more button.

Confused? so am I.

**Comment by redlibrarian** [comment]
Thanks everyone. I just did some testing on a few (clean) staff machines and the tests confirms @scastell 's diagnosis. For some reason, a successful search needs to go through before an "Articles & More" search will work. I think this is a problem with the EDS API and should be temporary. This issue came up briefly right at the beginning of Blacklight development. I'll keep an eye on it and open a ticket with Ebsco if necessary.

**Comment by redlibrarian** [comment]
Gah. There was a bug in the Ebsco view code (it was literally telling it not to search EDS unless a search had already taken place). This should be fixed in the next release to test.

**Comment by redlibrarian** [comment]
This is working now.
