### ISSUE TITLE
Use Indiana EDS gem instead of default EDS.

### ISSUE THREAD

**Issue by lindaslater** [ualbertalib/discovery#929]
I notice that there is an author facet in the Book results which allows people to limit to books written by the author rather than books about the author.  The Articles results does not have this face.  As an example, I searched "atword margaret" and click into the Articles list.  Most of what was listed was about Margaret Atwood or her works.  It wasn't possible within Blacklight to retrieve a list of articles she wrote.  In EDS, I was able to retrieve 962 articles authored by her by limiting to Academic Journals and Magazines.

Is it possible to add an author facet to the articles list?

**Comment by redlibrarian** [comment]
@lindaslater - It's trickier than it should be to add a facet to the Articles/EDS functionality, but I'll look into it.

**Comment by redlibrarian** [comment]
I'm going to move to the University of Indiana gem this summer. I think that gem will have better/different functionality.

**Comment by redlibrarian** [comment]
If possible, see if we can use blacklight_range_limit with this gem.
