### ISSUE TITLE
Authors/additional authors - different results from advanced vs. find more by this author search

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#938]
Clicking on find more by this author appears to only return results where the term is in the author field, but not additional author fields. However, an advanced search for an author returns results that include the term in the additional author field.

For example, clicking on [find more by this author from the Darnton book](https://search.library.ualberta.ca/catalog?f%5Bauthor_display%5D%5B%5D=Darnton,+Robert) returns 31 results, but an advanced search for [Darnton, Robert](https://search.library.ualberta.ca/catalog?all_fields=&author=Darnton%2C+Robert&commit=Search&op=AND&page=2&range%5Bpub_date%5D%5Bbegin%5D=&range%5Bpub_date%5D%5Bend%5D=&search_field=advanced&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&subject=&title=&utf8=%E2%9C%93) returns 38 results, 7 of which are for titles where this author is an additional author.

It would be ideal if these worked the same way, and I think it's useful to include titles where the author is an additional author. What does everyone on @ualbertalib/discovery-testing think?

**Comment by redlibrarian** [comment]
I agree that the functionality should be consistent. I'm not sure which (Solr) fields the advanced search box looks at, but I should be able to add them to the facet for "more by this author".

**Comment by theLinkResolver** [comment]
@seanluyk Agreed.

**Comment by linds37** [comment]
also agree that both search functions should pull results from the author and additional author fields.

**Comment by redlibrarian** [comment]
Done when:

- [ ] Discrepancy identified
- [ ] Problem solved (see also issue #886 )

**Comment by weiweishi** [comment]
Should already be fixed in Release 3.0.85.
