### ISSUE TITLE
Upgrade to latest version of Blacklight

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#940]

**Comment by redlibrarian** [comment]
Judging by what I learned at the Blacklight summit, this should be done sooner rather than later in order to give us better functionality.

**Comment by redlibrarian** [comment]
What I'm now thinking is that it would be better to build a "Discovery 2" repo on the latest version of Blacklight and port our customizations to it. This issue is done when:
- [ ] We have a CI/UAT environment running with Blacklight 6.10.1 (as of April 30).

**Comment by seanluyk** [comment]
Out of scope until discovery strategy work completed. Closing.
