### ISSUE TITLE
adding various note fields

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#944]
There are a number of open issues that are asking for note fields to be added. Here is a list of all of them (I believe):

515 - Numbering peculiarities (#720)
518 - Date/time and place of an event (#905)
540 - Terms of use and reproduction (#720)
546 - Language (#720)
550 - Issuing body (#918)
586 - Awards (#879)

In addition to these (many suggested by others), I would add the following:

525 - Supplement note - display; not index
580 - Title history - display; not index

It may seem like the list of included note fields is getting long, but you would almost never see all of them in a given record, as they apply to specific circumstances and formats.

**Comment by redlibrarian** [comment]
Thanks @theLinkResolver - I have a Milestone for these (https://github.com/ualbertalib/discovery/milestones/Records%20and%20Fields) which I'll be working on this week.

**Comment by redlibrarian** [comment]
OK. Issue #720 has been postponed until the summer. The others are set to be closed. I've added 525 and 580 to the display and this can be checked in the next release.

**Comment by theLinkResolver** [comment]
@redlibrarian To clarify, can you add the 515, 540 and 546 now, though, from #720?

**Comment by redlibrarian** [comment]
OK, those have been added, and will be in the next release.

**Comment by theLinkResolver** [comment]
580 looks good
525 looks good but the field name should be "Supplement note" - opened issue #965 (low priority)
515 looks good
546 looks good - and we can probably suppress the other language note - opened issue #966 (low priority)
540 looks good

Closing.
