### ISSUE TITLE
improve use and display of 245 field data

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#949]
We've touched on this in various contexts (see below) but there is not one issue that pulls it all together. @redlibrarian When we talked about authorship with @seanluyk this also came up and it seemed like a summer project.

Basically, everything in the 245 before $c should be displayed as the title in results and records, and there is also some consideration needed for displaying the $c (statement of responsibility) somewhere in the record view.

The challenge, I think, is using the data correctly and effectively, as it is chopped up into subfields and not always arranged in the same order. There may also be some considerations for how it is indexed.

-Described in terms of authorship/responsibility here: #827 
-In terms of records with no 245a here: #784 
-in terms of section and part numbers here: #718 (closed- the issue was getting them displayed _somewhere_ and indexed, but the need for the elements to appear as part of the title remains)

**Comment by theLinkResolver** [comment]
@redlibrarian I'm thinking about the logic for title display in all situations (#978, #997, #990), and I have to say, it's pretty much impossible to separate the $c (statement of responsibility) without having some kind of negative impact on the title (due to this MARC21 rule: "Once a subfield $c has been recorded, no further subfield coding of field 245 is possible").

Therefore, in good conscience, I recommend including the statement of responsibility in title displays (option 1), which does also help us with issue #827 ........... Conscience aside, my other recommendation is to mimic the way iLink/Classic Catalogue does it (option 2), which does impact title display (in particular, parallel titles would sometimes be omitted from display; this does not affect title searching, because parallel titles are also in 246).

Option 1 (the careful way):
1. Take all contents of 245 as text.
2. Remove $h text that is enclosed in square brackets, and also remove the brackets. (Don't remove all text, as spaces, colons, slashes, etc. are still needed.) Also the "$h" itself can be removed.
3. Replace each remaining subfield code with a space (b, c, f, g, k, n, p, s).
4. If last character in the remaining string is a period, remove it.
5. Display remaining text as title. Suppress display of author in grid and list views, as it will be unneeded.

Option 2 (the iLink way):
1. Take all contents of 245 as text.
2. Remove $h text as in option 1.
3. Remove $c and everything after it.
3. Replace each remaining subfield code with a space (b, f, g, k, n, p, s).
4. If the last character in the remaining string is a slash, remove it.
5. Display remaining text as title.

Either way, you _theoretically_ need to index a clean version of 245abfgknps text as the title, but this requires more thought, because indexing those date subfields (f, g) as well as the section number and name (n, p) _as title data_ may have unintended consequences; also $s. It might be safer to do a,b,k only, and let relevance bring the dates and section data forward only when it's appropriate.

If you think either of these options is something you might work on, let's run this logic by Brian S. and @SerialsLibrarian.

**Comment by theLinkResolver** [comment]
Just logging an example record for future testing:
[Blacklight](https://www.library.ualberta.ca/catalog/1480307) / [iLink](http://www.library.ualberta.ca/permalink/opac/1480307/WUAARCHIVE)

In this example, option 1 would preserve the English parallel title for display:
**Actes / Association canadienne de linguistique appliquée = Proceedings / Canadian Association of Applied Linguistics**

Option 2 drops it (the way iLink does):
**Actes**

**Comment by theLinkResolver** [comment]
@redlibrarian Hmm.. I suppose, if Blacklight could look at indicators and tease out 246 11 from other 246s, the parallel title could be identified as such and given display prominence, making option 1 more palatable. (will stop talking now)

**Comment by SerialsLibrarian** [comment]
I would go with option 1. Subfield c provides information for all those proceedings, annual reports, and other 'generic' titles that would otherwise not be distinguishable among each-other unless combined with the conference, corporate body, or jurisdiction that is responsible for them. 
Option 1: **Proceedings / International Symposium on Software Metrics**
Option 2: Proceedings 
(bdw, there are 88,468 hits in Advanced title search for this title)

The use of the 246s' indicators would work for books, but for serials the 2nd indicator is not required and therefore empty in all RDA and many older records too.

**Comment by seanluyk** [comment]
Closing as this issue has been rewritten #1364

**Comment by theLinkResolver** [comment]
@seanluyk Agreed that a lot of this has been or is being solved but there are some loose ends. This is one where I don't feel comfortable writing a new issue myself and I would want to discuss some things with you in person. And I might bring a colleague to help out. Can I set up a meeting?

**Comment by seanluyk** [comment]
@theLinkResolver yes,  meeting would be really helpful, please feel free to set one up!
