### ISSUE TITLE
display more fields in SFX records

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#951]
We can improve SFX records a little bit by displaying more of the metadata that's available (earlier/later title and publisher, in particular). @redlibrarian Can you point me to the current mapping for these?

**Comment by redlibrarian** [comment]
https://github.com/ualbertalib/discovery/blob/master/config/SolrMarc/sfx_index.properties

**Comment by theLinkResolver** [comment]
@redlibrarian Could you please send me the marcxml record for this SFX object? 110978977743753

I want to analyze a bit more closely why the SFX record is so sparse [as it appears in Blacklight](https://www.library.ualberta.ca/catalog/110978977743753).

**Comment by theLinkResolver** [comment]
Forgot to log my findings on this. What I found here is that there isn't much record metadata coming through for SFX records. The extract that is used to ingest the records was developed for other purposes (SFX2Sirsi) and so it is fairly "lean". The complete SFX records are lean anyway, but they appear even leaner in Blacklight because of this. @redlibrarian I think we can close this issue, because the mapping is in place - the data just ain't there to map!
