### ISSUE TITLE
new library: AHS_INT

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#952]
There is a new library in the system: AHS_INT (Alberta Health Services Internet)

**Comment by redlibrarian** [comment]
I need to work with the Symphony team to make sure Blacklight is updated with Symphony is. I can add this one right away, but I'll have to check with Elaine to see if there are any more. It would be nice to automate this, but I'm not sure that's possible...

**Comment by redlibrarian** [comment]
OK. It looks like the 596 code is 27, so I've added both to our configuration. They'll be in place in the next release.

**Comment by theLinkResolver** [comment]
@redlibrarian [Doesn't look right](https://search-test.library.ualberta.ca/catalog?utf8=%E2%9C%93&op=AND&all_fields=&title=&author=&subject=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search&f_inclusive[location_tesim][]=ahsint&utf8=%E2%9C%93&search_field=dummy_range&range[pub_date][begin]=&range[pub_date][end]=&sort=score+desc%2C+pub_date_sort+desc%2C+title_sort+asc&search_field=advanced).

**Comment by theLinkResolver** [comment]
@redlibrarian still no good

**Comment by redlibrarian** [comment]
Hm. OK. I'll check it again.

**Comment by redlibrarian** [comment]
OK, I think I see what the problem is. Check in next release.

**Comment by redlibrarian** [comment]
Still something weird with this one.

**Comment by redlibrarian** [comment]
See #1001 . This should be working, but still isn't. I'll have to keep digging.

**Comment by redlibrarian** [comment]
This should be working in the next release.

**Comment by theLinkResolver** [comment]
fixed
