### ISSUE TITLE
Collection: Linguistics

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#959]
- [ ] OAI-DC records
- [ ] Monthly ingest

from @sfarnel : 

Endpoint: https://catalog.ldc.upenn.edu/olac/ldc_catalog.xml

We can get either DC or OLAC, which is a DC based but richer metadata schema for describing linguistic resources. This would actually be great if we could get it.

We'll need to explore a bit in terms of how we pull in only what we have access to as well as how to indicate holdings in the harvested records. Some of these items are available in physical form from the data library, others are downloadable through our LDC portal (which requires a user account).

**Comment by redlibrarian** [comment]
Done when:

- [ ] Build new Traject rules for Dublin Core
- [ ] Linguistic records in Solr/Blacklight
- [ ] Set up monthly ingest pipeline (work with sysadmins)

**Comment by seanluyk** [comment]
Out of scope pending discovery strategy recommendation
