### ISSUE TITLE
Formatting number of results in grid view

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#961]
Though a low priority issue, I noticed this today while in search test and thought I'd note it.

Regarding the number of results presented to users when in the bento box display, previous feedback suggested that people found formatted numbers (ex. 943,555 instead of 943555) more readable. 

There are commas in numbers just about everywhere Blacklight displays the number of results, with one exception (that I could find). Number of results in individual bento boxes still displays without commas. 

![2016-04-19_10-11-12](https://cloud.githubusercontent.com/assets/14891931/14646728/d792f838-0617-11e6-93a9-7d009fc3997c.jpg)

For the sake of readability and consistency hopefully commas can be added there as well.

**Comment by redlibrarian** [comment]
This will be in the final release.

**Comment by theLinkResolver** [comment]
Looks good.
