### ISSUE TITLE
Possible result ranking issue with contents notes

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#962]
Just noticed this while preparing training materials:

Search example is to find a copy of An Die Musik (Schubert) for low voice.

Have a look at [this search](https://www.library.ualberta.ca/symphony?f%5Bformat%5D%5B%5D=Musical+Score&f%5Blocation_tesim%5D%5B%5D=uahss&f%5Bsubject_topic_facet%5D%5B%5D=Songs+%28Low+voice%29+with+piano&q=schubert+an+die+musik)

There doesn't seem to be a way to get an item that this song is actually contained in to appear at the top of the results list, and some odd results pop up. I realize that I could be "over librarianing" this one, by using the subject heading to get to the correct medium of performance, and that this could potentially mess up the ranking. I suspect it has something to do with the weighting of contents notes, which presents a huge problem for anthologies of all kinds. 

Not something urgent of course, but this is certainly one of the weak points that I've noticed that could hopefully be tweaked.

**Comment by theLinkResolver** [comment]
It would be interesting to see what would happen with increased weighting on contents note. Contents notes often include section or chapter titles (e.g. "index") that are not so important for searching, but as you say, in any kind of anthology, they are a very important piece of indexed data.
 
@seanluyk Putting quotes around the name of the song seems to be helpful - what do you think?

**Comment by seanluyk** [comment]
@theLinkResolver it does improve it, but there are still some false hits quite high on the list. I'm not sure if there's a way around this, and I'm wondering if the improvement has something to do with the fact that both a definite and indefinite article are in the title, and these words show up all over the place

**Comment by redlibrarian** [comment]
Hm. I think there's probably a bunch of things going on here. *schubert an die musik* returns results that shouldn't - as far as I can see - be returned (true false positives). With the phrase search, I can at least understand what's being found that would cause the erroneous result to appear. All that to say that weighting might not be the only thing to look at here. It's certainly worth further investigation.

**Comment by seanluyk** [comment]
Now that I'm beginning to understand how SOLR ranking works, and how to improve search results, I don't think this is an issue we can fix. Adding quotes to "an die musik" and then post-filtering brings back the 1 item that fits the information need. This one is just hard to find in any case
