### ISSUE TITLE
Replace EDS snippet with Blacklight snippet

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#964]
- The "Journals" button needs to be changed to "e-Journals".

- The hover box for the "Books, media & more" button needs to have "ejournals" added to the list.

- The hover box for the "e-Journals" button needs to have "journals" removed from the list.

**Comment by redlibrarian** [comment]
OK. I've updated this as well as I can. Bear in mind that this code snippet is not the one that will be on the front page. We'll have to verify that the new snippet is correct when we launch. @kgood I think you said you have the code for the snippet somewhere?
