### ISSUE TITLE
suppress display of Language field/facet

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#966]
Example record: https://search-test.library.ualberta.ca/catalog/6563867

The field called "Language" is mapped from 008/35-37, which is machine-readable and used for faceting.

Now that we are displaying the "Language note" field in the record, which gives more descriptive information for works in multiple languages, we can probably suppress the "Language" field from display (but continue using it for faceting). Or more complicated logic could have "Language" display when there is no "Language note"... but the value might not outweigh the effort. (Theoretically, the language should be apparent from the title in those cases, but other cataloguers should weigh in on this to be sure.)

**Comment by redlibrarian** [comment]
OK, this is done. I also changed the brief results view to use the same language field (note, not facet) for consistency.

**Comment by theLinkResolver** [comment]
looks good
