### ISSUE TITLE
Clicking on subject terms from results in databases container should search that container only

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#968]
*Description*: When a user searches for databases, then selects a database result and clicks on a subject heading, they lose the database limit.

*Expected behaviour*: The subject search should retain the database format/controller to limit to databases, if the user has pre-limited to databases. If they have not, then the databases context can be ignored.

*To reproduce*: 
1. Do a search limited to databases
    Add screenshot of the home page with the database search identified.
2. Select a database result
3. Click on one of the subject headings.
The new search will lose the database context

**Comment by redlibrarian** [comment]
Done when:

- [ ] Navigation logic fixed.

**Comment by seanluyk** [comment]
Not a relevant issue with the removal of the bento design. Closing.
