### ISSUE TITLE
Should titles be linked, instead of having the electronic access link?

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#969]
Now that the title itself of the e-resources are linked (yay!), the wording of the note that appears when you click on University of Alberta Internet at the bottom has to be changed. The current wording is: "This material is available Online. Click the Electronic Access Link in the record to access this material"

Suggested new wording: This material is available Online. Click on the title at the top of the previous screen to access it.

When you hover over the  University of Alberta Internet link, could there also be a tag that says "Click on the title at the top of the screen"

**Comment by fculpepper** [comment]
Are ebooks live in the search test catalogue? Every title I click on searches the title, sometimes bringing results [example] (https://search-test.library.ualberta.ca/catalog/6713469), sometimes an error message [example] (https://search-test.library.ualberta.ca/catalog/7411160), but never the book.

**Comment by theLinkResolver** [comment]
Yikes - I'm going to break @fculpepper's question into two new issues.

**Comment by redlibrarian** [comment]
@linds37 Can you give me an example record? The title-linking just does a search for the title (i.e. to find other copies of the same title) - I don't think I linked e-resources out to their online copy... having said that, the note in question is in Symphony, so that would be changed in iLink somewhere. I want to verify that the note is incorrect now before I ask for that change to be made.

**Comment by redlibrarian** [comment]
@fculpepper @theLinkResolver The title linking does a search for the title in the catalogue. It doesn't link out to the resource in question. I don't know what's happened to the electronic access links in the catalogue records, though...

**Comment by redlibrarian** [comment]
A bug had crept in which prevented the e-access link from showing this will be fixed in the next release. I hope this will make the distinction between the title link and the e-access link clearer.

**Comment by linds37** [comment]
Hi. Ok, so I totally misunderstood because I wasn't aware of the bug.  DO NOT CHANGE THE NOTE.
I thought the internet access link wasn't supposed to be there anymore. I thought the title linked to the resource itself.

I think this is problematic. In SIRSI, the title is linked, but only in the catalogue record tab. Not on the holdings info page. Since we only have one level in Blacklight, which definitely has its advantages, I don't think the title should be linked. Maybe there could be a link inserted somewhere into the record or somewhere on the screen that says "Find related titles"?

With this approach, I think we need to to some user testing. I'm concerned that users will have the following problems:
- for e-resources, they will understandably assume that the title link links to the item itself. That is googl-y. They will click on the title and get taken in a loop. 
- for print resources, users could assume that the title is an e-resource and then be confused/disppointed/frustrated when they can't get to the resource online -- and they will be distracted from scrolling down to see the call number and figure out how to find the book
- Here's an example record where the title keyword search that happens when you click on the title leads to no hits: https://search-test.library.ualberta.ca/catalog/2831071 That could lead the user to assume that there is something wrong and that the title is not actually available. In this case, the solution of a "find related titles" link is not a good one, because there are definitely other works in our collection on this topic, and we already have linked subject headings and other limiters to accomplish that.

I think part of the problem is the display. The title is so huge, and if it is linked, it is going to attract the eye. Even if the title links get removed, this leads me to wonder if the url that links to the actual item should be larger or highlighted in some way.

My suggestion is: remove the title link for release on May 5, until we have more time to think this through and do user studies.  What do others think?

**Comment by redlibrarian** [comment]
I'm happy to do what the group thinks. I just want to point out that the e-access link that appears right below the title is not only in a different font, but it's surrounded by a button border. To me that's prominent enough, especially since the link-effect for the title is just colouring it green (i.e. not underlining it). 

This was in response to another issue. If we want to change it back, I need to know pretty quickly. @ualbertalib/discovery-testing what are your thoughts?

**Comment by theLinkResolver** [comment]
I think all of @linds37's concerns are very important things to test and monitor. My personal opinion, though, is to still keep the title link feature. Hope to hear from others on this.

**Comment by lindaslater** [comment]
I think the message below the title (Click here for University of Alberta Access) is pretty obvious, and that being the case, I agree with Lindsay that if the title link often doesn't go anywhere meaningful or only leads to an error screen, it is going to confuse users.

**Comment by redlibrarian** [comment]
@ualbertalib/discovery-testing This clearly needs some more discussion. I'm going to turn the link off for now and we can revisit later on.

**Comment by theLinkResolver** [comment]
@redlibrarian Should we rename this issue - are you treating it as the title search link issue now?

**Comment by redlibrarian** [comment]
I've renamed this issue. The question now is should titles be linked, or should we continue to use the "electtronic access" link. For discussion.

**Comment by theLinkResolver** [comment]
@ualbertalib/discovery-testing Over time, and today again, I've heard a bit of feedback that users are clicking the "University of Alberta Internet" link in the items table rather than the "Click here for University of Alberta Access" link under the title. Is anyone else hearing this?

**Comment by seanluyk** [comment]
I've not heard this, but it's certainly possible. Is this maybe something we could do some low-fi usability testing on? If so, I would be happy to assist with this.

**Comment by scastell** [comment]
I wonder if some of the confusion re where to click is related to difference in the location of the UA e-access links in the records from the ejournal results box versus those from the books, media and more box. 

Example:
Business ethics quarterly
https://www.library.ualberta.ca/catalog/954921419504 - ejournals bento box - UA e-access links at the bottom of the entry
https://www.library.ualberta.ca/catalog/6823434 - books, media and more - UA e-access link at the top of the entry

**Comment by redlibrarian** [comment]
The link in books, media and more records *used* to be just above the holdings box, but I moved it on the group's recommendation to make it more prominent. I think this is probably one of those things where, for now, we should leave it alone and see what comes out of user-testing later in the term.
