### ISSUE TITLE
hyperlinked title search fails when subtitle present

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#971]
e.g. clicking the title in these records:
https://search-test.library.ualberta.ca/catalog/7411160
https://search-test.library.ualberta.ca/catalog/6341684

In this case, we get a result, but it does not include the record we linked from:
https://search-test.library.ualberta.ca/catalog/1785821

@redlibrarian I think we need to exclude the subtitle text from the search string.

**Comment by redlibrarian** [comment]
@theLinkResolver OK, that sounds fine. I'll do that now and we can tweak it if usability points us in another direction.

**Comment by redlibrarian** [comment]
We've removed the title link completely for now.
