### ISSUE TITLE
Export to RefWorks not working

### ISSUE THREAD

**Issue by lindaslater** [ualbertalib/discovery#972]
When I try to export (using search-test), I get an 'Export failed' message in RefWorks.   EndNote works, but it would be nice to have the Notes get exported into EndNote as well.

Linda

**Comment by redlibrarian** [comment]
@lindaslater it works in production, and I haven't changed anything in the RefWorks export functionality. I'm going to assume that this is a peculiarity of the test environment. We'll have to try it once the latest version of the application is in production next week.

As for exporting notes fields to EndNote - I don't know how that works, so it will have to be looked at as an enhancement to tackle later on.

**Comment by theLinkResolver** [comment]
@redlibrarian Just looking at this now with Erika - are you sure that it's working in production? I can't get to the bookmarks in production to try this (#924).

**Comment by redlibrarian** [comment]
@theLinkResolver I did it with a single record (i.e. not using a bookmark). I'll look into #924

**Comment by redlibrarian** [comment]
#924 should be fixed now. Please check in the new release.

**Comment by theLinkResolver** [comment]
This is definitely working now.
