### ISSUE TITLE
Help with Search guide

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#973]
I'm working on the "Limits" section of the search guide. Please take a look https://ualberta.libapps.com/libguides/admin_c.php?g=469542&p=3209716 (this is shared with all unit library locations. Sam, do you have a login?)
Please have a look at the descriptions of the limiters and the questions at the bottom.
I know this is wordy -- using Stanford's guide as a model, and we did have that chat transcript recently that asked for this level of detail

**Comment by redlibrarian** [comment]
@ualbertalib/discovery-testing 

@linds37 Yes, I have a log in - I'll take a look. Thanks.

**Comment by linds37** [comment]
Thanks. I've just added a new box that lists all of the limits for Articles & more.
