### ISSUE TITLE
diacritics in database titles not displaying correctly

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#976]
https://www.library.ualberta.ca/databases?utf8=%3F&q=Machado+

[Here's what it should look like](https://web.library.ualberta.ca/databases/databaseinfo/index.cfm?ID=4086)

**Comment by redlibrarian** [comment]
Ugh. That's actually how it looks in the LibGuides entry - this must be a holdover from Ernie's old system. I'll change the data and get in touch with April - this might require a cleanup project.

**Comment by redlibrarian** [comment]
I've gotten in touch with April to see if the data can be changed at source.

**Comment by redlibrarian** [comment]
April changed the titles and descriptions in LibGuides, but the HTML elements are still coming through in the LibGuides API (the API isn't using UTF-8). So I'll have to modify Blacklight's database ingest to render the special characters.

**Comment by seanluyk** [comment]
Submitted ticket to April to try to fix again - we can test tomorrow to see if the diacritics come through. What was appearing in BL was what was in LibGuides.

**Comment by seanluyk** [comment]
Fixed, forgot to close
