### ISSUE TITLE
parentheses missing in display text for internet access links

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#977]
https://search-test.library.ualberta.ca/catalog/6845187

The text from the MARC 856 field is e.g. v.132(1998)-v.148(2014) - the parentheses have been stripped out.

**Comment by redlibrarian** [comment]
Gah. I stripped out the parens to fix a different problem, and didn't foresee this consequence.

**Comment by redlibrarian** [comment]
Ok, I've put them back in, but we'll have to watch out for whatever that other formatting tweak was.

**Comment by theLinkResolver** [comment]
@redlibrarian #767? My best guess at an issue that involved the formatting of coverage.

**Comment by redlibrarian** [comment]
@theLinkResolver I don't think that was it...

**Comment by theLinkResolver** [comment]
@redlibrarian You're right, and I just remembered. I bet it had something to do with the handling of the 856 $z (note text).

https://search-test.library.ualberta.ca/catalog/4276360
https://search-test.library.ualberta.ca/catalog/7152141

..perhaps to deal with the aesthetics of a double closing parenthesis in an example like the second one above.

**Comment by redlibrarian** [comment]
@theLinkResolver That's probably it. 7152141 is correct in search-test right now, but won't be when the parens have been put back. It's low priority, but I'll tweak it when I get a second.

**Comment by theLinkResolver** [comment]
Looking good.
