### ISSUE TITLE
[Discovery] 110 and 245 $k and $f not displaying properly

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#978]
Will not apply to a huge number of records, but I stumbled upon this one looking for something else:

Still not mapped: https://www.library.ualberta.ca/catalog/910509

On this record, title should be: Records 1945-1982

Here's the NEOS record: http://www.library.ualberta.ca/permalink/opac/910509/WUAARCHIVE

**Comment by redlibrarian** [comment]
Hm. Interesting. I'll take a look.

**Comment by theLinkResolver** [comment]
@redlibrarian I think the records with no 245 $a are not working again (this is one). 

another (first result)
https://search.library.ualberta.ca/symphony?q=Canadian%20Phytopathology%20Society.%20Alberta%20Regional%20Group

**Comment by redlibrarian** [comment]
I don't think I'm going to have time to dig into this one before thursday.

**Comment by redlibrarian** [comment]
Yes, @sjshores reported this problem again today. I've made a temporary fix to stop the system from giving an error, but I'll have to deal with these soon. #997

**Comment by redlibrarian** [comment]
Hm. The initial problem record comes up at least in production, but not in test.

**Comment by redlibrarian** [comment]
Done when:

- [ ] Problem confirmed
- [ ] 245 subfields displaying properly

**Comment by seanluyk** [comment]
This either needs to be fixed at the record level or in BL mappings. Added high priority label, hopefully, this can get fixed before the freeze @pgwillia @weiweishi @murny

**Comment by seanluyk** [comment]
Fixed in test, closing.
