### ISSUE TITLE
Found another ebook that doesn't show date in record

### ISSUE THREAD

**Issue by linds37** [ualbertalib/discovery#979]
Hi. I know we've dealt with this before, and you've found dates in weird fields in records from some ebook vendors. Here's a new ebook from two different vendors, and the date doesn't show up in either:
Science Direct (Elsevier): https://search-test.library.ualberta.ca/catalog/7123942
Proquest Safari collection: https://search-test.library.ualberta.ca/catalog/7123835

- reporting from a colleague

thanks!

**Comment by redlibrarian** [comment]
I've added the RDA 264c for date handling which should fix the problem.

**Comment by theLinkResolver** [comment]
Yay! This seems to be working.
