### ISSUE TITLE
Articles publication year limits

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/discovery#982]
-- remove second one
-- replace first one with range slider

**Comment by redlibrarian** [comment]
We're locked out of the EDS admin interface. I have a ticket in with Ebsco support. This will have to wait until then.

**Comment by redlibrarian** [comment]
Publication Year slider looks like this in the Catalog controller:

![image](https://cloud.githubusercontent.com/assets/1093066/17181898/f6a1b92a-53de-11e6-99f8-df1c15f1b082.png)

That slider is activated here: https://github.com/ualbertalib/discovery/blob/master/app/controllers/catalog_controller.rb#L126

by using the `:range => true` modifier

**Comment by redlibrarian** [comment]
Range_field helper in Rails, might work. 

http://apidock.com/rails/ActionView/Helpers/FormHelper/range_field

**Comment by astrilet** [comment]
range_field will allow selecting single number from a range, example below 
![screenshot from 2016-07-26 15 06 04](https://cloud.githubusercontent.com/assets/11414991/17254957/cae7109e-556b-11e6-8198-0aeabae7f0b4.png)

**Comment by astrilet** [comment]
blacklight publication year slider will not work on EBSCO data returned and saved in $results hash table, 
blacklight uses blacklight_range_limit gem to display publication year slider.

**Comment by seanluyk** [comment]
I'm not seeing the range slider anymore in test, but instead it's now a list of years in reverse chronological order. Is it not possible to replicate the start and end date range slider from EDS? @ualbertalib/discovery-testing any comments on this?

**Comment by redlibrarian** [comment]
We've never been able to get the slider working in EDS. Alex's screenshot shows the best we could do, but that only works with a single date, not a date range. 

This issue fixes the problem with two publication year facets appearing in articles. I think we can close this one. I'll add the date slider functionality to #929
