### ISSUE TITLE
Limiting to Articles & More from main search box produces no results in Firefox

### ISSUE THREAD

**Issue by lindaslater** [ualbertalib/discovery#985]
When I enter a search statement and select the Articles & More option from the main search box, I get no results, but when I re-enter the search terms from the No results screen, I will get a search result.  Also, results will appear in the Articles & More panel if I do an Everything search.  The problem does not occur on Chrome.

**Comment by redlibrarian** [comment]
This is the same problem as #928. It should be fixed in test, and will be fixed in the next production release.
