### ISSUE TITLE
Cochrane databases do not show up in Blacklight

### ISSUE THREAD

**Issue by lindaslater** [ualbertalib/discovery#986]
I tried to access the Cochrane Database of Systematic Reviews and the Cochrane Central Register of Controlled Trials via Blacklight, and the databases do not get retrieved.  I also tried their 'umbrella' names, i.e. Evidence Based Medicine Reviews, EBM Reviews and EBMR, Cochrane Library as well as simply Cochrane, and none of these would retrieve the databases either.

**Comment by redlibrarian** [comment]
Hi Linda, 

Can you check again? At least some of the Cochrane databases are showing up: https://search.library.ualberta.ca/databases?utf8=%3F&q=cochrane

**Comment by redlibrarian** [comment]
The three that are showing up in Blacklight are the three that come up in a "Cochrane" search in LibGuides:

http://guides.library.ualberta.ca/az.php?q=cochrane

**Comment by lindaslater** [comment]
Hi, Sam,
I forgot to check the test version.  As long as it's working in the version
that comes up on Thursday, that should be fine.

Linda

*Linda Slater*, Public Services Manager, John W. Scott Health Sciences
Library, 2K312 WMC
University of Alberta, Edmonton, AB T6G 2R7.  Tel:  780-492-7948. Fax:
780-492-6960. Email:  linda.slater@ualberta.ca

**Comment by theLinkResolver** [comment]
@lindaslater @redlibrarian I'm satisfied with most, but not all, of the results in Blacklight for these, but this can be improved by adding some alternative titles to the LibGuides description. As far as searching in the LibGuides-based database search goes, I think there is work to be done to improve findability (that was not the basis of @lindaslater's original question but I was checking it out and found some issues).

As fixing both are non-Blacklight issues, I agree that this issue can be closed. @lindaslater, I will followup via email when I have some time to work on this.
