### ISSUE TITLE
Directed to an All Records results page

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#987]
I hadn't noticed this behaviour previously, so I think it's new this release. 

I'm being directed to an "All Records" bento results page (https://library.ualberta.ca/results?q=) on occasion. You can get to this page by clicking the search button from the initial search box without entering any terms: https://library.ualberta.ca/search. 

I don't think this is necessarily a problem (though the fact that no results appear in Articles doesn't look the best visually). Conducting a blank search is bound to lead to either an error page or (in this case) all results minus articles.

What I think may be a problem is that upon conducting a search, if you reclick the Search button from a bento results page, you're directed to the All Records results page. The reason being, that although it looks as if your previous search term is still in the search box, the search box is actually 'blank' (if you click into it you need to retype your search terms). 

I feel this is inconsistent with the behaviour within bento boxes, where you can "search again", and your previous search terms are actually preserved in the search box. Not that the search boxes need behave the same way ('search' and 'search again' aren't necessarily identical), but if a term appears in a search box I feel it signals to the user that the search terms are actually there.

I feel that if a search box is indeed blank, it should appear blank to the user. Or, the search box should behave like the 'search again' box within bento boxes. Whatever is desired. 

![2016-05-03_10-57-32](https://cloud.githubusercontent.com/assets/14891931/14991629/816cfcac-111f-11e6-93db-2343c9fb9865.jpg)
![2016-05-03_10-58-11](https://cloud.githubusercontent.com/assets/14891931/14991631/85bde000-111f-11e6-96d6-23b2b3ba2e99.jpg)

**Comment by redlibrarian** [comment]
Thanks @gooyers - if I'm understanding you properly, there are two issues: 1) you're being taken to a full result set sometimes and 2) the search terms which appear in the search box after a search aren't really there. 

I've fixed 1) by baking the behaviour of the bento screen the same as the result screen: if no search term has been entered, the screen will say "begin your search here" and no results will be shown. I'll have to look into problem 2), but it should be fixable.

**Comment by redlibrarian** [comment]
OK, I've fixed both these bugs. They should be in the next (last) release.

**Comment by gooyers** [comment]
Thanks for the quick fixes @redlibrarian!

**Comment by redlibrarian** [comment]
@gooyers No problem. If you want to check these out, the code fix is now in search-test.

**Comment by redlibrarian** [comment]
This is working.
