### ISSUE TITLE
Suppress ILL records 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#988]
Just stumbled across this searching for an item for a patron. The following is an ILL record (as indicated in Workflows):

https://library.ualberta.ca/catalog/6403536 

I think this possibly relates to #927, although for a different type of record.

**Comment by redlibrarian** [comment]
Hm. I think that's supposed to be excluded from the data extract...

**Comment by theLinkResolver** [comment]
@seanluyk mmmmm.... maybe some lingering issues.
https://www.library.ualberta.ca/catalog/4124324
https://www.library.ualberta.ca/catalog/4133061

Some or all of this could be related to mistakes in procedure. It looks like most ILL items are shadowed using Workflows settings at the title, call number, or item level (which do function correctly with Blacklight), but perhaps it's a manual step by ILL staff to do these settings, and then of course mistakes happen. ILL and ILL_ and home locations vs. current locations may also have different meanings, so I would be reluctant to make any assumptions about what we want.

**Comment by seanluyk** [comment]
Thanks for catching, @theLinkResolver  - I'll reopen this issue. From what I know right now, this record would not be excluded in BL, because the location "on loan to another library" hasn't been excluded in Jim's script. The original issue I put in could have been in error, as I'm seeing both of these items in elibrary. However, I don't see a reason why these kinds of records should come through, but will need to verify with CJ and others just in case.

**Comment by seanluyk** [comment]
Current status: ILL will attempt to clean up from the Workflows side.

**Comment by seanluyk** [comment]
Update - will ask Jim to exclude this location from script
