### ISSUE TITLE
Index and display 245 $h (Section Number) in titles where present

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#990]
Searching BL for The Handbook of Labour Economics 4B yields some ambiguous results in both the [grid](https://library.ualberta.ca/results?utf8=%3F&q=handbook+of+labor+economics+4b) and [list](https://library.ualberta.ca/symphony?q=handbook%20of%20labor%20economics%204b) views.

I think what needs to happen is for the 245 $h (already indexed) to be added to the title and displayed in grid and list views. This is a similar issue to #718

**Comment by theLinkResolver** [comment]
@seanluyk Definitely true, as the section and part numbers are integral parts of the title. (You mentioned $h but I think you meant $n and $p.)

#718 discussed it and I tried to capture the bigger picture in #949 also.

**Comment by seanluyk** [comment]
Thanks @theLinkResolver, that n must have looked like an h ;)

**Comment by seanluyk** [comment]
Fixed in test, closing.
