### ISSUE TITLE
Usability issue with articles list view

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/discovery#994]
It was mentioned to me that all the other bento box list views have next/previous buttons at the top and bottom of results pages, but articles results pages only have next/previous buttons at the top of the page.

**Comment by redlibrarian** [comment]
Try to add this bar to the bottom of the article results screen.

![image](https://cloud.githubusercontent.com/assets/1093066/16960168/82d5c41c-4da5-11e6-83ed-32764cda7229.png)

**Comment by astrilet** [comment]
fixed this issue, PR #1026 
![screenshot from 2016-07-26 15 06 04](https://cloud.githubusercontent.com/assets/11414991/17183094/eaa82414-53da-11e6-9f37-a4927e9fd79d.png)

**Comment by seanluyk** [comment]
Fixed, looks good, closing
