### ISSUE TITLE
"Start Over" link directs to page that mentions list/grid view. 

### ISSUE THREAD

**Issue by gooyers** [ualbertalib/discovery#995]
Small issue, but the "Start Over" link at the top of a results page redirects to this page: https://library.ualberta.ca/search. This page was used while the search wasn't the default, is the plan to still use this page?

If so, the page mentions that you can "select your preferred view from your initial search results" which alludes to the removed list/grid view. I suggest this language be removed. Thanks!

![2016-05-13_9-54-57](https://cloud.githubusercontent.com/assets/14891931/15253872/5d69b474-18f1-11e6-881b-db2d85c00ff1.jpg)
![2016-05-13_9-55-23](https://cloud.githubusercontent.com/assets/14891931/15253881/63fbfd1a-18f1-11e6-92b8-0c9794021f05.jpg)

**Comment by redlibrarian** [comment]
Fixed.
