### ISSUE TITLE
next/previous buttons not behaving in database results list

### ISSUE THREAD

**Issue by theLinkResolver** [ualbertalib/discovery#996]
[Go here](https://www.library.ualberta.ca/databases?page=2&q=encyclopedia&utf8=%3F) and pick a title, then click next or previous. I'm in some other, larger result set.

![image](https://user-images.githubusercontent.com/2047614/39454005-0dcc7052-4c96-11e8-9a81-9961c6be793e.png)
Click on any of the title, it shows it's in a bigger result set:
![image](https://user-images.githubusercontent.com/2047614/39454076-6e1f8dc2-4c96-11e8-928c-78c81b7d2cf2.png)

**Comment by redlibrarian** [comment]
Done when:

- [ ] Behaviour fixed. You should be able to navigate using "previous" and "next" the same as you would through the list of brief results.

**Comment by seanluyk** [comment]
No longer relevant with removal of bento design.
